### ISSUE TITLE
syncing on smartphone

### ISSUE THREAD

**Issue by acha85** [streetwriters/notesnook#100]
**Describe the bug**
![NN-tags érronés](https://user-images.githubusercontent.com/60747298/143619937-aa343c8c-a486-43af-b1b3-072d1e331844.png)

les tags, sur mon téléphone samsung, sont mal synchronisés: les "é" n'apparaissent plus ( alors qu'ils sont corrects dans NN desk )
**To Reproduce**

**Expected behavior**
syncing : all is ok on my desk , except on my phone

**Screenshots**

**Desktop (please complete the following information):**
 - Browser [e.g. chrome, safari]: firefox
 - Version : 1.6.4 ( my phone); on my desk: NN86_64_appimage (  linux )

**Smartphone (please complete the following information):**
 - Device: samsung E7
 - OS: système /e/
 - Browser : firefox

**Additional context**

**Comment by thecodrr** [comment]
@acha85 Have you tried logging out and logging back in?

**Comment by acha85** [comment]
on my phone, when I tempt to sync, the message: "bad base-64".
