### ISSUE TITLE
poor score at https://observatory.mozilla.org/ a set of tools to analyze website's https configuration

### ISSUE THREAD

**Issue by gpdevsoft** [streetwriters/notesnook#1012]
You are doin a great job, recently i tried to run the Mozilla HTTP Observatory service test (is a set of tools to analyze a website and inform if you are utilizing the many available methods to secure it) I noticed that the score obtained is quite low, D+ in a scale from A to F, so I wanted to point out this aspect so when you have time and if you think it useful you can also improve this aspect of safety

Thanks and good job.

here you can find the analysis results for the login page https://app.notesnook.com/login.
https://observatory.mozilla.org/analyze/app.notesnook.com

**Comment by ammarahm-ed** [comment]
Hey thanks for reporting. We will look into this soon.

**Comment by thecodrr** [comment]
Hi, the score should now be B. I am taking a look on how it can further be improved.

**Comment by gpdevsoft** [comment]
> Hi, the score should now be B. I am taking a look on how it can further be improved.

Great job thanks, all further improvment will be good
