### ISSUE TITLE
Desktop - can't select tag by simply hitting Enter

### ISSUE THREAD

**Issue by short-y** [streetwriters/notesnook#1045]
### What problem are you facing?

Not sure if this is a bug or a feature request but, in the desktop/web interface, if I type all or part of a tag I can;t just hit Enter to select it, but must click on it with my pointer. Seems like a waste of movement.

### What's the solution you'd like to see in Notesnook?

Allow the Enter key to select the current/selected/highlighted tag.

**Comment by thecodrr** [comment]
This has been fixed in v2.2.0.
