### ISSUE TITLE
"<folder> was removed, reassigning <name> to homedir" when launching app

### ISSUE THREAD

**Issue by JLuc** [streetwriters/notesnook#1059]
### What happened?

i installed on Ubuntu 22.04 using `snap install notesnook` as advised.

I tried to launch it via the launcher but got a "missing exec in .desktop" error.

I then launched it via command line : `notesnook` and got the following message 
```
/home/jluc/Musique was removed, reassigning MUSIC to homedir
/home/jluc/Vidéos was removed, reassigning VIDEOS to homedir
```
OOOoops !
By chance, my Music and Video folder where not deleted and still active.

### Steps to reproduce the problem

- install via snap on ubuntu
- try to launch

### Version

v2.2.0

### Platform/OS

Linux

**Comment by thecodrr** [comment]
I am not able to reproduce this. Snap is installing and functioning as it should.

**Comment by JLuc** [comment]
FYI when launching the app in the terminal, notices are issued :  

```
(Notesnook:18372): GdkPixbuf-WARNING **: 11:13:38.326: Cannot open pixbuf loader module file '/home/jluc/snap/notesnook/common/.cache/gdk-pixbuf-loaders.cache': No such file or directory
This likely means that your installation is broken.
Try running the command
  gdk-pixbuf-query-loaders > /home/jluc/snap/notesnook/common/.cache/gdk-pixbuf-loaders.cache
to make things work again for the time being.
```
But i cannot run the advised command because 
`command not found: gdk-pixbuf-query-loaders`

In case it's relevant, after this first notice come more notices : Theme parsing error for « 'font-feature-settings' (not a valid property name)» ; about « Kernel has no file descriptor comparison support: Operation not permitted » and about «buffer.Blob is an experimental feature. »

**Comment by thecodrr** [comment]
I think since I am on KDE, it's working fine for me. Does the app crash immediately?

[This comment](https://github.com/microsoft/vscode/issues/100940#issuecomment-651225395) might help temporarily.

**Comment by JLuc** [comment]
When using the launcher the app is not launched at all because .desktop file is not OK
When launching with command line, it launches fine and doesnt crash.

**Comment by JLuc** [comment]
thx
