### ISSUE TITLE
Issues in app

### ISSUE THREAD

**Issue by abhishekarora12** [streetwriters/notesnook#107]
Hi there, some more issues i faced while using the app:

- [x] 1. There is no way to remove color coding from a note
- [x] 2. Improve checkbox functionality (samsung notes crosses the entire text if checked)
- [x] 3. On android, note doesn't get saved if I only pasted content
- [x] 4. On android, if i pasted some content, and delete the starting few letters by backspacing, the keyboard closes as soon as it reaches the para before (need this for copied checkbox content from other apps, they show in notesnook as "[]")
- [x] 5. Notes should show modified date instead of created date (if modified date is selected in sorting order)

**Comment by ammarahm-ed** [comment]
Hi thanks for reporting

> There is no way to remove color coding from a note

Is this happening on android or desktop app? I am using android and I can remove color from a note using three-dot menu. The selected color is checked and if you tap on it, it will get removed from the note.

> Improve checkbox functionality (samsung notes crosses the entire text if checked)

I think this varies from app to app. Some will strikethrough the checked item and some don't.

> On android, note doesn't get saved if I only pasted content

This has been fixed in version 1.6.7.

> On android, if i pasted some content, and delete the starting few letters by backspacing, the keyboard closes as soon as it reaches the para before (need this for copied checkbox content from other apps, they show in notesnook as "[]")

I tried to reproduce this on android but failed to. If you can provide some example note copied content from other apps. I will be able reproduce and fix this.

> Notes should show modified date instead of created date (if modified date is selected in sorting order)

I think you are right about this. We will add this in the next release.

**Comment by abhishekarora12** [comment]
Hi,

> Abhishek: There is no way to remove color coding from a note
Ammar: Is this happening on android or desktop app? I am using android and I can remove color from a note using three-dot menu. The selected color is checked and if you tap on it, it will get removed from the note.

It's happening on the mac app 1.6.7, clicking on the selected color doesn't do anything. I have to delete the note if i want to remove the color from a note.

> Abhishek: Improve checkbox functionality (samsung notes crosses the entire text if checked)
Ammar: I think this varies from app to app. Some will strikethrough the checked item and some don't.

I agree, but if the design of checkboxes can be improved it would be great, like dimming colour to differentiate or something like that.

>Abhishek: On android, if i pasted some content, and delete the starting few letters by backspacing, the keyboard closes as soon as it reaches the para before (need this for copied checkbox content from other apps, they show in notesnook as "[]")
Ammar: AI tried to reproduce this on android but failed to. If you can provide some example note copied content from other apps. I will be able reproduce and fix this.

This looks like a bug in editor instead of pasting, to reproduce, on android -
1. Create a checkbox line
2. Create second line without checkbox
3. Delete starting characters from the second line
4. As soon as it reaches to the first line, the keyboard closes and it's impossible to figure out where the second line was (especially problematic in the case of bigger notes)

**Comment by thecodrr** [comment]
All these issues have been fixed.
