### ISSUE TITLE
Dark titlebar in windows

### ISSUE THREAD

**Issue by Guray00** [streetwriters/notesnook#1086]
### What problem are you facing?

Even with the dark theme, in windows appears a white titlebar. 

![image](https://user-images.githubusercontent.com/30523962/192856878-6bb4c2ef-f691-4ea0-85fe-f5ea9a9a58e6.png)

### What's the solution you'd like to see in Notesnook?

Make the titlebar following the theme, becoming dark with the dark theme.

**Comment by thecodrr** [comment]
Currently the only way around this is building our own custom titlebar.

**Comment by drannex42** [comment]
Has there been any thoughts towards this lately? On GTK/Gnome it's quite bright and out of place with the rest of the OS.

**Comment by ammarahm-ed** [comment]
Hi, custom titlebar is here in V3. Thanks everyone for the feedback.
