### ISSUE TITLE
Paragrahp and font not work at latest version

### ISSUE THREAD

**Issue by Antony-Jia** [streetwriters/notesnook#1089]
### What happened?

![image](https://user-images.githubusercontent.com/58219593/192914933-32d38cf3-cc7f-4558-8fe4-17baddcc46a3.png)
this feature not work at lastest version

### Steps to reproduce the problem

After update 2022/09/29

### Version

version 2.2.0-a61b577-desktop

### Platform/OS

Windows

**Comment by Antony-Jia** [comment]
I roll back to version 2.1.6-deb04d6-desktop the bug is missiong

**Comment by thecodrr** [comment]
Hi, this is already reported here #1067. The fix has been implemented and waiting release here #1078
