### ISSUE TITLE
OneNote import: JS error during import: `Error: The specified resource ID does not exist.`

### ISSUE THREAD

**Issue by altano** [streetwriters/notesnook#11]
I got this far in the import:

> Fetched 402/598 pages content

The JS console says:

> Uncaught (in promise) Error: The specified resource ID does not exist.

I started the import from scratch with "Pause on exceptions" enabled so I could get more info. It died on the same page (402) but the minified code didn't mean much to me:

![image](https://user-images.githubusercontent.com/1009/119632267-81dec780-bdc5-11eb-889e-ded6ee09d7e8.png)

The XHR that failed (that lead to the error) had this response:

```JSON
{"error":{"code":"20102","message":"The specified resource ID does not exist.","innerError":{"date":"2021-05-26T08:51:11","request-id":"8c556108-ab23-49d2-b4cc-60be4f236ef4","client-request-id":"6e2538e3-87e2-4a0f-4da2-3f43931dea34"}}}
```

**Comment by thecodrr** [comment]
The page it got stuck on doesn't exist. Perhaps it got deleted during import?

**Comment by altano** [comment]
I haven't edited my notebooks all day so I don't think that's it? I just did a manual resync from the Windows desktop OneNote client, closed the client, and re-initiated the import. I had the same result.

Any chance you could just dump whatever info you have about the problematic page (even if just the containing notebook name or whatever) and let the import continue?

Or even just dump the info and let me see if that's revealing of the problem in some way?

**Comment by thecodrr** [comment]
> Any chance you could just dump whatever info you have about the problematic page (even if just the containing notebook name or whatever) and let the import continue?

That's what I did. It logs the error that occurred in the console and moves on.

**Comment by altano** [comment]
Oh nice, I just re-initiated the import and it didn't stop on the failed page.

The error in the JS console is:
> Error fetching page 404 with contentUrl https://graph.microsoft.com/v1.0/users/alan@terriblefish.com…e9544a03082138177546ab86588e!1-B4848BE9A8709757!483/content: Error: The specified resource ID does not exist.

This didn't give me much to go on but went and looked at the network response for the `https://graph.microsoft.com/v1.0/me/onenote/pages?$top=100&$skip=400` response which had more info about the page. That JSON object has a `links` object with a `oneNoteWebUrl` property. I know what page is the problem but interestingly the page exists and I can access it from that URL. So I don't see what the issue is.

No big deal though as I don't need the page and it didn't fatal the whole import, so now I can continue the import.

I actually just hit the `Uncaught (in promise) TypeError: g.content is undefined` that I mentioned in https://github.com/streetwriters/notesnook/issues/9#issuecomment-848615499. I deleted the empty page and am re-initiating import.

**Comment by thecodrr** [comment]
> I then hit the Uncaught (in promise) TypeError: g.content is undefined that I mentioned in #9 (comment). I deleted the empty page and am re-initiating import.

This should be fixed in the version I just deployed.

> So I don't see what the issue is.

MS is saying "Resource ID" doesn't exist so maybe the there is some issue in the URL being used to fetch the page?

**Comment by altano** [comment]
> MS is saying "Resource ID" doesn't exist so maybe the there is some issue in the URL being used to fetch the page?

Probably. I don't know how to authenticate so that the graph API URL works so I don't know how to dig in further. I'm content to live with the minor mystery of why that didn't work though and just ignore it.

I see you dumping more info during the import now:
![image](https://user-images.githubusercontent.com/1009/119639056-16e4bf00-bdcc-11eb-9cf9-539fe7262272.png)

Looks awesome. Thanks for the amazing turnaround times on this.

**Comment by altano** [comment]
And the JS error says the page name. Perfect :)

**Comment by thecodrr** [comment]
According to [this issue](https://github.com/microsoftgraph/microsoft-graph-docs/issues/10138), this error can occur if the resource is shared.

**Comment by altano** [comment]
This problematic page is indeed shared, although I have a LOT of shared pages and that was the only one erroring. 🤷🏾‍♀️

With the fixes I was able to complete the import! I'll take a look at the quality of the import tomorrow. Thanks again for all your help!
