### ISSUE TITLE
Allow pinning more than three notes

### ISSUE THREAD

**Issue by tylermercer** [streetwriters/notesnook#1102]
### What problem are you facing?

I have four or five notes that I need to access frequently but not change often, and I create one or more notes every day, so they get lost in the Notes and per-notebook list views. I find it frustrating that I can't pin however many notes I want.

### What's the solution you'd like to see in Notesnook?

Allow the user to pin any number of notes, or make the limit configurable as a setting.

### What alternatives have you considered?

Bundling notes together to reduce the number to three -- not ideal because two of my three notes are pinned to my notifications and I don't want to bloat them. The third ends up being a sort of "everything else that I want pinned" note, which is not great.

**Comment by thecodrr** [comment]
Thank you for trying out Notesnook. This is being worked on in #1103
