### ISSUE TITLE
[SOLVED] Android UI bug after upgrade to 2.2.0 and above can't add or update notes

### ISSUE THREAD

**Issue by gpdevsoft** [streetwriters/notesnook#1105]
Hi, I wanted report a UI bug, when I try to update a note  after press on it  as soon as I try to type some text the screen with list of the notes appears again  and also a  long  thin strip on the right in which I should write the note but it is too small you cannot read anything it is clearly a bug as you can see from the screenshot

![screenshot](https://user-images.githubusercontent.com/14260912/193125625-cf5bf714-2930-4bfd-8757-801631cb3e74.jpg)

**Comment by ammarahm-ed** [comment]
Hi, does it look normal with the keyboard closed and only becomes like above when keyboard is opened?

**Comment by gpdevsoft** [comment]
yes, it seems happen only when keyboard is opened

**Comment by gpdevsoft** [comment]
Hi! any news about fix this issue? the app still remain unusable

**Comment by ammarahm-ed** [comment]
Hey @gpdevsoft i will make a release tomorrow hopefully. The issue has been fixed already.

**Comment by gpdevsoft** [comment]
i have just update and the issue is solved, thanks!
