### ISSUE TITLE
Unable to update from version 2.1.6

### ISSUE THREAD

**Issue by ikurek** [streetwriters/notesnook#1109]
### What happened?

I've installed Notesnook on MacOS from [Homebrew Cask](https://github.com/Homebrew/homebrew-cask/blob/HEAD/Casks/notesnook.rb) with the latest available version `2.1.6`. After the app is launched, I get a popup saying `New version is available`. After I click `update now` and then `install now` nothing happens. There's an information on the bottom bar saying `2.2.1 downloaded (restart required)` but when I close the app in any way, the update doesn't seem to install - the whole update process begins again.

### Steps to reproduce the problem

1. Install Notesnook from [Homebrew Cask](https://github.com/Homebrew/homebrew-cask/blob/HEAD/Casks/notesnook.rb)
2. Launch the appplication
3. Wait for the `New version is available` popup
4. Click `Update now`
5. Wait for the `Update ready for installation` popup
6. Click `Install now`
7. Restart the application

### Version

2.1.6

### Platform/OS

macOS

**Comment by thecodrr** [comment]
Hey, you'll have to install the update from Homebrew as well. Other ways won't work.

**Comment by ikurek** [comment]
In that case, shouldn't this feature be disabled in builds that do not use ? I'm guessing a similiar case may happen for other MacOS / Linux package managers, and it's really annoying to get the update popup each time the application is opened 😞

Maybe an alternative, simpler solution may be a `don't ask again` button to silence the update popup for current version?

**Comment by thecodrr** [comment]
The issue is that currently there is no way to detect if you installed via brew or not.
