### ISSUE TITLE
Some Suggestions

### ISSUE THREAD

**Issue by matt873** [streetwriters/notesnook#1111]
### What problem are you facing?

Here are some suggestions I've made. If helpful, kindly add them later.

### What's the solution you'd like to see in Notesnook?

1. If a note's title is blank, the first few words of the note's body should serve as the title rather than the date, as it does in ColorNote. Finding notes without titles would be simpler as a result.
2. Make the date labels, in the list view on the homepage, small.
3. And the date of the note should be displayed to the right of it.
4. To make it easier to distinguish between notes in the list view on the homepage, add green up-and-down lines for spacing. This is also how ColorNote does it.

**Comment by thecodrr** [comment]
Closing as these suggestions are no longer relevant to Notesnook.
