### ISSUE TITLE
Syncing issues: Having users solve merge conflicts is an atrocious UX

### ISSUE THREAD

**Issue by koraa** [streetwriters/notesnook#1112]
### What happened?

First of all thank you for writing such a useful application such as notesnook.

I was evaluating the app for two weeks and finally decided to buy pro at the start of the week; then yesterday, I updated the app on my mobile phone (using the normal app store – it's open source, why can I not install it through ~android~ **fdroid**). It told me to create a backup which is odd enough: Why are you not storing those backups automatically somewhere online? It also gave me a "migration progress"…again, why? This is a payed for app, even on servers I host myself I haven't seen migration dialogues for a decade. Migration should happen on the fly and reliable enough to not create issues.

I am not sure what happened, but I kept writing some notes wanted to type a ToDo in bed…when I was presented with a merge dialog. It took me a few moments to get what was happening and to realize I could just choose which of the two versions to use. Then I got another opaque "apply changes" dialogue (what other choice is there) and I was asked if I want to create a backup (why is this not happening automatically, behind the scenes? When would I ever choose not to create a backup).

Today I noticed the entire thing could not sync because another note had merge issues, but I did not find a way to know which note it is. I had to manually open my notes and find the one with the conflicts. Why is notesnook not at least showing me which note has conflicts? Why is another note having a merge conflict blocking me from editing my current note?

There is so many things that could be done to improve the user experience; how about using an automatic merge algorithm? How about tracking my updates to todo lists semantically so notesnook notices I just added some entries from another device? Why is notesnook not storing the merge conflict semantically as part of the document, so I can add my todo at 11 PM in peace and resolve the merge conflict some time later?

I happen to be a very technical user, but most users but a non-technical user would not even know what a merge conflict is…things like this lead to a lot of loss of users.

### Steps to reproduce the problem

I suppose for some technical reason, performing an upgrade on one device but not on the other blocks synchronization…

### Version

2.2.1

### Platform/OS

Android

**Comment by verymilan** [comment]
I would like to +1 one possibly related or partially the same problem (iOS), but also with a little story:
I use Notesnook in our Henhouses to write down the number of eggs i find – even tho in most of them there is bad to no signal, it worked fine _for over a month(!)_ – but it looks like it only managed to save the first one from yesterday, everything else is lost and i was stranded in a mergeconflict. 

I actually came here because i thought that there was a bug when applying a merge, because i really did not realize that i have to do a second action to discard the upstream note after having already chosen to merge the local version. This really should be improved. :)

**Comment by koraa** [comment]
Can we open this again? After a recent update I was *again* forced to manually merge things

**Comment by thecodrr** [comment]
> I was again forced to manually merge things

Manual merge has not been (and will not be) removed. Did you get a merge conflict on all your notes just like before?

I have changed the merge conflict detection algorithm to ignore semantic differences between documents. Merge conflicts are important if they occur when it makes sense. They do get annoying if they happen unintentionally though.

**Comment by koraa** [comment]
> > I was again forced to manually merge things
> 
> Manual merge has not been (and will not be) removed. Did you get a merge conflict on all your notes just like before?

I got a merge conflict on my most frequently edited note.

> I have changed the merge conflict detection algorithm to ignore semantic differences between documents. Merge conflicts are important if they occur when it makes sense. They do get annoying if they happen unintentionally though.

They happen because the sync fails and I switch frequently between phone and browser editing; I haven't edited during a long downtime or done anything that would conceivably trigger a long downtime; I had to manually press the "sync now" button, that started to improve things and wait to edit before the sync completes.

Merge conflicts make sense in a git repository where you need full control over the content you upload; if I needed my notes to be in a git I would use a git repo. This is an app I primarily use to create and check todo lists in addition to some other stuff.

I do nothing there that reasonably would resolve in a destructive merge if done automatically if more changes where tracked semantically as opposed to tracking them on document level.

I should not be prevented from creating a todo item just because of a flaky sync; if once in a blue moon a merge conflict happens, OK fine. Please give me the tools to (1) defer the problem and keep taking notes on my phone (2) allow me to perform a proper three-way merge on my phone later.
