### ISSUE TITLE
Accept Cryptocurrency payments

### ISSUE THREAD

**Issue by pluja** [streetwriters/notesnook#1125]
### What problem are you facing?

I would love to pay for the "Pro" version, but I don't want to give my card details.

### What's the solution you'd like to see in Notesnook?

I would love to be able to pay with Cryptocurrencies. In particular, with Monero (the most private cryptocurrency available).

There are many platforms that let you accept Monero and Bitcoin as payment options (along with many other cryptocurrencies). Here are some of these:

- https://plisio.net/
- https://www.coinpayments.net/
- https://nowpayments.io/
- https://www.cdpay.eu/

On the other hand, with a more "complex" setup, and if you don't want to pay fees, you could set up a [BtcPayServer](https://btcpayserver.org/) to accept Bitcoin [and Monero](https://sethforprivacy.com/guides/accepting-monero-via-btcpay-server/).

### What alternatives have you considered?

Accepting cash by mail could be another good option, although less convenient.

**Comment by trymeouteh** [comment]
Please accept bitcoin and Monero payments

**Comment by trymeouteh** [comment]
https://bitcartcc.com/

BitcartCC accepts Bitcoin, Bitcoin Cash, Litecoin and Monero.

**Comment by thecodrr** [comment]
There's no plan on supporting crypto payments due to legal issues in Pakistan regarding crypto.

**Comment by maxiim3** [comment]
People looking for privacy and E2E will by design go for a non KYC system. that's a weird decision
