### ISSUE TITLE
Native window title bar in Windows (10, 11)

### ISSUE THREAD

**Issue by McBaumwolle** [streetwriters/notesnook#1130]
### What problem are you facing?

The current status bar of Notesnook in Windows is always white no matter the theme. It also is very "think" like in older applications. 

### What's the solution you'd like to see in Notesnook?

Adaptive status bar for light and dark theme, eventually even the new layout (thicker) but adaptive colours would be enough. 

### What alternatives have you considered?

An option to hide it completely or (if the integration of this feature is too messy) just don't implement it I could use the web version (it is the same). 

### Additional context

![image](https://user-images.githubusercontent.com/67203883/193878192-dfb9d81f-0bc5-4905-ab93-2092f18a03fc.png)
Notesnook 

![image](https://user-images.githubusercontent.com/67203883/193878240-15247f42-0f0f-4b3f-9a5b-fcbd7b94286b.png)
native application

**Comment by thecodrr** [comment]
This is already under discussion at #1086

**Comment by McBaumwolle** [comment]
Oh sorry I forgot to check.
