### ISSUE TITLE
Multiple Accounts

### ISSUE THREAD

**Issue by trymeouteh** [streetwriters/notesnook#1133]
### What problem are you facing?

Unable to be logged into multiple accounts at once.

### What's the solution you'd like to see in Notesnook?

The ability to be logged into multiple accounts/profiles and switch between them in the client.

This will allow users to have a work account, personal account, family account, etc.

To have the ability to have unlimited online and offline account/profiles

**Comment by thecodrr** [comment]
This will not be supported. Instead we'll be offering workspaces support so users can create multiple workspaces under one account/subscription.

**Comment by trymeouteh** [comment]
Would be nice to be able to have one account siloed to yourself, that does not connect and share notes with anyone and a secondary account for interacting with others and sharing notes.

**Comment by trymeouteh** [comment]
Also when Self hosting becomes availble, it would be nice to be able to have an account on your self hosted server and the Notesnooks server. The self hosted server account can be ones private account and the notesnook account can be used to share notes with others.

To prevent abuse of users from having several free accounts, have the Notesnook app only allow one free account login on the notesnook server. And allow unlimited paid Notesnook accounts.

**Comment by aescgar** [comment]
> This will not be supported. Instead we'll be offering workspaces support so users can create multiple workspaces under one account/subscription.

I was looking at the various features of Notesnook and messing around in my account, mainly looking for a way to share a note or notebook with another user so we could collaboratively edit notes. I saw your mention of a workspace but didn't see any open issues about it. Where I can I go to read about this planned feature? Also, is it like I expect in that it let's users collaborate?
