### ISSUE TITLE
Reminders - One Time Reminders & Repeated Reminders

### ISSUE THREAD

**Issue by trymeouteh** [streetwriters/notesnook#1134]
### What problem are you facing?

Unable to add reminders to notes

### What's the solution you'd like to see in Notesnook?

The ability to add reminders to notes

- One time reminders
- Repeated reminders

A one time reminder will be a note which when it reaches the date and time, it will notify you via a notification of the note and delete the reminder on the note. A repeated reminder will will be a note which when it reaches the date and time, it will notify you via a notification of the note and wait until the next date and time is reached and notify the user again and again.

**Comment by toshi2d** [comment]
+ 1

**Comment by thecodrr** [comment]
These are coming in next version.
