### ISSUE TITLE
Note History

### ISSUE THREAD

**Issue by trymeouteh** [streetwriters/notesnook#1135]
### What problem are you facing?

Viewing and restoring older version of my notes.

### What's the solution you'd like to see in Notesnook?

A setting to enable note history and to be able to keep older versions of notes. Note history can work in the following way...

- Unlimited note history (Will stop when you run out of space)
- Delete older notes after X amount of versions
- Delete older notes after X days

**Comment by thecodrr** [comment]
This already exists in Notesnook. You can access it by opening the Note properties from the editor.
