### ISSUE TITLE
Drawing/Writing/Image Editor

### ISSUE THREAD

**Issue by trymeouteh** [streetwriters/notesnook#1136]
### What problem are you facing?

Being able to draw, write with a stylus and have a basic image editor to edit JPG and PNG files.

### What's the solution you'd like to see in Notesnook?

Being able to draw, write with a stylus and have a basic image editor to edit JPG and PNG files.

To have text notes and image notes.

**Comment by thecodrr** [comment]
Duplicate of #996 and #895
