### ISSUE TITLE
Sharing notes to users on different servers (Federation)

### ISSUE THREAD

**Issue by trymeouteh** [streetwriters/notesnook#1137]
### What problem are you facing?

Once self hosting becomes available, the ability to share notes with other users on different servers.

### What's the solution you'd like to see in Notesnook?

A E2EE secure and private way to share notes to other users who have accounts on different servers. This way if you have an account on the official Notesnook server and your friend Steve who likes to self host has an account on his own self hosted server. With you making an account on Steves server or Steve having to make an account on Notenooks official servers you can both share notes between each other with your own accounts on different servers.

**Comment by nettnikl** [comment]
As i understand, this could be related to https://github.com/streetwriters/notesnook/issues/966

**Comment by thecodrr** [comment]
Federation is out of scope of Notesnook.
