### ISSUE TITLE
App Lock on Desktop/Web app

### ISSUE THREAD

**Issue by trymeouteh** [streetwriters/notesnook#1140]
### What problem are you facing?

Adding an app lock on the desktop app

### What's the solution you'd like to see in Notesnook?

Having an app lock on the desktop app. Requires a password to unlock app when launching the app and an optional setting to lock the app after X minutes.

**Comment by umbellipher** [comment]
Auto-lock after a period set by user would make a whole world of difference to my use - if it renders the database of notes searchable.

I wish this could be done.

Notesnook is practically perfect, that apart!

**Comment by umbellipher** [comment]
May I briefly re-open this and refer to #1669. To say thank you for having added this to v3. I never thought time-based auto-lock would happen, and it has made a world of difference to my use of NS. Many thanks!
