### ISSUE TITLE
Saving custom colors to the palette

### ISSUE THREAD

**Issue by mockinbirdy** [streetwriters/notesnook#1148]
### What problem are you facing?

I cannot find a way to save my custom color for highlighting. If I want to use less opaque colors I believe I have to manually adjust them each time I need to highlight something? Let's say, I just want to use #F8DEDE highlight color every time. But apparently my android app does not allow me to save it to the palette. It is very time-consuming to create new colors each time and the inability to use the exact same color also frustrates me. 

Am I missing something or there is really no way to use the exact same color each time?

### What's the solution you'd like to see in Notesnook?

Save custom colors to the palette (at least one!)

**Comment by McBaumwolle** [comment]
I would really appreciate this too.

**Comment by McBaumwolle** [comment]
Another missing thing/suggestion for this would be to make the color-code a text field, so you can copy the code. I tried to format a cell in the light grey the header automatically is and did not get a match after several tries.
