### ISSUE TITLE
Add skip registering link on the same page as that of "Create Your account" button

### ISSUE THREAD

**Issue by alanjacobmathew** [streetwriters/notesnook#1149]
### What problem are you facing?

When getting started on Android, the app will ask for creating account. Although on the very next page there is a 'skip for now link' there are chances where users feel this like a roadblock. 

Say I wanted to simply try the app, and all I see is a "Create your account", I won't even click the button, and close the app. I will never come to know that there is a skip account link in the very next page and I can use the app without the account.

### What's the solution you'd like to see in Notesnook?

Either bring that skip for now link to the page where create account button is currently placed, or change the wordings to something more open like "Try now" and on the next page, users can choose to register or skip without registering

**Comment by thecodrr** [comment]
I think this is a reasonable suggestion.

**Comment by ammarahm-ed** [comment]
Added.
