### ISSUE TITLE
Option to add custom server url in notesnook apps

### ISSUE THREAD

**Issue by navilg** [streetwriters/notesnook#1162]
### What problem are you facing?

I am not facing problem as of now. As I see roadmap, sync server / self host is going to be open sourced, this feature would be required.

### What's the solution you'd like to see in Notesnook?

An option to add custom url in notesnook app incase user is using his self hosted sync server. This feature in parallel with sync server open source release would be great.

**Comment by ammarahm-ed** [comment]
Hi, this is on the roadmap. We are planning to open source sync server early next month.
