### ISSUE TITLE
increasing icons size on the primary side bar?

### ISSUE THREAD

**Issue by RadioRambo** [streetwriters/notesnook#1165]
![image](https://user-images.githubusercontent.com/64721943/194795258-1fd9dda0-8718-43a2-95d6-d4d9fc1caaa2.png)

Icons are so small and hard click on big screens.  size of like vscode activity bar would be better. What are your thoughts?

**Comment by thecodrr** [comment]
I am against this change as it would conflict with the overall UI of the app.
