### ISSUE TITLE
Cannot get passed "Your session has expired" page on Desktop

### ISSUE THREAD

**Issue by candroid-man** [streetwriters/notesnook#1168]
### What happened?

![image](https://user-images.githubusercontent.com/51019003/194934429-166055b3-98f3-456f-869b-8a62c586edf4.png)

I am unable to get passed this screen. After entering my password (which is saved in a password manager), it loads, refreshes, and then takes me straight back to this screen. To login, I ended up having to click the "Logout permanently" button and enter my info once more.

### Steps to reproduce the problem

N/A

### Version

2.2.1-cd9096d-desktop

### Platform/OS

Linux

**Comment by thecodrr** [comment]
This has been fixed and will be part of the next release!
