### ISSUE TITLE
App freezes when attempting to create more than 3 Notebooks without paid subscription

### ISSUE THREAD

**Issue by Leviob** [streetwriters/notesnook#1171]
### What happened?

When trying to create more than 3 notebooks by tapping the + using the free version, either
1. the app freezes and needs to be reopened, or
2. the app lets me type in a name for the notebook, but does not create it, then freezes and needs to be reopened. 

In other places in the app, when you try to use a premium feature, there is a popup to signup for pro / try trial, but not here. 

### Steps to reproduce the problem

Create multiple notebooks without a premium subscription. 

### Version

2.2.2

### Platform/OS

iOS

**Comment by ammarahm-ed** [comment]
Hi, this has been fixed.
