### ISSUE TITLE
Tags do not update and do not work anymore

### ISSUE THREAD

**Issue by mockinbirdy** [streetwriters/notesnook#1176]
### What happened?

So I'm currently trying a free version. It's limited to 5 tags, I get it but.
After changing the name of a tag, it doesn't update its name in notes.

Let's say I changed my tag `job` to `work`. I want to mark my note with an updated tag `work` but tags section in my note still shows me `job` as the only option. This is the first bug.

And as of today, I cannot tag my notes anymore for some reason. It keeps saying 'please upgrade to pro' but I'm not trying to use any pro features. I want to use my 5 tags, that's it. 

### Steps to reproduce the problem

Fix this error

### Version

web

### Platform/OS

Chrome/Chromium

**Comment by ammarahm-ed** [comment]
Hey I was able to reproduce both issues. Will fix these asap. thanks for reporting

**Comment by mockinbirdy** [comment]
Hi, when I delete or change the name of any of my tags, this bug starts occurring again. Once again it shows me 'upgrade to pro' pop-up.
