### ISSUE TITLE
Save window layout / column sizes

### ISSUE THREAD

**Issue by 0scvr** [streetwriters/notesnook#1189]
### What problem are you facing?

Whenever I open Notesnook on my laptop (running windows 11) the layout/size of the 3 colums gets reset and looks like 3 similarly-sized columns. However this isn't how I like my layout to be. I usually resize the left column to the smallest it can go and shrink the middle one a bit too. Unfortunately I have to do this everytime I close and reopen the app.

### What's the solution you'd like to see in Notesnook?

It would be nice to save the layout/size of the 3 main columns somewhere so that I don't have to resize them each time.

As far as I can tell this is already working on macOS but not on the windows desktop version.

### Additional context

I'm using Windows 11 with Notesnook 2.2.1-cd9096d-desktop

**Comment by thecodrr** [comment]
@0scvr are you still facing this issue?

**Comment by thecodrr** [comment]
This should be fixed in the latest versions.
