### ISSUE TITLE
Web app doesn't work well on Android

### ISSUE THREAD

**Issue by KatoriYuu** [streetwriters/notesnook#1198]
### What happened?

The web page just freezes.

### Steps to reproduce the problem

Open [the web app](https://app.notesnook.com) in Chrome.

### Version

2.2.1-aa27c27-web

### Platform/OS

Android, Chrome/Chromium

**Comment by thecodrr** [comment]
Hi, I am not able to reproduce this. Which version of Google Chrome are you on?

**Comment by KatoriYuu** [comment]
It's version 106.0.5249.79. The browser actually is Vanadium, a Chromium fork featured in GrapheneOS. However, the problem is also reproducible in Brave Browser 1.44.105.

**Comment by KatoriYuu** [comment]
It turns out that I can still swipe left to navigate to the menu, but clicking buttons, like the "menu" or "create new" button, doesn't work at all.

**Comment by thecodrr** [comment]
@KatoriYuu the web app experience on mobile isn't that good. I'll see if it can be improved but it's not a priority as we provide native apps on all mobile platforms.
