### ISSUE TITLE
Suggestion: advertise that importing is happening client-side

### ISSUE THREAD

**Issue by altano** [streetwriters/notesnook#12]
In [your reddit announcement of the importer](https://www.reddit.com/r/Notesnook/comments/njxeo8/notesnook_importer_import_your_notes_from_other/) you said:

> Oh and by the way, we kept to our privacy promise: everything happens on the client side inside your browser.

It might be good to advertise this in the importing page on the website. When it started importing I assumed it was going through Notesnook's servers and I was relieved when I read the reddit post.

**Comment by thecodrr** [comment]
Done.
