### ISSUE TITLE
Add option to disable tab navigation

### ISSUE THREAD

**Issue by developomp** [streetwriters/notesnook#1213]
### What problem are you facing?

I use the <kbd>tab</kbd> key very often because many of my documents are almost entirely composed of lists, and pressing <kbd>tab</kbd> / <kbd>shift</kbd>+<kbd>tab</kbd> is an easy way to change the indentation. However, the inconsistent behavior of notesnook is causing a bit of a frustration because when there is no more list to de-indent, pressing <kbd>shift</kbd>+<kbd>tab</kbd> brings me out of the editing area, so I often find myself clicking random buttons every once in a while. Also, pressing <kbd>tab</kbd> again does not immediately bring me to the edit area for some reason.

### What's the solution you'd like to see in Notesnook?

While completely deactivating tab navigation while in edit mode would be the best option for me (as a user coming from Joplin + vscode), since there are legitimate use cases for it especially for table editing, a much more reasonable middle-ground would be to add a toggle setting that disables tab navigation.

**Comment by thecodrr** [comment]
This is coming in the next version. See issue #443 & PR #1193

**Comment by developomp** [comment]
Please reopen this issue. The pr you linked does not solve the shift tab issue which is my main complaint.
