### ISSUE TITLE
Importing OneNote notes with importer fail

### ISSUE THREAD

**Issue by konradphoto** [streetwriters/notesnook#1214]
### What happened?

I tried twice to import my OneNote notes to notesnook using https://importer.notesnook.com/ . I successfully verified my account with MIcrosoft and gave the importer the appropriate access rights. The importer started processing the notes and pages and everything seemed fine until it finished. It says:
- 0 Notes found;
- 172 error occured.

The errors are:
- a few 
`. Failed to get sectionGroup (original error: The specified resource ID does not exist.). (Request failed with status code: 404).`
- lots of 
`Ha is not a function (page: Rota Vicentina)`
<img width="673" alt="Screenshot 2022-10-17 at 21 29 35" src="https://user-images.githubusercontent.com/39724928/196266044-5754a499-a1bb-4aec-a7f8-c2b531c37653.png">

### Steps to reproduce the problem

1. Open https://importer.notesnook.com/ (Notesnook Importer (v1.4.1) using Firefox 105.0.3 (64-bit) (Max oS X 12.6)
2. authenticate with Microsoft account and grant the importer access to OneNote
3. start the migration

### Version

Notesnook Importer (v1.4.1)

### Platform/OS

macOS

**Comment by thecodrr** [comment]
This has been reported in https://github.com/streetwriters/notesnook-importer/issues/35 & fixed in v1.4.2.
