### ISSUE TITLE
Linux Version is Blurry With Fractional Scaling

### ISSUE THREAD

**Issue by ImranR98** [streetwriters/notesnook#1226]
I'm on Fedora 37, using the Notesnook `rpm`, and the UI is very blurry since I turned on fractional scaling in the OS. I believe this only happens for Apps that do not support Wayland (XWayland isn't enough) since I had the same issue with Firefox and it was fixed by switching on the Wayland setting. Could Notenook be updated to support this? As more Linux users switch to Wayland by default this will be a problem. For now the only solution is to use the Web version.

**Comment by thecodrr** [comment]
Hey, can you try the latest flatpak version? It supports Wayland by default.

If you can't do that then you can manually start the app with these flags:
```
notesnook --ozone-platform-hint=auto --enable-features=WaylandWindowDecorations
```

**Comment by ImranR98** [comment]
Thanks, I was not aware of the Flatpak. It isn't blurry (it does have another problem - the mouse cursor is tiny - but that's a separate issue).

**Comment by muznyo** [comment]
> Thanks, I was not aware of the Flatpak. It isn't blurry (it does have another problem - the mouse cursor is tiny - but that's a separate issue).

that's why i use .rpm package, the cursor is normal sized

**Comment by ImranR98** [comment]
Apparently it's a general Flatpak issue:
https://github.com/flatpak/flatpak/issues/5114

**Comment by AdmerStroh** [comment]
The cursor issue with the notesnook flatpak can be fixed by setting
`XCURSOR_PATH=/run/host/user-share/icons:/run/host/share/icons`
