### ISSUE TITLE
Code block doesn't show syntax highlights

### ISSUE THREAD

**Issue by unomi-zan** [streetwriters/notesnook#1247]
### What happened?

As the title suggests, the code block doesn't show syntax highlights. This issue can be seen on the desktop, android and even on the published notes.

![Screenshot_20221027-000239984](https://user-images.githubusercontent.com/79187956/198107100-00c16708-519c-4bee-aa92-1ada1ec6ecfa.jpg)

This issue can be solved temporarily by selecting the code block or closing the note and opening it again. However, it'll be the same after closing the app.

### Steps to reproduce the problem

- create a note with a code block
- close and reopen the app
- open the same note again 

### Version

v2.2.4

### Platform/OS

Linux, Android, Firefox

**Comment by thecodrr** [comment]
I can confirm this. Would you be willing to work on a fix for this? I'd be happy to guide you along.

**Comment by unomi-zan** [comment]
I'm sorry. But I don't have experience in coding
