### ISSUE TITLE
Functions

### ISSUE THREAD

**Issue by toshi2d** [streetwriters/notesnook#1260]
### What problem are you facing?

When i'm trying to create table and i can't do some basic calculations using it. Excel, like sum and other.

### What's the solution you'd like to see in Notesnook?

Add functions support

**Comment by thecodrr** [comment]
Hey, the table is not an excel sheet and this is out of scope of Notesnook. You can use any excel-like spreadsheet software to do this and then copy paste it into Notesnook.
