### ISSUE TITLE
breadcrumb trail in note 

### ISSUE THREAD

**Issue by sharemind** [streetwriters/notesnook#1276]
### What problem are you facing?

In the android app while reading a note loose track of the position of the note in the notebook/topic structure. 

### What's the solution you'd like to see in Notesnook?

It will be useful to have a breadcrumb navigation inside the note on the top.

**Comment by thecodrr** [comment]
The problem is to decide which notebook/topic to show since a note can be in multiple topics/notebooks.

**Comment by sharemind** [comment]
If I am not wrong, since from the last update is possible to link a note only to one notebook or topic, and in future release the app may have a structure with deeper levels, a crumb trail: in the notes list view and when editing a note will be useful IMHO.
