### ISSUE TITLE
Start/Launch delay

### ISSUE THREAD

**Issue by JLuc** [streetwriters/notesnook#1277]
### What happened?

On my computer, apps usualy take a second or less to launch, but notesnook takes very long (about a minute) the first time.
OS is Ubuntu 22.04
Further starts are not so long.

### Steps to reproduce the problem

- install
- run

### Version

Says "you are on the latest version"

### Platform/OS

Linux

**Comment by thecodrr** [comment]
How did you install the app? Snap? flatpak?

**Comment by JLuc** [comment]
Yes it's a snap.

**Comment by JLuc** [comment]
I've downloaded the appimage and it looks much faster to launch

**Comment by thecodrr** [comment]
Snaps are horribly slow to launch. Not an issue specifically with Notesnook.
