### ISSUE TITLE
Date in Note title

### ISSUE THREAD

**Issue by sharemind** [streetwriters/notesnook#1278]
### What happened?

The Mac OS app create the automatic Note tile as follow:

Note 11/3/22, 10:56 AM

while the Android and Web App as follow:

Note 03/11/22, 10:57

It should have the same date and time format

### Steps to reproduce the problem

Create a new note.

### Version

Versione 2.2.3 (222)

### Platform/OS

macOS

**Comment by Romancha** [comment]
Same issue

**Comment by thecodrr** [comment]
Marking as duplicate of #959
