### ISSUE TITLE
Nesting Notebooks on the left tab under "Notebooks"

### ISSUE THREAD

**Issue by konradphoto** [streetwriters/notesnook#1288]
### What problem are you facing?

Sometimes when I look for a note or a topic (when I don't use the search function) I don't remember in which notebook the topic or the note is so I open the notebooks one by one. When I open a notebook, in order to go back and see the list of all of my notebooks, I have 'click' with a mousebutton but I would like to have the list of my notebooks constantly visible so I can quickly decide which notebook to open next without having to go back to the list of notebooks.

### What's the solution you'd like to see in Notesnook?

I definetely DO NOT want to have another panel because it would take away the available space for the notes (on the right hand side). I wonder if having the notebooks nested on the left side would be possible (see the screenshot)
<img width="165" alt="Screenshot 2022-11-05 at 10 33 25" src="https://user-images.githubusercontent.com/39724928/200113343-daca4dc2-26fd-4998-ad0e-83f8e847ccbe.png">

**Comment by thecodrr** [comment]
Hey, this has been discussed before and it's not a good idea. The space there is quite limited and it would clutter up the UI more.

Another option we have discussed is to show recently opened notebook on hover/long tap but nothing has come out of that yet.
