### ISSUE TITLE
Can’t open a PDF attached to a note inside Notesnook

### ISSUE THREAD

**Issue by Edodaddo** [streetwriters/notesnook#1293]
I have a pdf attached to a note but, despite downloading it, then I can't open it because it can't find any pdf reader on my smartphone (despite having many already installed). 

If I go to the folder where I downloaded the pdf and open the file obviously I can open it using a pdf reader, the problem is that it is rather inconvenient in terms of time and it would be more useful to be able to open it directly in Notesnook by tapping on "Open" a once downloaded (but, as you can see from the video, it seems impossible to do so for some reason)

https://user-images.githubusercontent.com/97398741/200141886-468174f6-f5d6-420c-85aa-7daefc13e3e2.mp4

**Comment by thecodrr** [comment]
This has been fixed in v2.2.6
