### ISSUE TITLE
Sync doesn't work when on Mullvad VPN

### ISSUE THREAD

**Issue by konradphoto** [streetwriters/notesnook#1294]
### What happened?

I noticed that syncing doesn't work when I'm on Mullvad VPN. It is a bit of a deal breaker because one privacy tools shouldn't exclude another privacy tool.

Version 2.2.3 (222)
Mullvad Latest version: 2022.5
MacOS 12.6 (21G115)

### Steps to reproduce the problem

1. Turn on Mullvad VPN
2. createa a new topic/note
3. try to sync
4. open notesnook on the web
5. notes are not synced
6. turn off mullvad VPN
7. notes sync

### Version

Version 2.2.3 (222)

### Platform/OS

macOS

**Comment by thecodrr** [comment]
Thats not an issue on Notesnook side but Mullvad's side.

**Comment by konradphoto** [comment]
everything else works fine when I'm on Mullvad, even MS OneNote syncing works.

**Comment by TJonCooper** [comment]
Working for me without issue on Mullvad VPN (Desktop, Linux, WireGuard). Refresh your connection and try again.

**Comment by thecodrr** [comment]
Notesnook doesn't do anything special so there's very little reason to block it.
