### ISSUE TITLE
Highlight merge conflicts to make it easy to select between two

### ISSUE THREAD

**Issue by radiorambo** [streetwriters/notesnook#1304]
### What problem are you facing?

When ever there is a merge conflict, notesnook is asking to select one of two versions. But to select, I have to compare two versions word by word to know where it conflicts. Sometimes that is simple impossible on large notes 

### What's the solution you'd like to see in Notesnook?

Highlighting the conflicts would make it much easier, something like git diff.

### What alternatives have you considered?

none

**Comment by ammarahm-ed** [comment]
Hi, this has been added in v3. Thanks.
