### ISSUE TITLE
Caret moves to the beginning of parent list item if it has a child

### ISSUE THREAD

**Issue by abhishekarora12** [streetwriters/notesnook#131]
To reproduce:

1. Create a nested list in mac
2. Click on the parent list element
3. The cursor goes to the starting instead of the end

**Comment by ammarahm-ed** [comment]
I tried to reproduce this but could not. When you click on the parent list item, it should move the cursor to where you click on it, not the start or the end.

**Comment by abhishekarora12** [comment]
To rephrase, clicking on the end of list item doesn't focus there
It's the same for mac and android
[Video](https://imgur.com/nIyzndn)

**Comment by thecodrr** [comment]
Fixed in the new editor.
