### ISSUE TITLE
Winget update installs the new version but does not commit it to the system

### ISSUE THREAD

**Issue by pomazanbohdan** [streetwriters/notesnook#1318]
### What happened?

Winget update installs the new version but does not commit it to the system

### Steps to reproduce the problem

- install manual old version
-  winget upgrade --all
![image](https://user-images.githubusercontent.com/696713/201197822-8048d3b3-29a5-4c65-8f5f-9970fc9e31c4.png)

- after upgrade winget see only first version
![image](https://user-images.githubusercontent.com/696713/201198092-2851bffd-163f-485e-89bc-900cd3d03110.png)

### Version

2.2.3

### Platform/OS

Windows

**Comment by pomazanbohdan** [comment]
![image](https://user-images.githubusercontent.com/696713/201198537-b1ee7bd8-cdcf-44dd-b4f0-f76991bfcf5d.png)

**Comment by pomazanbohdan** [comment]
Removing the old version also removes the new one.

**Comment by thecodrr** [comment]
This doesn't seem like an issue with Notesnook though. I think it'd be more appropriate asking in the [winget](https://github.com/microsoft/winget-cli) repo.
