### ISSUE TITLE
Space left on the top of editor after deleting first list item

### ISSUE THREAD

**Issue by abhishekarora12** [streetwriters/notesnook#132]
If a list is at the top of note, after deleting the first item, the space left before the list can't be removed by delete button in mac

**Comment by thecodrr** [comment]
I couldn't reproduce this on v1.6.11, can you test again?

**Comment by abhishekarora12** [comment]
**Describe the bug**
I'll rephrase - Pressing delete button on mac when the caret is at the top of the page even when there is content on the page, doesn't do anything

**Ideal Behavior**
The delete button should delete the top empty line and move to the title, so the list also comes to the top

**Screenshare**
https://user-images.githubusercontent.com/12087783/146254918-a861442b-b4ce-44bc-a155-01f4c611d703.mov

**Device**
 - OS: OS X 10.15.7
 - Browser Electron 15.0.0
 - App version: 1.6.11-f72f04a-desktop
 - Pro: true

**Comment by thecodrr** [comment]
> The delete button should delete the top empty line and move to the title, so the list also comes to the top

Delete button or backspace? Delete button is working as it should (i.e. deleting the empty line and moving the list back). The backspace doesn't work because there is literally nothing behind the caret. Title is not part of the editor space so you can't just jump to it.

**Comment by abhishekarora12** [comment]
There is only a delete button on mac

**Comment by abhishekarora12** [comment]
Have this same issue in **android** as well. Can't take the list to the top if you backspace the first element in the list.
@thecodrr Please open this issue again.

**Comment by Tamnac** [comment]
@thecodrr I think the issue is there is no way to delete an empty first line except by backspacing from previous line. To see how this is a problem, try this:

1. Make a new note
2. Write some text in first line
3. make a table on the second line
4. delete text in the first line

You now have a blank first line with no way to remove it, or move the table to the top.

**Comment by thecodrr** [comment]
Perhaps what we can do is to also allow backspacing the first empty line if it exists.
