### ISSUE TITLE
Adding/Deleting empty lines before/after todo lists is buggy

### ISSUE THREAD

**Issue by koraa** [streetwriters/notesnook#1364]
### What happened?

Adding text before a todo list is hard when it's the first item in a document. (I know there are ways but they are hacky es hell).

Deleing an empty line before the first todo list also creates artefacts.

Deleting an empty line after a todo list creates a *new* todo list point; but it should place the cursor on the end of the last todo.

I could spell it all out properly, but I am trying to create todos. Please do some UX testing, right now it feels extremely buggy.

### Steps to reproduce the problem

--

### Version

--

### Platform/OS

Windows, macOS, Linux, iOS, Android, Chrome/Chromium, Firefox, Safari, Other browser

**Comment by AqidaHaidari** [comment]
> ### What happened?
> Adding text before a todo list is hard when it's the first item in a document. (I know there are ways but they are hacky es hell).
> 
> Deleing an empty line before the first todo list also creates artefacts.
> 
> Deleting an empty line after a todo list creates a _new_ todo list point; but it should place the cursor on the end of the last todo.
> 
> I could spell it all out properly, but I am trying to create todos. Please do some UX testing, right now it feels extremely buggy.
> 
> ### Steps to reproduce the problem
> --
> 
> ### Version
> --
> 
> ### Platform/OS
> Windows, macOS, Linux, iOS, Android, Chrome/Chromium, Firefox, Safari, Other browser
> 
> ### Relevant log output
> _No response_

@thecodrr what is the exactly expected behavior? if there's any additional information please provide me I want to get started on this.
