### ISSUE TITLE
Responsiveness on small windows

### ISSUE THREAD

**Issue by koraa** [streetwriters/notesnook#1365]
### What problem are you facing?

I am creating two windows side by side to edit two todo lists at the same time; I can use focused mode but that is extra work. Notesnook should automatically switch to a horizontal layout when there is not enough window estate for the vertical layout. 

### What's the solution you'd like to see in Notesnook?

--

**Comment by thecodrr** [comment]
> Notesnook should automatically switch to a horizontal layout when there is not enough window estate for the vertical layout.

Not sure what you mean by this.

**Comment by koraa** [comment]
Well instead of doing this

    sidebar | folders | note

it should go to this

    sidebar
    --------
    folders
    --------
    note

Oh and what I also notice is that on a narrow window, the focus mode button is unreachable:

![20221122_08h32m02s_grim](https://user-images.githubusercontent.com/1451261/203252566-0779b130-d6c4-4007-9008-89c41f7c00dc.png)

I would have expected the three dots to open a dropdown so I can reach focus mode, instead it opens the settings (which is a bit unusual) and the settings are also unusable on narrow windows.

![20221122_08h31m46s_grim](https://user-images.githubusercontent.com/1451261/203252731-97b5c29a-f6a7-450d-b7fd-5fc566bfa55c.png)

**Comment by koraa** [comment]
Note also how in the screenshots my (long) email address and the "33s ago" are crumbled together; it's hard to see because I censored my notesnook email.

**Comment by thecodrr** [comment]
This is definitely a bug.
