### ISSUE TITLE
Cannot add sublists and subquotes 

### ISSUE THREAD

**Issue by Sharath44665** [streetwriters/notesnook#1377]
### What happened?

# Issue 1: Cannot add sub lists like this:

> Example1: 
### Hello World
- point to remember1
- point to remember2
  1. sublist1 unable to add
  2. sublist2 unable to add

***
# Issue 2:  cannot add quote inside quote:
> example2:

> quote text
>> subquote text, which is not possible via this app.

***
# Feature request: 
1. Please add support for editing text via Markdown.
2. This app is open source, but attaching files is now a premium option. **Please make this as free** ( Its free in [Evernote](https://www.evernote.com/) and [One Note](https://www.onenote.com/), and of course everything is free in _[Joplin](https://flathub.org/apps/details/net.cozic.joplin_desktop)_ )

### Steps to reproduce the problem

NA

### Version

latest version available on flathub

### Platform/OS

Linux

### Relevant log output

```shell
NA
```

**Comment by thecodrr** [comment]
What happens when you try to add sublists? Sub quotes aren't yet possible I think and not sure if they even make sense. What is your use case?

Attachments are a premium feature and they aren't going to be free.
