### ISSUE TITLE
Note doesn't save if just pasting in android without giving a title

### ISSUE THREAD

**Issue by abhishekarora12** [streetwriters/notesnook#144]
Note doesn't save if i just paste in android without giving it a title. And the most important thing is that it doesn't give any alert that the note won't get saved and just goes back to the previous screen.

**Comment by ammarahm-ed** [comment]
Can you tell me what you did. I am pasting at it saves. Did you paste something and then immediately close the editor with back press button?

**Comment by abhishekarora12** [comment]
yes i just pasted something and then pressed back and the note wasn't there. This was a very important note so fortunately i looked at that time, otherwise it would have been gone. There should be an alert at least that the note won't get saved if i press back

**Comment by ammarahm-ed** [comment]
Note should always get saved when you press back. Fixing this right now.

**Comment by ammarahm-ed** [comment]
Fixed in latest version. v1.6.92
