### ISSUE TITLE
Sync on Windows Desktop toggling between now and 0%

### ISSUE THREAD

**Issue by jermany182** [streetwriters/notesnook#1448]
### What happened?

Sync is working, but sync toggles between "0% downloading" and "now".  This is the first time I've used the windows desktop app, so don't know if this is normal or not.  I saw where you requested sync logs from people when I searched for this issue, so if you need those, please let me know how to retrieve them for you, or if it's just the generic "Download Logs" option.

### Steps to reproduce the problem

downloaded windows version.

### Version

2.2.4-95dd846-desktop

### Platform/OS

Windows

**Comment by ammarahm-ed** [comment]
Hi, sync servers are down for maintenance. They will be up again soon.

**Comment by thecodrr** [comment]
This has been fixed in v2.3.0
