### ISSUE TITLE
Intallation failure

### ISSUE THREAD

**Issue by Iamhexi** [streetwriters/notesnook#1467]
### What happened?

I wasn't able to finish installation as it results in
`> prepare
> husky install && npm run bootstrap

husky - Git hooks installed

> bootstrap
> lerna bootstrap -- --legacy-peer-deps --no-audit

lerna notice cli v5.4.3
lerna info versioning independent
lerna info Bootstrapping 12 packages
lerna info Installing external dependencies
lerna ERR! npm install --legacy-peer-deps --no-audit exited 127 in '@notesnook/web'
lerna ERR! npm install --legacy-peer-deps --no-audit stderr:
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@standardnotes/common@1.45.0',
npm WARN EBADENGINE   required: { node: '>=18.0.0 <19.0.0' },
npm WARN EBADENGINE   current: { node: 'v16.18.0', npm: '8.19.2' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@standardnotes/security@1.7.0',
npm WARN EBADENGINE   required: { node: '>=18.0.0 <19.0.0' },
npm WARN EBADENGINE   current: { node: 'v16.18.0', npm: '8.19.2' }
npm WARN EBADENGINE }
npm WARN deprecated w3c-hr-time@1.0.2: Use your platform's native performance.now() and performance.timeOrigin.
npm WARN deprecated stable@0.1.8: Modern JS already guarantees Array#sort() is a stable sort, so this library is deprecated. See the compatibility table on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#browser_compatibility
npm WARN deprecated svgo@1.3.2: This SVGO version is no longer supported. Upgrade to v2.x.x.
npm WARN deprecated electron-osx-sign@0.6.0: Please use @electron/osx-sign moving forward. Be aware the API is slightly different
npm WARN deprecated electron-notarize@1.2.2: Please use @electron/notarize moving forward.  There is no API change, just a package name change
npm WARN deprecated asar@3.2.0: Please use @electron/asar moving forward.  There is no API change, just a package name change
npm ERR! code 127
npm ERR! git dep preparation failed
npm ERR! command /usr/bin/node /usr/lib/node_modules/npm/bin/npm-cli.js install --force --cache=/home/.../.npm --prefer-offline=false --prefer-online=false --offline=false --no-progress --no-save --no-audit --include=dev --include=peer --include=optional --no-package-lock-only --no-dry-run
npm ERR! > node-html-parser@5.1.0 prepare
npm ERR! > cd test && yarn install
npm ERR! npm WARN using --force Recommended protections disabled.
npm ERR! npm WARN EBADENGINE Unsupported engine {
npm ERR! npm WARN EBADENGINE   package: 'htmlparser-benchmark@1.1.3',
npm ERR! npm WARN EBADENGINE   required: { node: '0.10 || 0.11', npm: '1' },
npm ERR! npm WARN EBADENGINE   current: { node: 'v16.18.0', npm: '8.19.2' }
npm ERR! npm WARN EBADENGINE }
npm ERR! npm WARN deprecated stringify-package@1.0.1: This module is not used anymore, and has been replaced by @npmcli/package-json
npm ERR! npm WARN deprecated p-memoize@4.0.2: 4.0.2 has a bug which causes cache misses. Stay on 4.0.1 or upgrade to 5.0.0.
npm ERR! npm WARN deprecated @types/entities@2.0.0: This is a stub types definition. entities provides its own type definitions, so you do not need this installed.
npm ERR! npm WARN deprecated standard-version@9.3.2: standard-version is deprecated. If you're a GitHub user, I recommend https://github.com/googleapis/release-please as an alternative.
npm ERR! sh: line 1: yarn: command not found
npm ERR! npm ERR! code 127
npm ERR! npm ERR! path /home/.../.npm/_cacache/tmp/git-cloneMrd5kh
npm ERR! npm ERR! command failed
npm ERR! npm ERR! command sh -c -- cd test && yarn install
npm ERR! 
npm ERR! npm ERR! A complete log of this run can be found in:
npm ERR! npm ERR!     /home/.../.npm/_logs/2022-12-07T11_17_28_139Z-debug-0.log

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/.../.npm/_logs/2022-12-07T11_17_05_300Z-debug-0.log
lerna ERR! npm install --legacy-peer-deps --no-audit exited 127 in '@notesnook/web'
lerna WARN complete Waiting for 2 child processes to exit. CTRL-C to exit immediately.
npm notice 
npm notice New major version of npm available! 8.19.2 -> 9.1.3
npm notice Changelog: https://github.com/npm/cli/releases/tag/v9.1.3
npm notice Run npm install -g npm@9.1.3 to update!
npm notice 
npm ERR! code 127
npm ERR! path /home/.../notesnook
npm ERR! command failed
npm ERR! command sh -c -- husky install && npm run bootstrap

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/.../.npm/_logs/2022-12-07T11_16_36_667Z-debug-0.log
`

I've also attempted to install packages suggested by the installer, however, it haven't helped as well (it request yet another package and so on). I couldn't access the log files provided by npm installer as they don't exist.

### Steps to reproduce the problem

I've used command provided for installation process: cloned repository, changed directory to notesnook, run 'npm install' (both with and without root privileges) . I'm using Linux Manjaro.

### Version

2.3.0

### Platform/OS

Linux

**Comment by olluz** [comment]
I'm getting contradictive error messages regarding the required node version when trying to build 2.4.2

`> bootstrap
> lerna bootstrap -- --legacy-peer-deps --no-audit

lerna notice cli v5.4.3
lerna info versioning independent
lerna info Bootstrapping 13 packages
lerna info Installing external dependencies
lerna ERR! npm install --legacy-peer-deps --no-audit exited 127 in '@notesnook/web'
lerna ERR! npm install --legacy-peer-deps --no-audit stderr:
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@standardnotes/auth@3.19.4',
npm WARN EBADENGINE   required: { node: '>=14.0.0 <17.0.0' },
npm WARN EBADENGINE   current: { node: 'v18.12.1', npm: '8.19.2' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@standardnotes/features@1.58.0',
npm WARN EBADENGINE   required: { node: '>=16.0.0 <17.0.0' },
npm WARN EBADENGINE   current: { node: 'v18.12.1', npm: '8.19.2' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@standardnotes/models@1.42.0',
npm WARN EBADENGINE   required: { node: '>=16.0.0 <17.0.0' },
npm WARN EBADENGINE   current: { node: 'v18.12.1', npm: '8.19.2' }
npm WARN EBADENGINE }
npm ERR! code 127
npm ERR! git dep preparation failed
npm ERR! command /share/ZFS530_DATA/.qpkg/NodeJS18/bin/node /share/ZFS530_DATA/.qpkg/NodeJS18/lib/node_modules/npm/bin/npm-cli.js install --force --cache=/share/Allshare/Innovatone/QPKG_DEV/Notesnook/tmp/npm --prefer-offline=false --prefer-online=false --offline=false --no-progress --no-save --no-audit --include=dev --include=peer --include=optional --no-package-lock-only --no-dry-run
npm ERR! > node-html-parser@5.1.0 prepare
npm ERR! > cd test && yarn install
npm ERR! npm WARN using --force Recommended protections disabled.
npm ERR! npm WARN EBADENGINE Unsupported engine {
npm ERR! npm WARN EBADENGINE   package: 'htmlparser-benchmark@1.1.3',
npm ERR! npm WARN EBADENGINE   required: { node: '0.10 || 0.11', npm: '1' },
npm ERR! npm WARN EBADENGINE   current: { node: 'v18.12.1', npm: '8.19.2' }
npm ERR! npm WARN EBADENGINE }
npm ERR! npm WARN deprecated stringify-package@1.0.1: This module is not used anymore, and has been replaced by @npmcli/package-json
npm ERR! npm WARN deprecated p-memoize@4.0.2: 4.0.2 has a bug which causes cache misses. Stay on 4.0.1 or upgrade to 5.0.0.
npm ERR! npm WARN deprecated standard-version@9.3.2: standard-version is deprecated. If you're a GitHub user, I recommend https://github.com/googleapis/release-please as an alternative.
npm ERR! npm WARN deprecated @types/entities@2.0.0: This is a stub types definition. entities provides its own type definitions, so you do not need this installed.
`

node v18, v16 or even v0.10 ?

I wonder what I'm doing wrong ...

**Comment by aliwaqar981** [comment]
Some dependencies ask for version between node v16 or v17 while other requires node v18. Any solution for this?
