### ISSUE TITLE
Prevent from Screenshot and Screen Recording 

### ISSUE THREAD

**Issue by gracie95** [streetwriters/notesnook#1479]
### What problem are you facing?

I still able to take some important things within app with those methods. 

I recorded screen with Filmora and I took the picture with Snipping Tool.

### What's the solution you'd like to see in Notesnook?

You can make like KeePassXC, that able to block those methods above. 

After trying that, you'll see a blank window only. 

I cannot put attachments here because they're blank. 😁

**Comment by thecodrr** [comment]
Which platform are you on? I can take screenshots and everything else on Linux in KeePassXC.

**Comment by gracie95** [comment]
https://user-images.githubusercontent.com/107738923/206699758-3c8deedd-060a-48b9-916b-fea742009b6c.mp4

Here I recorded using phone.

**Comment by gracie95** [comment]
Yeah, because in mobile you had set it up (screenshot), but not for desktop. I think, it isn't fair.

**Comment by thecodrr** [comment]
Thanks for bringing it to our attention.

**Comment by thecodrr** [comment]
Checklist for what needs to be done:

- [ ] Add a new toggle setting for "Privacy mode" just like in mobile app (it should be hidden on Linux)
- [ ] Toggling this setting should enable/disable content protection
