### ISSUE TITLE
Firefox clipper on Linux

### ISSUE THREAD

**Issue by opennomad** [streetwriters/notesnook#1483]
### What happened?

I installed the firefox web clipper (0.1.0) into Firefox installed via flatpak (107.0.1 (64-bit)). When I click the "connect with notesnook" it flashes once, but then nothing happens. web dev console shows no output, and I'm not sure how to proceed.

### Steps to reproduce the problem

install web clipper to firefox and attempt to clip

### Version

2.3.0

### Platform/OS

Firefox

**Comment by opennomad** [comment]
Today, I managed to get a different result. When I clicked the "Connect to Notesnook" it opened a tab with Notesnook and showed me a menu, which is saying "Could not establish connection ...."
![image](https://user-images.githubusercontent.com/4350520/208158556-701dbe31-bab1-4296-9174-254ae4a5fb5d.png)

**Comment by numb699** [comment]
Also it seems if you have more than one browser windows open it doesn't know what to clip and clips from all other windows than the one you are in.

**Comment by thecodrr** [comment]
@opennomad the clipper cannot clip the default home page. Try a different website.
