### ISSUE TITLE
Uncaught ReferenceError: blobCache is not defined     at FileReader.r.mark.r.wrap.onload

### ISSUE THREAD

**Issue by ammarahm-ed** [streetwriters/notesnook#149]
Bug happens when copying a website with text and images. For example [https://websitesetup.org/](https://websitesetup.org/). 

The error takes place when certain images are not loaded properly hence their links are replaced with blob links like `src="blob:https://app.notesnook.com/0ba9399a-df12-4e3a-9781-d54594684180"` while the original image link is present in data-src tag? 

A sample img tag that causes this issue:
```
<img class="shadow-2 wp-image-34660 size-full aligncenter wp-bullet-lazy-load" src="data:image/svg+xml,%3Csvg%20xmlns='http://www.w3.org/2000/svg'%20viewBox='0%200%201392%20700'%3E%3C/svg%3E" alt="WebsiteSetup Homepage" width="1392" height="700" data-src="https://websitesetup.org/wp-content/uploads/2021/04/WebsiteSetup-Homepage-April-2021.jpg">
```

A note with such data is not saved due to the above error while getting html. However if by any chance the note gets saved with such data, it can cause issues such as #148.

Edit: I just pasted a base64 image in editor from this link and note is not saved: https://codepen.io/jamiekane/pen/YayWOa and gives the same error as above.

**Comment by thecodrr** [comment]
> A sample img tag that causes this issue:

This must be because the src is not base64. Because FileReader is asked to convert the Blob to Base64, it obviously fails.

> with blob links like src="blob:https://app.notesnook.com/0ba9399a-df12-4e3a-9781-d54594684180" while the original image link is present in `data-src` attribute?

This link is correct. It is a normal Blob url. The `data-src` attribute is ignored by the editor so it doesn't matter.

**Comment by thecodrr** [comment]
I have fixed this and added a failure check that should remove the img tag if an error occurs during data-uri to blob conversion.
