### ISSUE TITLE
Searching is not working

### ISSUE THREAD

**Issue by vmlaurentiu** [streetwriters/notesnook#15]
**Describe the bug**

Searching is not working. When I search the app closes unexpectedly 

**To Reproduce**
1. Go to Ios app
2. Click on Notes section
3. Use search
4. Search for a word that appear both in note title and in note content
5. press ios blue search button from keyboard 
6. application exits with not result

**Expected behavior**
To show the searched results

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: iphone 11
 - OS: 14.6
 - Notesnook aplication from app store
 - Version last version 1.3.76

**Additional context**

**Comment by thecodrr** [comment]
Hey, we are investigating this issue.
