### ISSUE TITLE
Task list cannot be collapsed or expanded

### ISSUE THREAD

**Issue by 4fosaefp** [streetwriters/notesnook#1503]
### What happened?

Previously collapsed task list cannot be expanded. The expand/collapse button that used to show up when hovered over is replaced with "X" that deletes the item instead.
As a result, anything inside the collapsed list items can no longer be accessed.

P.S. This bug was originally reported on Discord, and confirmed by dev. I though I'll create a ticket here so I can track it.

### Steps to reproduce the problem

1. Open a task list that has previously collapsed sub-tasks, or create a new task list with sub-tasks
2. When mouse hover over the item, the button to collapse/expand is nowhere to be found
3. User cannot expand or collapse sub-task anymore

### Version

2.3.0-7b7fd62-web

### Platform/OS

Windows, Firefox

**Comment by thecodrr** [comment]
This will be fixed in the next release! Thanks for opening a ticket here.

The issue seems to be due to the recent removal of the collapse/uncollapse button. I forgot to also reset the collapse state of the task list.

**Comment by vertigo220** [comment]
This was completed three weeks ago but in testing yesterday the issue persists. I'm assuming the PR just hasn't made it to release yet, but am posting to check and monitor.
