### ISSUE TITLE
Note edit locking to prevent accidental edits

### ISSUE THREAD

**Issue by thecodrr** [streetwriters/notesnook#151]
This feature is concerned with Core as well as the frontend app.

The following subfeatures are required:

- [ ] Add an entry in note & editor properties to make a note `readonly`.
- [ ] When a `readonly` note is opened, it should disable the editor (this part is already partially done as part of Version History but currently a notice is shown at the top indicating the readonly status of the note. We should separate both.)
- [ ] The `readonly` property should be saved in the database for syncing

**Comment by alihamuh** [comment]
@thecodrr   Okay.
