### ISSUE TITLE
Note version history does not scroll

### ISSUE THREAD

**Issue by tylermercer** [streetwriters/notesnook#1511]
### What happened?

I have a note with 30+ versions, but I can only click on about half of them because the list (which is in a bottom sheet) does not scroll.

![Screenshot_20221217-065843](https://user-images.githubusercontent.com/40773575/208245586-43169960-fde0-4ec4-bb79-bb6aac23e85e.png)

### Steps to reproduce the problem

Open a note you've had for a while and changed a lot (this might be hard to create manually....). Tap the kebab icon to see the menu options. Then tap the "History" option.

Note that the list goes off the bottom of the screen and can't be scrolled, resulting in some versions not being selectable.

### Version

2.3.0

### Platform/OS

Android

**Comment by ammarahm-ed** [comment]
Hey, fixing this asap! Thanks for reporting.

**Comment by ammarahm-ed** [comment]
Fixed in #1553
