### ISSUE TITLE
Cursor Hover Bug [very small bug]

### ISSUE THREAD

**Issue by McBaumwolle** [streetwriters/notesnook#1546]
### What happened?

When opening the ... for properties on a page, the close button (back arrow) does not trigger the "clickable cursor". 

### Steps to reproduce the problem

Open any page and click on ... and see what how the cursor behaves when closing it with the arrow. 

![image](https://user-images.githubusercontent.com/67203883/210158076-f9a4a89b-0fa4-4cf1-9e02-5594e2750a94.png)

(I cannot screenshot with the cursor so when hovering over the switches for example changes the cursor to the "hand" and doing the same on the <- does nothing. Very, very small bug.)

### Version

2.3.0-7b7fd62-web

### Platform/OS

Firefox

**Comment by ammarahm-ed** [comment]
This issue has been fixed in #1580
