### ISSUE TITLE
Unable to sort Topics by title

### ISSUE THREAD

**Issue by candroid-man** [streetwriters/notesnook#156]
**Describe the bug**
When I try to sort Topics by title (alphabetical order), it doesn't apply the filter. When I click sort by title, the menu closes, and the filter is still set to what it was before (in my case, sort by date edited).

**To Reproduce**
1. Go to a notebook with 2 or more topics
2. Click on the sort button
3. Click on `Sort by title`

**Desktop (please complete the following information):**
 - OS: EndeavourOS Atlantis
 - Browser: Electron (AppImage)
 - Version: v1.6.11

**Additional context**
At first, I was not using the most recent update, so I updated, and restarted the app. The issue still remains.

**Comment by thecodrr** [comment]
Upon further investigation, the bug is actually in how the Sort by title menu item appears. It should be disabled when Group by A - Z is not selected. This is now fixed.
