### ISSUE TITLE
Show all errors in a single place with error history

### ISSUE THREAD

**Issue by candroid-man** [streetwriters/notesnook#158]
**Errors**

While using the mobile app, you are constantly bombarded with sync error notifications. Some of these errors include:
- `Sync failed: invalid_grant`
- `Sync failed: Request failed with status code: 520 .`
- `Failed to sync: code 150`
- `Sync failed: Sync is already running on another device. Please wait.`

This isn't related to syncing, but the initial alert for your notes being synced when you open the app also contributes to this.

**Potential solution**

These notifications are large, and can distract the user while typing or organizing notes. If they were resized and put somewhere else it could be a little better, or simply use system notifications instead. It would also be beneficial to add a button that downloads the log of what happened at that moment, so the user may report it to GitHub to better understand these errors.

**Desktop**
 - OS: EndeavourOS Atlantis
 - Browser Electron (AppImage)
 - Version v1.6.11

**Smartphone**
 - Device: Samsung Galaxy S10+
 - OS: Android 11
 - Browser: Native application
 - Version: v1.6.92

**Additional context**

Some of these may have something to do with multiple instances of the app running on different devices. Maybe it would be best to stall real-time syncing when multiple instances are running, and then add a refresh button so when you make changes on one device, and you'd like to switch to another device, you can refresh and all of your notes are synced in that moment.

**Comment by thecodrr** [comment]
> Sync failed: invalid_grant

Fixed in #155

> Sync failed: Sync is already running on another device. Please wait.

This is normal; it occurs to handle cross device sync race conditions.

> Sync failed: Request failed with status code: 520 .
> Failed to sync: code 150

These 2 are flaky — could be anything.

The errors could be better shown, I agree. We'll work on this.

**Comment by thecodrr** [comment]
This has been completed via logs.
