### ISSUE TITLE
Keyboard closing repeatedly on mobile

### ISSUE THREAD

**Issue by candroid-man** [streetwriters/notesnook#159]
**Describe the bug**

When creating a new note, a bug can occur where your keyboard will keep disappearing when you try editing a text field. This makes it impossible to edit that particular note even after restarting the **device**. To fix it, you have to delete the note and create a new one, but you have to finish the title completely before switching apps.

**To Reproduce**

1. Create a new note, and type a few words into the title field
2. While they keyboard is open, switch to a different application with the quick switch button on Android
3. Go back to Notesnook

**Video of the bug in action**

https://user-images.githubusercontent.com/51019003/145659561-c359ca8c-75b7-40d0-a00a-9bc1c86d5008.mp4

**Smartphone**

 - Device: Samsung Galaxy S10+
 - OS: Android 11
 - Browser: Native application
 - Version: v1.6.92

**Comment by ammarahm-ed** [comment]
Fixed
