### ISSUE TITLE
No documentation on encryption

### ISSUE THREAD

**Issue by Domant3lis** [streetwriters/notesnook#16]
This page about encryption is empty (<https://docs.notesnook.com/encryption>). This wouldn't be a big problem exept for the fact that is is linked from the main page.

**To Reproduce**
1. Go to <https://notesnook.com/>
2. Scroll down to "See it in action" section.
3. There should be what looks like to be a small box with an explanation about encryption under witch where is a button called: "Learn how we encrypt your data"
4. Clicking on  this buttom leads to documentation page about encryption. 
5. This page is empty

I believe this is an issue which affects everyone.

**Expected behavior**
The button doesn't exist or the documentation exists.

**Screenshots**
![image](https://user-images.githubusercontent.com/49041398/123474259-5c322180-d602-11eb-8b0c-4d06e88e9ac4.png)

**Desktop**
 - OS: Fedora 34 Workstation 64-bit (A linux disto)
 - Browsers: Edge Dev Version 92.0.902.9; Firefox 89.0.1 (Flatpak version); Gnome Web 40.2 (Flatpak)

**Comment by thecodrr** [comment]
Hey, the documentation for encryption will be live today.

**Comment by thecodrr** [comment]
Completed and pubilshed: https://docs.notesnook.com/how-is-my-data-encrypted/
