### ISSUE TITLE
Undo button after note deletion doesn't always work

### ISSUE THREAD

**Issue by candroid-man** [streetwriters/notesnook#160]
**Describe the bug**

I don't do it often, but if I accidentally delete something and I press `Undo`, it doesn't actually undo it and put it back where it was. I tested it on mobile and desktop

**To Reproduce**

1. Create a new note or use an existing note
2. Delete the note
3. Click `Undo`

**Desktop**
 - OS: EndeavourOS Atlantis
 - Browser Electron (AppImage)
 - Version v1.6.11

**Smartphone**
 - Device: Samsung Galaxy S10+
 - OS: Android 11
 - Browser: Native application
 - Version: v1.6.92

**Comment by thecodrr** [comment]
Fixed on Web/Desktop.

**Comment by ammarahm-ed** [comment]
Fixed on mobile
