### ISSUE TITLE
Disable menu bar

### ISSUE THREAD

**Issue by vholer** [streetwriters/notesnook#1606]
### What problem are you facing?

Disable visibility toggling of menu bar via Alt

![image](https://user-images.githubusercontent.com/414850/211151098-20e2f4ea-d087-4ade-846d-c45a0060100f.png)

1. There is nothing relevant in menu bar in day-to-day use of Notesnook.
2. In my case, it's showing menu bar every time I'm using some own global shortcuts (Ctrl+Alt+[something], Alt+[something])... and it's very irritating.

### What's the solution you'd like to see in Notesnook?

1. Disable menu bar at all.
2. Have an option in settings to disable menu bar.

**Comment by thecodrr** [comment]
This has been fixed.
