### ISSUE TITLE
Downloading images directly from a note

### ISSUE THREAD

**Issue by candroid-man** [streetwriters/notesnook#163]
**Request**

Add the ability to download images just by clicking a download button when clicking on it.

![Selection_015](https://user-images.githubusercontent.com/51019003/145661277-4b0b9661-3a19-415d-8a94-437baef0524e.png)

**Alternative solution**

If you decide to do #161, you could add an attachments section to the menu that shows all the information (resolution, size, metadata, etc.) of all attachments on that note, and you could allow the user to download them from there.

**Comment by thecodrr** [comment]
> you could add an attachments section

There is already an attachments section on both platforms. On Web/Desktop, it appears when you open note properties from the side (the vertical 3-dot button at the top right corner). On mobile, it is opened through a button in the note properties menu.

**Comment by candroid-man** [comment]
You are referring to this menu, correct? I have 2 attachments and there is nothing about them here.

![Selection_016](https://user-images.githubusercontent.com/51019003/145665505-54899fef-35e7-4ee2-987b-af5abce250d7.png)

**Comment by thecodrr** [comment]
Ah yes, images don't get listed there. That's a bug.
