### ISSUE TITLE
Make adding a topic to a notebook optional

### ISSUE THREAD

**Issue by candroid-man** [streetwriters/notesnook#164]
**Request**

To add to the level of organization and ease of use, you shouldn't be required to create topics (subfolders) to make a notebook (root folder). This could be useful in many ways, for example if I wanted to make a notebook for personal stuff like thoughts and ideas and whatnot, I feel like if I wanted to quickly write something down but still organize it, I wouldn't want to go into the notebook, pick a topic, and THEN create my note. Instead, I would rather have a collection of all of my thoughts and ideas in one place within the notebook. Allow tags to organize your notes, but allow them to all be in one place.

**Comment by thecodrr** [comment]
> Allow tags to organize your notes, but allow them to all be in one place.

Not sure what you mean by this.

**Comment by candroid-man** [comment]
Worded that badly. I was basically trying to say that instead of using topics to organize your notes within a notebook, you could use other ways of organizing them such as tags, or not at all. Hope that clears it up a little.
