### ISSUE TITLE
Note previews are a little weird

### ISSUE THREAD

**Issue by candroid-man** [streetwriters/notesnook#165]
**Describe the bug**

On mobile and desktop, the note previews are a little weird. They seem to ignore that there are separate lines, and treats it like all of your text is on one line.

![Screenshot_20211210-044655_Notesnook](https://user-images.githubusercontent.com/51019003/145661899-9667ff88-a349-4cc5-9fc6-6cf0b1f1252e.jpg)

**Possible solutions**

Maybe you could make it to where it only reads the first line of each note to keep it clean, or maybe separate each line with a pipe in the preview. You could even make it to where you can select what section of the note you want to be in the preview, so users can more easily locate which note they are looking for, or use the preview to add a custom explanation of the contents of the note.

**Comment by thecodrr** [comment]
This has been fixed in the last couple of versions. The app now only extracts the first paragraph if available.
