### ISSUE TITLE
Draggable attachments/images

### ISSUE THREAD

**Issue by candroid-man** [streetwriters/notesnook#166]
**Request**

Often times when dealing with images and attachments on mobile, I wish I was able to simply drag it somewhere else, as well as be able to easily move it down a line even if the line doesn't exist yet. Without this, I have to manually attempt to get my cursor behind the image and press enter. Attachments are worse because you are unable to move them at all without deleting them and uploading them again.

**Alternative solution**

You could add buttons that would move the image or attachment up or down a line.

**Comment by thecodrr** [comment]
Fixed in the new editor.
