### ISSUE TITLE
[Reminders] Suggestions

### ISSUE THREAD

**Issue by xfzv** [streetwriters/notesnook#1660]
I've just updated to v2.4.0 on Desktop (`notesnook_linux_x86_64.AppImage`) and Android and played around with reminders. 

Thank you for adding this feature! I have a few suggestions.

## Desktop

I'm using KDE Plasma. There's no difference between "Vibrate" and "Urgent". I'm getting a regular notification in both cases, which disappears after a few seconds if I don't close it manually. It would be nice if "Urgent" was equivalent to `notify-send -u critical` so that the notification is displayed indefinitely until I close it manually:
![image](https://user-images.githubusercontent.com/78810647/212469325-fee02c20-7f09-499b-8994-1097ff198794.png)

Plus, the notification isn't displayed in the system tray notification applet history, even if I don't close it manually:
![image](https://user-images.githubusercontent.com/78810647/212469388-8faeeb49-ee16-49f0-8996-d9bb5ec757bf.png)
It would be nice if it was the case so that we don't miss any notification. Some apps such as Dolphin or qBittorrent can do this:
![image](https://user-images.githubusercontent.com/78810647/212469807-f1cf3aa6-7116-492d-ac48-4c651952bc18.png)

---

## Android app

It would be useful if we could adjust the ring/vibrate repetitions (once, five times, nonstop...)

**Comment by thecodrr** [comment]
The desktop issues have been fixed. Please create a separate issue for Android.
