### ISSUE TITLE
Notesnook is freezing.

### ISSUE THREAD

**Issue by EmirLogas** [streetwriters/notesnook#1667]
### What happened?

In Firefox the page freezes when you are in another tab for 4-5 minutes and then open back notesnook.

![image](https://user-images.githubusercontent.com/76751818/212532909-00ba96be-2108-4994-9c24-9180311f4433.png)

### Steps to reproduce the problem

When Notesnook is open and I switch to another tab and then switch back to Notesnook after 4-5 minutes, Notesnook becomes unusable. It doesn't work until I refresh the page.

### Version

2.4.0-9e382b1-web

### Platform/OS

Windows

**Comment by thecodrr** [comment]
This has been fixed.

**Comment by EmirLogas** [comment]
Yes, the problem seems to have been solved.
