### ISSUE TITLE
Sync issues on desktop

### ISSUE THREAD

**Issue by umbellipher** [streetwriters/notesnook#1668]
### What happened?

W10 Pro, desktop app, and Android 12. VPN, both. Latest versions, both. Locked notes.

Syncing from desktop to Android could be smoother. To get full accurate sync, I have to do the steps in the box below. If I don't, some characters or numbers at the end of the note are not reproduced on the phone after sync has finished.

The 'double return, backspace' action should not be needed, but (for me) it is.

### Steps to reproduce the problem

Write in opened locked note on W10 desktop app.
Allow to auto- sync.
Check phone is auto-synced, and open same note.
Some characters are likely to be missing, of those just written on W10 app.
Go back to desktop app, and do two returns. Allow to sync. Backspace to remove one return. Allow to sync.
Check same note on phone. Notes will now be accurately in sync.

### Version

v2.4.0 desktop

### Platform/OS

Windows

**Comment by thecodrr** [comment]
@umbellipher are you still having this issue?

**Comment by umbellipher** [comment]
Seems to be resolved, thanks.
