### ISSUE TITLE
Desktop app: auto-lock whole app after period selected by user

### ISSUE THREAD

**Issue by umbellipher** [streetwriters/notesnook#1669]
### What problem are you facing?

Great desktop app update to 2.4.0. But...

Could we please have whole-app auto-lock, after a period selected in options by the user?

It happens by choice on the Android app, when screen closes. Why not on the desktop app? Monkkee does it: could notesnook?

Reason why: at the moment I choose, for security, to vault-lock each note, unlocking to add text etc. This means notes are no longer searchable.

I'd like the whole app to auto-lock after, say, 5/15/30/60 seconds, requiring password to be used to open it again. I wouldn't need to lock each note in a vault then, and I presume notes would remain searchable.

### What's the solution you'd like to see in Notesnook?

As above.

**Comment by umbellipher** [comment]
On the day when Notesnook is further updated - thank you - I feel entitled to ask:

When, finally, will we please have whole-app (desktop) auto-lock, after a period selected in options by the user?

**Comment by thecodrr** [comment]
There's no when. It'll come when it'll come.

**Comment by umbellipher** [comment]
I feel slightly upbraided by your reply. It was a perfectly civil enquiry!
