### ISSUE TITLE
Changes to Monographs

### ISSUE THREAD

**Issue by candroid-man** [streetwriters/notesnook#167]
**Request**

1. When I started using Notesnook, I really didn't understand what Monographs were. If it were called something simpler, such as "Shared Notes" or something like that, I believe it would make more sense to new users. For example, Simplenote just gives you a link like simple.note/blahblahblah, I don't think there is any reason to put a fancy label on it when it is such a basic feature.
2. You could automate the update process for Monographs, so you don't have to re-publish it each time you edit it. You could, however, have the option to pause auto-updates at any time.

**Comment by Tamnac** [comment]
I would call it "publish note" and treat it like a blog. You can edit all you want, but edits only go live when you press publish again. 

Monograph is a nice name though. Still good to keep around.
