### ISSUE TITLE
Allow for 3rd party syncing

### ISSUE THREAD

**Issue by candroid-man** [streetwriters/notesnook#168]
**Request**

Have an option where once you enable it, it creates an encrypted file on your local device that contains everything (notes, notebooks, tags, **everything**), that the user can then sync to other devices in whatever way they wish (such as Syncthing). Even with zero-knowledge encryption, I believe that the user should have full control over their notes and data. Creating options for users is critical when it comes to privacy and security, and it ensures no one feels trapped into doing something they may not feel comfortable with. An example of this would be how KeePassXC works.

**Alternative solutions**

Allow users to self-host Notesnook, although having both would be much better.

**Additional context**

People in the privacy community often look for features like this in all applications they use, and I know this because I am one of those people. No matter how convenient you make it for users, it is still essential to give users the ability to do whatever they want with their data.

**Comment by developomp** [comment]
- #1162 
probably related

**Comment by thecodrr** [comment]
3rd party syncing is out of scope for Notesnook. We will add support for self hosting but that's it.
