### ISSUE TITLE
[Android] Popups impossible to be dismissed

### ISSUE THREAD

**Issue by 0rAX0** [streetwriters/notesnook#1683]
### What happened?

New version/features popups are impossible to dismiss. The button rarely works, it only worked one time. And if you try to dismiss by swiping down, you won't be able to use the UI afterwards. It's like the popup itself is gone, but the background overlay is preventing you from tapping on anything below it.

Phone: Pixel 3A
Android: 12

### Steps to reproduce the problem

Just try to dismiss any of the popups on Android

### Version

Latest stable from Playstore

### Platform/OS

Android

**Comment by ammarahm-ed** [comment]
Hey, I am unable to reproduce this issue on emulator & various devices that I have available. Sheets that show from bottom are getting dismissed properly on swiping down.

**Comment by 0rAX0** [comment]
@ammarahm-ed Yeah, I think the freezing was due to something in the background not because of the popups, I can now dismiss them properly.
