### ISSUE TITLE
New features popup keeps popping up after each app restart 

### ISSUE THREAD

**Issue by 0rAX0** [streetwriters/notesnook#1684]
### What happened?

I get the new features popup after each app launch, which is very annoying

### Steps to reproduce the problem

Just keep opening the app and closing it

### Version

Latest stable from playstore

### Platform/OS

Android

**Comment by thecodrr** [comment]
This is a critical issue. Fix is on the way.

**Comment by ammarahm-ed** [comment]
Fixed in #1702
