### ISSUE TITLE
RTL titles are left aligned (and therefore cut off)

### ISSUE THREAD

**Issue by 0rAX0** [streetwriters/notesnook#1686]
### What happened?

Having a long RTL title will look cut off because it is left aligned

### Steps to reproduce the problem

Write a title in an RTL language

### Version

2.4.0 (240)

### Platform/OS

macOS

**Comment by thecodrr** [comment]
Have you tried aligning to the right?

**Comment by 0rAX0** [comment]
I did but

**Comment by 0rAX0** [comment]
I did but it didn't work. Also, I think rtl should be picked up automatically. Meaning that, when you start typing, it should align the text depending on the language.

**Comment by thecodrr** [comment]
Recently, I found out that if you use the `dir="auto"` attribute, the browser can automatically align the text depending on the language. Maybe we can use that as well.

**Comment by alihamuh** [comment]
feature already added.
