### ISSUE TITLE
Reminders should require an action to clear/complete

### ISSUE THREAD

**Issue by Chrisgozd** [streetwriters/notesnook#1690]
### What problem are you facing?

Currently, reminders in Notesnook clear themselves and go into the "Inactive" grouping. I would like reminders to require being cleared/checked manually, before being added to Inactive, kind of like in the IOS build in reminders app.

### What's the solution you'd like to see in Notesnook?

I would like reminders to require being cleared/checked manually, before being added to Inactive, kind of like in the IOS build in reminders app.

**Comment by thecodrr** [comment]
I am not sure I understand the advantage of doing so. Can you give your use case?
