### ISSUE TITLE
IOS: Reminders that trigger should show a notification badge

### ISSUE THREAD

**Issue by Chrisgozd** [streetwriters/notesnook#1691]
### What problem are you facing?

IOS: Reminders that trigger should show a notification badge.

### What's the solution you'd like to see in Notesnook?

IOS: Reminders that trigger should show a notification badge.

**Comment by thecodrr** [comment]
@Chrisgozd Can you explain what you mean by notification badge? Is it the tiny dot on the app icon?

**Comment by ammarahm-ed** [comment]
This has been added in #1701
