### ISSUE TITLE
Can't purchase subscription

### ISSUE THREAD

**Issue by altano** [streetwriters/notesnook#17]
**Describe the bug**
When trying to purchase a subscription I get stuck with a loading spinner

**To Reproduce**
1. Open Notesnook
2. Go to Settings
3. Click "Upgrade to Notesnook Pro"
4. Click "Subscribe to Notesnook Pro"

**Expected behavior**
I would expect to be presented with payment options here

**Screenshots**
https://user-images.githubusercontent.com/1009/127755874-c330cc63-4225-43e8-b334-07b59e0fd10b.mp4

**Desktop (please complete the following information):**
 - OS: Windows
 - Native app
 - Version: 1.4.1-781aa6a-web

**Comment by thecodrr** [comment]
I can confirm this is a bug. Will be fixed in the upcoming version.

**Comment by thecodrr** [comment]
Fixed. Coming in the next version.
