### ISSUE TITLE
Remove Unnecessary Spaces

### ISSUE THREAD

**Issue by gracie95** [streetwriters/notesnook#1707]
### What happened?

![20230117_203002](https://user-images.githubusercontent.com/107738923/212900597-0f2da79b-489d-41ce-bcfc-0890a9ae0ce9.jpg)
![20230117_203059](https://user-images.githubusercontent.com/107738923/212900610-3f01ed27-9473-4102-8356-6ac9c799b02c.jpg)

There are unnecessary spaces from those captures. It should be removed if it wasn't useful or fill them with remaining things.

### Steps to reproduce the problem

Just scroll them till the end. 

The remaing spaces should be there.

### Version

2.4.0

### Platform/OS

Android

**Comment by alihamuh** [comment]
I don't think it is a problem. It is just expected behaviour. 

@ammarahm-ed
