### ISSUE TITLE
Allow Option to Disable Version Highlights

### ISSUE THREAD

**Issue by gracie95** [streetwriters/notesnook#1708]
### What problem are you facing?

Since new version released, I am a bit annoying with the highlights. But, there's no way to disable it or show it once.

### What's the solution you'd like to see in Notesnook?

Add options "do not show again" or other relevant option(s) while opening app.

**Comment by thecodrr** [comment]
Highlights are only showed once and go away after dismissing. I think what you are referring to is the change log that was shown whenever a new version was released. We removed that a few versions back.
