### ISSUE TITLE
Imported notes do not show body in the list

### ISSUE THREAD

**Issue by 0rAX0** [streetwriters/notesnook#1709]
### What happened?

Importing notes results in many untitled notes with hidden body in the list. The only way to fix that is to go to them one by one and make changes (adding a space works)

### Steps to reproduce the problem

* Import notes
* Notice how the the body text is missing
* Open one
* Add something
* The body text suddenly appears on the left
*
<img width="337" alt="Screenshot 2023-01-17 at 16 37 00" src="https://user-images.githubusercontent.com/1044370/212941975-269ca314-7c8d-4512-83ce-63622086ede0.png">

### Version

2.4.0 (240)

### Platform/OS

macOS

**Comment by alihamuh** [comment]
Issue not found.

**Comment by 0rAX0** [comment]
@alihamuh The issue is still present with my notes, this is not resolved.

**Comment by thecodrr** [comment]
@0rAX0 The fix only affects newly imported notes - not notes that you already imported. Can you try importing again and see if the issue is still present?

**Comment by 0rAX0** [comment]
@thecodrr Indeed, I confirm it works now. Thanks!

**Comment by 0rAX0** [comment]
@thecodrr I tried again from scratch today. While the Google Keep imports worked well, Zoho Notes are still broken just FYI
