### ISSUE TITLE
Make toggles in settings make more sense

### ISSUE THREAD

**Issue by candroid-man** [streetwriters/notesnook#1713]
### What problem are you facing?

![image](https://user-images.githubusercontent.com/51019003/213084462-78714559-8cd2-43f6-8622-73e873a1e0d3.png)

This is the menu specifically that I am referring to. Rather than doing it this way, it would be easier to comprehend if you made it like this (using checkmarks instead of toggle switches for demonstration):

- [x] Real-time syncing in editor
- [x] Syncing
- [x] Auto sync

So instead of having toggles for not doing things, have toggles that are on by default and can be disabled. You should also re-order these as well, so it would go:

- [x] Syncing
- [x] Auto sync
- [x] Real-time syncing in editor

Just a little thing that will help the UI in my opinion

**Comment by candroid-man** [comment]
I am going to start going through #412 and renewing, it and also separating each of the things into different issues, so we can discuss them individually

**Comment by thecodrr** [comment]
@candroid-man I have given you triaging access so feel free to organize as you see fit.

**Comment by thecodrr** [comment]
@candroid-man 

> This is the menu specifically that I am referring to. Rather than doing it this way, it would be easier to comprehend if you made it like this (using checkmarks instead of toggle switches for demonstration):

I agree. These toggles are inconsistent with everything else. Though, I wouldn't make them checkboxes.

**Comment by candroid-man** [comment]
Yes, checkmarks were for demonstration, please continue to use the toggles that are already used in the app
