### ISSUE TITLE
Allow users to manually sort Notes, Notebooks, and Favorites

### ISSUE THREAD

**Issue by candroid-man** [streetwriters/notesnook#1715]
### What problem are you facing?

Sometimes it would be handy to be able to manually sort Notes, Notebooks, or Favorites in an order that is better for the user's workflow. 

### What's the solution you'd like to see in Notesnook?

Create a new sorting option called "manual", that would allow users to drag and drop Notes, Notebooks, and Favorites in the order that the user prefers.

### Additional context

This was originally suggested by Victor Kogan#1333 on Discord.

**Comment by luxcalor** [comment]
Wouldn't this be nice indeed. :)
