### ISSUE TITLE
[IMPORTANT] Data encryption key mismatch on two browsers, correct key match only on one browser

### ISSUE THREAD

**Issue by NinjaGobbler** [streetwriters/notesnook#1753]
Hello team,

I am using the Vericrypt page https://vericrypt.notesnook.com/ to validate encryption as explained. On Brave and Microsoft Edge after entering the account salt and password, data encryption key showed on Vericrypt does not match the backup recovery key showed on the Notesnook app. On the other hand, if I use Firefox browser, it fetches the data encryption key correctly.

This is a little scary to me as I didn't expect to see this mismatch. Can you please help explaining this discrepancy so we can address this as quickly as possible?

**Comment by thecodrr** [comment]
Can you make sure the salt is absolutely correct on all browsers? Even a single space can cause issues.

**Comment by NinjaGobbler** [comment]
Hello @thecodrr , you are right. The salt is actually different on brave/Edge vs Firefox. Using notesnook android app or windows app if I check recovery key it matches the Firefox salt and not other browser salts. Is it normal for different browsers to have different salts??

**Comment by NinjaGobbler** [comment]
@thecodrr I have confirmed that this works, as you mentioned I took the wrong salt on edge and brave browsers which led to this confusion. I will mark this resolved, thanks a lot for clarifying this issue :)
