### ISSUE TITLE
Outline Lists not displayed correctly on Web and Desktop

### ISSUE THREAD

**Issue by ayush123460** [streetwriters/notesnook#1765]
### What happened?

Outline lists on the web and desktop apps are not displayed correctly, while they're perfectly fine on the android app.

![image](https://user-images.githubusercontent.com/13494534/213958121-a9e33b84-6664-4ba1-8ecc-1278ab19ed3b.png)

### Steps to reproduce the problem

Create an outline list on the web/desktop interface

### Version

v2.4.0

### Platform/OS

Linux, Firefox

**Comment by thecodrr** [comment]
@ayush123460 I am not sure I see a problem in the screenshot above. Can you explain what's the issue?

**Comment by ayush123460** [comment]
@thecodrr hey, this is what it's supposed to look like:

![Screenshot_20230124-104946_Notesnook](https://user-images.githubusercontent.com/13494534/214217673-a499f2ec-31cc-4444-b066-3bd0959ea265.png)

Basically, bad spacing between items, and items don't toggle properly either:

![image](https://user-images.githubusercontent.com/13494534/214217907-a732a82f-fd1a-4753-8342-5ea9bb052d84.png)
![image](https://user-images.githubusercontent.com/13494534/214217921-41e096c6-5a36-4f99-88b4-49b75a8da586.png)

**Comment by ayush123460** [comment]
Hey, this seems to have been fixed with v2.4.2. Thanks!
