### ISSUE TITLE
Deleted reminders are not found in Trash

### ISSUE THREAD

**Issue by NinjaGobbler** [streetwriters/notesnook#1776]
### What happened?

I deleted some reminders and now I am unable to find them in Trash. Only the notes that are deleted are present in Trash and not the reminders. This behavior is same on android and windows app.

### Steps to reproduce the problem

1. Create any reminder with any data
2. Right click and "Delete" the reminder
3. Go to "Trash" and I am unable to find the deleted reminder.

If let's say I accidentally deleted some reminders, then I have no way of restoring those now. 

### Version

v2.4.2

### Platform/OS

Windows, Android

**Comment by thecodrr** [comment]
Hey, reminders are not a part of the trash. I am personally not convinced that reminders should move to trash on deletion as they are fairly simple to recreate and don't usually contain any critical information.

**Comment by NinjaGobbler** [comment]
Hi @thecodrr I understand what you are saying, but consider this scenario - Let's say I have a few reminders to do certain tasks by certain specific dates sometime in the future. If I right click on it to perform some operation like "Turn off" or "copy data", the delete button is right next to it and I accidentally ended up clicking on it and as the delete button has No confirmation prompt, it just disappeared. 

Now I would have to think again on what was the date on that reminder, the help text containing specific details about the reminder itself, which I don't remember exactly.

At the least, we could give a confirmation prompt before deletion. What do you think?
