### ISSUE TITLE
Can't undo clearing of completed list items

### ISSUE THREAD

**Issue by vertigo220** [streetwriters/notesnook#1793]
### What problem are you facing?

Doing some testing, I created a task list, then I used the bar at the top (which, btw, isn't intuitive and gives little indication of its purpose) to clear completed list items. While that worked as expected, what was unexpected was the fact that the undo function failed to bring those items back, forcing me to redo them all. This happened due to testing, but it could just as easily happen by mistake.

### What's the solution you'd like to see in Notesnook?

Have undo actually undo everything, including the clearing of completed tasks.

**Comment by thecodrr** [comment]
I tried to reproduce this but couldn't. Can you try again?

**Comment by vertigo220** [comment]
Just tried again and it worked, but I knew it didn't before, so I played around a bit and found that if the cursor is in the text box (still have no idea what it's for, but when this happened before I must have hit the clear button after trying to type in the box, as I know I did that thinking it was some sort of search or filter feature), then clearing completed tasks causes it to not be able to be undone.

**Comment by thecodrr** [comment]
The text box is the title for the task list. It doesn't _yet_ serve any use and is completely optional. Since it is separate from the editor, it has its own undo history.

**Comment by vertigo220** [comment]
Ok, but the fact it doesn't do anything makes its existence confusing, especially since that was another thing I thought it might be, only to find the note's title unchanged when I typed in it. But the real problem is that even just putting the cursor in it before clicking the button to clear completed tasks permanently deletes them with no ability to undo. Have you repro'd that?

**Comment by thecodrr** [comment]
The editor needs to be focused to trigger undo shortcut (or use the undo button at the top). Focusing the Task list's title input and clicking the clear completed tasks does not focus the editor. It keeps the focus where it was before.

**Comment by vertigo220** [comment]
That's fine, but simply closing this without dealing with it will likely result in others having the same problem, since there's nothing to indicate what's going on. Having the  possibility of running into this and forgetting the "solution," resulting in not being able to undo something, is a deterrent to using this.

**Comment by thecodrr** [comment]
@vertigo220 This commit (https://github.com/streetwriters/notesnook/commit/b948dcee224ed58883484c3ba91ae3c6bcee5fd5) moves the focus back to the editor when "Clear all completed tasks" button is clicked no matter where the focus was before. As a consequence, this issue will no longer occur.
