### ISSUE TITLE
Text selection issue

### ISSUE THREAD

**Issue by vertigo220** [streetwriters/notesnook#1798]
### What happened?

When clicking and dragging to select text, if selection is dragged past last line in note (limit seems to be anywhere just past the last line, which is always a blank line at the very end), it removes the selection.

### Steps to reproduce the problem

1. Enter some lines of text
2. Click and hold and drag from anywhere before or within the text to highlight the text
3. Continue dragging to slightly below the blank line at the end of the note and release the mouse button
4. Selected text selection will be cleared

### Version

2.4.0

### Platform/OS

Windows, Chrome/Chromium

**Comment by thecodrr** [comment]
I can confirm this is happening.
