### ISSUE TITLE
Rename color text always getting set to all lowercase without spaces

### ISSUE THREAD

**Issue by NinjaGobbler** [streetwriters/notesnook#1823]
### What happened?

When I try to right click on a specific color, purple in my example, and then click "Rename color" and type my desired name (for example, Official Notes) and click on Save. 

It ignores any formatting, becomes case insensitive, ignores spaces and gets saved as "officialnotes". I tested and it appears to accept special characters but not spaces.

### Steps to reproduce the problem

1. Right click on any color from left pane
2. Click "Rename color"
3. Type any desired name (with a mix of uppercase, lowercase and spaces)
4. Click on Save
5. You will see the effect

### Version

v2.4.0

### Platform/OS

Windows

**Comment by alihamuh** [comment]
Cases and Spaces are not saved in naming. This is the expected behaviour.

**Comment by NinjaGobbler** [comment]
@alihamuh Thanks for letting me know. I also wanted to share that behavior is a little different on android. On the android app, it saves any text capitalizing the first letter while on desktop all characters are lowercased. 

No major issues due to this. Just putting it out there so you know, in case it wasn't noticed earlier :)
