### ISSUE TITLE
MacOS Ventura 13.1 | Update Version 2.4.1 | Nothing Happens When Opening the App

### ISSUE THREAD

**Issue by confettimoney** [streetwriters/notesnook#1827]
Dear Team,

After updating to the latest version on MacOS (Ventura 13.1) nothing happens, i.e., no interface shows up. Any thoughts on why this is happening and how to fix this?

Thanks a lot,

CM

**Comment by thecodrr** [comment]
Hey, v2.4.2 is on the way which fixes this.

**Comment by confettimoney** [comment]
Cool, thanks for the update.

**Comment by thecodrr** [comment]
Release is out. You will have to manually download the update. (your data won't be affected).
