### ISSUE TITLE
Blurry tray icons in menu

### ISSUE THREAD

**Issue by muznyo** [streetwriters/notesnook#1830]
### What happened?

Latest update added tray icon, but its icons are blurry 
![image](https://user-images.githubusercontent.com/24987471/215508007-8c056c34-2f77-4a5f-80f0-7b606e06cd55.png)

### Steps to reproduce the problem

Update and check tray

I have gnome and 3.5K display

### Version

v2.4.1

### Platform/OS

Linux

**Comment by thecodrr** [comment]
I support 16px doesn't work with Gnome. Will bump it up to 32.
