### ISSUE TITLE
Telemetry automatically turns on after reopening the app

### ISSUE THREAD

**Issue by eserdk** [streetwriters/notesnook#1847]
### What happened?

Every time I reopen the app, telemetry gets turned on, given I turned it off before closing the window.

P.S. I'm actually not sure it gets turned off when I turn it off.

### Steps to reproduce the problem

1. Turn off the telemetry
2. Close the window
3. Open the app again
4. See that telemetry is on

### Version

2.4.2-9df44b1-desktop

### Platform/OS

macOS

**Comment by thecodrr** [comment]
This is a regression from #1700
