### ISSUE TITLE
Account recovery

### ISSUE THREAD

**Issue by justanothertechguy** [streetwriters/notesnook#185]
**Describe the bug**
I'm not able to login to my primary account even after providing proper credentials. "Forgot Password" option isn't available, lost access to critical data due to being unable to recover the same through recovery key as well.

**Desktop:**
 - OS: Windows 10 64-bit
 - Browser: Chrome
 - Version: 96.0.4664.93
 - Pro: false

**Comment by ammarahm-ed** [comment]
Hey, we will add back forgot password option again soon. Till then we request you to keep your recovery key safe.

**Comment by justanothertechguy** [comment]
Sure, Thanks!
Tentatively, when can we expect to have it back?

**Comment by ammarahm-ed** [comment]
@justanothertechguy I can't give you an exact date but we will make it available as soon as possible. I will inform here when it is added back.

**Comment by justanothertechguy** [comment]
Thank you!  This issue is blocking my work in a major way, hence the urgency to know a tentative date. 
Anyways, eagerly waiting in anticipation, hoping it's fixed soon.

**Comment by justanothertechguy** [comment]
Hello, 

Thank you for looking into the issue. Unfortunately, even with the new update this still does not work for me. It does not accept my original password and on trying to reset/recover the account through the recovery key it is giving me below error. Identifying the recovery key as invalid although I am providing it as exactly the same that I have copied earlier, eliminating any unwanted space or such.

I'm still in the same situation as I was before, locked out of my account and without access to the critical data that has been blocking my work for many weeks now in a major way. Please advise.


![invalid recovery key](https://user-images.githubusercontent.com/11338163/148668980-0987c802-c3a1-49a4-906e-af7d71f09219.PNG)

**Comment by thecodrr** [comment]
Hey @justanothertechguy, from the screenshot I can see that this is an older version of account recovery. Can you try doing a hard refresh?

**Comment by justanothertechguy** [comment]
@thecodrr sorry, hard refresh?

**Comment by thecodrr** [comment]
@justanothertechguy See [this guide](https://www.howtogeek.com/672607/how-to-hard-refresh-your-web-browser-to-bypass-your-cache/)

**Comment by justanothertechguy** [comment]
I was able to recover my account successfully. Thank you @thecodrr , appreciate all your efforts into fixing this.
