### ISSUE TITLE
Undo (Ctrl+Z) doesn't affect tables

### ISSUE THREAD

**Issue by candroid-man** [streetwriters/notesnook#189]
**Describe the bug**

When pressing Ctrl+Z to undo an action done to a table, it doesn't work.

**Desktop**
 - OS: EndeavourOS Atlantis
 - Browser: Electron (AppImage)
 - Version: v1.6.11

**Additional context**

Seems to be a desktop issue specifically, the mobile app is not affected. As a matter of fact, it works very well.

**Comment by thecodrr** [comment]
This should be fixed in the new editor.
