### ISSUE TITLE
Multi-select notes

### ISSUE THREAD

**Issue by altano** [streetwriters/notesnook#19]
**Is your feature request related to a problem? Please describe.**
I am testing the OneNote import. A ton of notes were added to my Notes tab. Deleting the Notebooks left me with a ton of Notes still. These notes are poorly imported and I'm just testing, so I would like to delete all of them and reattempt the import with the latest OneNote Importer, so I can file fresh bug reports.

**Describe the solution you'd like**
I would like to be able to multi-select and delete a lot of Notes at once. Right now I have to go through the flow of deleting each note one-by-one which is too hard for the number of Notes I have.

I don't care how this is achieved (shift-click multi-select, a button called "select all", a button called "delete all", whatever)

**Describe alternatives you've considered**
A button in the settings to delete all data?

**Comment by altano** [comment]
So I actually just found this feature in the context menu (sorry, I'm blind) but I think it actually doesn't work? Clicking "select all" unselected everything. Clicking "unselect all" exits selection mode:
https://user-images.githubusercontent.com/1009/127756350-9599b9fb-9a2f-427a-9278-4b72fe751580.mp4

**Desktop (please complete the following information):**
* OS: Windows
* Native app
* Version: 1.4.1-781aa6a-web

**Comment by thecodrr** [comment]
This has been fixed and will be available in the next version. Leaving it open for now.

**Comment by altano** [comment]
Awesome, thanks @thecodrr. I got a little sidetracked by other projects but I'm getting back to this. When the fix is released I'll get you those OneNote import bugs I promised a month ago :)
