### ISSUE TITLE
Problem with Joplin import

### ISSUE THREAD

**Issue by warthog3** [streetwriters/notesnook#1932]
I have a 130 MB Joplin (.jex) library with ~500 notes I'm trying to import and get this error. What should I be doing differently or should the Importer be updated?

I get about 5-6 notes imported before this error pops up:

![image](https://user-images.githubusercontent.com/4109409/219114400-418688b8-414f-49d1-93b5-e3f325e132cd.png)

**Comment by warthog3** [comment]
Instead of importing the whole library, I only get about 6 notes imported before this error comes up.

**Comment by thecodrr** [comment]
Read the relevant docs here: https://help.notesnook.com/importing-notes/import-notes-from-joplin

Let me know if you still see the errors.
