### ISSUE TITLE
Bullets not going to every line when you use Shift+Enter for each line

### ISSUE THREAD

**Issue by candroid-man** [streetwriters/notesnook#194]
**Describe the bug**

Not sure what the technical term is for this, but when you Shift+Enter, it creates a line with 1x spacing between it and the line before it. If you create a list of things with the 1x spacing, you are unable to add bullets to each line like you can normally.

**To Reproduce**

1. Create a new note
2. Create a small list of text, making sure to use 1x spacing (shift+enter)
3. Highlight the entire list, and click the bullet list button

**Screenshots**

![Selection_020](https://user-images.githubusercontent.com/51019003/146142771-8211e98a-4de6-4fc0-b211-1a32dd2d547d.png)

**Desktop**
 - OS: EndeavourOS Atlantis
 - Browser Electron ([PKGBUILD](https://monograph.notesnook.com/5dade0d4dea5b23de7e73ab7))
 - Version v1.6.11

**Additional context**

I was actually kind of unsure if this was intentional, but I thought I would report it just in case.

**Comment by Tamnac** [comment]
This is definitely on purpose, shift+enter is supposed to act like "create a new line, but don't take any action associated with Enter".

**Comment by candroid-man** [comment]
@Tamnac Thank you for clearing that up for me!
