### ISSUE TITLE
[small bug] assign colour submenu not correctly aligned

### ISSUE THREAD

**Issue by McBaumwolle** [streetwriters/notesnook#1942]
### What happened?

When selecting a colour for a page the submenu is not aligned as it should (see the screenshot).
![image](https://user-images.githubusercontent.com/67203883/219468518-a0096420-3a49-46c6-8262-479ea4d972c8.png)

It is down by one row and sometimes (I did not see any pattern in this) it also selects the colour that should be there (aka the one beneath the one you click). 

### Steps to reproduce the problem

1. right click on note
2. assign colour

Firefox Dev 111.0b1 (64-bit)
Windows 11 Pro

### Version

version 2.4.3-bb0c48f-web

### Platform/OS

Firefox

**Comment by thecodrr** [comment]
This has been fixed.
