### ISSUE TITLE
Ability to Share Notebooks and Topics

### ISSUE THREAD

**Issue by Bizzet** [streetwriters/notesnook#1954]
I think it would be a great addition if you allowed users to share entire notebooks and topics with others, similar to how the Monographs work.

I would personally like to see the abilities to:

- Make a private link for users to browse through entire notebooks using a web version if they have the link

> (OneNote does a great job at this. Here’s some information regarding their sharing feature: 
> https://support.microsoft.com/en-us/office/share-a-page-of-notes-or-an-entire-notebook-from-onenote-for-windows-10-d4a74a14-44a3-411e-8fb5-06e73ddf047f)

- Make a private link for users to browse through entire topics using a web version if they have the link

- Share notebooks and topics with other Notesnook users so they can download it to their account and view it on their device

_Originally posted by @Bizzet in https://github.com/streetwriters/notesnook/discussions/1953_

**Comment by thecodrr** [comment]
Hey please don't spam the discussions & issues with the same duplicate issue over and over again. Posting in one place is enough.
