### ISSUE TITLE
Monographs are using Cloudflare for no apparent reason

### ISSUE THREAD

**Issue by candroid-man** [streetwriters/notesnook#196]
**Describe the bug**

I was on a Monograph page and I noticed that uBlock Origin detected a Cloudflare domain. I blocked it and the site acted the same way as before. 

**Screenshots**

![20211215_041207](https://user-images.githubusercontent.com/51019003/146167470-614bd5c3-6239-4f52-b617-5b9e8fa474d3.jpg)

**Desktop:**
 - OS: EndeavourOS ATLANTIS
 - Browser: Firefox

**Comment by candroid-man** [comment]
So, I discovered what the purpose of Cloudflare is on the site, and I think you could possibly avoid using Cloudflare. It is simply the text color and font. So, is it absolutely necessary for Cloudflare to be used here?

**Comment by thecodrr** [comment]
This has been fixed in the new Monographs.
