### ISSUE TITLE
Notebooks list not showing (right click on the note)

### ISSUE THREAD

**Issue by foozzi** [streetwriters/notesnook#1966]
### What happened?

Notebooks list not showing (right click on the note)

### Steps to reproduce the problem

1. right click to the note
2. try linking the note to existing notebooks

![Screenshot from 2023-02-19 19-11-38](https://user-images.githubusercontent.com/1178208/219970054-8dace262-8be5-4c85-b3ac-29e8337dc06f.png)

### Version

2.4.3-bb0c48f (Appimage)

### Platform/OS

Linux

**Comment by foozzi** [comment]
The menu is displayed above the main menu

![Screenshot from 2023-02-19 19-27-41](https://user-images.githubusercontent.com/1178208/219970640-97048595-96be-4226-921f-8da6bcd45414.png)

**Comment by thecodrr** [comment]
Hey, this is already reported at #1929
