### ISSUE TITLE
Unable to indent Outlines on mobile app?

### ISSUE THREAD

**Issue by Bizzet** [streetwriters/notesnook#1972]
### What happened?

I am attempting to make an outline using the Outline feature and it looks something like this:

- Item 1
- Item 2
- Item 3

but I want to indent some items. However, there is no clear way how to do this. I would assume you are suppose to press the indent button on the toolbar but this does not produce any results.

I am trying to achieve:

- Item 1
- Item2
- Item 3
  - Item 4
 
 I have tried using another dash like this:

- ‘’- Item 4’’

And I have tried indenting it with spaces as well to no success.

So my guess is that the indent button is not working on the app. 

There is no documentation on this feature. Some simple usage instructions for each input type would be a time-saving addition to the project.

### Steps to reproduce the problem

* Open app
* Navigate to any note
* Add an Outline from the + menu of the toolbar
* Add some list items
* Attempt to indent some items to the next level by using the indent button
* Attempt to indent some items by using syntax

### Version

2.4.4

### Platform/OS

iOS

**Comment by Bizzet** [comment]
Also, the mobile app Documentation link within the settings menu states: 

> “Learn about every feature and how it works”

but this is simply not true because I don’t see any information on how any of the content features work.

**Comment by ammarahm-ed** [comment]
This has been fixed in #1993
