### ISSUE TITLE
Half of app is blank after exiting and returning to app

### ISSUE THREAD

**Issue by Bizzet** [streetwriters/notesnook#1973]
### What happened?

Sometimes when I switch to another app then return to Notesnook, half of the app is completely blank.

It seems the space where the keyboard is when editing a note is the area that is blank if the keyboard is closed on return to the app.

The only way to remedy the problem is to close the app and reopen it, which consequently sends me to the home screen and requires me to navigate to my note which is frequent annoyance.

I am using iPhone 14 Pro Max with iOS 16 if that makes any difference.

### Steps to reproduce the problem

* Open app
* Navigate to note
* Add some text
> The following part I am unsure of what causes the keyboard space to become blank when returning to the app. But it can be one of these:

- Switch to another app by swiping from left side of screen 

- Switch to another app by swiping from right side of screen

- Switch to another app by swiping up from bottom on the screen and tapping a background app

- Switch to another app by swiping down from top left and tapping a notification

- Switch to another app by tapping a notification banner

- Locking the screen while editing a note

I do have my settings set to lock Notesnook when returning to the app which requires my Face ID to unlock. I believe this has something to do with it.

### Version

v2.4.4

### Platform/OS

iOS

**Comment by ammarahm-ed** [comment]
Hi, I have been trying to reproduce this problem locally and was unable to. Can you provide me with the following information:

1. Once you see the blank white space at the bottom, what happens if you tap on the editor area and try opening the keyboard to edit the note? Or is it that the keyboard does not open either
2. What happens if you change orientation of the app to horizontal then back to normal
3. What happens if you go into background again and then open the app once more.

**Comment by Bizzet** [comment]
> Hi, I have been trying to reproduce this problem locally and was unable to. Can you provide me with the following information:
> 
> 
> 
> 1. Once you see the blank white space at the bottom, what happens if you tap on the editor area and try opening the keyboard to edit the note? Or is it that the keyboard does not open either
> 
> 2. What happens if you change orientation of the app to horizontal then back to normal
> 
> 3. What happens if you go into background again and then open the app once more.

I will test each of those the next time it happens.

Here's a photo that I took earlier showing what it looks like ![image](https://user-images.githubusercontent.com/6588165/220863646-3ad136b1-bb7b-4883-8dd9-9251ada59206.png)

**Comment by thecodrr** [comment]
This has been fixed in the latest version. Please upgrade.
