### ISSUE TITLE
I wanted to know how the content is rendered after publish

### ISSUE THREAD

**Issue by gigabytem** [streetwriters/notesnook#1979]
### What problem are you facing?

I am a 4th-year btech student, I was studying your code and wanted to know how the content is rendered in the publish URL, how the data from the monograph is rendered and displayed in publish url page

### What's the solution you'd like to see in Notesnook?

how the data is rendered https://monograph.notesnook.com/noteid here

**Comment by ammarahm-ed** [comment]
Hi, when you open a monograph url such as `https://monograph.notesnook.com/noteid`, a request is sent to the server where it checks if a monograph with the noteid in url is published. If it is published, it returns a webpage with the monograph pre-rendered as html.
