### ISSUE TITLE
Cannot login from mobile app (Android)

### ISSUE THREAD

**Issue by bonnepioche** [streetwriters/notesnook#1982]
### What happened?

Hi,
On Mobile (Android, Samsung S21), Notesnook wants me to login via MFA (via email), but never sends the email with the code to enter.
Therefore I cannot use Notesnook on mobile.

I am using NotesNook on the browser on my PC without problem (without 2FA being setup as I do not want to use it).

Thanks,

Patrick

### Steps to reproduce the problem

* Installed Notesnook Android app for the first time 
* Launch the app, 
* Enters your email, the application asks for a "Two Factor Authentication" asking for a "6 digit code sent to my email"
* I never receive the email (and no, it is not in my spam). 
* Therefore I cannot use Notesnook on my phone.

As a reminder, Notesnook works fine on my PC (via web browser), and 2FA is _not_ setup (and I do not want it).

### Version

Latest android version

### Platform/OS

Android

**Comment by thecodrr** [comment]
@bonnepioche can you try reaching out via email so I can check why you aren't getting the 2FA email? It could be that your mail provider is blocking emails from us which can be annoying.
