### ISSUE TITLE
Can't move a note to another notebook

### ISSUE THREAD

**Issue by ianpablob** [streetwriters/notesnook#2002]
### What happened?

Cant change note storage

Device information:
App version: 2.4.3-bb0c48f-desktop
OS: Windows 10 64-bit
Browser: Electron 21.1.1
Pro: true

### Steps to reproduce the problem

I do right click in a new note, move my cursor on the option Notebooks and can't reach in "link to". If i move my cursor to out of notebook close the option

### Version

2.4.3

### Platform/OS

Windows

**Comment by thecodrr** [comment]
Hey, thanks for clarifying. This was already reported (#1929) and fixed. It'll be part of the next release.
