### ISSUE TITLE
Title saves last character entered

### ISSUE THREAD

**Issue by candroid-man** [streetwriters/notesnook#201]
**Describe the bug**

Similarly to #175, the first character you type into the `Note title` field cannot be removed, and is saved in the preview, forcing it back every time the character is removed.

**To Reproduce**

1. Create a new note
2. Type in a single character in `Note title`
3. Delete the character
4. Move to a different note
5. See error

**Expected behavior**

Whenever you create a note, add text, and then remove all the text, it should remove the note if you switch to a different note.

**Screenshots**

![Selection_021](https://user-images.githubusercontent.com/51019003/146384655-5d08e1bd-07cd-4a84-9eb5-568ac8878b99.png)

**Desktop**
 - OS: Arch
 - Browser: Electron ([PKGBUILD](https://monograph.notesnook.com/5dade0d4dea5b23de7e73ab7))
 - Version: v1.6.12

**Comment by thecodrr** [comment]
> Whenever you create a note, add text, and then remove all the text, it should remove the note if you switch to a different note.

A couple versions back this was happening but we have removed all auto deletion logic inside Notesnook. As such we only have a few options regarding this:

1. When title is emptied out, a default title should appear
2. Do nothing

A note's title cannot be empty in any case.

**Comment by candroid-man** [comment]
@thecodrr So it would be impossible to make it to where if you created a blank note, and then moved out of that note it would just delete itself since there is nothing there? That is the way most notes apps work from my understanding

**Comment by thecodrr** [comment]
> That is the way most notes apps work from my understanding

It differs from note app to note app. Some allow title to become empty but not the note's content and some the other way around. Auto deletion is dangerous no matter how sensible since there is always the chance of a false positive. At the end of the day, all destructive actions should be in the hands of the user — not the app (unless there is 100% guarantee).

**Comment by candroid-man** [comment]
> At the end of the day, all destructive actions should be in the hands of the user — not the app (unless there is 100% guarantee).

Fair enough, I agree that the user should have 100% control, meanwhile I also think this could be a nice quality of life improvement. Maybe it would be best to (if you want to of course), develop this in a sandboxed version of the app and perfect it.

Cause for example if I accidentally create a note somehow, and back out of that note I personally wouldn't want to have to delete it manually.

If you don't agree with me, feel free to close out this issue.

**Comment by thecodrr** [comment]
Closing this as we have removed all auto-deleting mechanisms from the app. It's too dangerous and risky. User can take the very infrequent action to delete a note they accidentally created. This is not something that's the responsibility of the app — for example, file managers don't automatically delete empty files or files with empty filenames.
