### ISSUE TITLE
Night mode Search bar Auto Complete text color is not correct

### ISSUE THREAD

**Issue by Abdulrehman-Jafer** [streetwriters/notesnook#2010]
![issue](https://user-images.githubusercontent.com/121712508/221375364-7501b4bb-5566-4b15-b823-2bb4ccc1f7fd.PNG)
Look here

**Comment by ammarahm-ed** [comment]
Hey, i am unable to reproduce this bug. Please provide all relevant information such as Platform/OS, App Version etc.

**Comment by Abdulrehman-Jafer** [comment]
![issue2](https://user-images.githubusercontent.com/121712508/221800279-e6d9ecb4-da3f-4c0b-a817-27b8597f2613.PNG)
Here when I click in the search bar "nodejs" suggestion box appears
![issue3](https://user-images.githubusercontent.com/121712508/221800985-c672d199-37e2-4211-a6ed-11cd10998c75.PNG)
