### ISSUE TITLE
The Additional Options Wrongly Display

### ISSUE THREAD

**Issue by gracie95** [streetwriters/notesnook#2013]
### What happened?

Other additional options appear to the right side as well. But, this one didn't.

![nn menu bug](https://user-images.githubusercontent.com/107738923/221407861-d79b27c7-7d96-4b14-862d-073ee428edac.png)

### Steps to reproduce the problem

1. Right click to a note you want to link to a notebook
2. Point cursor at the **Notebooks**
3. The additional option(s) appear over note name. Not to the right side.

### Version

2.4.3

### Platform/OS

Windows

**Comment by confettimoney** [comment]
Same for me.

App & Version: Notesnook Desktop v2.4.3
OS: macOS Ventura 13.1
Pro: True
