### ISSUE TITLE
Mail input is disabled on session expired page

### ISSUE THREAD

**Issue by lepeli** [streetwriters/notesnook#2023]
### What happened?

I have a session that expired and the email field is disabled for some reasons.

![firefox_6p5cSZTvZ4](https://user-images.githubusercontent.com/24854702/221698098-3bbfe1ad-e2e1-4586-9e6f-d88a6f66eb10.png)

### Steps to reproduce the problem

Have a session that expired.

Tried to type mail in the input.

Can't because the field is disabled.

### Version

According to updater: v.2.4.2 (not sure) 

### Platform/OS

Firefox

**Comment by thecodrr** [comment]
This has been fixed and will be part of the next release. For now, you can just click on `Relogin to your account` button.
