### ISSUE TITLE
Unable to switch back to Monospace font after switching from it

### ISSUE THREAD

**Issue by candroid-man** [streetwriters/notesnook#203]
**Describe the bug**

Whenever you switch from Monospace to Classic, for instance, you can re-select Monospace font, but it will not change the text.

**To Reproduce**

1. Create or use pre-existing note with different font
2. Change the font of the text to something other than Monospace
3. Change it back to Monospace

**Desktop**
 - OS: Arch
 - Browser: Electron ([PKGBUILD](https://monograph.notesnook.com/5dade0d4dea5b23de7e73ab7))
 - Version: v1.6.12

**Comment by thecodrr** [comment]
@candroid-man Monospace & classic fonts are similar on a lot of systems. Have you tried changing between Monospace & Sans-serif?

**Comment by thecodrr** [comment]
This should be fixed in the new editor.
