### ISSUE TITLE
Making a custom toolbar resulted in a broken toolbar

### ISSUE THREAD

**Issue by tothpsk** [streetwriters/notesnook#2037]
### What happened?

Hi,

I was exploring the "configure toolbar" option in the settings. I created new custom toolbar with groups and subgroups. When going back to notes, the toolbar seems broken. See screenshot. I tried to reset toolbar setting, it didn't help. Returning to default toolbar didn't help.

![Screenshot_20230302-090511](https://user-images.githubusercontent.com/11166910/222368914-512166d0-5f1b-411e-8928-ea04ea543e20.png)
a 

### Steps to reproduce the problem

- creating a custom toolbar

### Version

2.4.5

### Platform/OS

Android

**Comment by ammarahm-ed** [comment]
Hey, I am able to configure the toolbar on the latest version of Notesnook. Can you share your toolbar configuration probably. The empty || lines mean that there are empty groups in the toolbar in the beginning.

**Comment by tothpsk** [comment]
Hi, sure, here are the screenshots (from the start to the end):

![-1](https://user-images.githubusercontent.com/11166910/222387114-4bdf3621-eb91-4014-8b6a-1878cfc0c4b9.png)
![-2](https://user-images.githubusercontent.com/11166910/222387111-d9946d09-845b-4c8c-86ea-fe97b2dadbc5.png)
![-3](https://user-images.githubusercontent.com/11166910/222387105-ee333d13-eb85-470a-ab51-faa8fec04d4d.png)

**Comment by tothpsk** [comment]
Ok, this is interesting. After updating to version 2.4.6 the empty lines in the toolbar disappeared. I did nothing, no edits in the toolbar settings were made. Whatever you did on your side it solved my issue. Thanks.
