### ISSUE TITLE
Fonts in monograph don't support some characters

### ISSUE THREAD

**Issue by muznyo** [streetwriters/notesnook#2043]
### What happened?

When I published a note, I noticed that the font in monograph doesn't support some characters.
I am not sure if it's a browser issue, or Notesnook issue. (I use Firefox on Linux)

### Steps to reproduce the problem

1. publish a note with some of those characters: č, ř, ě, š
2. 

![image](https://user-images.githubusercontent.com/24987471/222459543-44239191-0a79-43d6-818d-b0086474968f.png)

### Version

v2.4.4

### Platform/OS

Linux

### Relevant log output

*No response*

**Comment by thecodrr** [comment]
Yes, this is a valid issue. Will fix this ASAP.
