### ISSUE TITLE
Math blocks are not rendered in Export

### ISSUE THREAD

**Issue by Hexagon666666** [streetwriters/notesnook#2045]
### What happened?

I had a document containing math blocks and wanted to export it to PDF for sharing. In the result file I noticed that the math blocks were not rendered as such, instead the file just contained the LaTeX commands. 

After that, I tried exporting as Markdown, Text and HTML, expecting the "$$" markup especially for the former, but there also just were the commands. I attached the Desktop screenshots, but the behavior is the same on my Android phone (Android 8.1, newest Notesnook version from F-Droid).

# The math formatted correctly in Notesnook Desktop

Text: `$$\frac{17}{73} \cdot \Omega$$`

![Bildschirmfoto von 2023-03-02 18 39 39](https://user-images.githubusercontent.com/99750559/222508365-5cf5ad3d-7dd7-4638-ad6b-78a211661792.png)

# The same note exported as PDF

![Bildschirmfoto von 2023-03-02 18 42 08](https://user-images.githubusercontent.com/99750559/222510360-ac9f7648-a683-415b-87e0-93f8da3a0ce9.png)

# As txt

![Bildschirmfoto von 2023-03-02 18 49 46](https://user-images.githubusercontent.com/99750559/222510893-8835cc42-98ec-44cb-89f7-28c21cde6f9b.png)

# As Markdown

![Bildschirmfoto von 2023-03-02 18 50 36](https://user-images.githubusercontent.com/99750559/222510929-8b1be1c6-3abb-48dd-b969-1182058101a1.png)

# And as HTML

![Bildschirmfoto von 2023-03-02 18 51 16](https://user-images.githubusercontent.com/99750559/222510969-80e15d86-8c08-440f-bbd2-43cdac02d55b.png)

### Steps to reproduce the problem

Create a note with a math block (containing LaTeX formatting) and export to any format

### Version

v2.4.4

### Platform/OS

Linux, Android

**Comment by thecodrr** [comment]
@Hexagon666666 this is a real issue. We'll fix this ASAP.

**Comment by spmp** [comment]
Sorry for the necromancy; can Notesnook be set to include the LaTeX in MD exports between $ similar to how it is displayed in the this issue, ie.:
```
$\frac{17}{73} \cdot \Omega$
```
Having HTML in MD export ruins having MD as a source of truth.
