### ISSUE TITLE
Allow resizing of certain areas on Desktop

### ISSUE THREAD

**Issue by candroid-man** [streetwriters/notesnook#205]
**Request**

On Desktop, you have 3 main sections of the app:
1. Sidebar on the very left
2. Where all the notes are shown in the current selected location
3. Editor of current selected note

It would be cool to allow the user to change the size of the middle bar (2) depending on how much of the editor the user wants to see.

**Comment by thecodrr** [comment]
@alihamuh we can use [`react-split-pane`](https://www.npmjs.com/package/react-split-pane).
