### ISSUE TITLE
Hyperlink fonts not changing on Desktop

### ISSUE THREAD

**Issue by candroid-man** [streetwriters/notesnook#206]
**Describe the bug**

Whenever you try changing the font of a hyperlink on the desktop app, Italy. Appear as that font. However on the mobile version it does show as the font that is selected.

**To Reproduce**

1. On the Linux desktop app, create a note
2. Create a hyperlink
3. Attempt to stylize the hyperlink with a font
4. Sync
5. Go to the note on the mobile app
6. See error

**Desktop**
 - OS: Arch
 - Browser: Electron (PKGBUILD)
 - Version: v1.6.12

**Comment by thecodrr** [comment]
@candroid-man I couldn't reproduce this on the latest version.
