### ISSUE TITLE
Missing icon and text in the "Configure toolbar" window

### ISSUE THREAD

**Issue by pluutoon** [streetwriters/notesnook#2080]
### What happened?

I noticed an icon and a text missing on an element in the window that allows the user to customize his toolbar.
![image](https://user-images.githubusercontent.com/50050064/223565178-d3ed6c14-17b3-4539-8e8f-a2e8d14c4a08.png)
![image](https://user-images.githubusercontent.com/50050064/223565221-d1d54a61-c4c4-4cc1-9e24-da0a1699330a.png)

While I report this bug, I wanted to also report the fact that clicking on this closes the window just in case it's not intented :
![image](https://user-images.githubusercontent.com/50050064/223565635-c5bdf553-d26f-4353-a68d-61316d1db7dd.png)

### Steps to reproduce the problem

From the "Notes" tab:
Settings >> Editor settings >> Configure toolbar

### Version

v2.4.4

### Platform/OS

Windows

**Comment by thecodrr** [comment]
@pluutoon definitely a bug. Will fix this ASAP.
