### ISSUE TITLE
Table options are gone (on old tables)

### ISSUE THREAD

**Issue by McBaumwolle** [streetwriters/notesnook#2103]
### What happened?

So on all my already created tables, the edit buttons for adding, deleting, ... rows or the whole things are gone. I cannot delete a table for now (Firefox & Windows) - I can only delete whole tables with "del".  https://github.com/streetwriters/notesnook/issues/2098 mentioned this I think.  

![image](https://user-images.githubusercontent.com/67203883/224493811-08f3db73-f7bc-4da2-a098-92d1c22b0416.png)
[old table]

![image](https://user-images.githubusercontent.com/67203883/224493826-d09d7e96-b236-418c-b13d-df5f17ff09f9.png)
[new table]

### Steps to reproduce the problem

1. Go to any already created note and select a table. 
2. The buttons should be missing. 

### Version

version 2.4.4-2c6f205-web

### Platform/OS

Windows, Firefox

**Comment by McBaumwolle** [comment]
I just found out that when I close the note and reopen it, all the tables are the same (uneditable).

**Comment by asanghc** [comment]
I have the same problem. Every table I create (even without leaving the note and returning to it)
It seems more related to how many rows you add/remove or how many different operations you do (like adding and removing rows, copying and pasting between cells, etc...)
This is very unusable... Kind of disappointing.

In case it is relevant, this is on:
linux (6.1.12-zen1-1-zen)
notesnook appimage 2.4.4 desktop

I have not tried to reproduce on different OS / version / web version etc...
