### ISSUE TITLE
Is it possible to disable multifactor authentication?

### ISSUE THREAD

**Issue by asanghc** [streetwriters/notesnook#2106]
### What problem are you facing?

I just logged into my notesnook via a web browser and was prompted for a 6 digit code sent to my email.
I checked 2factor auth options and disabling it doesn't seem to be an option..
Am I missing something?
I will always appear to login to the notesnook service from a different browser and/or computer because of the way my systems are configure. Does this mean I will have to jump through the 2FA hoops every time?

### What's the solution you'd like to see in Notesnook?

I'm pro having 2FA options but against not having choices for unimportant notebooks.

### What alternatives have you considered?

not using notesnook (alternative notes apps)

**Comment by thecodrr** [comment]
Hey, 2FA was made mandatory recently. It is one of the better security practices and while it may be inconvenient it prevents a whole class of attackers.

> not having choices for unimportant notebooks

It doesn't take long for "unimportant notebooks" to become really important. That's why we made 2FA mandatory.

**Comment by asanghc** [comment]
Please do not close this until resolved.

**Comment by thecodrr** [comment]
There's nothing to resolve. 2FA will stay.
