### ISSUE TITLE
Title of the note in the browser

### ISSUE THREAD

**Issue by livejamie** [streetwriters/notesnook#2109]
### What problem are you facing?

It's excellent context when using a note program in the browser to have the title of what you're working with displayed on the tab.

### What's the solution you'd like to see in Notesnook?

n/a

### What alternatives have you considered?

n/a

### Additional context

Here's the same note in Evernote, Supernotes and Notesnook showing the difference it makes.

![image](https://user-images.githubusercontent.com/49513/224619515-f21d4695-4ef6-4358-ab8a-2cab71cdc0ca.png)

**Comment by thecodrr** [comment]
I agree! Will add this ASAP.

**Comment by ammarahm-ed** [comment]
This has been added in #2127
