### ISSUE TITLE
Automatic Backups switch to Never

### ISSUE THREAD

**Issue by prestr** [streetwriters/notesnook#2118]
### What happened?

As of the 2.4.4 update, on macOS and Windows if you enable automatic backups the setting will revert to Never upon relaunching the app. 

### Steps to reproduce the problem

1. Setup backup configuration similar to the screenshot: 
![Screenshot 2023-03-15 at 11 43 24 AM](https://user-images.githubusercontent.com/39970655/225363599-3fbedce2-2710-440d-a305-31b03be3d0d4.png)
2. Restart the app
3. Backup setting is changed to Never. 

Issue does not persist on iOS, it works fine there. 

### Version

2.4.4

### Platform/OS

Windows, macOS

**Comment by confettimoney** [comment]
Same issue here. 

OS: macOS Ventura 13.1
Version: 2.4.4

**Comment by thecodrr** [comment]
This has been fixed in v2.4.6
