### ISSUE TITLE
Tables cannot be resized

### ISSUE THREAD

**Issue by laksby** [streetwriters/notesnook#212]
**Describe the bug**
Unable to change width/height of table and width of columns.

**To Reproduce**
1. Open application
2. Add table to the note
3. Try to drag column borders to resize columns - Nothing happens
4. Try to drag table borders to change its size - Nothing happens

**Expected behavior**
Table columns should change size
Table should change size

**Desktop (please complete the following information):**
 - OS: Linux Mint 19.2 Cinnamon
 - Desktop Application
 - Version 1.6.12-b53a158-desktop

**Comment by thecodrr** [comment]
Duplicate of #67
