### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by ettmetal** [streetwriters/notesnook#2122]
### What happened?

After session expriy, the client no longer allows selecting nor typing in the email prompt.
![Screenshot of Notesnook desktop client on Windows showing unresponsive 'enter email' input box](https://user-images.githubusercontent.com/3324453/225698147-6dc8e873-151a-4323-b6c7-a9a90c300a52.png)

There is no way to check the version, as there are no entries in the help menu (typically, vesion is listed in Help/About)
![Screenshot of Notesnook desktop client on Windows showing empty help menu](https://user-images.githubusercontent.com/3324453/225698462-27486ce7-562c-4311-9362-ebff4c5b5281.png)

### Steps to reproduce the problem

1. Log in to client
2. Wait for session to expire
3. Open client
4. Attempt to select email prompt with mouse, or tab key, and attempt to type.

### Version

Unknown (there is no help menu available)

### Platform/OS

Windows

**Comment by thecodrr** [comment]
@ettmetal this was fixed in the recent versions. You should upgrade to the latest version or if that isn't possible, just click "Relogin to your account". The email input is disabled because it is ideally prefilled with your email address.
