### ISSUE TITLE
New Note does not get add to existing note from the Android widget

### ISSUE THREAD

**Issue by rahulTPatil** [streetwriters/notesnook#2129]
### What happened?

While adding a new note in one of the existing notes, once clicked on ok icon it doesn't add the note and takes forever to resolve if it's added via the notesnook widget in android. It works faster in a new note though. 

### Steps to reproduce the problem

* Place notesnook widget on home screen of Android (if not already done)
* Select and existing note from the options
* Add content in the text box
* Press ok (Green ok button)
* Takes forever to complete and doesn't even work

### Version

2.4.6

### Platform/OS

Android

**Comment by thecodrr** [comment]
I wasn't able to reproduce this. Can you try again? And if possible can you send a screencast?

**Comment by rahulTPatil** [comment]
I tried again, but still getting the same issue. Attaching the screen-cast video as requested.
At the end of the video I have tapped outside the view. But the note does not get appended to existing notes.
OS: Android 12

https://user-images.githubusercontent.com/31767757/228595615-8f19c645-b60e-4ee6-8aca-d2ef0cb4a6ee.mp4

**Comment by rahulTPatil** [comment]
Yes, It did work on another note. Seems there is some issue with the previous selected note.
Will be closing out this issue, as it is working fine.
