### ISSUE TITLE
Heading markdown shortcuts don't work on mac editor

### ISSUE THREAD

**Issue by abhishekarora12** [streetwriters/notesnook#214]
**Describe the bug**
Heading markdown shortcuts (##) are not working in the mac editor

**Expected behavior**
(##) should format text to Heading 2, and so on

**Desktop**
 - OS: OS X 10.15.7
 - Browser: Electron 15.0.0
 - Version: 1.6.12-b53a158-desktop
 - Pro: true

**Comment by thecodrr** [comment]
@abhishekarora12 I wasn't able to reproduce this on the web version. Can you try? Do note that heading format is not applied until you press enter.

**Comment by abhishekarora12** [comment]
It's working in mac, I forgot to give the space between ## and the word. Closing this issue.
