### ISSUE TITLE
Android app starts acting quirky after playing with the formatting options like color highlight/text color

### ISSUE THREAD

**Issue by abhishekarora12** [streetwriters/notesnook#215]
**Describe the bug**
Android app starts gets quirky after playing with the formatting options like color highlight/text color. 
It stopped saving my created notes or saving any changes to existing notes, I had to quit the app from background and start it again.

**To Reproduce**
1. Open note
2. Set some highlight color/text color
 
You might need to play with combinations and write test cases for finding out other editor bugs like these

**Screenshots**
![0f4b612b-04d6-4ca5-a2fa-07be19fb097f](https://user-images.githubusercontent.com/12087783/147093425-20478d05-e248-4f6a-859a-86ccb64a3f78.jpg)

**Smartphone (please complete the following information):**
 - Device: Samsung S21 Ultra
 - OS: Android 12
 - Version: 1.6.93
 - Pro: true

**Comment by ammarahm-ed** [comment]
Hey I tried to reproduce this issue but was unable to. Are you able to reproduce this everytime you apply text/highlight color formatting or it happens randomly?

**Comment by abhishekarora12** [comment]
It was random, but the bug came once, it can come again. Fortunately, I look at the "Saved note" message at the top everytime before going back, otherwise i would i have lost my data. 
You have to do proper testing with various combinations to see if it can re-appear.
