### ISSUE TITLE
Change font size of the user interface 

### ISSUE THREAD

**Issue by LeslyeCream** [streetwriters/notesnook#2167]
On a 5.2 inch screen at 1080p resolution and 440dp the font of the user interface looks too small in comparison to the other texts (or apps) within the notes (title, content). Increasing the font size in the settings helps a bit but disproportions instead the font size of the content of the notes. Changing the dp leads me to the same situation (with the added bonus that the whole UI will now look huge).

I have tried with other apps and with different settings (font size, resolution, dp) and the result is correct.

**Comment by thecodrr** [comment]
@LeslyeCream can you attach a screenshot?

**Comment by LeslyeCream** [comment]
Sure 
![1679455377526](https://user-images.githubusercontent.com/81089188/226796947-f84a865d-6d9f-4088-b647-d3e15a048b86.jpg)
![1679455617019](https://user-images.githubusercontent.com/81089188/226796982-05b4af45-9daf-4d18-b43f-11e3c5f88b26.jpg)
![1679455530660](https://user-images.githubusercontent.com/81089188/226797013-78cb2e99-9068-47a5-8fc7-c0f00692d213.jpg)
![1679455473719](https://user-images.githubusercontent.com/81089188/226797043-0f2fe6db-ba3a-443b-a5c8-b6def68ac1d3.jpg)
![1679456501155](https://user-images.githubusercontent.com/81089188/226797049-ebc136c4-42ee-400e-8337-6512bc467f74.jpg)

As you can see in the first two screenshots it is difficult to see the letters easily, but inside the note everything seems to be fine. In comparison I place a screenshot of evernote and MindNotes

**Comment by dubs10** [comment]
> On a 5.2 inch screen at 1080p resolution and 440dp the font of the user interface looks too small in comparison to the other texts (or apps) within the notes (title, content). Increasing the font size in the settings helps a bit but disproportions instead the font size of the content of the notes. Changing the dp leads me to the same situation (with the added bonus that the whole UI will now look huge).
> 
> I have tried with other apps and with different settings (font size, resolution, dp) and the result is correct.


I agree with this issue. On iOS there is an accessibility setting that lets you change the default font scaling.  Notesnook doesn't follow this setting at all - changing it doesn't affect the UI or notes. On my iPad mini this means the default text size of notes and the UI is uncomfortably small for the size of the screen.

**Comment by luxcalor** [comment]
Same thing on Android. The font size in the notes list is very small and systemwide font size scaling won't apply to the app.

**Comment by thecodrr** [comment]
@luxcalor font scaling was added a few versions back. Can you still reproduce this?

**Comment by luxcalor** [comment]
> @luxcalor font scaling was added a few versions back. Can you still reproduce this?

Font scaling works fine for both the UI and note text since then.
