### ISSUE TITLE
You need to enable JavaScript to run this app

### ISSUE THREAD

**Issue by WiseMetalhead** [streetwriters/notesnook#22]
**Describe the bug**
In the 1.5.0 version of the application, the contents of the notes are not displayed. An error is visible in the list of notes: 

"You need to enable JavaScript to run this app.Hello World! Function (e) {function t (t) {for (var n, o, u = t [0], f = t [1 ], i = t [2], d = 0, s = []; d <u.length; d ++) o = u [d], Object.prototype.h..."

**To Reproduce**
1. Open App
2. Click on any note

**Screenshots**
[Imgur](https://imgur.com/a/PIEBnOX)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Notesnook app 1.5.0

**Comment by thecodrr** [comment]
This only happens for the welcome note, correct?

**Comment by WiseMetalhead** [comment]
Didn't notice right away. Yes, other notes are not affected.

**Comment by thecodrr** [comment]
This has been fixed. Will be coming in the next release.
