### ISSUE TITLE
Duplicate note: attributes not being copied?

### ISSUE THREAD

**Issue by mschiff** [streetwriters/notesnook#2223]
### What happened?

When duplicating a note it would be nice to have the copy in the same notebook.
Right now the new copy is not in any notebook when the source in fact was.

Seems like a bug.

### Steps to reproduce the problem

Link a note to a notebook, then copy the note.  Expected behavior would be to finde the new copy just near the original. But instead yu have to got to "notes" and find it there without any notebook linked to it

### Version

2.4.9

### Platform/OS

Android

**Comment by alihamuh** [comment]
The app copies the note into the same notebook when you duplicate it. This is the expected behaviour. 

I have checked and this functions seems to be working fine on the android. 

Can you send me a clip to demontrate what is the issue?

**Comment by mschiff** [comment]
> The app copies the note into the same notebook when you duplicate it. This is the expected behaviour.
> 
> I have checked and this functions seems to be working fine on the android.
> 
> Can you send me a clip to demontrate what is the issue?

How can I send it to you?

**Comment by thecodrr** [comment]
The issue seems to be with notes that are directly in a notebook (not under a topic).
