### ISSUE TITLE
.deb link is not working

### ISSUE THREAD

**Issue by CamaradaPrestes** [streetwriters/notesnook#2255]
### What happened?

The link for the .deb package in your website is broken.

### Steps to reproduce the problem

Click on the .deb link on the official website.

### Version

latest

### Platform/OS

Linux

### Relevant log output

```shell
That's it, just fix it. Thanks.
```

**Comment by thecodrr** [comment]
.deb & .rpm has been removed. I have also updated the website (sorry about the confusion). Please use either AppImage or Snap/Flatpak.

**Comment by CamaradaPrestes** [comment]
Bring it back, please.
