### ISSUE TITLE
Markdown file import doesn't work correctly

### ISSUE THREAD

**Issue by dmytrodubinin** [streetwriters/notesnook#2276]
### What happened?

I'm testing the program now and tried to import my files and was very disappointed. Import completely breaks file formatting, while some of the content may disappear altogether. Here is one example:
[Screencast from 2023-04-05 18-47-16.webm](https://user-images.githubusercontent.com/8066458/230134905-b5093a3e-2db8-42a9-8f63-d5ee317dd737.webm)

File from video:
[gulp4_configuration.md](https://github.com/streetwriters/notesnook/files/11160641/gulp4_configuration.md)

Unfortunately, the program really disappointed me. In addition to limited functionality (lack of cross-references, no way to view the file structure and limited nesting of files), it is impossible to correctly import a file just like that.

I tried to import the entire folder with my files, the files themselves were created, but the formatting was badly broken (from indentation to broken tables written in pure markdown). You obviously have some problem with this. And I already tried to switch to your program earlier, then I did not observe such problems when importing.

I would really like to use an open source program, but, unfortunately, so far it is simply impossible.

### Steps to reproduce the problem

Posted above

### Version

version 2.4.7-71ecc05-desktop

### Platform/OS

Linux

**Comment by thecodrr** [comment]
Hey, thanks for reporting this issue. I am taking a look right now.

**Comment by dmytrodubinin** [comment]
Currently better, but i have this:
![image](https://user-images.githubusercontent.com/8066458/230162804-37098698-de01-498a-bffd-892391938243.png)

In original file:
```markdown
- `npm install gulp browser-sync --save-dev`
- `npm init`
- `gulp watch` - to run project
```

![image](https://user-images.githubusercontent.com/8066458/230163139-fd40f1e9-df8a-48cf-bc4c-8f8ce2186245.png)

```markdown
1. install global gulp-cli and remove gulp: `sudo npm rm --global gulp` and `sudo npm install --global gulp-cli --force`
2. `npm install gulp sass gulp-sass browser-sync --save-dev`
3. `npm init`
4. `gulp watch` - to run project
```

And so on through the file...

**Comment by dmytrodubinin** [comment]
And demo with table:

![image](https://user-images.githubusercontent.com/8066458/230164617-c8bd803d-b826-47a6-853f-035621463757.png)

```markdown
| title1  | title2  | title3  | title4  |
| ------- | ------- | ------- | ------- |
| Item1.1 | Item2.1 | Item3.1 | Item4.1 |
| Item1.2 | Item2.2 | Item3.2 | Item4.2 |
| Item1.3 | Item2.3 | Item3.3 | Item4.3 |
| Item1.4 | Item2.4 | Item3.4 | Item4.4 |

```

And result after import:
![image](https://user-images.githubusercontent.com/8066458/230164822-ac2805c9-4340-4b81-b613-3876c85e052b.png)

**Comment by thecodrr** [comment]
@dmytrodubinin you're right. The spacing is all over the place.

**Comment by thecodrr** [comment]
@dmytrodubinin try v1.7.5. Both issues have been fixed.

**Comment by dmytrodubinin** [comment]
Thanks, I can check it tomorrow.

**Comment by dmytrodubinin** [comment]
Currently perfect work! No issue with formatting. 

One more question: local files doesn't import to file?
Here is in my local file:
![image](https://user-images.githubusercontent.com/8066458/230292560-6e7c5b79-756e-4ac0-a069-73bc91dddb39.png)
![image](https://user-images.githubusercontent.com/8066458/230292634-ed0b0c7b-e9dc-4bb9-a4fc-1172adf71212.png)

After import:
![image](https://user-images.githubusercontent.com/8066458/230292780-5f33827a-6955-4629-8cfe-8dc7295572e4.png)

**Comment by thecodrr** [comment]
Did you put them inside the .zip file?

**Comment by dmytrodubinin** [comment]
Yes, I archive all notes with assets. Structure is: root folder with md files and inside another folder (_resources) with images and some files
![image](https://user-images.githubusercontent.com/8066458/230452744-ed2a5717-9794-4bbd-9a62-18b534948698.png)

**Comment by thecodrr** [comment]
@dmytrodubinin then it should work. This is definitely a bug. Can you check and see if you have new attachments? Maybe the attachments got imported but they were removed from inside the note.

**Comment by dmytrodubinin** [comment]
I test again with new one note and get the same result:
My note:
![image](https://user-images.githubusercontent.com/8066458/230657982-50865a3d-6e34-4129-97a9-b6a990f7358d.png)
Rendered result:
![image](https://user-images.githubusercontent.com/8066458/230657908-cf53bfe6-1cd5-46b4-8a07-2e9c0289414b.png)

And after import:
![image](https://user-images.githubusercontent.com/8066458/230658023-cc2972e4-adcc-492a-af76-b6ac3252b021.png)
App show that note doesn't have attachments!

Here is the file from my demo:

[temp.zip](https://github.com/streetwriters/notesnook/files/11180715/temp.zip)

**Comment by dmytrodubinin** [comment]
I see that imported files doesn't contains my image but have link into it:
 
![image](https://user-images.githubusercontent.com/8066458/230658802-e5e7f621-53d5-41b5-b76e-56aaab2f5547.png)
![image](https://user-images.githubusercontent.com/8066458/230658812-41421698-22f0-486e-8db7-5c3e7f5dbe1f.png)
![image](https://user-images.githubusercontent.com/8066458/230658843-8dd8d29a-bfa5-4008-8f18-c010d0d7b285.png)

**Comment by dmytrodubinin** [comment]
As I can see, you updated Importer:
![image](https://user-images.githubusercontent.com/8066458/235137427-e039e631-73d6-49ca-af30-bdea6c2d0779.png)

In update description I see: "1. Markdown & HTML imports now support attachments (they must be placed inside the .zip archive)"

But it doesn't work! I tested it again and all my notes after import doesn't have any attachments (I mean imbedded local images). Also I tested one file from my comment below and again it doesn't work.

Any progress with it?

**Comment by thecodrr** [comment]
@dmytrodubinin should be fixed in v1.7.6

**Comment by dmytrodubinin** [comment]
Images import well, thank you.
But pdf files don't imported. I got link to pdf files, but link broken because it to local directory (from where I imported it)
![image](https://github.com/streetwriters/notesnook/assets/8066458/fec209cc-7caf-44e8-8f94-05c9700dc766)

**Comment by thecodrr** [comment]
@dmytrodubinin fixed! Do note, however, that this won't make any distinction between internal links and attachments. So anything that can be resolved to a file will get imported as attachments.

**Comment by dmytrodubinin** [comment]
> @dmytrodubinin fixed! Do note, however, that this won't make any distinction between internal links and attachments. So anything that can be resolved to a file will get imported as attachments.
> 
> Try it in v1.7.7.
Oh, thank you very much. Now everything works well. The only thing that in the future would be nice to be able to rename attached files (at least change the text name when displayed)
![image](https://github.com/streetwriters/notesnook/assets/8066458/6954215d-ca9a-4f4f-ba18-e98a805b59d3)

Thank you for a great open source program. This is certainly not a place for wishes, but I would like to get the following functionality in the near future (yes, I see that some of this is in the rodumap):
1. Linking notes, it would be nice to link headings in the text, and even better any paragraph
2. Table of Content in note
3. View the images of the document as a gallery so that you do not have to open each image separately each time
4. Improve content search
5. Improve performance in large documents (now this is a serious problem for me - when opening files from 100 thousand words, the program freezes for a long time even on very productive hardware)
6. Tabs with notes

**Comment by thecodrr** [comment]
@dmytrodubinin you can rename the files from the attachments manager in Settings. Or from the note properties inside the editor.

**Comment by dmytrodubinin** [comment]
I already have correct names in Attachment section, but in document the name is other:
![image](https://github.com/streetwriters/notesnook/assets/8066458/e6d682f2-0d60-466e-96c5-37c0a291a150)

And when I rename the file in attachment section, the original file in document doesn't change:
![image](https://github.com/streetwriters/notesnook/assets/8066458/4d70c293-a70e-4e93-a2e8-8c9363ba21d1)
