### ISSUE TITLE
Can't use anonaddy email

### ISSUE THREAD

**Issue by Getty101** [streetwriters/notesnook#2282]
### What happened?

I wanted to use an alias from anonaddy but it failed, other note taking services let me use anonaddy aliases so i expected Notesnook to be the same.

### Steps to reproduce the problem

1- Use anonaddy alias
2- The alias is not supported

### Version

2.4.11

### Platform/OS

Android, Chrome/Chromium

**Comment by thecodrr** [comment]
Hey, `anonaddy.com` is blacklisted because it is widely abused by scammers as a disposable email.
