### ISSUE TITLE
Restore Options is not available with no account

### ISSUE THREAD

**Issue by gracie95** [streetwriters/notesnook#2283]
### What happened?

Restore option is not available without account logged in.

### Steps to reproduce the problem

Just go to settings and compare **Backup & Restore** options availability.

With account: All options are available.
![Screenshot 2023-04-06 221703](https://user-images.githubusercontent.com/107738923/230408017-ebd66741-7c8e-4dc3-9801-036581d3bc34.png)

Without account: Restore option isn't available.
![Screenshot 2023-04-06 221520](https://user-images.githubusercontent.com/107738923/230407993-fcf55dd4-0af1-4568-a4f5-77e67b1f932c.png)

### Version

2.4.7

### Platform/OS

Windows

**Comment by thecodrr** [comment]
Yes, this is intentional. Restore backup requires being logged in.
