### ISSUE TITLE
Import of notes with multiple pictures from Evernote

### ISSUE THREAD

**Issue by emuell1696** [streetwriters/notesnook#23]
Hello,

I am currently testing the Notesnook app and started importing one littel notebook from Evernote (ENEX format). All of the notes are in Notesnook now, but i could realize that notes with multiple pictures (screenshots) in it only contain the one picture and the rest is beeing skipped.
I did use the "Notesnook Importer tool.

Am I doing something wrong?

br
Ernst

**Comment by thecodrr** [comment]
@emuell1696 That definitely seems like a bug in the Importer. Thanks for reporting.

**Comment by derherrm** [comment]
I'm experiencing the same issue, both with ENEX and with HTML files. As most of my current notes contain multiple images, this could be a real deal breaker for me. Do you have any plans to address this issue?

Cheers
M

**Comment by thecodrr** [comment]
@derherrm Yes, definitely. We are in the process of rewriting a much better, more accurate, and open-source version of the Notesnook Importer. Please hang tight, it will be put out soon.

**Comment by thecodrr** [comment]
The new [Notesnook Importer](https://importer.notesnook.com/) is here which should fix this issue.
