### ISSUE TITLE
Android keyboard closes on pressing backspace on a list item

### ISSUE THREAD

**Issue by abhishekarora12** [streetwriters/notesnook#230]
**Describe the bug**
On android, keyboard closes on pressing backspace on the second list item

**To Reproduce**
1. Create a list item
2. Create second list item
3. Bring the caret to the starting of second item and backspace
4. The keyboard closes as soon as it reaches to the first item

It's impossible to figure out where the second line was (especially problematic in the case of bigger notes)

**Expected behavior**
The keyboard should remain open, unless we close it manually because most of the times i want to bring the second item back on the next line.

**Smartphone**
 - Device: Samsung S21 Ultra
 - OS: Android 12
 - Version: 1.2.94

**Comment by ammarahm-ed** [comment]
@abhishekarora12 Can you try again with v1.7.0 and see if you face the problem still?

**Comment by abhishekarora12** [comment]
Fixed in v1.7.0. Closing this issue.
