### ISSUE TITLE
Android app crash after search

### ISSUE THREAD

**Issue by mschiff** [streetwriters/notesnook#2300]
### What happened?

After searching and finding a not, the app crashes

### Steps to reproduce the problem

1. Navigate to "Notes" list
2. use search bar to search for a term with some results
3. select the first note to open it
4. Return to list by clicking the left arrow in the upper left corner
5. app is closed

### Version

2.4.11

### Platform/OS

Android

**Comment by thecodrr** [comment]
This issue has been fixed.
