### ISSUE TITLE
Font in cells isn't aware of cell background color

### ISSUE THREAD

**Issue by muznyo** [streetwriters/notesnook#2308]
### What happened?

Font can be unreadable in light/dark mode depending on the color.

I think you should fix this bug with some color awareness feature

### Steps to reproduce the problem

1. Create a table
2. Select cells and set a cell background color

Light mode:
![image](https://user-images.githubusercontent.com/24987471/230742709-cfc09a57-5fd2-4f20-8e9a-f03a7441f625.png)
The font color is okay i guess

But then there's dark mode:
![image](https://user-images.githubusercontent.com/24987471/230742724-fabca096-597f-4cde-8201-23a185fed1cd.png)
The font is hard to read, because it doesn't change its color

### Version

version 2.4.7-71ecc05-desktop

### Platform/OS

Linux

**Comment by thecodrr** [comment]
>  The font is hard to read, because it doesn't change its color

And it is not supposed to. Use a color that goes well with both or set the foreground color as well in the cells. We don't make these decisions but give the user the control.
