### ISSUE TITLE
Enter doesnt insert a new row in a table

### ISSUE THREAD

**Issue by muznyo** [streetwriters/notesnook#2309]
### What happened?

When i press enter key, it adds a new line, but it should add a new row.

### Steps to reproduce the problem

1. Press enter
2. It just adds another line, not a new wor

### Version

version 2.4.7-71ecc05-desktop

### Platform/OS

Linux

**Comment by thecodrr** [comment]
I disagree. Enter always adds a new line. You need to use the toolbar to add a new row.

**Comment by muznyo** [comment]
Is there any shortcut at least?

**Comment by thecodrr** [comment]
Adding a row is possible using the toolbar button on both mobile & desktop apps.

**Comment by himanshugoswamiii** [comment]
@muznyo 
Shortcut : You can use `<Tab>` to create a new row
