### ISSUE TITLE
Backspace before a header removes addition character above the header

### ISSUE THREAD

**Issue by muznyo** [streetwriters/notesnook#2310]
### What happened?

If i set cursor to a start of a header and press backspace, it removes the line AND removes additional character of text above it.

It should only remove the line and put the text on the end of the text above

### Steps to reproduce the problem

1. Set cursor to start of a header
2. Press backspace
3. Backspace removes the line and additional character of the text above and puts the text you backspaced there

### Version

version 2.4.7-71ecc05-desktop

### Platform/OS

Linux

**Comment by thecodrr** [comment]
@muznyo are you still experiencing this? This should be fixed in the latest version.

**Comment by muznyo** [comment]
I am not experiencing it anymore, it is fixed.
