### ISSUE TITLE
Stuck at white screen when I try to create a new note (Android)

### ISSUE THREAD

**Issue by JFMugen** [streetwriters/notesnook#2323]
### What happened?

Stuck at white screen when I try to create a new note. It goes to (probably) not creation screen for a half sec and then 3-4 sec of white screen, this loop goes on and on. 

### Steps to reproduce the problem

I am just trying to create a new note to try the app before singing up. 

### Version

2.4.12

### Platform/OS

Android

**Comment by thecodrr** [comment]
This usually happens when your Android Webview version is outdated. Please update to the latest Android Web View version (and the latest Notesnook version) to fix this.
