### ISSUE TITLE
Notesnook fails to import notesnook.zip from JEX due to not failing to read the property "type"

### ISSUE THREAD

**Issue by Rowaaaaan** [streetwriters/notesnook#2327]
# Description
I'm getting the exact same issue as #1932, where exporting to JEX and then importing using the Notesnook importer fails to import because of "...undefined(reading 'type')". I followed the instructions on the [site](https://help.notesnook.com/importing-notes/import-notes-from-joplin) to a tee.

It appears as though the importer site can see the notes that I have.
![image](https://user-images.githubusercontent.com/82100519/231080208-7a35e0c7-6c88-4d9e-968f-c181551e6826.png)

But once I import it into Notesnook, I still get the error.
![image](https://user-images.githubusercontent.com/82100519/231077594-d550db88-be70-435d-8aab-9cdf1200bf8e.png)

# Steps to reproduce
1. Create Joplin notes.
2. Export Joplin notes all to JEX.
3. Create Notesnook import through the [importer](https://importer.notesnook.com/joplin)
4. Import notes.zip through Notesnook Importer.

# Expected Behavior
Notesnook imports all the notes, as well as the notebooks it's part of and the tags/metadata attached.

# Actual Behavior
Notesnook imports _some_ of the notes, and errors out.

**Comment by Rowaaaaan** [comment]
I would also like to note that it says on the site that I have 88 notes, but it only imports ~20 of them. Maybe having more than 5 tags and/or 3 Notebooks has something to do with it?

**Comment by Rowaaaaan** [comment]
Update: I tried importing a Joplin export that only had 1 Notebook, with 14 notes and no tags. Still got the same error.

![image](https://user-images.githubusercontent.com/82100519/231083876-f5226b8e-0582-4fb0-a9ea-2fbaa8201f73.png)

This is what the notebook looks like
![image](https://user-images.githubusercontent.com/82100519/231084059-fd9d9e1e-15ed-4343-b2b3-e58839e5cb77.png)

**Comment by thecodrr** [comment]
@Rowaaaaan can you try again on v2.5.0?
