### ISSUE TITLE
UI/UX Issues

### ISSUE THREAD

**Issue by SWAGATTAM** [streetwriters/notesnook#2330]
### What happened?

- [ ] 1. When rearranging check boxes holding the dotted boxes keyboard pops up. It's very hard to rearrange without the keyboard popping.
- [x] 2. Duplicate option does not work sometimes when offline.
- [x] 3. Can't change font colour because of the overlapping issue.
- [x] 4. Reminder does not save  when selected as repeat and nothing is selected under the week option. The notification that asks to select the day to repeat but it is not properly visible.
- [x] 5. Moved to trash notification sometimes stays constant and only restarting the app helps.

I have attached the screenshots of the issues.

![IMG_20230411_232843](https://user-images.githubusercontent.com/39881069/231251953-077bf330-96ed-4700-a2c5-fa7661593353.jpg)

![IMG_20230411_232402](https://user-images.githubusercontent.com/39881069/231251975-23cbb433-22a2-44f5-bd2d-d30590046e9f.jpg)

![Screenshot_2023-04-11-22-06-10-99_293ad2e737335fce7c2b783e8aed96fe](https://user-images.githubusercontent.com/39881069/231251982-a351f47f-147c-4001-a419-0545f6dfe342.jpg)

![IMG_20230411_220740](https://user-images.githubusercontent.com/39881069/231251985-5ffa5fe3-36ab-4ae2-b8c2-984e4ac68951.jpg)

### Steps to reproduce the problem

Already mentioned

### Version

2.4.12

### Platform/OS

Android

**Comment by luxcalor** [comment]
Have the same problem with rearranging checkboxes.
Android 12
Also similar layout problems on a smaller sized screen phone. Works fine on a 6 inch screen, though. Love this apps design btw.

**Comment by thecodrr** [comment]
The last issue is being tracked in #745
