### ISSUE TITLE
Frequently crashes in Android 13 phones

### ISSUE THREAD

**Issue by gracie95** [streetwriters/notesnook#2331]
### What happened?

Just upgraded to Android 13 and had this issue.

### Steps to reproduce the problem

Make sure you have OS with A13 version.

### Version

2.4.12

### Platform/OS

Android

**Comment by thecodrr** [comment]
Where and how does it crash? On startup?

**Comment by gracie95** [comment]
Yes.

**Comment by ammarahm-ed** [comment]
> Yes.

Has reinstalling the application helped?

**Comment by gracie95** [comment]
Yes. This happened cause moving app with arch armeabi-v7a to arm64-v8a phone.
