### ISSUE TITLE
scrollbar too tiny

### ISSUE THREAD

**Issue by c4r1u** [streetwriters/notesnook#2338]
### What problem are you facing?

![Screenshot_20230413_101116_Notesnook](https://user-images.githubusercontent.com/130585526/231683066-0a9b589d-265f-47c9-ad98-f1620ea8b6f6.jpg)
the scroll bar is too tiny.

### What's the solution you'd like to see in Notesnook?

make it bigger

**Comment by thecodrr** [comment]
The scrollbar is not meant to be interacted with directly on mobile.
