### ISSUE TITLE
'Report an issue' feature does not work

### ISSUE THREAD

**Issue by lyybra** [streetwriters/notesnook#235]
'Report an issue' feature does not work neither on Linux app, neither on browser.
When I click it does nothing. Tried from the begining of using Notesnook, never worked.

App version 1.6.12-b53a158-desktop up to date
Mozilla Firefox 95.0.1 (64 bit) up to date
Linux Mint 20.2 up to date

**Comment by thecodrr** [comment]
Duplicate of #211 

This has been fixed as of v1.7.0.
