### ISSUE TITLE
broken blog urls

### ISSUE THREAD

**Issue by jermanuts** [streetwriters/notesnook#2369]
### What happened?

blog.notesnook.com,  hovering over blog cards that contain broken href like {Introducing notesnook for Education} below the heading results into redirection to broken url (the heading of the post specifically). This is also the case with why notes notes requires... and notesnook 1.4 update blog posts.

### Steps to reproduce the problem

<a href="//introducing-notesnook-for-education" class="css-13gjyvs"><picture class="css-dmk2dr" style="transform: none;"><source type="image/webp" srcset="/_next/static....

just remove the extra /

fix:
<a href="/introducing-notesnook-for-education"

same with: why notes notes requires... and notesnook 1.4 update blog posts href.

### Version

website

### Platform/OS

Chrome/Chromium, Firefox, Safari, Other browser

**Comment by thecodrr** [comment]
This issue has been fixed. Thanks for reporting!
