### ISSUE TITLE
UI glitch in the note options sheet [Android]

### ISSUE THREAD

**Issue by luxcalor** [streetwriters/notesnook#2389]
### What happened?

![Screenshot_2023-04-19-21-21-43-635-edit_com streetwriters notesnook](https://user-images.githubusercontent.com/76074147/233168407-69082a7a-1306-4340-90f9-185adc4ca4ff.jpg)
Was not there in the previous version. 

### Steps to reproduce the problem

Tap three dot menu in any note. Favorite button got a problem. 

### Version

2.4.13

### Platform/OS

Android

**Comment by thecodrr** [comment]
What's the problem? If you mean the text being wrapped, how else would you prefer it? Clearly there's not enough space.

**Comment by ammarahm-ed** [comment]
I have improved it now, alignment if items is also fixed:

![Screenshot_20230425-152049_Notesnook.png](https://user-images.githubusercontent.com/40239442/234248452-591f2ab7-6ae4-4e3d-b897-350ce19e7cf4.png)

Also have changed some wording here, for example Pin/Unpin is now just Pin always, the button gets highlighted when it is On which seems a good enough indicator. Same case with Favorite/Unfavorite too.

**Comment by luxcalor** [comment]
> I have improved it now, alignment if items is also fixed

Thank you very much @ammarahm-ed The attention to detail and dedication is much appreciated. 

> Regarding text wrap consider breaking the single word with "-" symbol or shortening it with "..." or hide the title on a particularly narrow screens with option of a tip on longpressing the icon.

I suggest you still think about this. You never know what kind of screen will the app be used on or what system text size some users could set for their phones. 

> Also have changed some wording here

The wording was right. User should understand immediately what is going to happen when he/she taps the button. I suggest you leave the wording, but optimize the interface.

**Comment by ammarahm-ed** [comment]
> I suggest you still think about this. You never know what kind of screen will the app be used on or what system text size some users could set for their phones.

I am investigating how to do it in a better way.

> The wording was right. User should understand immediately what is going to happen when he/she taps the button. I suggest you leave the wording, but optimize the interface.

I agree, however for now it seems a good enough indicator that the button is highlighted, meaning it's on. Ideally words shouldn't have to wrap at all. Another option is to use  some short form words like Fav/UnFav instead of Favorite/Unfavorite which are very long and harder to fit in the UI comparatively. Right now each button in a row takes a fixed amount of space horizontally and it must fit itself in that space.
