### ISSUE TITLE
Customizing toolbar gets messy [Android web chrome]

### ISSUE THREAD

**Issue by luxcalor** [streetwriters/notesnook#2398]
### What happened?

https://user-images.githubusercontent.com/76074147/233753891-eafd4a0f-248a-49b7-8b12-c445bbf1c2e4.mp4

### Steps to reproduce the problem

Settings - editor - configure toolbar - drag and drop items

### Version

2.4.8-176c46e-web

### Platform/OS

Android, Chrome/Chromium

**Comment by thecodrr** [comment]
@luxcalor the web app is not optimized for mobile screens. Please use the native mobile app.
