### ISSUE TITLE
Exclude GIF from Google Keep invalid extensions

### ISSUE THREAD

**Issue by perjandk** [streetwriters/notesnook#240]
Hi
I get an error message when I try to import from the Google takeout file to Notesnook. See attachment.
Best regards
Per Jan
![Skærmbillede 2021-12-30 104408](https://user-images.githubusercontent.com/96866536/147740235-4c09ab9e-8b15-4a9a-9cdc-c115038b1738.jpg)

**Comment by thecodrr** [comment]
@perjandk you can safely ignore this error message. I'll write up an exclusion as well.
