### ISSUE TITLE
Sort by title (ascending and descending) on notebooks and topics

### ISSUE THREAD

**Issue by jrcacd** [streetwriters/notesnook#2451]
### What problem are you facing?

Inexistent option

### What's the solution you'd like to see in Notesnook?

Option to sort by title (ascending and descending)

**Comment by thecodrr** [comment]
I am not sure what you mean. Notesnook allows sorting topics & Notebooks by title. Just set the Group by to ABC and it'll work.

**Comment by jrcacd** [comment]
On android the option to sort by title appears only on topics, not on notebooks. 
On web does not appear on both.

![image](https://github.com/streetwriters/notesnook/assets/26005662/6ecfbabf-588b-4ce9-9f1f-2c80a66c1bf9)

**Comment by thecodrr** [comment]
@jrcacd you have to change the group by to A - Z.

**Comment by jrcacd** [comment]
Okay, I got it. 

But doesn't it get a little confusing because the options don't always appear visible?
Perhaps should always be visible and when selecting this option, the program itself changed the group by to A - Z. (Just a suggestion)

But thank you, for me the problem is solved.
