### ISSUE TITLE
Create side menu shortcuts for individual notes

### ISSUE THREAD

**Issue by luxcalor** [streetwriters/notesnook#2459]
### What problem are you facing?

Would make it easy(ier) to access some very frequently used notes. 

### What's the solution you'd like to see in Notesnook?

See the title

**Comment by thecodrr** [comment]
It would unnecessarily clutter up the UI. You can instead create a shortcut for a notebook/topic and use that to access frequently accessed notes. In the future, we'll add a list of most recently opened notes.

**Comment by luxcalor** [comment]
That is the solution I use for now. But to switch between notes I work on at the moment I have to go to notebook screen then select a note than go back there again etc. If I had them on the side menu that would be just swipe and tap. Especially if you'd add an ability to access side menu from note editor (I was going to suggest this separately). As for the UI, that would just be another shortcut on the side menu. I could have several tag or notebook shortcuts in there or several note shortcuts - the clutter is the same.

**Comment by thecodrr** [comment]
It seems what you require is a tabbed experience.

**Comment by luxcalor** [comment]
> It seems what you require is a tabbed experience.

That would be a nice solution, you are right.
