### ISSUE TITLE
Trojan detected by VirusTotal

### ISSUE THREAD

**Issue by robertvoy** [streetwriters/notesnook#2472]
### What happened?

I scanned notesnook.exe with VirusTotal and got 1 detection:

https://www.virustotal.com/gui/file/97a84b245701bab2acbcde30ab2c6d3515658a6ae50eaa5ebabea6159c384822?nocache=1

It could be a false positive, but worth bringing it up.

Especially because security is one of the main features.

### Steps to reproduce the problem

Scan with VirusTotal

### Version

Newest

### Platform/OS

Windows

**Comment by thecodrr** [comment]
definitely a false positive. No other antivirus is reporting it as a Trojan except 1.

**Comment by robertvoy** [comment]
Most likely.

However, with security-focused software, it's not great when there is a shadow of a doubt.

Might be worth trying to resolve that.

**Comment by thecodrr** [comment]
There's nothing to do on our end. We don't ship a virus or a trojan. The false positive is on the antivirus end.
