### ISSUE TITLE
Alternative Editor Support

### ISSUE THREAD

**Issue by arjunrbery** [streetwriters/notesnook#2480]
### What problem are you facing?

Typically I use Markdown to for all of my note taking. However, the back and forth translation of MD is not supported natively by TipTap.

### What's the solution you'd like to see in Notesnook?

[TipTap's documentation](https://tiptap.dev/guide/output#not-an-option-markdown) links to an [example](https://prosemirror.net/examples/markdown/) showing how to swap back and forth between multiple editor options.

### What alternatives have you considered?

Based on the available functionality, I would use NextCloud Text.

### Additional context

Thanks for the consideration. I really enjoy the tool, but as I use the tool more and more, I realize how much time I'm loosing on clean up when I copy and paste things back and forth. Unfortunately, that means that I would need to transition my subscription to another service.

**Comment by thecodrr** [comment]
There is no plan to support alternative editors.

**Comment by bendschs** [comment]
what about porting this app to nextlcoud?
