### ISSUE TITLE
Automatic backups menu on mobile should be changed

### ISSUE THREAD

**Issue by candroid-man** [streetwriters/notesnook#249]
**Request**

![Screenshot_20211231-112622_Notesnook](https://user-images.githubusercontent.com/51019003/147834226-a54f1287-c297-44c6-a6ca-df82795b5a1f.jpg)

As you can see, this doesn't look quite right, maybe add a dropdown menu instead of what you use on the desktop app.

**Comment by ammarahm-ed** [comment]
Maybe it can be moved below the description.

**Comment by thecodrr** [comment]
@ammarahm-ed that's a good idea.
