### ISSUE TITLE
Deleting notes

### ISSUE THREAD

**Issue by mcinel** [streetwriters/notesnook#25]
**Describe the bug**
Cannot delete single or multiple note

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by thecodrr** [comment]
Hey, thanks for reporting the issue. Can you please fill in the additional information in the issue template so I can fix it ASAP? Mainly, I need to know which platform you are using Notesnook on.

**Comment by thecodrr** [comment]
@mcinel Please check if you have an update for the app in the Google Play Store. I have tried reproducing this in the latest (v1.5.1) version and I couldn't.

**Comment by mcinel** [comment]
Yes I have the latest version.                I uninstalled and reinstalled for a fresh start                I was able to delete a single note but when I try to delete multiple notes I couldn't.                Then when I try to delete a single note again nothing happens.                                Thanks                                                                                                           On Wednesday, Aug 11, 2021 at 9:14 AM, Abdullah Atta <       ***@***.***> wrote:                                 @mcinel Please check if you have an update for the app in the Google Play Store. I have tried reproducing this in the latest (v1.5.1) version and I couldn't.       —You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.       ***@***.***": ***@***.***": "EmailMessage","potentialAction": ***@***.***": "ViewAction","target": "https://github.com/streetwriters/notesnook/issues/25#issuecomment-896531629","url": "https://github.com/streetwriters/notesnook/issues/25#issuecomment-896531629","name": "View Issue"},"description": "View this Issue on GitHub","publisher": ***@***.***": "Organization","name": "GitHub","url": "https://github.com"}}]

**Comment by thecodrr** [comment]
Alright I am taking a look.

**Comment by ammarahm-ed** [comment]
@mcinel I have tested again with the latest version on Google Playstore. I did the following.

1. Created 4 new notes.
2. Delete one of them and it worked.
3. Delete multiple notes with multi-select. it worked
4. Deleted a single note. It worked too.

Can you tell more about the issue. How did you create notes? Were the notes imported using Notesnook importer or did you create them normally in the editor?

The latest version of the app is v1.5.2.

**Comment by mcinel** [comment]
Yes you are right, the problem was with imported notes from Evernote.                I started fresh from scratch and was able to delete any number of notes without a problem.                                So the problem is with imported notes                                Thanks                                                                                                           On Monday, Aug 16, 2021 at 7:53 AM, Ammar Ahmed <       ***@***.***> wrote:                                 @mcinel I have tested again with the latest version on Google Playstore. I did the following.               Created 4 new notes.        Delete one of them and it worked.        Delete multiple notes with multi-select. it worked        Deleted a single note. It worked too.              Can you tell more about the issue. How did you create notes? Were the notes imported using Notesnook importer or did you create them normally in the editor?       The latest version of the app is v1.5.2.       —You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.       ***@***.***": ***@***.***": "EmailMessage","potentialAction": ***@***.***": "ViewAction","target": "https://github.com/streetwriters/notesnook/issues/25#issuecomment-899212528","url": "https://github.com/streetwriters/notesnook/issues/25#issuecomment-899212528","name": "View Issue"},"description": "View this Issue on GitHub","publisher": ***@***.***": "Organization","name": "GitHub","url": "https://github.com"}}]
