### ISSUE TITLE
Single space does not work for lists

### ISSUE THREAD

**Issue by Pjsrcool** [streetwriters/notesnook#2533]
### What happened?

In editor settings, when I disable "Use double spaced lines", new text becomes single space as expected. But lists remain double spaced. See screenshot below.

![Screenshot from 2023-05-14 20-44-06](https://github.com/streetwriters/notesnook/assets/8054560/45cb861e-f2a3-4ed9-8f0c-4f25d09fdd56)

### Steps to reproduce the problem

1. In editor settings, switch "Use double spaced lines" to off.
2. refresh editor
3. in any note, create a list and it will continue to be double spaced

### Version

version 2.4.9-f9116b2-web

### Platform/OS

Chrome/Chromium, Firefox

**Comment by thecodrr** [comment]
The spacing between list items is not the same as spacing between "lines". List items are not single spaced or double spaced.
