### ISSUE TITLE
Enabling "Backup encryption" as a non-premium user doesn't trigger the Notesnook Pro upgrade screen

### ISSUE THREAD

**Issue by xfzv** [streetwriters/notesnook#2548]
### What happened?

1. As a non-premium user, open Notesnook Android app (2.4.17)
2. Go to Settings > Backups
3. Tick "Backup encryption" (premium feature)
4. The option is ticked (it shouldn't)
5. The Notesnook Pro upgrade screen isn't displayed (it should be)

The created backup isn't encrypted (as expected). No issue with the Linux AppImage (2.4.11).

### Steps to reproduce the problem

1. As a non-premium user, open Notesnook Android app (2.4.17)
2. Go to Settings > Backups
3. Tick "Backup encryption" (premium feature)
4. The option is ticked (it shouldn't)
5. The Notesnook Pro upgrade screen isn't displayed (it should be)

### Version

2.4.17

### Platform/OS

Android

**Comment by ammarahm-ed** [comment]
Backup encryption has been made available to all users (Pro & Basic) in the latest version of Notesnook.
