### ISSUE TITLE
Outline list bullet/arrow position

### ISSUE THREAD

**Issue by luxcalor** [streetwriters/notesnook#2553]
### What happened?

I have to bring this up again, since the previous issue is closed. One of the main reasons I have subscribed to NN was a nicely working outliner combined with other brilliant features. But since a few updates now the outline lists' layout is broken and hard to work with on all devices. I hope this is not the intended behaviour as it is very inconvenient to work with. 
![Screenshot_2023-05-18-17-53-53-133_com streetwriters notesnook-edit](https://github.com/streetwriters/notesnook/assets/76074147/372b75c9-d973-4a67-bfc1-860ec4178a30)

![IMG_20230518_175039_911](https://github.com/streetwriters/notesnook/assets/76074147/79aa6998-fe91-4abe-b229-788c9dd43dc6)

### Steps to reproduce the problem

Create an outline list with substantial amount of text in each list item, compare where the actual paragraph starts and where the bullets/arrows are.

### Version

2.4.17 / 2.4.11

### Platform/OS

Windows, Android, Chrome/Chromium

**Comment by thecodrr** [comment]
@luxcalor this is definitely an issue. Will fix this ASAP.

**Comment by luxcalor** [comment]
@thecodrr thank you
