### ISSUE TITLE
The app only attaches a photo from the camera on android on the second attempt in a new note 

### ISSUE THREAD

**Issue by jrcacd** [streetwriters/notesnook#2563]
### What happened?

The app only attaches a photo from the camera on android on the second attempt in a new note 

### Steps to reproduce the problem

New note > Image > Take a photo using camera

### Version

2.4.17

### Platform/OS

Android

**Comment by luxcalor** [comment]
Same. Most of the times the photo appears in the new note only after the second try. But not always. If I kill the app process and then start the app anew sometimes it works right away.

**Comment by thecodrr** [comment]
I haven't been able to reproduce this on Android. I have tried a few times.

**Comment by jrcacd** [comment]
My phone: xiaomi redmi note 9S. Hope it helps if the bug is platform specific

**Comment by thecodrr** [comment]
Can you share a video recording?

**Comment by luxcalor** [comment]
> Can you share a video recording?

Tried it many times during the day and the issue happened twice. Could not pinpoint what triggers the behaviour. Sometimes the image just does not appear in the note and it stays empty. I do use a xiaomi redmi note phone too.

**Comment by luxcalor** [comment]
> Can you share a video recording?

Here you go. Was able to capture the issue on video.
https://github.com/streetwriters/notesnook/assets/76074147/95010b1e-bee3-4a10-956b-ce6b0f2c87a6

**Comment by thecodrr** [comment]
@luxcalor are you still have this problem?

**Comment by luxcalor** [comment]
> @luxcalor are you still have this problem?

Yes. Also the same happens with attaching images on Android from time to time. I think it is true same issue with inserting and image into a note.

**Comment by ammarahm-ed** [comment]
Hey @luxcalor Are you still facing this issue? I made a few fixes that prevent the editor from reloading now.

**Comment by luxcalor** [comment]
> Hey @luxcalor Are you still facing this issue? I made a few fixes that prevent the editor from reloading now.

Hi. This seems to be fixed. Also the image appears in the note faster. Thanks!
