### ISSUE TITLE
Google Keep import: ~70% of notes imported without images

### ISSUE THREAD

**Issue by luxcalor** [streetwriters/notesnook#2566]
### What happened?

~70 percent of notes that had images in them in Keep were imported to NN sans images. Most of the affected notes now have headings with lots of numbers and ending with .json in NN after importing.

The images are there in the google takeout zip, HTML files of the exported notes do contain the images.

The zip file that got out of the NN Importer is half the size of the takeout one, for that matter.

I have tried importing several times now with different takeouts, result is the same.

### Steps to reproduce the problem

As described in Google Keep import instruction.

### Version

2.4.11 / 2.4.17

### Platform/OS

Windows, Android, Chrome/Chromium

**Comment by thecodrr** [comment]
@luxcalor can you confirm that all notes are without images or only some? Because the Takeout I tried with, all the images are getting imported.

**Comment by thecodrr** [comment]
It'll also be really helpful if you can send the JSON content of a Google Keep note that is importing without images. My suspicion is that the filename is causing the importer to not find the file in the Takeout.zip.

To find the specific note, you can open the Takeout.zip in any Archive tool and go into `Takeout/Keep` directory. Here you will find a lot of files. These files are named according to their title. Find the file you need and make sure it ends with `.json`.

When pasting here the JSON contents, you can take out the sensitive information. The only thing I am concerned about is the structure of the file and the filenames of the attachments.

**Comment by luxcalor** [comment]
> @luxcalor can you confirm that all notes are without images or only some? Because the Takeout I tried with, all the images are getting imported.

Not all. Only similar to the ones I have mentioned in the above comment. Approx. 70 percent of the notes.

**Comment by thecodrr** [comment]
@luxcalor did you take out the content from the above examples or are all of them like that?

**Comment by luxcalor** [comment]
> @luxcalor did you take out the content from the above examples or are all of them like that?

Most of them are like that. Just a title, a tag and an image attached to a note. A few have some text and the text got imported.

**Comment by thecodrr** [comment]
In my testing, Google Keep notes that don't have any text content also don't get their attachments imported. However, if there is any text present, the attachments also get imported.

I tested with the above examples you provided.

**Comment by thecodrr** [comment]
@luxcalor I updated the importer with a couple of fixes to Google Keep importer. Can you try again? Version is 1.7.7

**Comment by luxcalor** [comment]
It did work nicely this time around. The size of the Notesnook generated import zip file was still exactly half the size of the Google takeout one. Nevertheless, the images were imported correctly in every note I've checked, and in what seems like an original size and quality. All the titles and tags are correct as well. 

Thank you very much @thecodrr

**Comment by thecodrr** [comment]
That's great! The size difference is due to a lot of duplication in the Takeout zip. Nothing to worry about, though.

I'll close this issue.

**Comment by luxcalor** [comment]
Good. I'll be working extensively with imported notes, will let you know if something is off. It seems to be allright, though.
