### ISSUE TITLE
AMOLED Night Mode on Desktop

### ISSUE THREAD

**Issue by drannex42** [streetwriters/notesnook#2575]
### What problem are you facing?

Mobile has an AMOLED dark mode, is it possible to enable this option on desktop? I am sure there is another issue mentioning this, but unable to find one.

### What's the solution you'd like to see in Notesnook?

AMOLED dark mode on desktop

**Comment by thecodrr** [comment]
This has been fixed with the new themes. Just use the Notesnook Pitch Black theme or create your own.
