### ISSUE TITLE
Note edit time is in AM/PM format even though the system time is in 24h [Android]

### ISSUE THREAD

**Issue by luxcalor** [streetwriters/notesnook#2583]
### What happened?

![IMG_20230524_020912](https://github.com/streetwriters/notesnook/assets/76074147/e9a9992d-401c-4bb2-b25d-4c6ae226d151)

### Steps to reproduce the problem

Look at the note edit time.

### Version

2.4.17

### Platform/OS

Android

**Comment by ammarahm-ed** [comment]
This has been fixed in the latest version.
