### ISSUE TITLE
Only 30 objects can be modified

### ISSUE THREAD

**Issue by ipstyle** [streetwriters/notesnook#2588]
### What happened?

You can only modify 30 note at a time.

The GUI tells you that e.g. all 33 notes have been assigned to a topic, but that's not true.
Only 30 can be handled.

This is a problem if you import large amount of objects from e.g. evernote or modify lot of objects.

### Steps to reproduce the problem

How to reproduce:

1. reproduce procedure, start ;
- imported notes from evernote
or
- created manually 1,2,3, to 35 notes

2. mark them all (35 notes same time) and add them to a notebook/topic

3. in the app you have assigned them to the notebook/topic everything look fine
BUT if you check e.g. the web version then you can see that ONLY 30 notes have been applied

So theres a bug by handling more than 30 notes at the same time - looks like a limit.

tested with
 - macosxp app
 - webbrowser firefox
 - windows app

### Version

2.4.11 (240)

### Platform/OS

Windows, macOS, Chrome/Chromium, Firefox, Safari

**Comment by thecodrr** [comment]
I haven't been able to reproduce it. I added 68 notes into a notebook and it works just fine. Maybe what's happening is that it is erroring out on the 30th note.

**Comment by ipstyle** [comment]
I can reproduce the task when i import e.g. a evernote file with 40 notes, mark them all, add them to a topic or notebook.
Let me deep dive and reproduce this later - i will come back with some more details.

**Comment by thecodrr** [comment]
@ipstyle have you been able to find out why this occurs or how to reproduce this reliably?
