### ISSUE TITLE
Table of contents

### ISSUE THREAD

**Issue by fernando-mesquita** [streetwriters/notesnook#2590]
### What problem are you facing?

A big improvement would be an option to view titles within a note in an index or side panel, as in Obsidian or Typora.

### What's the solution you'd like to see in Notesnook?

A side title panel or a `[TOC]` markdown syntax.

### What alternatives have you considered?

Obsidian and Typora use this solution as example.

**Comment by Madhan-kumar-selvaraj** [comment]
I too want this feature in our notes and the reason is that when we are having the long notes with multiple heading, its become very hectic to switch to the particular heading. As we are having "Table of contents" in our Monograph page, add the same feature in the note page also. Thanks in advance.

**Comment by dmytrodubinin** [comment]
Are there any plans to do this?
