### ISSUE TITLE
Minimize to system tray - Desktop Linux Gnome

### ISSUE THREAD

**Issue by fernando-mesquita** [streetwriters/notesnook#2591]
### What happened?

Minimize to system tray is not working on Fedora Workstation, Gnome wayland and "AppIndicator and KStatusNotifierItem Support" plugin.
The three dots appear unstable, and when triggering any action, the icon disappears and the application does not return.
It is necessary to end the process and restart the application to return to the notes.

### Steps to reproduce the problem

Enable "minimize to system tray" in settings.

### Version

version 2.4.10-abb89ec-desktop

### Platform/OS

Linux

**Comment by thecodrr** [comment]
@fernando-mesquita can you verify this bug on v2.6.3?
