### ISSUE TITLE
Webclipper not compatible with latest firefox version 102.11.0

### ISSUE THREAD

**Issue by ipstyle** [streetwriters/notesnook#2594]
### What happened?

Hi dev guys,

![image](https://github.com/streetwriters/notesnook/assets/71832991/dafb2344-eba1-4c9c-84cd-98c18ced4c01)

cheers

### Steps to reproduce the problem

see upon

### Version

latest version, web

### Platform/OS

Firefox

**Comment by thecodrr** [comment]
Yes, we don't support outdated Firefox versions. You will have to update your Firefox installation.

**Comment by ipstyle** [comment]
Hi thecodrr,

Sorry - you're right. Wrong release verification on my side.
I will give it a try again.

Closed.
