### ISSUE TITLE
Can't download Windows installer

### ISSUE THREAD

**Issue by daveclayton** [streetwriters/notesnook#26]
Windows Defender is blocking the download of the installer file, possibly because it has a URL from github-releases.githubusercontent.com but the site that I'm triggering the download from is notesnook.com

![Screenshot 2021-08-12 093853](https://user-images.githubusercontent.com/140399/129166292-089d7d4b-4875-4884-ad33-71db601648e0.png)

**Comment by thecodrr** [comment]
Self hosting or using a CDN would be much better. Thank you for bringing this to my attention.

**Comment by thecodrr** [comment]
This has now been fixed.
