### ISSUE TITLE
iOS Font Sizing Issue

### ISSUE THREAD

**Issue by nullifiedtoast** [streetwriters/notesnook#2617]
I saw another post about this but wanted to provide a video of what exactly is happening. The font jumps to 120px and then doesn't want to properly shrink back down until another section with no text is selected and then the giant text is reselected and the center of the sizing tapped at which point it returns to 16px.

https://github.com/streetwriters/notesnook/assets/134788604/e122ed21-9006-4146-be24-4d570528e2e7

**Comment by thecodrr** [comment]
Hi, thank you for the video. I can reproduce this on Android as well. Will fix ASAP.
