### ISSUE TITLE
F-Droid can't build

### ISSUE THREAD

**Issue by licaon-kter** [streetwriters/notesnook#2645]
https://monitor.f-droid.org/builds/log/com.streetwriters.notesnook/10248#site-footer ah, ok, something changed, let me remove that line...

But rebuilding fails differently: [com.streetwriters.notesnook_10248.log.gz](https://github.com/streetwriters/notesnook/files/11626596/com.streetwriters.notesnook_10248.log.gz) as if it does not try to build vips first?!

/LE: fyi https://gitlab.com/fdroid/fdroiddata/-/commit/67406f23bc320b7e6b39a42b2543d693f1a54e1d

**Comment by ammarahm-ed** [comment]
Seems like one of the packages has been changed and the fdroid build config needs some updating. I will take a look and fix this.

**Comment by ammarahm-ed** [comment]
I think I fixed it. Let's see the build: https://gitlab.com/fdroid/fdroiddata/-/merge_requests/13173

Also I think the rebuilding error was due to something else probably.

**Comment by licaon-kter** [comment]
Done
