### ISSUE TITLE
Notebooks - Link to...

### ISSUE THREAD

**Issue by sharemind** [streetwriters/notesnook#2661]
### What problem are you facing?

In the android app when inside a Notebook, selecting more than one note the batch command don't include the "+" sign to Link to another Notebook/Topic. (the "+" sign is present when inside a Topic )

There is only the "–" sign to remove from the Notebook.

![Screenshot_20230605_185757_Notesnook](https://github.com/streetwriters/notesnook/assets/4588470/dbc32b29-7b4b-45e9-bdf4-4cfac36ddfc5)

### What's the solution you'd like to see in Notesnook?

Add the "+" sign to Link to another Notebook/Topic and the "#" sign for tagging

![Screenshot_20230605_190318_Notesnook](https://github.com/streetwriters/notesnook/assets/4588470/768efdc8-a250-4d1b-a795-d6de689a4f4f)

**Comment by Coding-Algorithm** [comment]
> ### What problem are you facing?
> 
> In the android app when inside a Notebook, selecting more than one note the batch command don't include the "+" sign to Link to another Notebook/Topic. (the "+" sign is present when inside a Topic )
> 
> There is only the "–" sign to remove from the Notebook.

@sharemind , I am trying to reproduce the issue you are facing, but I could see that the solution you are requesting for have already been provided.

May I ask which version of the app you are using and what is the name of your device?

Thanks

**Comment by sharemind** [comment]
On android I have notesnook version 2.5.1

**Comment by Coding-Algorithm** [comment]
I also use v2.5.1 but I could see those request you are making.

**Comment by sharemind** [comment]
I have deleted the app and reinstalled, but nothing changed
