### ISSUE TITLE
Coma is added after each word in new note custom title [Android]

### ISSUE THREAD

**Issue by luxcalor** [streetwriters/notesnook#2665]
### What happened?

When the new note title custom formatting is set to `$headline$ $date$ $time$`, coma is added after each word in the title:
![Screenshot_2023-06-06-09-40-50-292_com streetwriters notesnook-edit](https://github.com/streetwriters/notesnook/assets/76074147/bb7cbeb8-e67b-4f8b-9159-ea41f068c506)

### Steps to reproduce the problem

See above

### Version

2.5.1

### Platform/OS

Android

**Comment by ammarahm-ed** [comment]
Fixed in https://github.com/streetwriters/notesnook/commit/1224e48bc89f49a9b0a53e90ca2bec08535de995
