### ISSUE TITLE
Add Notesnook to Nixpkgs repository

### ISSUE THREAD

**Issue by mjarosie** [streetwriters/notesnook#2676]
### What problem are you facing?

That'd be great if Notesnook could be installed with `nix` package manager. I think that'd actually adhere to the current roadmap ("Publish on more app stores")?

### What's the solution you'd like to see in Notesnook?

That would require adding Notesnook to [nixpkgs repo](https://github.com/NixOS/nixpkgs). Here are the instructions: https://nixos.org/manual/nixpkgs/stable/#chap-quick-start

**Comment by j0lol** [comment]
if you have a flake enabled system you can use my `notesnook-appimage` package from here until notesnook is merged into nixpkgs: https://codeberg.org/j0/jopkgs :)
