### ISSUE TITLE
Lexical ordering date format

### ISSUE THREAD

**Issue by tylermercer** [streetwriters/notesnook#2679]
### What problem are you facing?

The new date format list does not contain `YYYY-MM-DD`, which is ~the One True Date Format~ the only format that orders lexicographically. Can that be added?

(It does, bewilderingly, contain `YYYY-DD-MM`. 🤔)

### What's the solution you'd like to see in Notesnook?

Add `YYYY-MM-DD` format to date format picker.

### What alternatives have you considered?

Just leaving it as is

### Additional context

I have been using YYYY-MM-DD in my note titles since I started using Notesnook. Having it automatically do it for me would be awesome 🎉

**Comment by thecodrr** [comment]
@tylermercer sorry about that. We have fixed this and it'll be part of the new release.

**Comment by tylermercer** [comment]
@thecodrr thank you! And thank you for responding so quickly!
