### ISSUE TITLE
Invalid email address?

### ISSUE THREAD

**Issue by neekless** [streetwriters/notesnook#2700]
### What happened?

I use Tutanota, a privacy focused email service, and my email address ends with "@tutamail.com". I tried to sign up a Notesnook account and I get the error "Invalid email address". I tried again with a Gmail email address and it works. 

How are you verifying the validity of email addresses? Are you just matching the common email services like Gmail and Outlook? If that is so I have very little faith in the way you do things. I use my Tutanota email address for plenty of things and this is the first service that claims it is "invalid"

### Steps to reproduce the problem

Use a Tutanota email address to sign up.

### Version

Website

### Platform/OS

Chrome/Chromium

**Comment by thecodrr** [comment]
@neekless That error is very generic and it doesn't always mean that the email address is blocked. We have many Tutanota users who are using Notesnook without issues so I don't think we are blocking Tutanota.

What you could be seeing is probably duplicate account issue where this email is already registered.
