### ISSUE TITLE
Import from Standard Notes

### ISSUE THREAD

**Issue by EDITH300** [streetwriters/notesnook#274]
i cant found the import option standard notes 
[where is the option](https://i.ibb.co/3WyFXhW/Screenshot-20220107-173830.png)

**Comment by EDITH300** [comment]
[](https://i.ibb.co/3WyFXhW/Screenshot-20220107-173830.png

**Comment by thecodrr** [comment]
Standard notes is not yet supported in the imported. It will be added soon.
