### ISSUE TITLE
Share several images/files to NN at once [Mobile]

### ISSUE THREAD

**Issue by luxcalor** [streetwriters/notesnook#2749]
### What problem are you facing?

First of all, thank you for implementing sharing feature, it is very useful.
Now, being able to select several images or files and share them all at once to NN would be even more useful.
Also attaching several files at ones from the NN itself would be useful too.

### What's the solution you'd like to see in Notesnook?

See above

**Comment by luxcalor** [comment]
Any progress on this? Frankly, it's a PITA to attach several images/files to a note at the moment. Especially considering that the app won't remember the last accessed folder.

**Comment by ammarahm-ed** [comment]
It's WIP in https://github.com/streetwriters/notesnook/pull/3167
