### ISSUE TITLE
Option to change background color for each notes in light mode

### ISSUE THREAD

**Issue by Madhan-kumar-selvaraj** [streetwriters/notesnook#2751]
### What problem are you facing?

* Formatting options for the Notes are good, but if there is any option to change the complete background color of the  notes will be very cool feature.

### What's the solution you'd like to see in Notesnook?

* I found this feature in the Gratitude app and while writing notes in the same background color, sometimes it'll be boring.
* Check the below screenshot for reference – https://gratefulness.me/
* 
![image](https://github.com/streetwriters/notesnook/assets/59301245/d48646c2-846f-4acf-808c-dd7e18dda3ce)

**Comment by thecodrr** [comment]
This goes against the overall UI of Notesnook which is simple and consistent. We do offer themes which allow changing the background of the editor for all notes.
