### ISSUE TITLE
can't verify my email. return 'invalid token' error

### ISSUE THREAD

**Issue by Ahmdrza** [streetwriters/notesnook#2765]
### What happened?

I was trying to verify my email by clicking on link in the email but it return an error saying 'invalid token'

### Steps to reproduce the problem

create an account, it will send you an email to verify your account/email, click on the link in the email. Instead of verifying email, it returns error

### Version

latest

### Platform/OS

macOS

**Comment by danielintempesta** [comment]
The same thing happened to me. I clicked on resend and the second time it did let me.

**Comment by ammarahm-ed** [comment]
This issue has been fixed.
