### ISSUE TITLE
Previously clipped article gets saved again when clipping from web, making quick note or sharing to NN app [Android]

### ISSUE THREAD

**Issue by luxcalor** [streetwriters/notesnook#2771]
### What happened?

When clipping or making a quick note or sharing anything to NN app, previously clipped article gets saved again and again, together with the new notes, at the same exact time. 

### Steps to reproduce the problem

See above

### Version

2.5.3

### Platform/OS

Android

**Comment by luxcalor** [comment]
Did reinstall the app. And it still happens every single time.

**Comment by ammarahm-ed** [comment]
Hi, this issue has been fixed. A new update will be available soon. It also might be the reason for notes reverting back. Fixed in #2874

**Comment by luxcalor** [comment]
> Hi, this issue has been fixed. A new update will be available soon. It also might be the reason for notes reverting back. Fixed in #2874

Thanks. Appreciated.
