### ISSUE TITLE
drag & drop multiple images are not displayed correctly on windows desktop app

### ISSUE THREAD

**Issue by tolgaulas** [streetwriters/notesnook#2788]
### What happened?

When i drag & drop multiple images files into the note, only the first image is displayed correctly but the other images are displayed as first image. Although it displays like the same images is pasted similarly, when i go to the web application, i see the images are properly placed with correct images. 

On desktop client when you click the eye icon (preview attachment) of the image it displays it correctly in the preview. 

When I exit and restart the desktop app, then the images are displayed correctly. 

### Steps to reproduce the problem

Described in the what happened

### Version

2.5.3-548eda9-desktop

### Platform/OS

Windows

**Comment by ammarahm-ed** [comment]
Hi, this issue has been fixed in v2.5.4 of the desktop app. Please upgrade your app to the latest version.
