### ISSUE TITLE
Unable to attach new documents to a notes since update

### ISSUE THREAD

**Issue by TJonCooper** [streetwriters/notesnook#2797]
### What happened?

I'm unable to attach a new document to a pre-existing note. When attempting to do so, NotesNook gives the error message:

![Screenshot from 2023-06-22 11-29-47](https://github.com/streetwriters/notesnook/assets/15924377/a38b9d9e-1e34-4e4e-a5af-a3669eab012e)

And then indefinitely hangs as the 'encrypting attachment' progress indicator spins. 

This is on Ubuntu 22.04.2 LTS.

### Steps to reproduce the problem

Attach a document (in this case, a PDF) to a note.

### Version

2.5.3-548eda9-desktop

### Platform/OS

Linux

**Comment by dmytrodubinin** [comment]
The same problem
