### ISSUE TITLE
Password Recovery Stuck at Authenticating User

### ISSUE THREAD

**Issue by ejedades** [streetwriters/notesnook#2837]
### What happened?

I have a backup file but I keep getting stuck at "Authenticating User" following the link provided in email recovery. Tried several times and waiting for several minutes but the issue still persists. 

### Steps to reproduce the problem

1. Open app and enter email
2. Select "forgot password?"
3. Enter registered email
4. Follow email instructions and click "Reset your password"

### Version

2.5.4-bb1cb8d-desktop

### Platform/OS

Windows

**Comment by ammarahm-ed** [comment]
This has been fixed.
