### ISSUE TITLE
Android instal on second device is blocked

### ISSUE THREAD

**Issue by MicheleSaltori** [streetwriters/notesnook#2857]
### What happened?

After installing the Android app v2.5.3 or 2.5.4 on the screen appears the request to choose one of the three privacy levels, however any choice reports the error "Biometrics no enrolled. To use app lock, you must enable biometrics such as Fingerprint lock or Face ID on your phone or create an account."
My phone does not have a biometric locking system and this request is not feasible, I already have an online account but the app, in this state,  does not allow other actions.

### Steps to reproduce the problem

Install the app on a second device without bimetric recognition, then run the app.
Attached screencast file...

https://github.com/streetwriters/notesnook/assets/40836499/bcabcaf9-fb37-4e51-84a7-86cd509b577e

### Version

v2.5.4

### Platform/OS

Android

**Comment by ammarahm-ed** [comment]
Fixed in #2885
