### ISSUE TITLE
Issues close/minimize on Ubuntu

### ISSUE THREAD

**Issue by iJorgen** [streetwriters/notesnook#2907]
### What happened?

Starting the AppImage works fine the first time, but if I close Notesnook on "X" or "_" I can't get it back in focus. When looking in System Monitor I see that Notesnook is running. Only solution I found is to select these processes and "End process". Now I can start Notesnook again.

![Screenshot from 2023-07-08 16-05-38](https://github.com/streetwriters/notesnook/assets/52280788/8dc1034e-b7c7-4951-9e64-a86b5b4f3d62)

No icons shows in the top bar either, if these to are selected. Using Ubuntu 23.04

![Screenshot from 2023-07-08 16-17-43](https://github.com/streetwriters/notesnook/assets/52280788/6f78b9ed-0133-4997-9f36-de2eeba23687)

### Steps to reproduce the problem

1. Start notesnook_linux_x86_64-v2.5.7.AppImage
2. Exit the program using "X" or "_"
3. Now you can't make the program comeback unless you end the processes in System Monitor.

### Version

notesnook_linux_x86_64-v2.5.7.AppImage

### Platform/OS

Linux

**Comment by thecodrr** [comment]
This should be fixed in v2.5.8.
