### ISSUE TITLE
Task list parent item remain unchecked after moving the last unchecked sub-item outside

### ISSUE THREAD

**Issue by 4fosaefp** [streetwriters/notesnook#2910]
### What happened?

When a task has all but one sub-item checked like this:
![image](https://github.com/streetwriters/notesnook/assets/115563922/5b1ea2cd-f28e-4ce2-89c9-57d88413c83e)
If I then drag the unchecked sub-item out of the parent item:
![image](https://github.com/streetwriters/notesnook/assets/115563922/dc3bd4f4-079b-4884-a4e3-c62a01fa2014)
The parent item remains unchecked, even though it should automatically be checked since all the sub-items are checked.
Furthermore, trying to manually check the parent item will not work.

### Steps to reproduce the problem

1. Create a task list with a parent item containing multiple sub-items
2. Check all but one sub-item
3. Drag the unchecked sub-item out of the parent item
4. Observe that the parent item remains unchecked and cannot be checked manually either

### Version

version 2.5.2-3e95960-web

### Platform/OS

Windows, Firefox

**Comment by alihamuh** [comment]
I tried. issue not solved. 

Progress: The parent taskitem is gets checked in the database/store but the change is not relected in the editor. node.attrs.checked also gets updated but still editor does not reflect this change. When the note is refershed or when it is closed and opened again, the parent item shows correctly in the editor.
