### ISSUE TITLE
NotesNook software is not available in windows store

### ISSUE THREAD

**Issue by Madhan-kumar-selvaraj** [streetwriters/notesnook#2924]
### What problem are you facing?

- Checked the NotesNook software in the windows 11 store but I can't get it
- ![image](https://github.com/streetwriters/notesnook/assets/59301245/18cba266-4821-4a00-95ef-b7305b25d6d8)

### What's the solution you'd like to see in Notesnook?

- Want to have the software in windows store and it'll have a better reach to all

**Comment by thecodrr** [comment]
There's no plan currently to distribute Notesnook via Windows Store
