### ISSUE TITLE
Nested lists and elements in lists

### ISSUE THREAD

**Issue by shawn1thompson** [streetwriters/notesnook#2950]
### What problem are you facing?

Can't find a way to create a nested list.
e.g.
1. Do this
    - this is how
2. Do that
    - that is how
3. Report
    > Don't worry, be happy was a number one jam, but damn if I say it you can slap right here

### What's the solution you'd like to see in Notesnook?

See this [link](https://www.markdownguide.org/basic-syntax/#adding-elements-in-lists)

Be able to create nested lists and nested elements in lists

### What alternatives have you considered?

haven't

**Comment by thecodrr** [comment]
It's possible. Just use the `Tab` key to indent and have nested lists.

**Comment by shawn1thompson** [comment]
Using the Tab key to indent only indents a list element. Please see my example. I want to be able to have other elements within a list. Also, have a look at the link which shows how it's normally done in Markdown.
