### ISSUE TITLE
Logging in on a new device resets several synced preferences

### ISSUE THREAD

**Issue by ajgraves** [streetwriters/notesnook#2953]
### What happened?

When you log in from a new device, several preferences get reset to the default value (as the new device, which has the default values, pushes those across on the first sync). It would be better if the new device didn't push the default values to what is already synced.

Data which is reset:

- Date format
- Time format
- Trash cleanup interval
- Default title format
- Possibly some others I have missed

### Steps to reproduce the problem

Change one of the above mentioned default values to something other than the default. Log in from a new device/browser/session, and notice that those values are now set back to the default values.

### Version

2.5.7-92bafba-desktop

### Platform/OS

Windows, macOS, Linux, iOS, Android, Chrome/Chromium, Firefox, Safari, Other browser

**Comment by thecodrr** [comment]
This has been fixed.
