### ISSUE TITLE
Unable to import files

### ISSUE THREAD

**Issue by passionate2023** [streetwriters/notesnook#2975]
### What happened?

Unable to import files

### Steps to reproduce the problem

No error. No files imported
[txt.zip](https://github.com/streetwriters/notesnook/files/12087900/txt.zip)

### Version

latest

### Platform/OS

Windows

### Relevant log output

```shell
Unable to import files
```

**Comment by ammarahm-ed** [comment]
Hey I just tested with your provided files. The import works, you just have to wait a little longer for it to complete.

**Comment by passionate2023** [comment]
Can you please add a progress bar or atleast a blocking message until the processing gets completed? any percentage would be great

**Comment by ammarahm-ed** [comment]
> Can you please add a progress bar or atleast a blocking message until the processing gets completed? any percentage would be great

Yes, we will fix this.

**Comment by thecodrr** [comment]
Please wait for the next version of the Notesnook Importer.

**Comment by passionate2023** [comment]
The latest version has the issue. which version is the next version. Please help

**Comment by thecodrr** [comment]
@passionate2023 are you following the steps from here: https://help.notesnook.com/importing-notes/import-notes-from-plaintext-files

**Comment by passionate2023** [comment]
@thecodrr I tried but it doesn't work. Please check whether the version supports unicode characters. Also i would recommend to have support for .txt files directly along with the zip files. The steps are not clear. Do i need to convert .txt files to any other formats? what are the file formats is supported inside zip file format?

**Comment by thecodrr** [comment]
@passionate2023 did you try it recently on v2.0.3 of the Importer? I am trying it and it's working flawlessly with the zip you provided and yes, Unicode is preserved. Not sure what you are doing.

**Comment by passionate2023** [comment]
Attached the zip file which failed to get imported. 
[stories.zip](https://github.com/streetwriters/notesnook/files/12323643/stories.zip)

**Comment by passionate2023** [comment]
issue: full content search is also not supported. only it searches for the titles
