### ISSUE TITLE
Embed the mobile version: notesnook anywhere

### ISSUE THREAD

**Issue by ghost** [streetwriters/notesnook#2978]
### What problem are you facing?

A general problem for  mobile device developers is unofficial stores. This is a problem, because there are often poorly made open or closed source versions in these unofficial stores.

### What's the solution you'd like to see in Notesnook?

One way to solve this problem is to adopt unofficial stores as official ones, to direct the correct installation of an application by the official distributor. So "embed the mobile version: notesnook anywhere"

### What alternatives have you considered?

We must give greater security, privacy and control to users and not to hackers. This would be avoided by adopting unofficial stores as official distribution of notesnook. The list below are unofficial links, which the user often has to download and install:

* [apklis store](https://www.apklis.cu):  It is the Android Application Center, which is called APKlis and is available at https://www.apklis.cu. It consists of the software and services that allow the publication and distribution of Applications. APKlis is a solution from the University of Informatics Sciences.
* [izzysoft store](https://apt.izzysoft.de/): This is the F-Droid Repository by IzzyOnDroid
* androidapkfree
* apkcombo
* majorgeeks
* macupdate
* oldversion
* apkmirror
* apkpure
* androidpicks
* originalapk
* uptodown
* 9apps
* apkflax
* oldapkversion
* appchive

### Additional context

None

**Comment by thecodrr** [comment]
Not sure what you mean. Can you please elaborate further? We cannot possibly manage or handle all these different stores. If a user is depending on these stores to download unofficial APKs for any app, it is not the fault of the developer. They should either download from the developer website (we make it available on our Downloads page) or use Google Play Store.
