### ISSUE TITLE
Plank icon

### ISSUE THREAD

**Issue by shawn1thompson** [streetwriters/notesnook#2979]
### What happened?

I've installed via Flatpak and the icon shows up in the system (Linux Mint 21.2), but not on Plank. Other Flatpak installed apps show up fine. Also, I don't know where Flatpak desktop files are to try and fix on my own.

### Steps to reproduce the problem

Install via Flatpak. Open app. Observe gear icon on the dock.

### Version

2.5.8-9e3646e-desktop

### Platform/OS

Linux

**Comment by shawn1thompson** [comment]
I found out where the desktop files are for Flatpak applications and I don't see any difference between yours and other applications. I tried copying it to .local/share/applications, but also to no avail.

**Comment by thecodrr** [comment]
Try restarting/relogging in. Sometimes the icons don't update until a logout/login occurs.

**Comment by shawn1thompson** [comment]
Definitely tried that several times.

**Comment by thecodrr** [comment]
@shawn1thompson were you able to fix this somehow?

**Comment by shawn1thompson** [comment]
I didn't fix it, but have since reinstalled Ubuntu and it's now working properly.
