### ISSUE TITLE
Forms in notesnook 

### ISSUE THREAD

**Issue by degaur** [streetwriters/notesnook#2980]
### What problem are you facing?

It would be nice to create form-type templates

### What's the solution you'd like to see in Notesnook?

As we can see, we have an "form" in  notesnook:
![image](https://github.com/streetwriters/notesnook/assets/119423239/d6cf6a6f-cb68-4a0b-85ac-1bb34087c14a)

**Comment by thecodrr** [comment]
This is way too out of scope for Notesnook. What would even be the usefulness of something like this? Its a note taking app, not a website/form builder.
