### ISSUE TITLE
login with public/private key?

### ISSUE THREAD

**Issue by ghost** [streetwriters/notesnook#2985]
### What problem are you facing?

One of the biggest problems for the user is controlling the login to notesnook when he forgets the password or does not have access to the email to change the password.

### What's the solution you'd like to see in Notesnook?

Instead of the user entering the 'email', or 'username' along with the 'password' in notesnook, he logs in with a public and private key as nostr(protocol).

### What alternatives have you considered?

- WebAuthn is a browser-based API that allows for web applications to simplify and secure user authentication by using registered devices (phones, laptops, etc) as factors. It uses public key cryptography to protect users from advanced phishing attacks.
- nostr: Nostr is a simple, open protocol that enables global, decentralized, and censorship-resistant social media. Each Nostr account is based on a public/private key pair. A simple way to think about this is that your public key is your username and your private key is your password, with one major caveat. Unlike a password, your private key cannot be reset if lost.

### Additional context

**img-1**
![image](https://github.com/streetwriters/notesnook/assets/119423239/0d3ad96c-7af1-4263-a3eb-014e92c5f19c)

**description:** Here we can communicate the login through a public key, email, mobile number. These options can be more or less secure depending on how the user uses them. By "default", notesnook generates a public and private key for login. So, no email, password or mobile number would be required for login in nostesnook.

**Comment by catsuns** [comment]
I think this is a good idea, I would like to help implement it.

**Comment by thecodrr** [comment]
> One of the biggest problems for the user is controlling the login to notesnook when he forgets the password or does not have access to the email to change the password.

The above proposed solution does not fix this problem. In your own words, "Unlike a password, your private key cannot be reset if lost."

> By "default", notesnook generates a public and private key for login. So, no email, password or mobile number would be required for login in nostesnook.

I think email is a good middleground when it comes to login. Give this a read: https://blog.notesnook.com/why-notesnook-requires-an-email-address/

> Instead of the user entering the 'email', or 'username' along with the 'password' in notesnook, he logs in with a public and private key as nostr(protocol).

All that sounds good but it doesn't actually change anything or make anything more secure/private. The good thing about traditional forms of login is that people are used to them and know their way around them. If a user sees, "Enter your public key" instead of "Enter your email"; they wouldn't know what to do. Are the pros worth the cons?

**Comment by solarsbeans** [comment]
The only good thing is that you don't need to do email. Generally, email is used a lot in marketing. We receive ads that we don't need in the inbox.

But while this is good, this is bad. That is, it would increase spam considerably. Perhaps this feature could work in the sense: 'Notesnook business, Notesnook enterprise, Notesnook  professional', in the sense of companies and employees.

**Comment by thecodrr** [comment]
> This feature would avoid receiving marketing emails from Notesnook, or add anonymity to login, because in theory there would be no user's email identification in the registration.

That's easy. Just turn off marketing emails. You want anonymity? Use an aliasing service.

**Comment by thecodrr** [comment]
Closing as this does not make sense for Notesnook.
