### ISSUE TITLE
Java Script error

### ISSUE THREAD

**Issue by shawn1thompson** [streetwriters/notesnook#2987]
### What happened?

Notesnook was working fine, but now when I open I receive multiple Java Script errors. They're the same error over and over. Click OK until the app ultimately closes itself.

![Screenshot from 2023-07-21 06-52-50](https://github.com/streetwriters/notesnook/assets/32218754/86367c0c-72ea-412a-8950-030584aaa559)

### Steps to reproduce the problem

Launch Notesnook

### Version

2.5.8

### Platform/OS

Linux

**Comment by thecodrr** [comment]
This should be fixed in v2.6.7.
