### ISSUE TITLE
Japnese/Korean word gets deleted

### ISSUE THREAD

**Issue by alihamuh** [streetwriters/notesnook#2988]
### What happened?

Hi,

I love Notesnook so far but with Windows desktop application there is a bug with Japanese and Korean language when I 'Alt-tap' to move to other application it deletes last word that I wrote in.

It's not a big deal but kind of annoying and scary.

Could you guys include this bug fix to future update?

Thank you in advance.

### Steps to reproduce the problem

when I 'Alt-tap' to move to other application it deletes last word that I wrote in.

### Version

2.4.0

### Platform/OS

Windows

**Comment by thecodrr** [comment]
Cannot reproduce this. Tried on Windows.
