### ISSUE TITLE
Open sourcing

### ISSUE THREAD

**Issue by upward4** [streetwriters/notesnook#3]
Is there any plan to open source the project?

**Comment by thecodrr** [comment]
Please refer to [this faq.](https://github.com/streetwriters/notesnook#if-you-are-so-privacy-focused-why-did-you-not-make-notesnook-open-source)

**Comment by Myzel394** [comment]
@thecodrr It would be cool if you could still open source the project. Even if you wouldn't write good docs and don't accept pull requests open, it would still be beneficial as everyone could audit the program. The community can also write good docs on their own and make a pr ;)

**Comment by ammarahm-ed** [comment]
@Myzel394 We have plans to go open source in the upcoming months. You can check the roadmap at https://notesnook.com/roadmap

**Comment by thecodrr** [comment]
I have started a discussion #747. Everyone is welcome to join in.
