### ISSUE TITLE
Offline mode/fallback licenses

### ISSUE THREAD

**Issue by pshirshov** [streetwriters/notesnook#30]
While the app seems to be reasonably priced (subject of better UX and bugfixes), personal notes are a very sensitive subject.

Noone wants to have personal notes collection as a hostage and in case licensing/sync servers suddenly disappear noone would be happy.

I would suggest to let users who were paying but cancelled their subscription use the app in offline mode with all the featues. This is something Jetbrains does - in case you stop paying their subscription you still may continue using all the software you had access too. Without cloud sync and updates of course.

**Comment by thecodrr** [comment]
> Noone wants to have personal notes collection as a hostage and in case licensing/sync servers suddenly disappear noone would be happy.

This is not exactly an issue if you have backups of your data on your device. Or on the cloud.

But I am considering this.
