### ISSUE TITLE
App hangs while synching

### ISSUE THREAD

**Issue by alihamuh** [streetwriters/notesnook#3000]
### What happened?

I was editing a large note 4000-6000 words when suddenly sync failed and then the app hanged with not responding message. I had to close the tab and open a new instance of the app to resume my note editing. 

### Steps to reproduce the problem

Edit a large note for sometime. 

### Version

2.5.8

### Platform/OS

Chrome/Chromium

### Relevant log output

```shell
Sync failed
Failed to read large indexed DB value
```

**Comment by thecodrr** [comment]
This has been fixed.
