### ISSUE TITLE
retain formatting (spacing) from evernote

### ISSUE THREAD

**Issue by neftd** [streetwriters/notesnook#3003]
### What problem are you facing?

Hi. I just downloaded Notesnook, was feeling really enthusiastic! Exactly what I want from Evernote which is not delivering except.
I have a problem. When I copy text or import a note from Evernote it does not retain the formatting - specifically - the spacing between lines.
This is a huge problem for me. 

I tried with double spacing turned off as well. The lines are all copied over equidistant anyway.

I feel like every time I find an Evernote alternative and im gearing up to buy a subscription some simple but incredibly important feature turns out to be missing. Is it possible for this to be well... fixed?/ (re)built? Im hoping it's simple...

### What's the solution you'd like to see in Notesnook?

Retain linespacing from evernote  when copy-pasting and importing notes

### What alternatives have you considered?

Don't know if there is an alternative to simply making it so...

### Additional context

This is a real dealbreaker... really hope this can be changed.

**Comment by thecodrr** [comment]
Hi, thank you for trying out Notesnook.

Can you please give an example screenshot of the issue? It'd also help if you can give an ENEX file for the note you are having problems with.
