### ISSUE TITLE
My Subscription Isn't Working

### ISSUE THREAD

**Issue by altano** [streetwriters/notesnook#302]
**Describe the bug**
I hadn't opened Notesnook for a while. I opened the app and got a prompt that my free trial expired and I should upgrade. Interestingly though, I have a subscription. I was last charged on 2022/1/5 (just 15 days ago)

**To Reproduce**
1. Open desktop app
2. Upgrade to 1.7.6
2. Login again
![image](https://user-images.githubusercontent.com/1009/150479508-70d7614c-70c1-490f-92b3-4bc1a69f7a1b.png)
3. Go to website
4. Login on website
5. Click "Settings" to see subscription status
![image](https://user-images.githubusercontent.com/1009/150479588-1e549a5e-1649-42be-9e15-ba1717ef7a97.png)

**Expected behavior**
I would expect my subscription to be reflected in the app

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version: 1.7.6 
(and also in the browser, Notesnook version 1.5.4-3939941-web on Firefox 96.0.1)

**Comment by thecodrr** [comment]
Should be fixed for your account.

**Comment by altano** [comment]
Happened again. Today is 2022/02/23 and Notesnook thinks my subscription is expired:
![image](https://user-images.githubusercontent.com/1009/155417054-c1c01a4b-476f-4c12-8294-d4a55eabc566.png)

Subscription was last charged on 2022/02/05

**Comment by altano** [comment]
(And I don't see the option to re-open the issue, I can only comment)

**Comment by thecodrr** [comment]
This is extremely weird. Let me investigate why it's repeatedly rolling back.

**Comment by thecodrr** [comment]
Alright so upon investigating, it seems the bug created a second subscription status as basic. Can you tell me exactly what you did?

**Comment by altano** [comment]
I'm inactive for long stretches of time... perhaps that's causing the issue?

I THINK today this is what happened:
* I saw the Discord notification for the discount and thought "I wonder if I can take advantage of this" and clicked the link
* Somewhere in that process it seemed like it was only letting me sign up, not apply it to my existing account, so I just bailed on it (closed the browser)
* I decided to see if the newest version fixed my issue in #303 so I opened Notesnook in the browser. I noticed that my subscription wasn't active in Settings
* I opened the desktop app, was still blocked by the "Creating Backup" so I couldn't click the update
* I went to the website and manually downloaded the new desktop version and installed it
* I launched the desktop version. The issue in #303 seemed fixed but my backups were failing with an error about needing a subscription. I went to Settings and saw the same thing as the web app: no subscription.
* I came here and commented on this issue.

**Comment by altano** [comment]
FWIW my usage pattern is a little unusual in that I'm not opening Notesnook for long stretches of time. I've been waiting on bug fixes and quirks to get ironed out, coming back and seeing if it seems ready or not for me to fully switch over, and then taking another break. When I switch over fully I'll use it every day but I'm not there yet.

**Comment by thecodrr** [comment]
I think there was a race condition between your subscription getting marked as expired and your subscription renewing. I have fixed the main issue about duplicate subscription statuses so your subscription should be active again. I'll look into how to avoid the race condition in the future.

**Comment by altano** [comment]
Subscription shows up in Notesnook. Syncing and backup both appear to be working. Thanks!
