### ISSUE TITLE
Checked item in task list becomes unchecked when inserting a new item above it

### ISSUE THREAD

**Issue by 4fosaefp** [streetwriters/notesnook#3023]
### What happened?

When I insert a new item from a checked item in the task list by hitting enter at the beginning of the line:
![image](https://github.com/streetwriters/notesnook/assets/115563922/4b95d1d9-9238-4930-a9fd-7e5de8ddc9d9)

The inserted item becomes checked while the original item is unchecked:
![image](https://github.com/streetwriters/notesnook/assets/115563922/4c533d84-62bc-46de-9a88-5c461a2a9f53)

Same behavior is observed when the checked item has descendants.

### Steps to reproduce the problem

1. Create a task list with a checked item
2. Move the cursor to the beginning of the checked item
3. Hit enter to insert a new item above it
4. Observe the issue described

### Version

2.5.8-922fce7-web

### Platform/OS

Windows, Firefox

**Comment by thecodrr** [comment]
I am not sure whether this is really an issue. When you press enter, the editor moves everything after the cursor 1 line below. You can have the cursor anywhere inside the task item and it'll behave the same.

In other words, there is no way to create a new task item above another task item by pressing Enter. When you press Enter, the new item is always created below the line where you pressed enter. That is why you see that it is not checked by default.

This is working exactly like it should.

**Comment by 4fosaefp** [comment]
Hi @thecodrr, I see the logic now.

In this case, the bug only happens when the checked item has child items. If I apply the same operation to it:
![image](https://github.com/streetwriters/notesnook/assets/115563922/20f3dbc0-0475-48fa-a6b3-a9a3a91adcf4)
It becomes
![image](https://github.com/streetwriters/notesnook/assets/115563922/284bd8bd-6dee-4df6-a126-5305e36cc4b2)

The parent item is no longer checked despite the children still checked.
This might be related to #2910.

**Comment by 4fosaefp** [comment]
> Hi @thecodrr, I see the logic now.
> 
> In this case, the bug only happens when the checked item has child items. If I apply the same operation to it: ![image](https://private-user-images.githubusercontent.com/115563922/256846829-20f3dbc0-0475-48fa-a6b3-a9a3a91adcf4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUxMTkyMTUsIm5iZiI6MTcwNTExODkxNSwicGF0aCI6Ii8xMTU1NjM5MjIvMjU2ODQ2ODI5LTIwZjNkYmMwLTA0NzUtNDhmYS1hNmIzLWE5YTNhOTFhZGNmNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExM1QwNDA4MzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mOTJjNGJmYmIwZjkyMTFlNGZhNTdmNzdiNmNkYWM0OTliNzk3YjA0ZGI5YzkzMTA2NzUyMmFjMjBmMTQ0MTFkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.qfOzqB1XS8oBNAxPJWoU52KliTH-WtpfV3hikWozk0k) It becomes ![image](https://private-user-images.githubusercontent.com/115563922/256846743-284bd8bd-6dee-4df6-a126-5305e36cc4b2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUxMTkyMTUsIm5iZiI6MTcwNTExODkxNSwicGF0aCI6Ii8xMTU1NjM5MjIvMjU2ODQ2NzQzLTI4NGJkOGJkLTZkZWUtNGRmNi1hMTI2LTUzMDVlMzZjYzRiMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExM1QwNDA4MzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yM2ExMDkwMTY2Njg4NWVjYjdiYTllNzJhYWQwN2E2MWUyZmU1ODM2NjhiZmJmYzM4Yzk1ZTc5N2UwYjIwZTQ1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9._4d0VGG7PQwJB8AUIBk_7UICGfQ9lM3-4NXwLCffJH8)
> 
> The parent item is no longer checked despite the children still checked. This might be related to #2910.

The bug seem to have regressed. I am able to reproduce it once again.
