### ISSUE TITLE
Stuck at "Creating Backup"

### ISSUE THREAD

**Issue by altano** [streetwriters/notesnook#303]
**Describe the bug**
When I open Notesnook I am stuck at a "Creating backup" modal

**To Reproduce**
1. Open Notesnook
2. Wait ~5 seconds

**Expected behavior**
To *not* be stuck at this modal

**Screenshots**
![image](https://user-images.githubusercontent.com/1009/150630971-98e7705a-666d-4020-8e51-f39cfbe79ec6.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version 1.7.6

**Additional context**
I hadn't opened Notesnook in a while. I launched it again to checkout how things were working and had to relogin. Upon logging in I had three problems:
1. My subscription wasn't being detected
2. The "Error while syncing. Could not commit changes." you see in the screenshot above
3. This "Creating backup" modal that is blocking me from using the app (this issue)

**Comment by altano** [comment]
When you fixed https://github.com/streetwriters/notesnook/issues/302 I stopped having this issue. Sync is still failing though (last successful sync was 2 months ago)

![image](https://user-images.githubusercontent.com/1009/150905207-f649ee68-d51b-45d7-a573-1cd3f7f51624.png)

The "Having problems with syncing? Try force sync to resolve issues with syncing" button doesn't seem to work either. Let me know if you want me to open a separate, new issue for this.

**Comment by thecodrr** [comment]
@altano have you tried logging out and logging back in? I am taking a look into what could be the issue here.

**Comment by altano** [comment]
I opened notesnook today and got prompted to update the app. That seemed to complete successful. After, I'm stuck at the same dialog.

The "Creating backup" is modal so I can't log out through the app UI. I tried uninstalling and then reinstalling, but it comes up logged-in still.

How can I log out from outside the app without losing data?

**Comment by thecodrr** [comment]
The fix for this is coming in the next release.
