### ISSUE TITLE
Can't copy code blocks in read-only mode.

### ISSUE THREAD

**Issue by mikeve97** [streetwriters/notesnook#3061]
### What happened?

I tried to copy my code block using the copy button. However this button gets disabled when you enter read-only mode. 

### Steps to reproduce the problem

1. Make a new code block
2. Make note read-only
3. Try to use the copy block

Button should be disabled.

### Version

Latest

### Platform/OS

Windows, Android, Chrome/Chromium

**Comment by thecodrr** [comment]
This has been fixed. Please wait for the next release.
