### ISSUE TITLE
notes list show created time instead of modified time

### ISSUE THREAD

**Issue by zxzx1290** [streetwriters/notesnook#3067]
### What happened?

notes list show created time instead of modified time on the web client

![image](https://i.imgur.com/l0vl35N.jpg)

### Steps to reproduce the problem

just open the web client

### Version

2.5.8-922fce7-web

### Platform/OS

Chrome/Chromium, Firefox

**Comment by thecodrr** [comment]
When you set the sorting to Date edited, it'll automatically show the Date Edited time instead of the Date Created time.
