### ISSUE TITLE
Web Clipper - Clip Selection

### ISSUE THREAD

**Issue by BuzzKnightbeer** [streetwriters/notesnook#3088]
### What problem are you facing?

How can I clip just the selected elements? I'm sure there is a way and I just can't find it. The node selector usually doesn't cover everything I'd like to select.

### What's the solution you'd like to see in Notesnook?

Additional clipping are called selection.

**Comment by thecodrr** [comment]
Please refer to https://help.notesnook.com/web-clipper/clipping-your-first-web-page-with-web-clipper#selected-nodes
