### ISSUE TITLE
Support markdown as first class format

### ISSUE THREAD

**Issue by stgolem** [streetwriters/notesnook#31]
**Is your feature request related to a problem? Please describe.**
Many notes already written in markdown, no easy way to copy and paste them.

**Describe the solution you'd like**
I'd like to have markdown as first class formatting in notes. So if i paste text with markdown it visually formats as it should. 

**Describe alternatives you've considered**
Separate button for pasting markdown maybe.

**Comment by thecodrr** [comment]
Hey, supporting full markdown is not our goal. We provide our Importer that converts all Markdown notes into a format Notesnook understand. I suggest you use that to import all your markdown notes.

**Comment by rrpolanco** [comment]
I've been using the free trial of Notesnook and have enjoyed it so far, especially its privacy features. However, not fully supporting markdown as a first class citizen in the editor is a deal breaker for me. I would like not to rely on an import/export feature for Markdown and not be locked-in to a proprietary data format. I hope this feature is revisited in the near future.
