### ISSUE TITLE
App suddenly vanished after installing new version

### ISSUE THREAD

**Issue by gracie95** [streetwriters/notesnook#3101]
**I have a funny story with this app.**

I have this problem while upgrading to latest version (v2.6.0). Thought it was just released. I kept using app while downloading is on progress. After completion, I click to install. The installation went normally. After installation completed, they (Directory and Shortcut) suddenly disappear from PC.
If you tried to find it through start menu, you'll never find it. You'll find backup files only.

So, I decide to download from official website, install then login as well. 

Well. Idk why, but I have this for two times. It happens randomly.

Sorry for my bad grammar :(

OS: Windows 11
Version: 2.6.0

**Comment by thecodrr** [comment]
This looks like an issue with the anti-virus (Windows Defender) flagging and removing Notesnook for no reason whatsoever. Unfortunately, there's not much we can do about this. There is no malware in Notesnook installation. The only reason I can see for this behaviour is lack of a proper signing certificate.

**Comment by thecodrr** [comment]
This issue should be fixed now that we are signing all Notesnook binaries.
