### ISSUE TITLE
Multiple Submenu Panels Overlapped each Other

### ISSUE THREAD

**Issue by cardin** [streetwriters/notesnook#3123]
### What happened?

![IMG_4962](https://github.com/streetwriters/notesnook/assets/553816/8fcb7819-39be-4e02-88a9-483adcf3819a)

When I click on a few submenus, the submenus overlap and occlude each other.

This should be a bug - not more than 1 submenu should be open at one time, otherwise occlusion will happen.

### Steps to reproduce the problem

1. Click on the Highlight submenu
2. Click on the Image submenu
3. Click on the Attachment submenu

### Version

2.6.1

### Platform/OS

iOS

**Comment by thecodrr** [comment]
This has been fixed.
