### ISSUE TITLE
Make Monograph a full blogging platform

### ISSUE THREAD

**Issue by shawn1thompson** [streetwriters/notesnook#3137]
### What problem are you facing?

I need a blogging platform that knows how to deal with LTR and RTL text that is intermixed and you guys are the only ones I've found that are mostly getting it right.

### What's the solution you'd like to see in Notesnook?

One of two:
1. Make Monograph a full blogging platform as mentioned in issue #167 with custom domain support -or-
2. Create a blogging platform that is intuitively simple like write.as or Notesnook notes, is able to manage LRT and RTL text well, and has custom domain support.

### What alternatives have you considered?

write.as, Notepin, Simplenote's Listing, WordPress, Ghost, Medium

### Additional context

I currently use write.as which uses WriteFreely on the backend I believe and I like it except their handling of LTR and RTL text. [See](https://discuss.write.as/t/cumbersome-right-to-left/9768)
[And](https://blog.contemplari.life/)

**Comment by thecodrr** [comment]
This is out of scope for Notesnook. However, it can exist as a separate product.
