### ISSUE TITLE
System Tray bug: Zoho mail

### ISSUE THREAD

**Issue by alihamuh** [streetwriters/notesnook#3144]
### What happened?

There is a problem I am facing with the Windows version of Notesnook. When Notesnook is running minimized on system tray and I open it and after that I close it, it gets minimized normally as it should. But when I do the same thing second time it gets closed completely instead of minimizing itself in the system tray. Then I open it completely and after that again first time closing it minimizes it but second time it gets closed again.

### Steps to reproduce the problem

l

### Version

2.5.8

### Platform/OS

Windows

**Comment by thecodrr** [comment]
This has been fixed.
