### ISSUE TITLE
NN stoped working on windows 7

### ISSUE THREAD

**Issue by luxcalor** [streetwriters/notesnook#3149]
### What happened?

NN stopped working on win7 alltogether. Including web clipper. Used to be fine until the latest update(s). 

### Steps to reproduce the problem

Try to start NN on win7

### Version

2.6.0 

### Platform/OS

Windows

**Comment by thecodrr** [comment]
Chrome has stopped stopped supporting Windows 7 which made Electron drop the support as well. Unfortunately, there's nothing we can do here. Going back to an older version will log everyone out since downgrading is not supported. So not an option.
