### ISSUE TITLE
Creation dates got messed up [Android]

### ISSUE THREAD

**Issue by luxcalor** [streetwriters/notesnook#3151]
### What happened?

Some notes I have created a week ago have a "2 years ago" stamp, others that were imported from Evernote and had been created 5 or 6 years ago are marked as created 2 days ago. There are huge number of notes like that. 

I usually sort by date created and the whole notes system got messed up atm. 

### Steps to reproduce the problem

Open the Android app

### Version

2.6.1

### Platform/OS

Android

**Comment by thecodrr** [comment]
Can you explain what operations you performed on these notes? Are you use its the date created you are seeing and not date edited? The only time we update the date created is when you create the note for the first time.

**Comment by luxcalor** [comment]
![Screenshot_2023-08-15-13-18-56-080_com streetwriters notesnook-edit](https://github.com/streetwriters/notesnook/assets/76074147/c97f4421-67ea-4f22-8dfb-f43f48c1b20d)

Did perform no operations whatsoever, have been on holiday. Just updated the app and opened it this morning. 

Most of the notes on this screenshot where created in the last 6 months. One of them 2 years ago another maybe one year ago. But it says 3 years ago for all of them an if I unpin them they go all the way down the list of notes (I havecsort by creation rate enabled, newest first). There are seemingly random creation dates (3 month, 2 weeks, 5days) assigned to notes I did not even touch for years (apart from importing them to NN).

**Comment by luxcalor** [comment]
![Screenshot_2023-08-15-14-01-35-648_com streetwriters notesnook-edit](https://github.com/streetwriters/notesnook/assets/76074147/a099dafa-22f0-46b0-bbf4-19b0d04a24e5)

Did relogin and here is the change. Now NN says 2 years for the first note (real creation date is in the title), and different dates for other notes, and acts accordingly during sorting.

**Comment by thecodrr** [comment]
@luxcalor can you check the actual creation date from properties?

**Comment by luxcalor** [comment]
> @luxcalor can you check the actual creation date from properties?

There is a correct date in properties.
