### ISSUE TITLE
Linux: context menu in dock doesn't working (new window, new node etc)

### ISSUE THREAD

**Issue by dmytrodubinin** [streetwriters/notesnook#3154]
### What happened?

On Fedora Linux with Gnome 44 in dock when right click I got context menu such as new window, new note etc. But when I try to use it nothing happens.

### Steps to reproduce the problem

Here is the demo:

https://github.com/streetwriters/notesnook/assets/8066458/616c94ad-34e7-4126-8e24-2c89d89a22e6

### Version

2.6.1-e509c82-desktop - Flatpak, Fedora Linux with Gnome 44.3, Wayland session

### Platform/OS

Linux

**Comment by thecodrr** [comment]
This has been fixed.
