### ISSUE TITLE
Note title exception when using $headline$ option.

### ISSUE THREAD

**Issue by matt873** [streetwriters/notesnook#3176]
### What problem are you facing?

Notes not using specified title when using %headline$ option.

### What's the solution you'd like to see in Notesnook?

The note should use custom note title instead of first line of the note as headline, if title is specified, when $headline$ is selected in editor settings. I mean an exception for this option when Note title is specified at writing. Currently, the app still uses the first line of note as headline even when Note title is specified at writing.

**Comment by thecodrr** [comment]
That's not how it works. The \$headline\$ only applies when the title is empty or the note is new.
