### ISSUE TITLE
Pressing enter does not create a new line in Tables

### ISSUE THREAD

**Issue by abhishekarora12** [streetwriters/notesnook#318]
**Request**
Sometimes, I want to put multiple lines in a table cell, is this possible ?

**Example**
<img width="229" alt="Screenshot 2022-01-28 at 4 12 16 PM" src="https://user-images.githubusercontent.com/12087783/151533134-fce896cd-f796-475e-b0c7-808240301884.png">

Currently, I have to do this by using space and managing the margins for each column, is it possible to do this the right way by pressing enter ?

**Comment by thecodrr** [comment]
> Currently, I have to do this by using space and managing the margins for each column, is it possible to do this the right way by pressing enter ?

Looks like a bug.

**Comment by thecodrr** [comment]
The fix for this will be released in the next version. For now, you can use `Shift + Enter` to create new lines.

**Comment by abhishekarora12** [comment]
It works! Good to know.
