### ISSUE TITLE
Custom lock pin within the app, not relying on fingerprint or face

### ISSUE THREAD

**Issue by abhishekarora12** [streetwriters/notesnook#319]
**Request**
Notesnook app should have it's own pin/pattern implementation like most privacy focused apps have, instead of just using the biometrics in phone since sometimes close people who have their fingerprints registered in the phone should not be able to just read all the notes!

**Comment by thecodrr** [comment]
@ammarahm-ed what do you think?

**Comment by newhollandaus** [comment]
I'm on a older 2015 Macbook without touch ID. No general app lock for notesnook that I can see. Terrible if so! I'll be removing on this device until passcode is available.

Just able to vault individual items from what I can see.

I'm here for MacOS because issue #1256 was considered duplicate

**Comment by LatifAlj** [comment]
I never use biometrics, so it's disappointing that this is the only way to get encryption at rest on IOS.

**Comment by abdullatif-k** [comment]
this is the only thing preventing from going all in on notesnook
