### ISSUE TITLE
Content doesn't refresh in an open note, if new data is synced 

### ISSUE THREAD

**Issue by abhishekarora12** [streetwriters/notesnook#320]
**Describe the bug**
If a note is opened, content doesn't refresh even if new data is synced, this just creates a merge conflict.
At least should get a notification that this note is updated so open it again, otherwise there will be a conflict.

**To Reproduce**
1. Open a note in desktop app
2. Open the same note in mobile app
3. Modify content on mobile app
4. The desktop content doesn't change automatically and if you make any change to it now it will just generate a merge conflict

**Expected behavior**
The note content gets updated if it gets changed on another device, or get a notification at the top which user can click to refresh the note.

**Desktop (please complete the following information):**
 - OS: Mac OS X 10.15.7
 - Version 1.7.6

**Comment by thecodrr** [comment]
The plan is to show a notice at the top telling the user that a newer version of the note is available.

**Comment by thecodrr** [comment]
This is done.
