### ISSUE TITLE
Android app- UX issue with small font size

### ISSUE THREAD

**Issue by WeberAlex** [streetwriters/notesnook#3219]
### What happened?

I can't read the file names and the menus in the Notesnook Android application. It defaults to a very small font size that does not follow my OS font size setting.

I have to mention that I have a fairly bad eyesight.

Some screenshots of Notesnook:

<img src="https://github.com/streetwriters/notesnook/assets/28292190/cb14f627-8e21-46d0-9de3-7f0f2d6ee404" width="400"><br /><br />

<img src= "https://github.com/streetwriters/notesnook/assets/28292190/cb08737e-b22a-47db-8d86-7b98a0255304" width="400"><br /><br />

<img src= "https://github.com/streetwriters/notesnook/assets/28292190/2e8b244b-9b25-45fc-ba4b-571e00beb005" width="400"><br /><br />

By comparison some screenshots of Obsidian

<img src="https://github.com/streetwriters/notesnook/assets/28292190/e30b034c-1f66-4d2b-975d-7bbc5b0978bb" width="400"><br /><br />

<img src="https://github.com/streetwriters/notesnook/assets/28292190/f13c0549-7212-49c6-b3dd-4070503c8c6d" width="400"><br /><br />

The application should be designed to accommodate all type of eyesights, as per the OS font size setting (more or less...).

### Steps to reproduce the problem

My Android (ver. 10) font size settings are as follow:

* Font size: Largest
* Display size: Lage

These are the maximum default font sizes values. I would expect Notesnook Android to honors my settings.

### Version

2.6.1

### Platform/OS

Android

**Comment by Coding-Algorithm** [comment]
@thecodrr , I am looking to take this up. Can you assign it to me?

**Comment by Coding-Algorithm** [comment]
@ammarahm-ed , Oooh, I could see you are already on this, how's it going?
