### ISSUE TITLE
Reminders Don't Send a Notification on IOS

### ISSUE THREAD

**Issue by me6262** [streetwriters/notesnook#3243]
### What happened?

I set a reminder that would go off in two minutes just to test the functionality. It sent the notification on my desktop, but not to my iPhone. I even tried to set a reminder from my phone and close the app on my desktop, but it would not work. If this is an unimplemented feature or something, I have no idea. I did see that the reminders were still in beta, but this is the feature that honestly makes or breaks this app for me. As a side note, I noticed that in the settings app, there was no option to enable or disable notifications, as if the app had never asked or set up permissions for them at all.

### Steps to reproduce the problem

set a reminder, when it goes off, no notifications pop up on iOS even if notifications are enabled in the app.

### Version

v2.6.1

### Platform/OS

iOS

**Comment by ammarahm-ed** [comment]
@me6262 It's possible that the permission to display notifications have been denied accidentally. Go to Settings > Notifications > Notesnook and enable notifications if they are disabled.

Another thing to try is uninstall and reinstall the app, then try setting a reminder. When you set the reminder first time, it will ask for permission to enable notifications. Select "Allow".
