### ISSUE TITLE
Can we have the option to download the apks right here, from GitHub?

### ISSUE THREAD

**Issue by lyybra** [streetwriters/notesnook#325]
I do not have Google Play Store, so downloading new versions of the app sometimes is a struggle. Is there any way to download the new versions of the app directly from GitHub? Thank you!

**Comment by ammarahm-ed** [comment]
@lyybra I will release the next version here so that apks are available to download directly.

**Comment by lyybra** [comment]
Thank you so much! Better, as trying to access 3rd sites which reputation is.. doubtful, for downloading the app.. Have always doubts to access apkpure or aurora store in order to have the app updated.. Thank you so much!

**Comment by thecodrr** [comment]
This is done. From `v1.8.0` all new Android releases will be published here as well as on Google Play Store.

**Comment by lyybra** [comment]
Thank you so much!!!
