### ISSUE TITLE
Widget`s window is trembling

### ISSUE THREAD

**Issue by lyybra** [streetwriters/notesnook#326]
When I open the widget, this happens:

https://mega.nz/file/MJtBAIpA#4H3B_MnV9PfQuDitS_SntndBrNF0i_fyZY_VscV0YYk

**Comment by lyybra** [comment]
Thank you for the reply! Opening the widget externally does not cause any problems. It happens only when opening it directly.

**Comment by ammarahm-ed** [comment]
@lyybra i am working on a fix which should solve this issue properly so it does not flicker or jump.

**Comment by lyybra** [comment]
Thank you so much doing this app even greater!

**Comment by ammarahm-ed** [comment]
Fixed in v1.7.13

**Comment by lyybra** [comment]
Thank you!
