### ISSUE TITLE
Blank window when launching v2.6.2 on Linux (via AppImage)

### ISSUE THREAD

**Issue by TJonCooper** [streetwriters/notesnook#3278]
### What happened?

After installing the new version (v2.6.2) on Ubuntu 22.04.3 LTS, using notesnook_linux_x86_64.AppImage as downloaded from Github, NotesNook opens and briefly displays my content - but then reverts to a blank window and remains that way (see attached screenshot).

![Screenshot from 2023-09-07 20-15-34](https://github.com/streetwriters/notesnook/assets/15924377/87d5f3b3-d1d5-4ca4-bfe3-798012e7da0f)

### Steps to reproduce the problem

1. Open NotesNook 2.6.2 on Ubuntu 22.04.3 LTS using the AppImage
2. Wait ~10 seconds for a blank window to appear

### Version

v2.6.2

### Platform/OS

Linux

**Comment by TJonCooper** [comment]
No error when the bug occurs (when launching the AppImage from the terminal):

```
App ready. Opening window.
https protocol inteception "successful"
Intercepting request: https://app.notesnook.com/
Intercepting request: https://app.notesnook.com/assets/index-70bce852.js
Intercepting request: https://app.notesnook.com/assets/index-00536d7a4c5a.css
Intercepting request: https://app.notesnook.com/assets/nncrypto.worker-9e2f891e.js
Intercepting request: https://app.notesnook.com/assets/index-ce5c7da3b826.js
Intercepting request: https://app.notesnook.com/assets/total-notes-cc32e7ae6b8a.js
Intercepting request: https://app.notesnook.com/assets/string-1b6884f143c5.js
Intercepting request: https://app.notesnook.com/assets/random-4b33b3b0ddaf.js
Intercepting request: https://app.notesnook.com/assets/toast-dd554c8b33aa.js
Intercepting request: https://app.notesnook.com/assets/index-eabb570faab5.js
Intercepting request: https://app.notesnook.com/assets/browser-a0291a37f3e5.js
Intercepting request: https://app.notesnook.com/assets/toast-dea4ca770e0f.css
Intercepting request: https://app.notesnook.com/assets/compressor-5443352ddfc2.js
Intercepting request: https://app.notesnook.com/assets/network-check.worker-aed75908.js
Intercepting request: https://app.notesnook.com/assets/app-70d7b11802dd.js
Intercepting request: https://app.notesnook.com/assets/index-15ceb7cb526f.js
Intercepting request: https://app.notesnook.com/assets/index-8958265a83d4.js
Intercepting request: https://app.notesnook.com/assets/index-65ae70e2791f.js
Intercepting request: https://app.notesnook.com/assets/body-3e504c33d947.js
Intercepting request: https://app.notesnook.com/assets/index-0c07cdbefb90.css
Intercepting request: https://app.notesnook.com/assets/use-persistent-state-3bca2882997c.js
Intercepting request: https://app.notesnook.com/assets/index-6d7c135f2317.js
Intercepting request: https://app.notesnook.com/assets/app-effects-fee59a07d55f.js
Intercepting request: https://app.notesnook.com/assets/onboarding-dialog-b14712f0c30e.js
Intercepting request: https://app.notesnook.com/assets/nomad-5a999d53e7bf.js
Intercepting request: https://app.notesnook.com/assets/index-2717cc81e154.js
Intercepting request: https://app.notesnook.com/assets/index-a1bda4a231de.js
Intercepting request: https://app.notesnook.com/assets/index-be4bd5e6bb0a.js
Intercepting request: https://app.notesnook.com/assets/picker-fadd9e40295f.js
Intercepting request: https://app.notesnook.com/assets/index-d447bca0814a.css
Intercepting request: https://app.notesnook.com/assets/open-sans-v34-vietnamese_latin-ext_latin_hebrew_greek-ext_greek_cyrillic-ext_cyrillic-regular-52a27a6a1c18.woff2
Checking for update
Intercepting request: https://app.notesnook.com/assets/open-sans-v34-vietnamese_latin-ext_latin_hebrew_greek-ext_greek_cyrillic-ext_cyrillic-600-0240d31750de.woff2
Intercepting request: https://app.notesnook.com/assets/feature-dialog-d579cfc1655d.js
Update for version 2.6.2 is not available (latest version: 2.6.2, downgrade is disallowed).

```

**Comment by TJonCooper** [comment]
I can confirm that v2.6.1 still works as intended.

**Comment by thecodrr** [comment]
@TJonCooper can you press Ctrl + Shift + I when it goes blank and switch to the console tab to see why its crashing ? Do send a screenshot of it so I can investigate.

**Comment by TJonCooper** [comment]
@thecodrr Attached.
![Screenshot from 2023-09-07 20-37-39](https://github.com/streetwriters/notesnook/assets/15924377/cccfc823-403b-4742-bb37-0fc1030b2a8b)

**Comment by thecodrr** [comment]
@TJonCooper can you try reinstalling?

**Comment by TJonCooper** [comment]
@thecodrr I have - the error remains. It's also broken on 2 other independent Linux machines.

**Comment by thecodrr** [comment]
I tested the appimage on a Manjaro Linux machine and it worked but it could be that the error only occurs when certain conditions are met.

However, there are no errors or anything which is really weird. It looks as if the Chromium window context is getting destroyed/crashing because DevTools are also not connecting.

Can you press F5 when the DevTools error is shown? Make sure the DevTools are focused otherwise nothing will happen.

**Comment by TJonCooper** [comment]
@thecodrr F5 refreshes the application and my notes/content reappear - but only for ~10 seconds and then it crashes again and goes blank. 
![Screenshot from 2023-09-07 21-16-19](https://github.com/streetwriters/notesnook/assets/15924377/0ea6f5aa-9637-4fa3-b9ee-1f62eddbc779)

**Comment by TJonCooper** [comment]
It's happening on both X11 and Wayland for me, including on a fresh Ubuntu 22.04.3 LTS install. Seems like it could be Ubuntu-specific, although that's fairly odd.

**Comment by shenzhui007** [comment]
I have the same problem on v2.6.2. My OS is kali Linux which is a Debian-based OS. And v2.6.1 still works.

**Comment by thecodrr** [comment]
@shenzhui007 @TJonCooper are you on wayland by any chance? I tested on KDE Neon (Ubuntu/Debian based) and it is working.

Here's something you can try:

1. Backup the `~/.config/Notesnook` directory
2. Remove `~/.config/Notesnook` directory
3. Start Notesnook

If it works then there's a compatibility issue between v2.6.1 and v2.6.2.

**Comment by thecodrr** [comment]
Looks directly related to https://github.com/electron/electron/issues/39515

**Comment by TJonCooper** [comment]
@thecodrr Deleting the config folder has no effect - the window goes blank before I'm able to even login. Indeed, it looks like an electron issue.

**Comment by thecodrr** [comment]
@TJonCooper @shenzhui007 can you try this build?

https://wormhole.app/OR0ve#9yPhIxnQQUZbMWWtEHzJOQ

**Comment by TJonCooper** [comment]
@thecodrr I'm not able to download the file. Error:

These files are unavailable
The sender left before finishing the upload. You will not be able to download the files. Ask the sender to re-upload the files to Wormhole.

**Comment by thecodrr** [comment]
@TJonCooper  try this: https://anonymfile.com/oeAO/notesnook-linuxx8664.appimage

**Comment by TJonCooper** [comment]
@thecodrr It works and the window now stays rendered. However, there are a few rendering bugs within the application now (see attach. Upon click, the blue icons render properly.

![Screenshot from 2023-09-09 11-32-28](https://github.com/streetwriters/notesnook/assets/15924377/20a1c626-9104-40f7-96dc-aab3b356579f)
ed).

**Comment by thecodrr** [comment]
@TJonCooper that's an issue with the theme I think.

**Comment by shenzhui007** [comment]
@thecodrr Works fine and smoothly for me.
