### ISSUE TITLE
Backup failed error

### ISSUE THREAD

**Issue by candroid-man** [streetwriters/notesnook#328]
**Describe the bug**

Backup failed. Attempt to invoke virtual method 'byte[] java.lang.String.getBytes(java.nio.charset.Charset)' on a null object reference.

I get this error when simply opening the app. 

**Smartphone:**
 - Device: Samsung Galaxy S10+
 - OS: Android 12
 - Version: 1.7.11

**Comment by ammarahm-ed** [comment]
Fixed in v1.7.13.
