### ISSUE TITLE
Note Deletion not syncing?

### ISSUE THREAD

**Issue by edhans** [streetwriters/notesnook#3282]
### What happened?

I've noticed with the new 2.0 sync in 2.6.2, if I delete a note on one device, it doesn't get deleted on others. I've not noticed any problems with note creation or note changes. Just deletion. I have to delete it from every device in my tests.

It doesn't matter if the notes were created before or after my upgrade to 2.6.2. 

### Steps to reproduce the problem

Delete a note on device A. See if Device B shows it as deleted.

I am using Windows, iOS, and a browser session in Windows. Doesn't matter. Deleting from one doesn't delete from the others. All are on 2.6.2.

### Version

2.6.2

### Platform/OS

Windows

**Comment by Phil8655** [comment]
Same thing with the notebooks.

**Comment by thecodrr** [comment]
I am investigating this.

**Comment by Phil8655** [comment]
Thank you.
Philippe Mazur

**Comment by edhans** [comment]
Note that this is substantially better with 2.6.3, but I still have some notes not showing as deleted across devices. These may be notes deleted with 2.6.2 that aren't deleting under 2.6.3 either, but not 100% sure. Continuing to test.

**Comment by thecodrr** [comment]
@edhans can you confirm if this is still an issue?

**Comment by thecodrr** [comment]
Closing as fixed. Feel free to reopen/comment if this is still an issue.
