### ISSUE TITLE
iOS - Can’t remove red colour from side bar 

### ISSUE THREAD

**Issue by milesmcclane** [streetwriters/notesnook#3284]
### What happened?

Hello. 

I can’t remove the red colour circle from the side bar. 

I noticed in the closed issue this is marked as solved in Android. Alas, I’m seeing the same issue in iOS today. 

### Steps to reproduce the problem

Great red label for note, delete note or change colour label. The red remains regardless. 

### Version

2.6.2

### Platform/OS

iOS

**Comment by thecodrr** [comment]
This issue will be fixed in v3.
