### ISSUE TITLE
Apple Notes import

### ISSUE THREAD

**Issue by pshirshov** [streetwriters/notesnook#33]
Probably that's not easy but definitely possible. There is an app which does just that:

https://apps.apple.com/ie/app/exporter/id1099120373?mt=12

AFAIK it uses Automator workflows to control Notes.

**Comment by thecodrr** [comment]
From the app page:

> Notes can be exported to markdown or HTML format.

Problem solved. Just export them using the app and import them using our Importer tool.

**Comment by pshirshov** [comment]
Well, this tool produces incorrect markdown. And your import tool failed to import attachments exported by the tool.

**Comment by thecodrr** [comment]
Writing an Apple Notes exporter is out of scope. We aim to provide Importing from other apps but exporting is not our issue. If Apple Notes has any form of export format, I can take a look.

As for attachments, Notesnook only supports images. I'll take a look into Markdown importer and see what's the issue.
