### ISSUE TITLE
Notebooks are not deleted when selected on Android Pixel 6

### ISSUE THREAD

**Issue by Phil8655** [streetwriters/notesnook#3312]
### What happened?

I selected 86 empty Notebooks then clicked on Delete ( the trash bin) but nothing happened. The Notebooks are still there, all checked and not deleted.

### Steps to reproduce the problem

Highlight 86 Notebook, click on the box, then select Delete.

### Version

V 2.6.3

### Platform/OS

Android

**Comment by ammarahm-ed** [comment]
This has been fixed in v2.6.5

**Comment by Phil8655** [comment]
Yes, it works. Thank you!
