### ISSUE TITLE
New backups are very much broken 

### ISSUE THREAD

**Issue by mockinbirdy** [streetwriters/notesnook#3340]
### What happened?

Hi,

Is it even a good decision towards your customers to force an immediate backup when you open an app starting from today? I needed to quickly search my notes for some info, but no. I open the web version and boom, "we're creating a backup of your data, please wait". And it doesn't do anything for the next hour (?!). An hour, Carl? When in fact I have only 20 smallish notes. And I should go here to find out about your newest backup update. 

I refreshed the page after one hour of "loading". Same pop-up again, "we're creating a backup of your data, please wait". Forgive me for not wanting to wait another hour for nothing but what in the name of Christ is going on? I cannot access my notes! 

Thank God my phone app wasn't updated and it successfully loaded my notes previously saved from the web version the day before.

Maybe you should test it better before rolling it out? Now I am even worried about the safety of my notes on the servers and whether one day it will all break and erase people's data with the way backups work now.  

### Steps to reproduce the problem

Open the web version

### Version

the latest

### Platform/OS

Firefox

**Comment by thecodrr** [comment]
@mockinbirdy I am really sorry you had to go through that. We fixed and released a patch for the above issue just a few hours ago so if you are still having this issue, just do a hard refresh (Ctrl + F5 or Shift + F5) and everything should work.
