### ISSUE TITLE
Uncheck all the items in task list

### ISSUE THREAD

**Issue by Madhan-kumar-selvaraj** [streetwriters/notesnook#3342]
### What problem are you facing?

For the task list, can we introduce an option like unchecking all the items in the list? This will be helpful while doing certain tasks again and again. Like packing things for vacation, steps to follow on each projects

### What's the solution you'd like to see in Notesnook?

Checkout our discussion in discord: [https://discord.com/channels/796015620436787241/796063880677163109/1151870333381513297](https://discord.com/channels/796015620436787241/796063880677163109/1151870333381513297)

### What alternatives have you considered?

I think, this feature is available in Google keep

**Comment by Coding-Algorithm** [comment]
@thecodrr, how's this going to work out? Is there anyway I can come in?

**Comment by thecodrr** [comment]
@Coding-Algorithm sure! There will be a check box in the title bar area of the task list. Click this check box will check/uncheck all task items.

**Comment by Coding-Algorithm** [comment]
@thecodrr , Ok. Noted, you can assign it to me.

**Comment by Coding-Algorithm** [comment]
I need assistance with getting the changes made in the 'editor' module (whose start script was called with 'start:editor' in the base package.json) to show in the modile/android module (whose start script was called with 'start:metro' in base package.json). 

Presently, to see the changes I made in the 'editor' module reflect in the android module, I have to rebuild the debug apk which isn't efficient.

I want to ask if there is any way to reflect the changes as it happen

@thecodrr

**Comment by Madhan-kumar-selvaraj** [comment]
@thecodrr @Coding-Algorithm Can we get this feature in next update?

**Comment by Coding-Algorithm** [comment]
@Madhan-kumar-selvaraj , @thecodrr , apologise for the long silence. I know I should have communicate my unavailability ealier on.

I got engaged on some project and I haven't had enough time to dedicate to the development of this feature.

I will not be able to add this feature any time soon, someone else can take this up.

Thanks.
