### ISSUE TITLE
Desktop app won't update to the latest version [Windows]

### ISSUE THREAD

**Issue by luxcalor** [streetwriters/notesnook#3373]
### What happened?

There is a new version released according to the Github, but the app won't show this and checking for updates doesn't do anything. If I check in the settings, the progress circle spins for ages and nothing happens again. It was the same on 2.6.2, I did a manual update by downloading the file then. Now I am on the 2.6.4 and there is 2.6.5 out for a few days. 

Sync works fine, occasionally showing "sync failed" message in the status bar. 
I am under VPN always, Win10

### Steps to reproduce the problem

See above. 

### Version

2.6.4

### Platform/OS

Windows

**Comment by TJonCooper** [comment]
Same here, but on Linux (AppImage, Ubuntu 22.04.3).

**Comment by ckdanny** [comment]
Mac is the same, manually upgrade now.

**Comment by thecodrr** [comment]
I am taking a look at this issue. Will be fixed in the next release.
