### ISSUE TITLE
Support line wrapping and line numbers in code block

### ISSUE THREAD

**Issue by ckdanny** [streetwriters/notesnook#3377]
### What problem are you facing?

Supporting line wrapping and line numbers in code blocks would be incredibly helpful. Some code may be lengthy and occupy a single line, or there may be a long command. Additionally, displaying line numbers in code blocks can significantly assist in referencing a specific set of codes.

### What's the solution you'd like to see in Notesnook?

N/A. For line wrapping, manually break it into new line.

**Comment by thecodrr** [comment]
Duplicate of #1748
