### ISSUE TITLE
Cannot upgrade to latest version through FDroid

### ISSUE THREAD

**Issue by pachpict** [streetwriters/notesnook#3399]
### What happened?

I am using a version of Android without the Play store (Lineage OS). I downloaded and have been using Notesnook through the version installed on FDroid. I am on the latest version made available on FDroid, which is from 5 weeks ago and is v2.6.1. When it tries to sync, or I force a sync, it says, 
"Sync failed. Please update the app to the latest version."

I am assuming that the version uploaded to FDroid is not the latest.

I am also using the Linux desktop version, which updated correctly and is syncing.

I am an annual pro subscriber.

### Steps to reproduce the problem

 - Install latest version of Notesnook from FDroid
 - Try and sync from it.

### Version

2.6.1

### Platform/OS

Android/LineageOS

**Comment by pachpict** [comment]
I see the version on APKPure is v2.6.5, but as I cannot tell if that will then be easily upgraded in future through FDroid I am going to avoid that temporarily solution for now and hope the devs can upgrade FDroid, or allow older versions to continue to sync (if there are delays to getting approved on the FDroid repo).

**Comment by thecodrr** [comment]
I agree. F-Droid sucks big time. I wish they would do faster releases.
