### ISSUE TITLE
Show assigned topic instead of duplicating note text in pinned notifications

### ISSUE THREAD

**Issue by tylermercer** [streetwriters/notesnook#3403]
### What problem are you facing?

Pinned notes show the note's text twice:

![image](https://github.com/streetwriters/notesnook/assets/40773575/d990b966-3534-42ad-b834-6e261074cc57)

### What's the solution you'd like to see in Notesnook?

The smaller version of the note's text could be replaced with the note's assigned topic(s). This would provide more useful information instead of cluttering the notification appearance. (It looks especially cluttered with long notes.)

**Comment by thecodrr** [comment]
Good idea!

**Comment by abhinav700** [comment]
@thecodrr I would like to work on this issue. Would be a great chance to learn More about react native.

**Comment by ammarahm-ed** [comment]
For now, the subtitle is hidden.
