### ISSUE TITLE
Global ready-only mode when opening notes.

### ISSUE THREAD

**Issue by pred2k** [streetwriters/notesnook#3404]
### What problem are you facing?

When i open a note, i'm in edit mode instantly. This causes unwanted edits/deletes from time to time.

I have my training plan in notesnook. When i open the note in the gym, it happend that i accidentically deleted some parts of the note 😞 

### What's the solution you'd like to see in Notesnook?

As default, open notes in a read-only mode and offer a button to easily jump into edit mode.

This is common behaviour in Evernote, Google Docs.

Consider this as a optional setting.

**Comment by thecodrr** [comment]
Hi, you can turn on readonly mode for individual notes. There is no plan to make readonly mode the default via a setting since we already do provide readonly mode toggle on each note.
