### ISSUE TITLE
Cannot make any edits to locked notes from Android client

### ISSUE THREAD

**Issue by pachpict** [streetwriters/notesnook#3428]
### What happened?

I recently upgraded to v2.6.5 (see issue #3399).

After doing so I can go into a previously created and synched locked note. I am asked for the password as usual and the correct password unlocks it. Once inside it I can edit it. But if I leave that note (or background the app) those changes aren't saved. The last modified time stays the same as previously (e.g . 24 hours ago).

I can create a new note and that works fine. *However* if I go to lock that new note it prompts me to enter a password twice to "Create a vault". Of course I already have a vault.

My assumption is that the app has some disconnect and is not recognising the locked notes as belonging in an existing vault, which is why it can't edit them, and why it wants me to create a vault from scratch.

I have not tested what would happen if I went through with this and recreated the vault with the same password as previous. I am worried it will overwrite the previous notes.

### Steps to reproduce the problem

Install V2.6.5 on Android.
Connect it to an existing account with a vault containing locked notes.

### Version

v2.6.5

### Platform/OS

Android/Lineage OS

**Comment by thecodrr** [comment]
This has been fixed.
