### ISSUE TITLE
Norton detected Notesnook connection as a threat 

### ISSUE THREAD

**Issue by gracie95** [streetwriters/notesnook#3435]
`Notesnook does not have a valid digital signature.`

Version: 2.6.5-b85484f-desktop
OS: Windows 11 Pro

![Screenshot 2023-09-22 200404](https://github.com/streetwriters/notesnook/assets/107738923/f08e0708-c094-4060-9618-de72b7deb536)

**Comment by thecodrr** [comment]
That is true. Notesnook does not have a digital signature. That does not mean it's a threat or malware. It just means that we are not paying thousands of dollars to acquire a certificate to shut these AV notices. There's no need to worry about it.

**Comment by gracie95** [comment]
Again, but this time Norton become more aggressive. Norton detected and deleted Notesnook app and some files.

So, I switch to web version instead.

![Screenshot 2023-09-27 021951](https://github.com/streetwriters/notesnook/assets/107738923/f0b342ca-df80-40dc-ab63-634d5d93ad59)
.

**Comment by thecodrr** [comment]
Fixed
