### ISSUE TITLE
Ability to open multiple notes - Tabs

### ISSUE THREAD

**Issue by shanemc92** [streetwriters/notesnook#3458]
### What problem are you facing?

Sometimes I'll be editing a new note but want to quickly check something in another. But switching between them closes the existing note and then I have to find it again and scroll back down to where I was.
Other times I'll copy a note to notepad as a reference while editing a note in Notesnook.

### What's the solution you'd like to see in Notesnook?

Is there any appetite to add the ability to have two or more notes open in tabs? There's some space up top that could be used
![image](https://github.com/streetwriters/notesnook/assets/47665742/3197aa88-4ec0-4425-a334-7d077909bfd9)

Or even to have the last 5 recently opened notes as part of the sidebar for quick switching and have it remember your last position rather than jumping back to the top of the note each time.

### What alternatives have you considered?

*No response*

### Additional context

*No response*

**Comment by luxcalor** [comment]
Tabs where planned by devs as far as I remember. Looking forward to this on desktop and mobile myself.

**Comment by thecodrr** [comment]
Done.
