### ISSUE TITLE
Vault disappeared

### ISSUE THREAD

**Issue by 0xshippor** [streetwriters/notesnook#3471]
### What happened?

My vault has disappeared. When I go to vault settings I see create new vault. I have not changed anything regarding my vault.

Device information:
App version: 2.6.6-1facfbe-web/2.6.6-1facfbe-desktop
OS: Linux (PoP OS 22.04 LTS)
Browser: Brave Version 1.57.57 Chromium: 116.0.5845.163 (Official Build)
Pro: true

### Steps to reproduce the problem

The way I found out about this.
- unlock secure note
- try to type one letter to that note
- note immediately locks itself and the end of URL (if using web) changes to `/notes/undefined/unlock`
- I am unable to edit my notes in vault
Afterwards I went to settings of the vault and indeed it says only "Create". I don't want to do that as I don't want to loose my notes.

### Version

2.6.6-1facfbe-web/2.6.6-1facfbe-desktop

### Platform/OS

Linux

### Relevant log output

```shell
I did not find anything relevant in the logs.
```

**Comment by foozzi** [comment]
I have the same error on my iPad.

**Comment by 0xshippor** [comment]
I have backed up my notes and hit "Create" in vault settings. I re-created vault with same password and now it works well. I will leave this issue open as this should not happen.

**Comment by thecodrr** [comment]
This has been fixed. Please wait for the new version.
