### ISSUE TITLE
Notes restored from a backup don't sync at all on other devices

### ISSUE THREAD

**Issue by xfzv** [streetwriters/notesnook#3472]
### What happened?

I logged to my account on a machine I hadn't used for quite a long time (Linux with latest AppImage - `2.6.6-1facfbe-desktop`). Got quite a lot of merge conflicts, which I resolved manually. Afterwards, I still had completely outdated notes from like 6 months ago.

I decided to restore a backup from yesterday, which didn't work as expected because all  the outdated notes were still there.

I deleted all my notes and restored the backup. This time, everything looked OK, all my notes from yesterday were there.

However, despite syncing not giving any error, when I sync on another device (Android phone), I'm not getting any note at all. The notes list remains empty. 

If I use "Force sync" from either my Linux machine or my Android phone, then all my notes on my Linux machine disappear.

If I create a new note from either my Linux machine or my Android phone, it syncs fine and appear on both devices. 

I'd like my notes from the restored backup to sync, not only the new notes I'm taking...

In a nutshell: the notes restored from the backup are there but don't seem to sync whatsoever. I also tried to restore the same backup on my Android phone but I'm getting the exact same problem: the notes aren't showing up at all on my Linux machine.

Tried to log out from both devices prior to restoring the backup, to no avail.

Any help is appreciated.

Thanks.

### Steps to reproduce the problem

1. On the latest Linux AppImage, delete all notes
2. Restore a backup: the notes are successfully restored
3. Let the sync perform
4. Sync on the Android app
5. Zero note appear on the Android app, the notes list remains empty
6. Try to restore the backup on the Android device: the notes are successfully restored
7. Sync on the Linux AppImage
8. Zero note appear on the Linux AppImage, the notes list remains empty
9. Create a new note from either the Linux AppImage or the Android app, it syncs fine between both devices

### Version

Linux - 2.6.6-1facfbe-desktop | Android - 2.6.6

### Platform/OS

Linux

**Comment by derpydraggo** [comment]
I also ran into this issue.

Had started up Notesnook on a laptop I hadn't used in a couple of months, and had merge conflicts that I resolved (I would have liked an option asking if I wanted to either resolve merges or to just start fresh with what was already on the server, but I suppose that's more of an unrelated feature I would have liked). 

Saw old/outdated notes that I did not want showing back up, so I tried restoring from a backup I made the night before using my laptop with Notesnook, but the outdated notes were still there. Deleted all my notes then restored from backup, and everything *seemed* fine. Earlier today, however, I log into Notesnook using my phone that I use on a fairly regular basis, and my notes were gone. 

Tried to force sync on my phone, and got nothing. Went to my desktop with all my notes and force sync'd, and all of a sudden all of  my notes disappeared. Tried to restore from backup and check on my phone, nothing. Force syncing from desktop kept reverting the restorations. I then tried restoring backup, making a new backup, and restoring from that newer backup (I thought maybe it needed something newer to finally sync), and it still reverted to no notes.

I tried to export all my notes as text files and restore from that; no errors on import, but it imported absolutely nothing too.

I then log in via a web browser and repeated both a restoration from backup and with the exported .zip file, still didn't stick. I also tried to force logout all other devices *then* restore backup both ways, and it also didn't work (forcing logout on all other devices also didn't log me out of any other device for a couple of hours, by the way).

In the end, the only workaround that worked was for me to restore from backup, and then copy+paste some random string and `Ctrl-Z`-ing it in every single note, just so I could get all my notes properly synced  to the server, and onto all my other devices, and I'd imagine that'd be extremely annoying/infuriating to anyone with many notes and in similar circumstances.


If for some reason you need my client versions, my phone's app, desktop, and laptop were all updated to version 2.6.6 before opening any of them for the first time with this issue.
