### ISSUE TITLE
Unused "isDesktop" import in privacy-settings.ts

### ISSUE THREAD

**Issue by johnny-2123** [streetwriters/notesnook#3481]
File is located at apps/web/src/dialogs/settings/privacy-settings.ts
Unused "isDesktop" variable is at line 23

<img width="645" alt="image" src="https://github.com/streetwriters/notesnook/assets/95261336/ebd8b9bd-c131-41ad-9fb5-51a5975f14af">

**Comment by thecodrr** [comment]
@johnny-2123 feel free to open a PR!

**Comment by alihamuh** [comment]
issue solved
