### ISSUE TITLE
Clicking next to a link opens the link

### ISSUE THREAD

**Issue by NearestWater262** [streetwriters/notesnook#3484]
### What happened?

Link opened when i clicked next to it and not on it

### Steps to reproduce the problem

Have a link pasted in a note

Then click to the right of a link in an empty space but not on the link itself

It will open

I am using flatpak

VERY BAD FOR PRIVACY FOR THOSE WHO ACCIDENTLY OPEN

### Version

2.6.4

### Platform/OS

Linux

**Comment by thecodrr** [comment]
This has been in the latest version. Please upgrade.
