### ISSUE TITLE
Linux AppImage not syncing

### ISSUE THREAD

**Issue by NearestWater262** [streetwriters/notesnook#3485]
### What happened?

Stops at xx% and then says "Update app to latest version"

### Steps to reproduce the problem

Download the appimage from notesnook website

Try to sync notes

 I have to use flatpak because this doesn't work anymore

### Version

2.6.6

### Platform/OS

Linux

**Comment by thecodrr** [comment]
The appimage should already be on the latest version (2.6.6) so I don't think you should be seeing this error. Can you confirm that you are on version 2.6.6 when you see the error?
