### ISSUE TITLE
Vault Notes Re-locking On Sync MacOS Sonoma

### ISSUE THREAD

**Issue by mikeatlarge** [streetwriters/notesnook#3489]
I have a serious problem with Notesnook after upgrading to MacOS Sonoma. I can unlock my vault protected notes, but as soon as I type just one character, the note immediately re-locks! It wants the password again to unlock the note. This is very consistent and reproducible.

I assume the re-lock happens when it attempts to sync the change in the encrypted note. This makes my encrypted vault notes unusable as they are now all effectively read only.

I have re-installed, re-booted, done a forced sync, tried both 2.6.4 and the latest 2.6.6, and always have the same behavior.

On another MacBook with MacOS 12 Monterey, Notesnook still works OK including my encrypted vault notes. This is only happening with the new MacOS 14 Sonoma which was just released this week.

Anyone have any ideas or noticed similar behavior?

**Comment by thecodrr** [comment]
Fixed. Please wait for the next version.
