### ISSUE TITLE
Automatic single click on the first line of the notes.

### ISSUE THREAD

**Issue by Starship-Headlight** [streetwriters/notesnook#3521]
### What happened?

Issue in :- Editor
Issue :- Imagine you just edited a note "X". You closed the application or switched to another note. Now you switch back to note "X". 
The issue appears here. It seems when you open a note, NN single clicks the first line of the note by itself.
In these images (attached) NN clicked the embedded link on it's own as it was in the first line. In read only mode the link appears on the top left corner(WHICH IS ALSO A ISSUE AND NO IDEA WHY IT DOES THAT...) and in the editing mode it appears where it should when you click an embed link while editing a notes 

![1](https://github.com/streetwriters/notesnook/assets/142043604/b2274254-f43e-4a31-ad0b-ba7560d72e06)
![2](https://github.com/streetwriters/notesnook/assets/142043604/ff423cac-380d-4276-a360-cf006395747c)

In this image the divider gets selected on it's own.

![3](https://github.com/streetwriters/notesnook/assets/142043604/cda2987f-076b-41ac-811c-2bd9f41a98d3)

Also happens in math when switching to the note while in editing mode

![4](https://github.com/streetwriters/notesnook/assets/142043604/bd60d928-5e0d-4f61-8e83-ef90dc784ac4)

This issue appears in both web app and android app but the link click issue will appear on web app when you set the app in portrait mode(half of the screen) and sometimes it randomly appears in full screen too. 
The divider and math issues appear everywhere.

### Steps to reproduce the problem

As stated in "What happened?" section.

### Version

2.6.7

### Platform/OS

Android, Chrome/Chromium

**Comment by thecodrr** [comment]
This is by design. The app automatically focuses the editor and places the caret at the beginning. If you have a link or something else at the beginning then the app will follow normal behavior.

> In read only mode the link appears on the top left corner(WHICH IS ALSO A ISSUE AND NO IDEA WHY IT DOES THAT...) 

That's an issue.

**Comment by Starship-Headlight** [comment]
>> This is by design. The app automatically focuses the editor and places the caret at the beginning. If you have a link or something else at the beginning then the app will follow normal behavior.
>
>Got it. So you mean if there is a link at the start of the page then it will not click that link. Is it possible to do that same for divider. It looks a little odd in the picture...


![3](https://github.com/streetwriters/notesnook/assets/142043604/18695915-94c8-45b3-ac37-25ddb17a90e9)

**Comment by thecodrr** [comment]
@Starship-Headlight whatever is at the beginning of the page gets the focus.

**Comment by Starship-Headlight** [comment]
Got it.

**Comment by thecodrr** [comment]
Opened a separate issue for the readonly mode issue: #3669
