### ISSUE TITLE
Capital letters not allowed in Tags.

### ISSUE THREAD

**Issue by Starship-Headlight** [streetwriters/notesnook#3530]
### What happened?

One of the recent updates removed capital letters in tags. I don't exactly remember which one. But I have some tags which have capital letters but now I can not create any such tags anymore.

For example :- 
 
#placewithcity #devmisc

could be (if capital letters are allowed)

#PlaceWithCity #DevMisc

This looks better and is easily distinguishable otherwise the whole tag looks like a single word.

Please check this.
. 

### Steps to reproduce the problem

As stated in "what happened?" section.

### Version

2.6.7

### Platform/OS

Windows, macOS, Linux, iOS, Android, Chrome/Chromium, Firefox, Safari, Other browser

**Comment by thecodrr** [comment]
Capital letters were never allowed. This will be fixed in the next major release. For now you can just rename the tag after creating it.

**Comment by Starship-Headlight** [comment]
Got it. Waiting for the next release😁👍

BTW maybe this was a glitch for a while but I have this...

![7](https://github.com/streetwriters/notesnook/assets/142043604/295c3db5-e7a5-42ae-aac6-9e41b1b6bf35)

**Comment by Starship-Headlight** [comment]
Space between 2 words is also not allowed in tags.
