### ISSUE TITLE
Bring back .deb and .rpm packages

### ISSUE THREAD

**Issue by CamaradaPrestes** [streetwriters/notesnook#3540]
### What problem are you facing?

None, I just want the .deb back (please).

### What's the solution you'd like to see in Notesnook?

Bring back .deb and .rpm packages.

**Comment by thecodrr** [comment]
.deb & .rpm will not be brought back because:

1. There's no way to provide automatic updates for them
2. There are better formats availale like flatpak, appimage & snap
