### ISSUE TITLE
Exporting to PDF hides "$$yourmath$$" part.

### ISSUE THREAD

**Issue by Starship-Headlight** [streetwriters/notesnook#3546]
### What happened?

Suppose the note has ***$$yourmath$$*** part in between the other text, then you can not export the note as PDF on Android. It gets stuck on the "Exporting note... Please wait" also the app becomes unresponsive. I am not sure if it is related to my device so please check it once.

But I am sure about web app that the exported PDF does not include the ***$$yourmath$$*** part of the note. There was one instance, in many attempts, where it included the ***$$yourmath$$*** part but I couldn't make that happen again.

As for Desktop app, I haven't checked it.

Please check these screenshots.

Thanks

![1](https://github.com/streetwriters/notesnook/assets/142043604/6153678e-3e0b-4957-8c64-e14fb67a93fd)
![2](https://github.com/streetwriters/notesnook/assets/142043604/895bfdc0-4d2d-4d95-8c55-d184400e2605)
![4](https://github.com/streetwriters/notesnook/assets/142043604/719dfaf4-9f3e-4c15-8861-fe431283ed41)

### Steps to reproduce the problem

As stated in "what happened?" section.

### Version

2.6.7

### Platform/OS

Android, Chrome/Chromium

**Comment by Starship-Headlight** [comment]
UPDATE :- I think this issue is also present in Math&Formula block not only in "$$___$$"

**Comment by thecodrr** [comment]
Not able to reproduce this on Windows Desktop App.

**Comment by Starship-Headlight** [comment]
I have not used it in desktop app. I used the export option in web app (Chrome). Please type the same text as shown in the screenshot and then try export as PDF in chrome web app. I can still reproduce this issue.

**Comment by thecodrr** [comment]
@Starship-Headlight tested on Google Chrome. Still can't reproduce it. For me it is rendering just fine.

**Comment by Starship-Headlight** [comment]
@thecodrr Maybe only I am facing this issue. I tried disabling all extensions and opening a new profile but still had the issue...

**Comment by Starship-Headlight** [comment]
@thecodrr are you able to export a note with "math" on android app? I can not do that.

**Comment by Starship-Headlight** [comment]
completed via #3773

**Comment by Starship-Headlight** [comment]
via #3773
