### ISSUE TITLE
Note Title's font size decreases the longer the text becomes

### ISSUE THREAD

**Issue by ARodriguezHacks** [streetwriters/notesnook#3568]
### What happened?

When creating a new note, I noticed that as I started typing out my note title, the text would decrease in font size more and more each time.

https://github.com/streetwriters/notesnook/assets/22532097/cdffcbfd-241d-4576-b32c-df3728357a94

### Steps to reproduce the problem

1. Click the "Add a Note" green plus button
2. Place cursor in "Note title" field and start typing

Expected output: the Note Title's font size should be consistent throughout typing, and not be shrinking the more you type.

Browsers tested/first noted: Brave and Firefox

### Version

2.6.7-3895569-web

### Platform/OS

macOS

**Comment by thecodrr** [comment]
This is not a bug but a feature in order to fit more of the title without it cutting off in a single line.
