### ISSUE TITLE
hide title of tasks list

### ISSUE THREAD

**Issue by terlan4** [streetwriters/notesnook#3576]
### What problem are you facing?

I would like to be able to hide title of tasks list and just see tasks themselves. Because I never use that title thing. Most of the time i just need to add quick task item to the note and having extra title bar taking space doesn't match what I would want.

![image](https://github.com/streetwriters/notesnook/assets/138553763/34fb5d84-b01d-4dd1-8e30-8f0f4f607141)

### What's the solution you'd like to see in Notesnook?

"hide title bar for task list" toggle button

**Comment by thecodrr** [comment]
There's no way to do this. The title bar is part of the task list.

**Comment by thecodrr** [comment]
Currently there is no plan to make this change.

**Comment by RayJW** [comment]
Would be nice if this could be reconsidered, a lot of times I add tasks to an overarching topic that isn't something that has like a fixed point in time to be completed but is rather ongoing. This makes the whole task title thing completely useless, as it's usually already part of whatever header the task list belongs to :)
