### ISSUE TITLE
Persian/Arabic font on MacOS is not the native Apple font and is ugly

### ISSUE THREAD

**Issue by asto-ms** [streetwriters/notesnook#3605]
### What problem are you facing?

Persian / Arabic font on MacOS version of NotesNook is the native Apple font and looks ugly. Interestingly, this is not the case with the iOS version of the app which uses the native Apple font for right to left languages such as Farsi / Arabic.

### What's the solution you'd like to see in Notesnook?

Implement the native Apple font for the MacOS version of the application.

### What alternatives have you considered?

NA

### Additional context

iOS version of the app:
![IMG_0001](https://github.com/streetwriters/notesnook/assets/143348971/c499b647-f3ba-4d42-a9a0-79a17c395050)

MacOS version of the app:
<img width="202" alt="Screenshot 2023-10-21 at 6 10 03 PM" src="https://github.com/streetwriters/notesnook/assets/143348971/2655de3a-e41b-477d-b329-f6f0989f8ef4">

**Comment by thecodrr** [comment]
This is out of control of Notesnook. What you are seeing here is your default system font being used for Arabic.
