### ISSUE TITLE
Possibility for users to reset their 2FA secret key

### ISSUE THREAD

**Issue by the-code-creator** [streetwriters/notesnook#3608]
### What problem are you facing?

There's no way to reset the 2FA via Authenticator secret key.
If one switches from 2FA via Authenticator to 2FA via email and back, it's still the same secret key as before.
This is a security flaw that needs to be fixed.
If users want a new 2FA secret key, it's currently impossible.
Users who had their 2FA secret key exposed or compromised are then unable to use the 2FA via Authenticator option anymore!

Please change that – almost all other websites enable the users to reset their 2FA secret key.

Thank you!😄

### What's the solution you'd like to see in Notesnook?

Make it possible for users to reset the 2FA secret key so their able to create a new one.👍

**Comment by thecodrr** [comment]
Duplicate of #3494
