### ISSUE TITLE
Web clipper won't process pages with frames [Android]

### ISSUE THREAD

**Issue by luxcalor** [streetwriters/notesnook#3616]
### What happened?

Web clipper does not fetch data from a framed web page. This issue was open before, but now is closed. Yet the problem is still there. 

### Steps to reproduce the problem

Open the page https://www.hustleescape.com/book-summary-lifespan-by-david-sinclair/?fbclid=IwAR3AqhoLHcfOEMTzbgb4jLlpAjbMXe1lCOttZiT9JzL-G0NkiFbtuqzh5MA as an example - share it to NN - select web clip - the process of fetching seems to start but then the dialog goes blank.

### Version

2.6.7

### Platform/OS

Android

**Comment by ammarahm-ed** [comment]
Hey, I just tested this and the given example page does get clipped correctly on android.

**Comment by luxcalor** [comment]
Don't know what happened, have been away for a while, but this seems to be fixed. Above-mentioned and other framed pages do get clipped on both Android and Windows. Closing this as complete.
