### ISSUE TITLE
Backup share prompt shows up every time i open the app

### ISSUE THREAD

**Issue by candroid-man** [streetwriters/notesnook#362]
**Describe the bug**

After I get the usual "backup complete" prompt, it then promtps me again to backup the backups to Google Drive or whatever. This seems unnecessary for it to happen every time.

**Screenshots**

![Screenshot_20220220-210721_Notesnook.jpg](https://user-images.githubusercontent.com/51019003/154883270-5552fa46-307b-415b-b7ef-ee9474847565.jpg)

**Smartphone:**

 - Device: Samsung Galaxy S10+
 - OS: Android 12
 - Version 1.7.13

**Comment by ammarahm-ed** [comment]
Fixed. User will be shown option to "Never ask again".
