### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by passionate2023** [streetwriters/notesnook#3622]
### What problem are you facing?

Features Missing

### What's the solution you'd like to see in Notesnook?

Below are the features needed

1 - Share the notes to public - any user will browse/view the content - without any credentials - however they cannot add or edit or delete the content - Just READ only like website. Public Sharing via URL
2 - Import option to import text files. Text file sizes may be huge - Max size of a single text file would be 10MB but not all...The smallest one is 200KB in size. Should support unicode characters
3 - Add a type-ahead search with number of hits found even before hitting the search
4 - Next, Previous buttons and arrows after search results are returned.....
5 - Highlight the text on the file name as well as on the right side content
6 - Following app produces the results in milliseconds....However it doesn't all the features listed

a. https://bible.rs/ => searches whole bible in fraction of milliseconds
b. https://app.simplenote.com/ ==> searches any details in fraction of milliseconds

**Comment by thecodrr** [comment]
@passionate2023 thank you for taking the time to list your requirements (without doing prior research):

1. This is already available: https://monograph.notesnook.com
2. This is also available: https://importer.notesnook.com
3. Not sure what you mean here.
4. For what?
5. There's already an issue for opened for this: #1759

**Comment by passionate2023** [comment]
@thecodrr The sharing works only for 1 note and not entire collection....Number of matches found on typing a keyword for search....ex: Test (1000) --- Testing (500) --- Testing This (10)...Arrows for navigate the searched result and matched kits via keyboard option as well as with arrows <-- and -->
