### ISSUE TITLE
Same tag twice in a single note

### ISSUE THREAD

**Issue by alihamuh** [streetwriters/notesnook#3629]
### What happened?

![same-tag-twice-bug](https://github.com/streetwriters/notesnook/assets/22678611/da8dda93-1b3c-4214-935c-c70a5e938ff2)

### Steps to reproduce the problem

---

### Version

2.6.7

### Platform/OS

Linux AppImage version.

**Comment by luxcalor** [comment]
This happens on android too.

**Comment by ammarahm-ed** [comment]
This has been fixed in v3.
