### ISSUE TITLE
Unable to use 2FA codes from iOS authenticator app to login

### ISSUE THREAD

**Issue by adworacz** [streetwriters/notesnook#3631]
### What happened?

On my 2FA app (Raivo), after setting up 2FA in Notesnook (and having my generated code accepted in the confirmation dialog after scanning the QR code), I cannot login using the codes generated by my 2FA app.

Only the codes sent to my email work.

I use this app for other sites as well, and Notesnook is the only one I'm experiencing issues with.

### Steps to reproduce the problem

1. Register for 2FA using the "Authenticator" option.
2. Enter the generated code in the confirmation dialog.
3. Have it accepted
4. Then try and login, using codes from said 2FA app.
5. Get rejected.

### Version

2.6.7

### Platform/OS

Linux, Firefox

**Comment by thecodrr** [comment]
What error are you getting @adworacz when you enter the 2FA code? I can assure you that there's no problem in the app because I just logged in using my TOTP codes on 2 of my devices.

**Comment by adworacz** [comment]
Fair question - I'll capture some network requests and get you proper error information once I get a spare moment.

**Comment by adworacz** [comment]
Ahhh wait a minute, I see whats going on - I can't use the same form for submitting 2FA codes from email *OR* my authenticator app.

I didn't notice the "Don't have access to your email?" link before. I expected to be able to use codes in the same login form no matter where they were coming from, just like Amazon and another sites support.

So I guess you can chalk this up to not a bug, just a confusing user experience.

**Comment by thecodrr** [comment]
@adworacz yes, both 2FAs are different and detached from each other. Closing this as there was no issue.
