### ISSUE TITLE
Imported PDF files are empty on iOS

### ISSUE THREAD

**Issue by edhans** [streetwriters/notesnook#3641]
### What happened?

I'm having an issue on my iPhone where PDF files are empty. When I open them they show "Page 1/0" (page 1 of 0) and it has no content. It doesn't matter if share the PDF from another app, or from that other app save it to files, then from the NotesNook app import from the file.

### Steps to reproduce the problem

Import a PDF file, either from files, or share from another app

### Version

2.6.7

### Platform/OS

iOS

**Comment by ammarahm-ed** [comment]
Hey, what if you download the PDF file from Notesnook and then open it in the default PDF viewer? Is it still empty?

**Comment by ammarahm-ed** [comment]
So I just tested with a sample PDF file and it's working fine. I am able to view the PDF and scroll through the pages in the PDF.
