### ISSUE TITLE
Add option to select how many lines the app is going to show

### ISSUE THREAD

**Issue by inson1** [streetwriters/notesnook#3647]
### What problem are you facing?

I would like none - I think its take too much space, someone would like 2, 3 ....... etc.

### What's the solution you'd like to see in Notesnook?

Add option to choose or write the number.

### What alternatives have you considered?

.

**Comment by thecodrr** [comment]
There is "Compact Mode" which hides all the lines. Have you tried that?

**Comment by inson1** [comment]
@thecodrr I didnt know about that, thank you, but my issue still stands - some wants 2, there is compact mode, then someone could want 3 etc.

**Comment by thecodrr** [comment]
I don't think increasing or decreasing the number of lines has any real utility. I'll keep this issue open so others can chime in. Maybe there is a use case I am failing to see.

**Comment by thecodrr** [comment]
Closing this issue as the purpose of the headline is not to allow reading the whole not but only to give an idea about what's inside.
