### ISSUE TITLE
[Feature request] Add custom sort of Notes and Noebooks

### ISSUE THREAD

**Issue by inson1** [streetwriters/notesnook#3653]
### What problem are you facing?

I want my own order with drag and drop feature.

### What's the solution you'd like to see in Notesnook?

Custom sort with with drag and drop feature. New  Notes and Noebooks would be added to bottom or top based on option in settings

**Comment by thecodrr** [comment]
This has been discussed before as well, and the answer is: no. Custom sort solves no problem aside from just being "convenient". Notesnook offers many types of sorting options which can be used to acheive almost everything that a custom sort would acheive. Secondly, the only real problem that (you can say) custom sort solves is keeping a few notes always at the top. This can already be done using Pinned notes.

**Comment by ginsterbusch** [comment]
Except if one uses this as a sort of Kanban, which would be just about perfect: Notebooks are different types of "lists", that can interact, and offer much more flexibility than something like eg. Trello.

Aside of that: Not a very user-friendly move. Has a touch of Apple ("you have to abide to OUR UI, not the other way around") and Gnome ("Users are clueless idiots, so lets hide all good customization options").

cu, w0lf.
