### ISSUE TITLE
[Feature request] Create account without email

### ISSUE THREAD

**Issue by inson1** [streetwriters/notesnook#3654]
### What problem are you facing?

I want more anonymity.

### What's the solution you'd like to see in Notesnook?

Add option to create account without email, identificator could be some long code like in Mullvad VPN, but longer.

**Comment by thecodrr** [comment]
Use email aliasing services like SimpleLogin to acheive all kinds of anonymity. Email allows us to prevent a lot of spam & bot accounts.

**Comment by inson1** [comment]
@thecodrr These services arent perfect either. Why not create tiers without email - free without sync and premium with everything? Paying is the best prevention against bots and spam etc.
