### ISSUE TITLE
Add link to Source code (Github) to About section in Settings.

### ISSUE THREAD

**Issue by inson1** [streetwriters/notesnook#3657]
I would like to have link to source code in Settings, not to issues, not to something else, but to source code. Thank you :)

**Comment by inumaki** [comment]
Hi @inson1 , I want to work on this issue, kindly assign it to me if no one is working on this.

**Comment by inson1** [comment]
@inumaki Hi, I dont have the privileges, so I cant, but that doesnt matter too much. Just work on it and then create pull request.

**Comment by inumaki** [comment]
![image](https://github.com/streetwriters/notesnook/assets/69989774/40893fa7-a0b4-46ac-95d8-953b9a69feb8)

Hi @inson1 , can you exactly tell me where exactly (section) you want me to add that link.
What I was thinking  to add this in the About section , just below **Available on ios & Android**.
![image](https://github.com/streetwriters/notesnook/assets/69989774/24418022-2166-44cc-9d8e-547aec3040f3)

**Comment by inson1** [comment]
@inumaki yes, About section, maybe as first item?

Or second item.....

**Comment by inumaki** [comment]
Will keep it as second item , since version on top is standard @inson1.
