### ISSUE TITLE
Notesnook.com is down

### ISSUE THREAD

**Issue by rudrakshkarpe** [streetwriters/notesnook#3674]
### What happened?

Can you anyone please look into? 

Both the URLs below seems to be down :( Mobile app is working but showing syncing issues. 

[app.notesnook.com/notes](https://notesnook.com/)

[notesnook.com](https://notesnook.com/)

<img width="752" alt="image" src="https://github.com/streetwriters/notesnook/assets/78851635/5613881b-23dc-4bbc-b194-84e2f2d1dee3">

### Steps to reproduce the problem

- Use edge/chome browser
- search for the URLs ```notesnook.com``` & ```app.notesnook.com/notes``` both are down

### Version

web-version

### Platform/OS

Windows

**Comment by thecodrr** [comment]
@rudrakshkarpe working fine for me.

**Comment by Starship-Headlight** [comment]
@rudrakshkarpe I also had the same issue and I found notesnook was added to 1Host(Xtra) block list. But as of now it has been removed from the block list and it should work as usual. But if you are still facing this issue then try disabling the adblocker for notesnook. And if you are using a custom dns then maybe add notesnook and streetwriters to the allowlist.

**Comment by rudrakshkarpe** [comment]
Thanks @Starship-Headlight & @thecodrr the issue got fixed next morning for me. It's working fine now.

**Comment by Starship-Headlight** [comment]
@rudrakshkarpe Yep. Then it must have been the block list. As of now, It has been removed from the blocklist so it should work as usual.
