### ISSUE TITLE
Themes missing

### ISSUE THREAD

**Issue by Kobaratz** [streetwriters/notesnook#3685]
### What happened?

Only two themes showing in the app and web interface (Dark and Light)

### Steps to reproduce the problem

The web version had all themes showing as of yesterday (31/10/23). I enabled the Dracula theme, and upon opening it today, I can only access Dracula or Light theme (or theme builder).
![image](https://github.com/streetwriters/notesnook/assets/145990344/977825d2-dd6d-4e8c-a635-b9a10c34add3)

Desktop version with login only shows dark and light 

![image](https://github.com/streetwriters/notesnook/assets/145990344/4acf73c3-b543-43a4-941c-505933807489)

### Version

v2.6.7

### Platform/OS

Windows, Chrome/Chromium

**Comment by thecodrr** [comment]
Should be back up.
