### ISSUE TITLE
Web-clipper returning `undefined` value

### ISSUE THREAD

**Issue by mtsbh** [streetwriters/notesnook#3762]
### What happened?

Every time when I try the web-clipper node clip feature it returning ``undefined`` value in notes. It also returning the same value when I click ``click here to preview`` in the extension.

[screenshot](https://i.imgur.com/sCO0o7b.png)

Is there any way of fixing that?

PS:. I'm using Arch Linux

### Steps to reproduce the problem

Click on the web-clipper extension -> click on selected nodes -> pick up a part of the site to clip -> pressing clip on the popped up in down side of the window clip button -> return to extension -> save clip -> error

### Version

2.6.8-91b0de0-web

### Platform/OS

Linux

**Comment by alihamuh** [comment]
We could not reproduce this issue. 

Can you please send a screen recording?

**Comment by mtsbh** [comment]
It was browser issue. It seems that the web-clipper doesnt really like Vivaldi. I've tried with other browsers - its working well. 

I'm closing that issue.
