### ISSUE TITLE
Merge outline list feature into number/bullet list

### ISSUE THREAD

**Issue by JVimes** [streetwriters/notesnook#3764]
### What problem are you facing?

I was confused at first about Outline lists vs Number/Bullet lists.

### What's the solution you'd like to see in Notesnook?

Would it work to make the Number/Bullet lists collapsible, and then remove the (now redundant) Outline list feature?

### Additional context

![image](https://github.com/streetwriters/notesnook/assets/6148201/ada2325d-59b9-4067-a874-e806cf7d4eb1)

**Comment by thecodrr** [comment]
I think outline lists are (and should be) different from other lists. I am not seeing clear indication that they should be merged into one. However, I am open to discussion on this.

**Comment by JVimes** [comment]
Thank you. How is an outline list different than a collapsible bullet list? Maybe I don't understand well.

**Comment by Starship-Headlight** [comment]
How about allowing other blocks inside outline list. That could solve everything...

**Comment by luxcalor** [comment]
I agree with @thecodrr on this one. I mostly work in outlines and they are quite different from the normal lists. Especially if some features that were discussed elsewhere (blocks, drag and drop, etc) will be implemented.

**Comment by JVimes** [comment]
Those features would benefit numbered lists, too. And there's no point in uses bullet lists, since Outline lists have bullets.

I still request all lists support the outline list features.
