### ISSUE TITLE
Android app is unusable after update

### ISSUE THREAD

**Issue by NikunjKhangwal** [streetwriters/notesnook#3847]
### What happened?

The app becomes unusable a few seconds after opening it. Most of the buttons freeze and I'm stucked in the app. In some cases where i quickly open a note after app launch, the app function normally but the buttons freeze as soon as i start typing. I can't go back from a note or main notes list with both the app's menu button and my phone's navigation bar button. Restarting the app doesn't fix it.
Here are some examples:-

https://github.com/streetwriters/notesnook/assets/99175083/a4223b7f-1cb1-4e8b-931c-2791d65259f0

https://github.com/streetwriters/notesnook/assets/99175083/84412bd1-2cdd-4dd2-93b9-56886674e96b

https://github.com/streetwriters/notesnook/assets/99175083/3d6b405a-2486-4457-8268-436ee7a3b703

I'm not entirely sure but I'm guessing what you guys did to solve #3742 is causing these side effects. The app doesn't crash now but it's not usable anymore either 

### Steps to reproduce the problem

Pretty much basic ui navigation.

### Version

v2.6.10

### Platform/OS

Android

**Comment by ammarahm-ed** [comment]
Hi, can you remember when this issue started happening and do you remember any specific actions you took before you saw the app hang on start for the first time?

Does it hang with internet disabled too?

**Comment by NikunjKhangwal** [comment]
This started happening right after update. I didn't took any specific action before this. This happens with internet disabled as well. Additionally the app start acting weird when internet is off. It puts huge gap between notes, random blank spaces and most of the notes at the very bottom of the list disappears.
Example:-
![image](https://github.com/streetwriters/notesnook/assets/99175083/e0b1adab-0b4a-4670-85b8-107e2f99490b)
![image](https://github.com/streetwriters/notesnook/assets/99175083/be9697e8-b0c1-480d-ad73-efbb1a94777d)
![image](https://github.com/streetwriters/notesnook/assets/99175083/fbffddc1-7ed0-411f-84c6-facdf7e0fdba)

**Comment by ammarahm-ed** [comment]
That's basically the app hanging a lot. Since it's not crashing it's hard to tell what might be causing it. What if you try to logout and relogin?

**Comment by NikunjKhangwal** [comment]
Logging out wasn't possible since settings sections freezed after 3 seconds. But i cleared data of the app and it started working again. I tried changing a few settings but it's still fine.
I don't know how to debug so sorry i can't help with that but i'll inform if this happens again.
