### ISSUE TITLE
Toolbar jumps/hides when window resized

### ISSUE THREAD

**Issue by JVimes** [streetwriters/notesnook#3854]
### What happened?

The toolbar sometimes disappears or jumps to the bottom when I resize the window (desktop and Chrome).

### Steps to reproduce the problem

I created a note and resized the window in various ways, see video.

https://github.com/streetwriters/notesnook/assets/6148201/247a9319-fc3f-4eab-bd2b-f09280f6efdd

### Version

2.6.11-2c635eb-desktop

### Platform/OS

Windows, Chrome/Chromium

**Comment by thecodrr** [comment]
This is working as intended. Toolbar moves to the bottom in Tablet/Mobile mode.

**Comment by JVimes** [comment]
@thecodrr it disappears entirely, too

**Comment by thecodrr** [comment]
@JVimes the toolbar is not shown if you haven't yet created a note.
