### ISSUE TITLE
Syncronization by WebDav

### ISSUE THREAD

**Issue by GildedHonour** [streetwriters/notesnook#3868]
### What problem are you facing?

Does Notesnook support syncroniztion by WebDav?

### What's the solution you'd like to see in Notesnook?

-

### What alternatives have you considered?

-

### Additional context

-

**Comment by GildedHonour** [comment]
up

**Comment by thecodrr** [comment]
There's no plan to offer this. We will instead make the sync server self hostable.

**Comment by kimsonvu** [comment]
Hi,
I really want to selfhost with my private webdav / sfpt server than use internet / company server. Is it possible?

**Comment by essys** [comment]
> There's no plan to offer this. We will instead make the sync server self hostable.

Hi Abdullah, many thanks for this awesome note application.
Can you provide a rough ETA when the sync server will be released?
Please keep up the excellent work.
