### ISSUE TITLE
Winget updates are massively delayed.

### ISSUE THREAD

**Issue by NikunjKhangwal** [streetwriters/notesnook#3877]
I don't know if you're pushing updates late or it's a winget problem. Winget version is still stucked on 2.6.8 while the new version is 2.6.12. If it's a delay from your side, please push the updates quicker.

**Comment by NikunjKhangwal** [comment]
Actually Winget has its own sets of problems. It mismatches the version when you manually update the app. Also it gets package conflicts when you update from another source.
I think only installing from exe file is plausible now.

**Comment by thecodrr** [comment]
I'll see if we can create an auto update mechanism for winget.

**Comment by NikunjKhangwal** [comment]
That would be much appreciated, Thanks

**Comment by thecodrr** [comment]
Closing as we currently don't have resources to fix this.
