### ISSUE TITLE
Spellcheck, persistent font & templates.

### ISSUE THREAD

**Issue by MsJonesy** [streetwriters/notesnook#388]
**Is your feature request related to a problem? Please describe.**

- [ ] *Spellcheck* - this should be fairly obvious as to why it’s needed, but if not, your customer base uses too many other applications that has spellcheck, to be slowed down and frustrated by the lack of one. (#404)
- [x] *Persistent font* - I’ve mentioned this before, but it still happens. I choose a font, start typing, and as soon as I hit enter, the font defaults to SYSTEM FONT.
- [ ] #940

**Describe the solution you'd like**
All of those things added or resolved.

**Describe alternatives you've considered**
I will make a note, favorite it, and copy it over and over, until at least the option to quickly duplicate is provided.

**Additional context**

**Comment by thecodrr** [comment]
> Persistent font - I’ve mentioned this before, but it still happens. I choose a font, start typing, and as soon as I hit enter, the font defaults to SYSTEM FONT.

This is done. Coming in the next release.

**Comment by MsJonesy** [comment]
Thank you very much for already having this ready to go, and the quick response.

**Comment by thecodrr** [comment]
@MsJonesy Option to quickly duplicate a note is coming in the next release.

**Comment by MsJonesy** [comment]
Thank you! This will be huge for me.

**Comment by thecodrr** [comment]
Closing as the remaining issues are being tracked in their separate issues.
