### ISSUE TITLE
Allow selection with Cmd+Click on macOS

### ISSUE THREAD

**Issue by gaganyadav80** [streetwriters/notesnook#389]
**Is your feature request related to a problem? Please describe.**
Right now you can only move note from one notebook to another by selecting one note at a time. This is really time consuming when you have to move more than just few notes.

**Describe the solution you'd like**
Allow multi-selecting notes (on desktop) and option to move all those selected notes to another notebook.

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by thecodrr** [comment]
This is already possible. If you select multiple notes and right click to open the context menu, you can see the "Add to notebook(s)" button. The Add note to notebook dialog also allows removing/moving items to other notebooks.

The next version will improve the UX of this dialog a lot.

**Comment by gaganyadav80** [comment]
I could find a way to multi select notes on desktop app. How do I do it on desktop?

**Comment by thecodrr** [comment]
Ctrl + Click or Ctrl + A works.

**Comment by gaganyadav80** [comment]
> Ctrl + Click or Ctrl + A works.

Okay, got it. I was using cmd key.

**Comment by thecodrr** [comment]
> > Ctrl + Click or Ctrl + A works.
> 
> Okay, got it. I was using cmd key.

Oh wait. Cmd should work too...that's a bug if it isn't working.

**Comment by chairmantheboring** [comment]
I want to spend a moment to highlight the importance of fixing this issue. This bug makes multi-note selection _much_ harder than it needs to be on macOS. Ctrl + click is hard-mapped to right click on macOS and there is no way to unmap this function. That means that Ctrl + click cannot be used to select notes on macOS, as it will just bring up the context menu. A quick band-aid solution for this would be to include a "select"/"unselect" option in the context menu.

Additionally, yes, Cmd + A is broken and will just select all the text in the client, including text from UI elements, for example, the "Notes" heading when you're in the Notes tab.

With that out of the way, I would like to say thanks for creating such a great application, minor issues like these aside. Your app flies in comparison to your competition.

**Comment by thecodrr** [comment]
This should be fixed in v2.2.4. Can you confirm @chairmantheboring @gaganyadav80

**Comment by sharemind** [comment]
Now it works, it selects multiple notes with CMD+click. 

But will be nice to be able to deselect a note by clicking again on top with CMD+click.

**Comment by thecodrr** [comment]
@sharemind

> deselect a note by clicking again on top with CMD+click.

This has been added.
