### ISSUE TITLE
Accounting for topics during export

### ISSUE THREAD

**Issue by GoodM4ven** [streetwriters/notesnook#3890]
### What problem are you facing?

Not having the exported notes currently categorized by their topics within the notebooks.

### What's the solution you'd like to see in Notesnook?

A checkbox to account for topics categorization during export.

### Additional context

Please make the exported notes in sub-folders based on notebooks first and topics second.

**Comment by ammarahm-ed** [comment]
This has been fixed in v3 with nested notebooks.
