### ISSUE TITLE
Image resizing resetting on the first try.

### ISSUE THREAD

**Issue by Starship-Headlight** [streetwriters/notesnook#3892]
### What happened?

Imagine you are trying to resize the image attached to a note. 

You click on the bottom right corner and use your mouse to resize the image. 

You drag the mouse according to the required size. Now you let the mouse free so that the image keeps the required size. But after leaving the mouse, the image size gets reset to original size.

This issue doesn't happen on the second try.

### Version

2.6.12

### Platform/OS

Windows, Chrome/Chromium

**Comment by ammarahm-ed** [comment]
This has been fixed in v3.
