### ISSUE TITLE
Searching through imported Arabic notes is broken

### ISSUE THREAD

**Issue by 0rAX0** [streetwriters/notesnook#3964]
### What happened?

I have many notes imported from Zoho, I also created some notes on Notesnook. I noticed that when I search for something that is supposed to be in the imported arabic notes, Notesnook doesn't return anything.

I even had to copy text specifically from one existing note and it still didn't find it.

### Steps to reproduce the problem

I tried a few combinations and here are my findings:

- Import some Arabic notes
- Create more.

- Searching with Latin letters works fine regardless of the source
- Searching for Arabic will only show you results from the ones created using Notenook
- Searching though imported Arabic notes yields nothing. 

### Version

2.6.12-4d7a8b9-desktop

### Platform/OS

Windows

**Comment by thecodrr** [comment]
Is it possible for you to privately share a sample Arabic note so I can try and reproduce this?
