### ISSUE TITLE
Android: Vault password not recognized: Reset vault / reset account 

### ISSUE THREAD

**Issue by aquatic7** [streetwriters/notesnook#4]
My vault worked fine yesterday, saved the password to bitwarden. Today it says incorrect password.

Let's assume it's the wrong password for the vault, ok.

How do I reset the vault password or the account (and lose the encrypted notes ofc)?

Also I'm able to turn on 'Vault biometrics unlock' from settings with the password. But it won't unlock the notes with the biometrics.

It seems like the 'Vault biometrics unlock' takes in any password and enable it, but it just won't unlock.
It would be good if it said 'Incorrect password' too when a wrong password is entered to enable the biometric unlock for the vault.

When trying to unlock a vault notenwith biometrics it gives an option to use PIN.
But I don't recall setting a PIN? and I do not see anywhere in the settings anything about a PIN?

It would seem like there are some minor issues/bug fixes about the vault.

Also it would be nice to be able to reset somehow (yes losing the vaulted notes ofc if no recovery for that is available) so the app ain't unusable from this point of. :)

Besides that the app seems promising.

A request as a sidenote would be an option to have the vault be unlocked for (remembered); never, 5 minutes, 1 hour, 1 week - like it's possible in standard notes.

When working on multiple notes that's locked(vault) then it's not very productive to have to unlock every note all the time for a period of time needed.

Thank you for your great work! Keep it up! <3

**Comment by ammarahm-ed** [comment]
> It seems like the 'Vault biometrics unlock' takes in any password and enable it, but it just won't unlock.
It would be good if it said 'Incorrect password' too when a wrong password is entered to enable the biometric unlock for the vault.

I can confirm that this is a bug in the current version. Biometrics should be enabled only if user enters the correct password. 

>Let's assume it's the wrong password for the vault, ok.
How do I reset the vault password or the account (and lose the encrypted notes ofc)?

I think we overlooked this. It seems that it would be very important if user wants to use the vault even after being locked out. So an option to delete the vault would be perfect. 

>A request as a sidenote would be an option to have the vault be unlocked for (remembered); never, 5 minutes, 1 hour, 1 week - like it's possible in standard notes.

Right now, once you unlock the vault, the app keeps the vault unlocked for 15 minutes restricted to the session. Once app is killed, you have to unlock vault again. An unlocked vault is useful only when locking notes. To unlock notes user always has to enter password. In future we will make this configurable.

> When trying to unlock a vault note with biometrics it gives an option to use PIN.
But I don't recall setting a PIN? and I do not see anywhere in the settings anything about a PIN?

If for some reason, your fingerprint/biometrics are not working. You can enter you device pin code which you use to unlock your phone as a fallback.

The option to delete the vault will be available in the next release. Hopefully within a week.

Thank you for taking time to report this issue and sharing your thoughts with us. You can join our Discord and talk to us directly any time.
