### ISSUE TITLE
Can't purchase subscription

### ISSUE THREAD

**Issue by altano** [streetwriters/notesnook#40]
**Describe the bug**
I'm getting stuck at a black window when trying to create a subscription

**To Reproduce**
Settings -> Upgrade to Notesnook Pro -> Monthly -> PayPal

**Expected behavior**
Subscription is purchasable

**Screenshots**
![image](https://user-images.githubusercontent.com/1009/132113228-1ec150ac-ce18-494d-8ac2-3704ec59a8f6.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox 91.0.2 (64-bit
 - Version: Notesnook 1.5.4.0

**Additional context**
n/a

**Comment by thecodrr** [comment]
Taking a look right now. You can purchase from the Web version in the meantime.

**Comment by thecodrr** [comment]
Fixed. Will be there in the upcoming versions.

**Comment by altano** [comment]
I can confirm I was able to purchase from the Web version. Thanks.
