### ISSUE TITLE
Support for increasing and decreasing Font size using standard keyboard shortcuts

### ISSUE THREAD

**Issue by abhinav700** [streetwriters/notesnook#4019]
### What problem are you facing?

Right now We have to  click on increase and decrease font size multiple times to change font size

### What's the solution you'd like to see in Notesnook?

I want the app to have standard key bindings for changing the size.
ctrl + ] -> size increases by one pixel
ctrl + [ -> size decreases by one pixel

These key bindings are used in standard text editors like MS word and Libre Office

### Additional context

Platform: web (desktop)
OS: Ubuntu 22.0.4

**Comment by abhinav700** [comment]
Platform: web (desktop)
OS: Ubuntu 22.0.4

**Comment by Night3y3** [comment]
Hey i would like to work on it. Can you assign it to me
