### ISSUE TITLE
Show note title in the attachment manager

### ISSUE THREAD

**Issue by gaganyadav80** [streetwriters/notesnook#402]
**Is your feature request related to a problem? Please describe.**
I like the new attachment manager but it is hard to guess which attachment belongs to which note. For example, in the note manager I saw an attachment that I don't remember uploading and is not useful to me but now I cannot see where it is located so I could not remove it.

**Describe the solution you'd like**
Show note title or the notebook hierarchy (if note is in a notebook) under each attachment.

**Comment by ammarahm-ed** [comment]
In attachment properties, does it show the number of notes the attachment is added to? It should say "1 note" etc below the title

**Comment by gaganyadav80** [comment]
Yes it does shows that.

Another example,
Here in this screenshot. It says there is some error in the attachment. Now I can't figure out where these are located.

![Screenshot_20220312-172638.jpg](https://user-images.githubusercontent.com/47142137/158017068-fdef60e9-2935-4a44-92cb-31515e9000e8.jpg)
