### ISSUE TITLE
mobile: Add support to Android themed icons

### ISSUE THREAD

**Issue by lucasfnicolau** [streetwriters/notesnook#4026]
### What problem are you facing?

I would like to have support to Android themed adaptive icons.

### What's the solution you'd like to see in Notesnook?

Add support to this feature.

### Linked Pull Requests solving this issue
[Pull Request #4028](https://github.com/streetwriters/notesnook/pull/4028)
```[tasklist]
### Tasks
- [ ] https://github.com/streetwriters/notesnook/pull/4028
```

**Comment by ammarahm-ed** [comment]
Added in V3.
