### ISSUE TITLE
Table adjustments

### ISSUE THREAD

**Issue by MsJonesy** [streetwriters/notesnook#407]
Am I missing something when trying to adjust a table? 

If I adjust one column, it spaces the other to compensate for the original size. Playing with them px doesn’t seem to help much.

I really could do without a gigantic table when it’s only two or three columns.

**Comment by MsJonesy** [comment]
Is there any response to this?

**Comment by thecodrr** [comment]
Hi, there's currently no way to insert variable width tables. This will be possible in the new editor coming in April.

**Comment by MsJonesy** [comment]
Okay, this sounds interesting.Thank you for getting back to me with an update.

**Comment by thecodrr** [comment]
The new editor has been released. Marking this as resolved. Feel free to reopen if the issue is still there.
