### ISSUE TITLE
Include tags in exported notes

### ISSUE THREAD

**Issue by opennomad** [streetwriters/notesnook#4074]
### What problem are you facing?

When exporting a note, the tags associated with said note are not included.

### What's the solution you'd like to see in Notesnook?

It would be lovely if the tags were included in the export. Perhaps in the Markdown frontmatter?

### What alternatives have you considered?

I was considering using a backup and handparsing that to extract what I need. However, I was unable to find any documentation on working with the JSON blob inside the zip. 

### Additional context

This feels a bit related to #3160 as both issues are related to exporting additional context of a note.

**Comment by thecodrr** [comment]
This is already possible.

**Comment by thecodrr** [comment]
![image](https://github.com/streetwriters/notesnook/assets/7473959/15eadd11-5216-4b38-98a3-b93d6ab64574)
