### ISSUE TITLE
Too much line spacing when using return key

### ISSUE THREAD

**Issue by gaganyadav80** [streetwriters/notesnook#408]
**Describe the bug**
Pressing the return key produces large line spacing. This is same on both desktop and mobile.

**To Reproduce**
See screenshot below

**Expected behavior**
Line spacing should be normal as produced by the newline key in the toolbar and shift+return key on desktop.

**Screenshots**
![IMG_20220317_144627_343.png](https://user-images.githubusercontent.com/47142137/158778126-e16e4b60-7c33-4e52-abcd-b7f6050cdc5c.png)

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Brave
 - Version: latest

**Smartphone (please complete the following information):**
 - Device: Oneplus 7T
 - OS: A11
 - Version: latest

**Comment by Vonskie04** [comment]
Kinda bothers me too couz I want clean and tight format for the paragraph.

**Comment by gaganyadav80** [comment]
@thecodrr Hi, any update on when this will be resolved?

**Comment by thecodrr** [comment]
This issue is being addressed in #714
