### ISSUE TITLE
Failed to import images from Joplin JEX or MD file

### ISSUE THREAD

**Issue by m4t3u-Dls** [streetwriters/notesnook#4091]
### What happened?

Hi team,

I'm new on Notesnook, triying if it fits with my needs, so I'm not sure if it is an issue or not, but when importing a Joplin file (JEX or MD) images are skipped from imported content.

![image](https://github.com/streetwriters/notesnook/assets/115062872/f8440bcb-122c-46fe-a6de-fc771526a9ad)

Tried on following apps and both importing tools ended with same skipping resources notice:

> App version: 2.6.14-fbded93-desktop
> OS: Windows 10 64-bit
> Browser: Electron 25.9.8
> Pro: false
> 
> App version: 2.6.14-fbded93-web
> OS: Windows 10 64-bit
> Browser: Microsoft Edge 120.0.0.0
> Pro: false

PD. In addition I've tried to import in HTML format, no error reported but nothing imported either.

### Steps to reproduce the problem

1. Export from Joplin as JEX or MD file.
2. Import by using  Notesnook importer.
3. Loading to Notesnook by either using web or desktop app importer.

### Version

2.6.14

### Platform/OS

Windows, Chrome/Chromium

### Relevant log output

```shell
[7/1/2024, 11:56:37] Unpacking 1 file(s)...
[7/1/2024, 11:56:37] Unpacked into 14...
[7/1/2024, 11:56:37] Preprocessing complete...
[7/1/2024, 11:56:37] Skipping Error Copias Auxiliares Anuales 2023 y mensuales Diciembre 2023.jex...
[7/1/2024, 11:56:37] Processing 0c62e7ee875c49a3a5c451cf868a8231.md...
[7/1/2024, 11:56:37] Processing 12eaec5768c84dfbab29232fac4f45ba.md...
[7/1/2024, 11:56:37] Processing 1c9fb77945354281a7e96cbcbc31f0b5.md...
[7/1/2024, 11:56:37] Processing 2f9ad76b086c404ab2a719b5ea9a4bd3.md...
[7/1/2024, 11:56:37] Processing 45c4211250cc46ba998943f6ef4b6299.md...
[7/1/2024, 11:56:37] Processing a3eea62f4ddc46c19e8368920f0ae6e8.md...
[7/1/2024, 11:56:37] Processing deb5c900f02d4f898e57096d8311e0a2.md...
[7/1/2024, 11:56:37] Skipping resources/0c62e7ee875c49a3a5c451cf868a8231.png...
[7/1/2024, 11:56:37] Skipping resources/12eaec5768c84dfbab29232fac4f45ba.png...
[7/1/2024, 11:56:37] Skipping resources/2f9ad76b086c404ab2a719b5ea9a4bd3.png...
[7/1/2024, 11:56:37] Skipping resources/45c4211250cc46ba998943f6ef4b6299.png...
[7/1/2024, 11:56:37] Skipping resources/a3eea62f4ddc46c19e8368920f0ae6e8.png...
[7/1/2024, 11:56:37] Skipping resources/deb5c900f02d4f898e57096d8311e0a2.png...
```

**Comment by thecodrr** [comment]
@m4t3u-Dls this is not an issue. The resources are not imported independently. The importer skips all irrelevant files from the archive/zip/JEX you provide. However, if there's an image reference inside your notes that does get resolved. You can confirm this by opening the note and checking the attachment count.

**Comment by m4t3u-Dls** [comment]
Hi @thecodrr, thanks for your reply.

As you said, today I tried again and the note was imported as expected. Yesterday and some days before they were not. Can't figure why...

Joplin note

![image](https://github.com/streetwriters/notesnook/assets/115062872/4d7f6230-d95b-46ed-950f-5673699e2b21)


Notesnook note

![image](https://github.com/streetwriters/notesnook/assets/115062872/4f306b1c-80b4-419b-af84-8bb8491c8c71)


After this first import I made a new one, with a bigger note, and this time the error I was reporting in my first post appeared again.

Joplin note:

![image](https://github.com/streetwriters/notesnook/assets/115062872/bd49991f-0fe0-4711-b554-cf56af790646)


Notesnook note:

![image](https://github.com/streetwriters/notesnook/assets/115062872/7613c4b6-06f9-4167-89ed-3076cc198c4c)

As you can see a the clip icon inform the note has 6 attachements but the original Joplin note have 46 images attached, not 6 as you can check in the import log. I don't know if it can be due to an import limit (images quantity or quality, note size, etc...) or similar, may be it is not a issue either.

[Notesnook import.txt](https://github.com/streetwriters/notesnook/files/13864144/Notesnook.import.txt)

Also some of 6 images (2 at least) are not well presented, after past more than 5 minutes, althoug they're present in the note.

![image](https://github.com/streetwriters/notesnook/assets/115062872/0e6278a0-e2bc-44b7-a62b-2c004bf5365f)

In order to finish, I've had another issue. This is new from today, yesterday I didn't have it. I'll go with it, but if you prefer, I can open a new issue for them, just tell me and I will do it.

The issue is that it seems on web app I've lost the link between notes and notebooks, on web notebooks appears as 0 notes each, while in desktop app it is well shown, and it indicates correct number of notes for each notebook.

![image](https://github.com/streetwriters/notesnook/assets/115062872/e148d50e-7c1c-4b4f-8f3a-025974812f36)


Thanks for your support and patience!

**Comment by thecodrr** [comment]
> As you can see a the clip icon inform the note has 6 attachements but the original Joplin note have 46 images attached, not 6 as you can check in the import log. I don't know if it can be due to an import limit (images quantity or quality, note size, etc...) or similar, may be it is not a issue either.

No, that is definitely an issue. Is there some way you can send over that specific note from the JEX file? It seems the importer is having problems detecting & extracting images.

> The issue is that it seems on web app I've lost the link between notes and notebooks, on web notebooks appears as 0 notes each, while in desktop app it is well shown, and it indicates correct number of notes for each notebook.

Can you send me the debug logs from the web app?

**Comment by m4t3u-Dls** [comment]
Hi,

No problem, just tell me how can I get Debug logs from Web App I've been looking for them but I'm unable to see the option to get them... sorry. Also give me a private mail to send the JEX file.

Regards

**Comment by thecodrr** [comment]
You can send the JEX & the debug logs to support@streetwriters.co

Here's how to get the Debug logs:

1. Open app
2. Go to settings
3. Go to Help and support
4. Click on "Download logs" button under "Debug logs"

**Comment by m4t3u-Dls** [comment]
I'm sorry but I can't get debug logs...

When I try to collect them, the app hangs. After clicking "Download" button app becomes unresponsive (no crash), just bricked.

![image](https://github.com/streetwriters/notesnook/assets/115062872/a3b1be67-b020-4afa-aca4-d9a51da85a3d)

Past 10 minutes app continues totally bricked.

I've sent JEX file to you by e-mail (subject "Failed to import images from Joplin JEX or MD file #4091"). It is an anonymized version of original note I'was first trying to import, but it has the same images, just some text generalized.

**Comment by thecodrr** [comment]
@m4t3u-Dls 

Regarding this:

> The issue is that it seems on web app I've lost the link between notes and notebooks, on web notebooks appears as 0 notes each, while in desktop app it is well shown, and it indicates correct number of notes for each notebook.

I was able to reproduce and fix the issue. Just run the sync on your device and all the links will be restored. No need to do anything else.

**Comment by m4t3u-Dls** [comment]
Hi Abdullah,

Yes it is resolved, the associations have been restored al 100%. Thanks for your work.

Regards
________________________________
De: Abdullah Atta ***@***.***>
Enviado: lunes, 15 de enero de 2024 9:32
Para: streetwriters/notesnook ***@***.***>
Cc: m4t3u-Dls ***@***.***>; Mention ***@***.***>
Asunto: Re: [streetwriters/notesnook] Failed to import images from Joplin JEX or MD file (Issue #4091)


@m4t3u-Dls<https://github.com/m4t3u-Dls>

Regarding this:

The issue is that it seems on web app I've lost the link between notes and notebooks, on web notebooks appears as 0 notes each, while in desktop app it is well shown, and it indicates correct number of notes for each notebook.

I was able to reproduce and fix the issue. Just run the sync on your device and all the links will be restored. No need to do anything else.
