### ISSUE TITLE
[OneNote Importer] Images not imported

### ISSUE THREAD

**Issue by altano** [streetwriters/notesnook#41]
**Describe the bug**
When importing OneNote notes, images show up as broken image icons in Notesnook. Due to the size of the .nnbackup (~1.5MB) I'm certain the images were never included in the backup in the first place, so this is not an issue with restoring the notes, but rather the actual nnbackup creation.

**To Reproduce**
1. Have a OneNote note with inline images
1. Go to [Notesnook Importer](https://importer.notesnook.com/onenote) and perform OneNote import. Download .nnbackup file.
1. Go to Notesnook desktop and click Settings -> Backup & restore -> Restore backup -> Select .nnbackup

**Expected behavior**
Images present in Notesnook note

**Screenshots**
| OneNote | Notesnook |
|-----------|---------------|
| ![image](https://user-images.githubusercontent.com/1009/132158422-02e9aa06-8902-4107-98ba-30debfb06f24.png) | ![image](https://user-images.githubusercontent.com/1009/132158461-c7eb931f-4d82-41d7-a8ab-a3545e396350.png) | 

**Desktop (please complete the following information):**
 - OS: Windows 10 20H2
 - Browser: Firefox 91.0.2 (64-bit)
 - Notesnook version 1.5.4-3939941-desktop

**Additional context**
 - Notesnook Importer Beta v1.0.24

In my opinion, this is a **high** severity issue

**Comment by thecodrr** [comment]
Fixed in the new importer.

**Comment by altano** [comment]
Confirmed fixed in Importer v1.2.1. Thanks!
