### ISSUE TITLE
Allow easy rearranging of checklists

### ISSUE THREAD

**Issue by candroid-man** [streetwriters/notesnook#411]
**Feature Request**

To rearrange things in a list, currently you have to do it manually, copy one item, delete an item, replace it, enter the other thing. Big hassle for a simple task.

**Solution**

Add some sort of icon to the left of each list item, and use that to easily rearrange items in a list. Perhaps if you don't want those to be visible the entire time, you can make it to where if you press and hold/click and drag an item you can drag it where you want it. This is how Google Keep does it:

![tempFileForShare_20220318-190605](https://user-images.githubusercontent.com/51019003/159098611-0b20fd70-1899-4d1f-a213-f2bc5a2f52c0.jpg)

**Additional Comments**

I think I prefer the look of Google Keep lists, how the items are more spaced. Give it a shot, maybe? Also making the checkboxes bolder, currently they are very very thin.

**Comment by ammarahm-ed** [comment]
Better checklist items with more control are on the way. Probably next month as we will be migrating to Tiptap which is more extensible and powerful as compared to TinyMCE editor. The editor is going to get a lot better.

**Comment by Vonskie04** [comment]
Longing for this one. Can't rearrange the list of items in a notebook on the latest version. Hoping to be implemented this on later versions.

**Comment by thecodrr** [comment]
This has been fixed.
