### ISSUE TITLE
Feature Request: Remove title bar from Mac app

### ISSUE THREAD

**Issue by shawn-mitch** [streetwriters/notesnook#413]
Removing the title bar and having the traffic lights float over the sidebar would add a really nice coat of polish to an already great-looking app. It would give the impression that Notesnook is a native app instead of a webpage in an Electron wrapper.

Here are a couple of examples:

Standard Notes
![image](https://user-images.githubusercontent.com/5890308/159111836-fd2f2a30-31a3-49da-936b-a8cdec4526f7.png)

Craft
![image](https://user-images.githubusercontent.com/5890308/159111886-5bf3ad32-df94-44ff-8cbe-893a8de6c649.png)

According to the [Electron docs](https://www.electronjs.org/docs/latest/api/frameless-window#windows-control-overlay), this should™ be relatively easy. 

There is also likely an argument to do the same for Window, but I can't speak to that as I'm a Mac user.

**Comment by candroid-man** [comment]
It would also be cool to see this on Linux, adding this to #412
