### ISSUE TITLE
Android: Quick Settings Support

### ISSUE THREAD

**Issue by joewood9364** [streetwriters/notesnook#4174]
### What problem are you facing?

I am migrating from Microsoft To-do which integrates into Android quick settings allowing for note creation upon pressing its bespoke quick setting toggle within the notifications panel. Notesnook does not have this integration, instead opting for a persistent rich notification.

### What's the solution you'd like to see in Notesnook?

Implement note creation directly from Android quick settings.

### What alternatives have you considered?

The persistent notification to create notes is functional however it is poorer UX since it occupies notification space. The persistent notification is also subject to battery optimisation by Android so it may not be reliably present if for example the app is killed by the OS, whereas quick settings toggles are not.

**Comment by ammarahm-ed** [comment]
Hi, have you tried the Notesnook home screen widget?

**Comment by ammarahm-ed** [comment]
> @ammarahm-ed Give me your IBAN I will donate £10 if you implement this bhai.

So when a user taps on the quick settings tile it will show the same quick note widget as it is for home screen?

**Comment by ammarahm-ed** [comment]
Added in V3
