### ISSUE TITLE
Internxt cloud backup option

### ISSUE THREAD

**Issue by candroid-man** [streetwriters/notesnook#419]
**Feature Request**

[Internxt](https://internxt.com/) is a new open-source Dropbox alternative that has recently gained a bit of popularity do to [itsfoss's review](https://itsfoss.com/internxt-cloud-service/). This would be the ideal cloud storage service for people to use in tandem with Notesnook, as it is the most privacy respecting option (as far as I am aware), and is zero-knowledge much like Notesnook.

**Comment by thecodrr** [comment]
This would be hard to do unless they offer some kind of an API (I didn't see any mention of it on their website).
