### ISSUE TITLE
[OneNote Importer] Most notes not imported

### ISSUE THREAD

**Issue by altano** [streetwriters/notesnook#42]
**Describe the bug**
My imported notes are mostly missing. I have a lot of notes, but I think the majority are missing. There are entire sections/topics that have 0 notes (but the topics are present).

**To Reproduce**
1. Have a OneNote document with a lot of notes
1. Go to [Notesnook Importer](https://importer.notesnook.com/onenote) and perform OneNote import. Download .nnbackup file.
1. Go to Notesnook desktop and click Settings -> Backup & restore -> Restore backup -> Select .nnbackup

I don't see a common pattern to the missing notes so I'm not sure how exactly to reproduce the issue, but the above did it for me.

**Expected behavior**
I would expect all my notes to have made it to the resulting .nnbackup.

**Screenshots**
In OneNote you can see a ton of pages. In Notesnook, only 4 survived the import:
|   OneNote   |   Notesnook   |
|-------------|---------------|
| ![image](https://user-images.githubusercontent.com/1009/132159286-0138a0f0-a079-41e2-ac3b-afee0f84abfa.png) | ![image](https://user-images.githubusercontent.com/1009/132159057-eab4a358-3626-45ae-a487-4709eb2daf5e.png)| 

**Desktop (please complete the following information):**
 - OS: Windows 10 20H2
 - Browser: Firefox 91.0.2 (64-bit)
 - Notesnook version 1.5.4-3939941-desktop

**Additional context**
 - Notesnook Importer Beta v1.0.24

In my opinion, this is a **high** severity issue

**Comment by thecodrr** [comment]
Cannot be sure about this without testing but the new Importer is much more resilient to errors etc — if the API returns the data, it should have no issue importing it in one form or the other.

**Comment by altano** [comment]
Sounds good, I’m happy to test and report back. Is the new importer live?
