### ISSUE TITLE
Allow users to download images directly from the Attachments menu/right click menu of image

### ISSUE THREAD

**Issue by candroid-man** [streetwriters/notesnook#422]
**Feature Request**

I ran into this problem a few days ago. There was an image in a note that I needed on my phone, but I uploaded the image from my PC, and I was unable to download the image from the note, which was kind of frustrating.

**Comment by thecodrr** [comment]
This is already possible. What did you try?

**Comment by candroid-man** [comment]
Just a dumbass, my b
