### ISSUE TITLE
[Helpful tip] dark reader+midnight lizard if i use in website of notes then cpu ramps up and website consumes 800+mb ram+90% cpu utilization

### ISSUE THREAD

**Issue by HakaishinShwet** [streetwriters/notesnook#4257]
### What happened?

i know that website by default provides dark mode which is awesome but i use dark reader+midnight lizard addon to get best dark theme experience in max websites as many dont either support dark mode or there dark mode is not decent so its enabled by default for all websites but in this website i for the first time face this kind of issue where a single website was consuming soo much ram and processor and i understand that some form of security is implemented which is preventing website styling manipulation and these addons are forcing values and security is not letting them change style so its causing this issue and i tested many times with on/off of my both Addons and with just dark reader its doesnt happen so something with midnight lizard is cause anyways i am creating this issue for other users like me who use these midnight addon please disable for this website as whole else you wont be able to use website at all and your system will slowdown 

### Steps to reproduce the problem

just use hardened firefox with midnight lizard addon and set any styling and boom :-))

### Version

latest

### Platform/OS

Linux

**Comment by thecodrr** [comment]
This is an issue with Dark Reader or Midnight Lizard – not Notesnook.
