### ISSUE TITLE
Unable to download images from Attachments menu on Desktop

### ISSUE THREAD

**Issue by candroid-man** [streetwriters/notesnook#426]
**Feature Request**

Sorry, @thecodrr I am all over the place today haha. You are unable to download images from a note on desktop. Clicking on the image in Attachments simply shows all attachments you have ever made.

![image](https://user-images.githubusercontent.com/51019003/159205782-a3e7fbcf-e7ed-4900-a662-f052081228da.png)
After clicking the attachment:
![image](https://user-images.githubusercontent.com/51019003/159205886-a50cda4f-ec03-4c4c-950e-bde4d71bfa5f.png)

**Comment by thecodrr** [comment]
Try right clicking on an attachment. It should open a context menu from where you can easily download the image.

**Comment by candroid-man** [comment]
Found it! Don't know if I'm just stupid, but that took me a long time to figure out, consider adding a simple download button to the side? Or perhaps a dropdown menu

**Comment by thecodrr** [comment]
> Found it! Don't know if I'm just stupid, but that took me a long time to figure out, consider adding a simple download button to the side? Or perhaps a dropdown menu

Haha on desktop, things are more desktop like. So for options there's always a context menu instead of a button and it opens by right click.
