### ISSUE TITLE
Cannot exit quote blocks by pressing Enter twice

### ISSUE THREAD

**Issue by thecodrr** [streetwriters/notesnook#4274]
### What happened?

It's not possible to exit out of a quote block by pressing Enter twice. In fact, only 1 Enter works and after that nothing happens no matter how many times you press Enter.

### Steps to reproduce the problem

1. Create a quote block
2. Enter some text
3. Press Enter
4. Press Enter again
5. Notice how it did not create a new line

### Version

v2.6.15

### Platform/OS

Android, Chrome/Chromium, Firefox

**Comment by alihamuh** [comment]
in node_modules/@tiptap/core/dist/index.js

```js
const liftEmptyBlock = () => ({ state, dispatch, editor }) => {
    return liftEmptyBlock$1(state, (tr) => {
        if (!dispatch) return true;

        const { selection, storedMarks } = state;
        const marks = storedMarks || (selection.$to.parentOffset && selection.$from.marks());

        if (!marks) return dispatch(tr);
        
        const { splittableMarks } = editor.extensionManager;
        const filteredMarks = marks.filter((mark) =>
            splittableMarks.includes(mark.type.name)
        );
        tr.ensureMarks(filteredMarks)

        return dispatch(tr);
    });
};
```
