### ISSUE TITLE
Text after markdown link in a checkbox becomes part of the link text

### ISSUE THREAD

**Issue by glindstedt** [streetwriters/notesnook#4304]
### What happened?

When writing a markdown link in a checkbox block the "link context" doesn't properly close with the ending parenthesis and it continues to consider the rest of the text as part of the link text. There's no way to navigate out of it by moving the cursor so I'm guessing the markdown is swallowed and replaced by some other internal state.

[notesnook_bug.webm](https://github.com/streetwriters/notesnook/assets/1015224/466e18c0-e445-486e-965a-49d7d266ddd7)

### Steps to reproduce the problem

Write a link in a checkbox using markdown syntax and try to write some text after it on the same line

### Version

2.6.15-aa730b5-web

### Platform/OS

Linux, Firefox

**Comment by sahibjotsaggu** [comment]
In Version 2.6.2 (240), I'm noticing this exact same thing happening everywhere (inside bulleted lists and in general). See attached video.

https://github.com/streetwriters/notesnook/assets/8991960/ca475328-1202-44f0-a00c-ed9a006e00d1

**Comment by thecodrr** [comment]
@sahibjotsaggu that's a very old version. The latest version is 2.6.16.

**Comment by thecodrr** [comment]
Fixed
