### ISSUE TITLE
Not possible to add content between 2 lists with Enter button

### ISSUE THREAD

**Issue by nickelaos** [streetwriters/notesnook#4306]
### What happened?

I cannot add a new list between the 2 already existing lists with the Enter button.

### Steps to reproduce the problem

1. Add 2 lists with checkboxes
2. Remove space between them
3. Go to the last item of the 1st list and press Enter
4. Press Enter again

Actual result: new checkboxes (list items) created.
Expected result: after the second click, the empty list item disappears and it is possible to add the content outside the list.

![image](https://github.com/streetwriters/notesnook/assets/21063721/18ff397c-9f1c-4580-854c-b8afda829be6)

### Version

2.6.15

### Platform/OS

Windows, Chrome/Chromium

**Comment by thecodrr** [comment]
Related to #4274
