### ISSUE TITLE
Unable to swipe left to exit once I am in the editor mobile

### ISSUE THREAD

**Issue by candroid-man** [streetwriters/notesnook#431]
**Describe the bug**

When you are in the notes page you are able to swipe right and get to an empty note, but you cannot swipe back to all of rest of your notes

**To Reproduce**

1. Go into Notes menu
2. Swipe left
3. Try to swipe back to the right

**Comment by thecodrr** [comment]
This is not a bug but an intentional user experience improvement. The main issue with 2 way swiping is that it affects the vertical scrolling in the editor causing accidental swipes.

**Comment by candroid-man** [comment]
From my experience, there is no way to accidentally swipe right in the editor (may be different for other users), but if you accidentally swipe left (which is very easy to do) while scrolling through notes you have to press the back button every time

**Comment by thecodrr** [comment]
> there is no way to accidentally swipe right in the editor

It is actually very easy (and annoying since the editor keeps jumping back and forth) for people who make the gestures/scrolling with their right hand. The opposite is true for people who prefer their left hand I suppose.
