### ISSUE TITLE
Disable swiping left/right in settings

### ISSUE THREAD

**Issue by candroid-man** [streetwriters/notesnook#433]
**Feature Request**

When you scroll through settings on mobile it is very easy to swipe left or right accidentally, I think personally it would be best to disable swiping in the settings menu, and rather than having a hamburger icon in the top-left corner, use a back arrow. If you are in settings, you don't need super easy access to your notes like that since you are making configurations/troubleshooting

**Comment by ammarahm-ed** [comment]
I agree. Makes sense! I will fix this in the next release

**Comment by thecodrr** [comment]
This has been fixed in v2.1.
