### ISSUE TITLE
Remove the swipe left for new note feature on mobile

### ISSUE THREAD

**Issue by candroid-man** [streetwriters/notesnook#437]
**Feature Request**

I would normally think this was a nice feature, but the problem with it is that when you are browsing through your Notes it is too easy to swipe either left or right. Swipe right makes sense because you obviously want quick access to the side menu to navigate around the app, but the plus button in the bottom-right corner (for Android anyway) does the same thing as swiping left. I have found this recently to be very frustrating.

**Comment by thecodrr** [comment]
This has also been fixed as #433. The swipe logic should now be much more resilient to accidental swipes.
