### ISSUE TITLE
Unable to sync on iOS

### ISSUE THREAD

**Issue by edhans** [streetwriters/notesnook#4370]
Sync fails. Copied logs:

@/private/var/containers/Bundle/Application/8C07408E-C13D-4842-857B-57518E863A6C/Notesnook.app/main.jsbundle:1:4102319
s@/private/var/containers/Bundle/Application/8C07408E-C13D-4842-857B-57518E863A6C/Notesnook.app/main.jsbundle:1:4093249
@/private/var/containers/Bundle/Application/8C07408E-C13D-4842-857B-57518E863A6C/Notesnook.app/main.jsbundle:1:5223785
@/private/var/containers/Bundle/Application/8C07408E-C13D-4842-857B-57518E863A6C/Notesnook.app/main.jsbundle:1:5223812
@/private/var/containers/Bundle/Application/8C07408E-C13D-4842-857B-57518E863A6C/Notesnook.app/main.jsbundle:1:2278521
v@/private/var/containers/Bundle/Application/8C07408E-C13D-4842-857B-57518E863A6C/Notesnook.app/main.jsbundle:1:2277270
y@/private/var/containers/Bundle/Application/8C07408E-C13D-4842-857B-57518E863A6C/Notesnook.app/main.jsbundle:1:2277665
callReactNativeMicrotasks@/private/var/containers/Bundle/Application/8C07408E-C13D-4842-857B-57518E863A6C/Notesnook.app/main.jsbundle:1:2279908
value@/private/var/containers/Bundle/Application/8C07408E-C13D-4842-857B-57518E863A6C/Notesnook.app/main.jsbundle:1:2120054
@/private/var/containers/Bundle/Application/8C07408E-C13D-4842-857B-57518E863A6C/Notesnook.app/main.jsbundle:1:2118156
value@/private/var/containers/Bundle/Application/8C07408E-C13D-4842-857B-57518E863A6C/Notesnook.app/main.jsbundle:1:2119702
value@/private/var/containers/Bundle/Application/8C07408E-C13D-4842-857B-57518E863A6C/Notesnook.app/main.jsbundle:1:2118114

**Comment by ammarahm-ed** [comment]
Hi @edhans are you still facing this issue?

**Comment by edhans** [comment]
No. it cleared up after a few hours.
