### ISSUE TITLE
Can’t sign up/create account - iOS app or web app

### ISSUE THREAD

**Issue by don-ferris** [streetwriters/notesnook#4371]
### What happened?

I tried to sign up in the app. At first I got “Could not create an account. Error code: 500”. Whatever that means. A more detailed error message would be nice. I typically use 24 character random passwords (generated by BitWarden). I thought maybe if I tried a shorter password… nope. Sometimes signup forms will throw an error if you paste the password twice - but sometimes, if you delete the last character of the “confirm password” then type it manually, that will circumvent the error… and it did — sort of. The error changed to “invalid email address”. I have my own domain with wildcard forwarding so I always use [website/app/service]@myowndomain.com but some sites flag the use of their domain name within an email address so I replaced “notesnook@“ with [random]@… same “invalid email address” error. Next thought maybe they only accept well-known email addresses so I tried using my gmail account. Same error.

### Steps to reproduce the problem

I don’t know if you can reproduce this or not. Try creating an account for donnybahama@gmail.com. If you’re successful, please email me the password. I’ll login and change it.

### Version

Whatever is current as of today

### Platform/OS

iOS

**Comment by TiniestCupcake** [comment]
Same results with my own email accounts, where I first got error 500 then nothing but invalid email address.

**Comment by BledItIt** [comment]
same results trying to sign-up... where I first got error 500 then nothing but invalid email address...

**Comment by thecodrr** [comment]
This has been fixed.

**Comment by TiniestCupcake** [comment]
Tried again, no more 500 error but I'm still getting invalid email address.

**Comment by don-ferris** [comment]
Nope. Not fixed. I still can't create an account. I tried with an @ddress from one of my personal domains and got "invalid email address". Then I tried a gmail @ddress and after clicking submit, it just took me right back to the same page.

> This has been fixed.

**Comment by thecodrr** [comment]
For anyone else reading this later and still getting the `Invalid email address` error, please reach out to us at support@streetwriters.co so we can fix it for you.

**Comment by jordanmontt** [comment]
Hello, I am having the same issue

> Could not create a new account. Error code: 500

I have no VPN and I am using a secure password. I used both Firefox and Chrome and the issue persists
