### ISSUE TITLE
Allow Notes to be divided up in 16:9 sections to allow printing and creation of PDFs

### ISSUE THREAD

**Issue by candroid-man** [streetwriters/notesnook#438]
**Feature Request**

1. Add the ability to switch between endless and printable Notes (inspired by Cryptee)
2. Add the ability to print Notes

With the powerful editor Notesnook has, people could easily use Notesnook to create documents. Adding this feature could open up Notesnook to many more possibilities.

**Comment by thecodrr** [comment]
Printing notes is now possible in the latest versions.
