### ISSUE TITLE
Sync to Beta Android 3.07 not working

### ISSUE THREAD

**Issue by mkoechli** [streetwriters/notesnook#4398]
### What happened?

I did a fresh install on my android device (Pixel 7) and was able to sync a note created on Android to my desktop installation (newest Beta 3). A sync "down" to my android device is not working. All i get is an error message

Sync failed
[react-native-quick-sqlite]
SQL execution error: table notes has no column named locked

regards
Marcel

### Steps to reproduce the problem

Create a note on Notesnook Desktop, try to sync on Android device > note is not synched instead get an error

Create a note on Notesnook Android. Note will be synced to Desktop

### Version

latest beta on al devices

### Platform/OS

Windows, Android

**Comment by thecodrr** [comment]
What's the exact app version on all your devices?

**Comment by mkoechli** [comment]
I did an update to the lastest beta 3.0 version before testing.

Android: 3.0.7
Windows: 3.0.6-2d546b6-desktop-beta

**Comment by mkoechli** [comment]
Additional test on mac book air, version: 3.0.6-2d546b6-desktop-beta

I get a similar error message like on my android device:
SqliteError: table notes has no column named locked

**Comment by thecodrr** [comment]
Got it, next beta version will fix this.
