### ISSUE TITLE
[OneNote Importer] Multiple page parts not imported

### ISSUE THREAD

**Issue by altano** [streetwriters/notesnook#44]
A page can have multiple areas in the canvas. I'll call them "parts" since I don't know the actual term. OneNote sometimes creates these automatically, but you can create them by clicking in the empty area of the page. They will get small bars at the top to allow them to be moved around.

**Describe the bug**
When a page has multiple page parts, only the first one is imported. The rest are gone. 

**To Reproduce**
1. Have a OneNote note with multiple page parts
1. Go to [Notesnook Importer](https://importer.notesnook.com/onenote) and perform OneNote import. Download .nnbackup file.
1. Go to Notesnook desktop and click Settings -> Backup & restore -> Restore backup -> Select .nnbackup

**Expected behavior**
All page parts are present and visible.

**Screenshots**
Example of how to create these page parts:
https://user-images.githubusercontent.com/1009/132159664-8d459171-49e9-44c0-bd73-a55df3c3ebf1.mp4

Bug repro:
|   OneNote   |   Notesnook   |
|-------------|---------------|
| ![image](https://user-images.githubusercontent.com/1009/132159705-d93ee757-2645-4848-85a2-94ec2f15eb0c.png) | ![image](https://user-images.githubusercontent.com/1009/132159743-e3225fd8-eafd-4700-b436-257b182e583f.png) | 

**Desktop (please complete the following information):**
 - OS: Windows 10 20H2
 - Browser: Firefox 91.0.2 (64-bit)
 - Notesnook version 1.5.4-3939941-desktop

**Additional context**
 - Notesnook Importer Beta v1.0.24

In my opinion, this is a **high** severity issue

**Comment by thecodrr** [comment]
Alright. As part of #296, I am currently adding support for OneNote in the new importer.

This is not possible. Notesnook notes do not support absolutely positioned content — everything flows down. The of course means a loss of context.

Is there some way we can preserve this context without absolutely positioning things?

**Comment by altano** [comment]
Oh, to be clear, I don’t care about the layout. Just the lost, not imported content.

If the importer grabbed both parts and just made one come right after the other I would be happy.

**Comment by altano** [comment]
Can still reproduce in Importer v1.2.1

**Comment by altano** [comment]
EDIT: False alarm, ignore the previous comment. I just tested with the latest import zip and this is 100% fixed. Sorry about the noise.
