### ISSUE TITLE
Unable to disable word wrap on image pasted from mobile

### ISSUE THREAD

**Issue by candroid-man** [streetwriters/notesnook#441]
**Describe the bug**

I pasted an image from mobile, and word wrap seems to be enabled somehow (even though I'm 90% sure that isn't a feature in Notesnook).

![image](https://user-images.githubusercontent.com/51019003/159839236-be0ff1c6-dbf0-4ce9-b2c8-ed77653c66ce.png)

**Desktop:**
 - OS: Arch
 - Version: 1.8.3

**Smartphone:**
 - Device: Samsung Galaxy S10+
 - OS: Android 12
 - Version: 1.8.4

**Comment by candroid-man** [comment]
Just to clarify a few things:

1. The image provided is a note on desktop, that has a screenshot of the mobile version because it happened to be the image I was having issues with, the bars on the right are showing the amount of Enter's I did to get to the bottom
2. I figured out it was only when the image was shrunk, if this is intentional, it needs to be optional

**Comment by thecodrr** [comment]
By default images were in float mode i.e. text would flow around them. This has been fixed in the new editor so I am closing this.
