### ISSUE TITLE
Some FAQs are not updated and/or contradicting updated sections on notesnook website.

### ISSUE THREAD

**Issue by gaganyadav80** [streetwriters/notesnook#442]
| Not Updated (Under Pricing FAQs) | Contradicting |
| --- | --- |
| <img width="952" alt="Screenshot 2022-03-24 at 11 14 08" src="https://user-images.githubusercontent.com/47142137/159851239-c2a98142-379b-4989-9ed7-a0ee1a630a37.png"> | Home Page: <img width="530" alt="Screenshot 2022-03-24 at 11 13 57" src="https://user-images.githubusercontent.com/47142137/159851246-794874a6-f4f8-4a9c-8ec7-bd4da3557be9.png"> |
| <img width="955" alt="Screenshot 2022-03-24 at 11 15 12" src="https://user-images.githubusercontent.com/47142137/159851502-c4c966a3-482b-4f46-be17-22d7e3853900.png"> | Pricing Page: <img width="1122" alt="Screenshot 2022-03-24 at 11 15 24" src="https://user-images.githubusercontent.com/47142137/159851546-f24521f4-ff24-4b17-8b68-db52f78c5cf4.png"> |

EDIT: In the comparison table with different notes app. Evernote DO HAVE built-in app lock.

**Comment by thecodrr** [comment]
I don't see anything contradictory about those 2.

1. Yes, completely free services make money selling users' data (e.g. Google). Notesnook is not a free service. We _have_ a free plan which is supported by the Pro plan i.e., we don't make money off of selling users' data but only when users' decide to pay for the Pro plan.
2. At this moment, we do not have a proper Student Plan so the statement is correct. I suppose we can put the same thing in the FAQ as in the banner above.

I'll update the comparison table.

**Comment by thecodrr** [comment]
Both issues have been fixed.
