### ISSUE TITLE
Icon in Linux

### ISSUE THREAD

**Issue by Johndjk** [streetwriters/notesnook#4426]
### What problem are you facing?

It's difficult to find the app when it's in the background, especially with other apps that don't have the icon either.
Please implement it.
It's essential!

![2024-03-09 13-46-07](https://github.com/streetwriters/notesnook/assets/154085819/4cdbfd3f-6d4b-4776-a5d3-ae0b33ba3cd2)

### What's the solution you'd like to see in Notesnook?

Add icon in Linux

### Additional context

Debian 12

**Comment by ammarahm-ed** [comment]
If you restart the app, this issue should be fixed.
