### ISSUE TITLE
Obsidian import - weird formatting

### ISSUE THREAD

**Issue by Taffer** [streetwriters/notesnook#4427]
### What happened?

Using the importer to convert some Obsidian "to-do" notes results in some weird formatting for pages of to-do items.

### Steps to reproduce the problem

I've got a page listing stuff I was going to install on my laptop when I reinstalled Linux; it's Markdown like this:

```md
# Linux Software

## Portable

- [ ] 1Password
- [ ] balenaEtcher
- [ ] Calibre
- [ ] digiKam
- [ ] Discord
```

The list with `[ ]` prefixes is a to-do list, it gets rendered as a checkbox; when you click it changes to `[x]` which is a selected checkbox.

This comes into Notesnook with an extra, empty to-do list item, and the actual to-do list items are indented below the empty one (see comment below for screen shot).

### Version

2.6.14-fbded93-desktop

### Platform/OS

Linux

**Comment by Taffer** [comment]
Hmm, that doesn't seem to have pulled in my screen shot, let's try again:

![Screenshot_20240309_143257](https://github.com/streetwriters/notesnook/assets/1213088/583994be-0ab8-45d7-b939-dcdf2444f17d)

**Comment by Nagidrop** [comment]
This problem isn't exclusive to Obsidian import. I imported from Standard Notes and it has similar issue. Possibly all other Markdown imports pose same issues as that's how Notesnook internally convert the square brackets `[ ]`. You could try creating a new note and type `[ ]` to see how it converts to 2 checkboxes: first empty check box (seems like a "progress bar") and an indented checkbox below.

**Comment by thecodrr** [comment]
This is a non-issue. That's how Task lists are rendered in Notesnook. That empty checkbox at the top isn't a task item, it is used for checking/unchecking all task below.
