### ISSUE TITLE
Obsidian import - Import into Notebook or Tag

### ISSUE THREAD

**Issue by Taffer** [streetwriters/notesnook#4429]
### What problem are you facing?

I imported almost 400 notes from Obsidian via the note importer in several steps organized into folders in Obsidian.

### What's the solution you'd like to see in Notesnook?

I'd like that organization to be duplicated in Notesnook, or I'd like to designate a Notebook/Tag as the "target" for an import operation.

With the incoming nested notebooks feature, an Obsidian import could map the directories directly into a set of nested notebooks.

### What alternatives have you considered?

After importing each subset of notes, I'd go through the increasing list of notes to add the new ones to the Notebook they belonged in.

### Additional context

*No response*

**Comment by alechudson** [comment]
Were you ever able to get the notes to import properly? I am running into the same issue.

**Comment by thecodrr** [comment]
This has been fixed in v2.4.0 of the Importer.
