### ISSUE TITLE
Flatpak still on 2.6.14

### ISSUE THREAD

**Issue by ccampbell9** [streetwriters/notesnook#4451]
### What happened?

Hello, the Notesnook flatpak is still on version 2.6.14 and has not been updated in almost two months. 

I am under the impression the flatpak is an official release but if that is not the case- I will be happy to close this issue and move it to the manifest github page. 

### Steps to reproduce the problem

Download/install the Notesnook flatpak from flathub.

### Version

2.6.14

### Platform/OS

Linux

**Comment by thecodrr** [comment]
Done.
