### ISSUE TITLE
Unable to move Topics to different Notebooks

### ISSUE THREAD

**Issue by candroid-man** [streetwriters/notesnook#446]
**Feature Request**

Allow users to move Topics to different Notebooks easily.

**Comment by thecodrr** [comment]
Can you clarify what you mean?

**Comment by candroid-man** [comment]
Currently you are unable to move entire Topics to different Notebooks, so if you wanted to move everything from one Notebook to another, you would have to create a new Topic in thr new Notebook, then manually move the individual notes over rather than just right clicking the original Topic and moving it
