### ISSUE TITLE
Deleting a Note in the Monographs menu doesn't remove the Note from the list until you refresh

### ISSUE THREAD

**Issue by candroid-man** [streetwriters/notesnook#449]
**Describe the bug**

Deleting a Note in the Monographs menu doesn't remove the Note from the list until you refresh by clicking off Monographs and clicking back into it.

**To Reproduce**

1. Go to Monographs
2. Unpublish a published Note
3. Delete the Note while still in Monographs

**Desktop:**
 - OS: Arch
 - Version: 1.8.4

**Comment by thecodrr** [comment]
Fixed.
