### ISSUE TITLE
[OneNote Importer] Checkmarks/TODOs not imported

### ISSUE THREAD

**Issue by altano** [streetwriters/notesnook#45]
In OneNote you can create a TODO/checkbox by pressing ctrl+1. Pressing it twice marks the item as complete (checks the checkbox).

**Describe the bug**
Imported notes lose TODOs/checkboxes.

**To Reproduce**
1. Have a OneNote note with a TODO list
1. Have Notesnook free edition
1. Go to [Notesnook Importer](https://importer.notesnook.com/onenote) and perform OneNote import. Download .nnbackup file.
1. Go to Notesnook desktop and click Settings -> Backup & restore -> Restore backup -> Select .nnbackup
1. Upgrade to Notesnook Pro

I don't know if this would work if I had Notesnook Pro during the import, but there shouldn't be data loss in the import when upgrading to Pro, so it's definitely a bug either way.

**Expected behavior**
The TODOs should be converted to a Notesnook checklist:
![image](https://user-images.githubusercontent.com/1009/132160779-52c63c8d-ee66-482f-bb55-e1f4510404e7.png)

**Screenshots**
|   OneNote   |   Notesnook   |
|-------------|---------------|
| ![image](https://user-images.githubusercontent.com/1009/132160269-b72ffd7b-aeae-406f-afcd-241d77b1705a.png) | ![image](https://user-images.githubusercontent.com/1009/132160286-de3ddfd8-3491-44bc-806f-05c56d057b9e.png) | 

**Desktop (please complete the following information):**
 - OS: Windows 10 20H2
 - Browser: Firefox 91.0.2 (64-bit)
 - Notesnook version 1.5.4-3939941-desktop

**Additional context**
 - Notesnook Importer Beta v1.0.24

In my opinion, this is a **medium** severity issue

**Comment by thecodrr** [comment]
The new importer fixes this.

**Comment by altano** [comment]
Can still reproduce in Importer v1.2.1

**Comment by thecodrr** [comment]
@altano did you actually import into Notesnook or are you using the preview function? The preview function in Importer doesn't have a lot of features (it's just a preview).

**Comment by altano** [comment]
Oh, you know what, I did something even dumber: I used the old nnbackup import file. I just tested with the latest import zip and this is 100% fixed. Sorry about the noise.
