### ISSUE TITLE
2.6.17 BUGged update - huge disappointment.

### ISSUE THREAD

**Issue by begin-theadventure** [streetwriters/notesnook#4506]
I updated the app through F-Droid 2.6.17 3/13/24, opened it and a pop-up blocked me from accessing my notes!
It said something about migration and prompted me to log in or re-login - I'm not sure as I logged in only once because it was required to have an account for backups (edit: still is for backup encryption).

Alright, I  logged in and then "Migration failed"
<img src="https://github.com/streetwriters/notesnook/assets/99835765/d92957b2-d70e-47a1-bff8-dccd86a5bda9" width="20%"> (the background is black due to the "Privacy mode")
"You must download a backup of your data before migrating."
How if the app was blocked with pop-ups.
Then there was the logs button, which was bugged because "Copy logs" did not work, but IIRC it showed a cut of this: "TypeError: Cannot read properties of undefined (reading 'hash')" (that pop-up didn't show on a screenshot).

I  really wanted to get back in my notes. I searched a bit on Github; thought about upgrading, but well it's F-Droid so I'd have to wait a long time for the next update, and well instead of reporting my issue I logged in to the web version.

There were no notes - which was understandable as I turned off the sync options - I created it only for a local backup when it was required.

In desperation, I stupidly logged out of devices despite the warning, and here I am with all my notes removed forever! 

I wonder why F-Droid doesn't have any changelogs and why there was no big warning advising to backup before upgrading.

Perhaps F-Droid should also be discouraged because of its sluggish updates and different apk signature.

Maybe warn and advise a backup in changelogs if something was done with sync and backups.

Two warnings instead of one, and a password re-prompt for logging out of all devices?

**Comment by thecodrr** [comment]
Fixed in v2.6.17 (web/desktop) and v2.6.18 (ios/android).
