### ISSUE TITLE
F-Droid can't build

### ISSUE THREAD

**Issue by licaon-kter** [streetwriters/notesnook#4515]
ref: https://monitor.f-droid.org/builds/log/com.streetwriters.notesnook/10451#site-footer

/LE: fyi https://gitlab.com/fdroid/fdroiddata/-/commit/31d64b29ed485ffac109407ce055f92e5ff9468d

**Comment by ammarahm-ed** [comment]
@licaon-kter Fixed it I think: https://gitlab.com/fdroid/fdroiddata/-/merge_requests/14733

**Comment by Frederick888** [comment]
May I know if this is why F-Droid users are stuck on 3.0.11? The MR says it fixes 2.6.18 build, what about newer betas?

**Comment by licaon-kter** [comment]
@Frederick888 The still open and not merged MR says: _"FAILED"_ ( https://gitlab.com/fdroid/fdroiddata/-/jobs/6469759394#L933 ) 

F-Droid is setup to NOT pickup RC/Alpha/Beta, but only stable releases.

**Comment by Frederick888** [comment]
> F-Droid is setup to NOT pickup RC/Alpha/Beta, but only stable releases.

@licaon-kter What did you mean? 3.0.11 is listed on F-Droid and I got the update normally. I did not enable 'Allow Beta Updates' either.

![Screenshot_20240412-092911~2](https://github.com/streetwriters/notesnook/assets/4507647/1a407943-fb7d-4c60-b8fb-440477c0d551)

**Comment by licaon-kter** [comment]
Hmm, indeed, I looked at the MR that modifies the check.

Will need to test locally

**Comment by licaon-kter** [comment]
https://gitlab.com/fdroid/fdroiddata/-/merge_requests/14733 is still in limbo

but 3.0.0 came https://gitlab.com/fdroid/fdroiddata/-/commit/4528389c10cb6c014caa13c1302e539bcef1f20c

failed oddly in the CI: https://gitlab.com/fdroid/fdroiddata/-/jobs/6736851981#L3788

so I tried locally too
```
> Task :ammarahmed_react-native-share-extension:compileReleaseKotlin FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':ammarahmed_react-native-share-extension:compileReleaseKotlin'.
> 'compileReleaseJavaWithJavac' task (current target is 11) and 'compileReleaseKotlin' task (current target is 17) jvm target compatibility should be set to the same Java version.
  Consider using JVM toolchain: https://kotl.in/gradle/jvm/toolchain
```

umm, so the app needs Java 17 but `:ammarahmed_react-native-share-extension:` needs 11?

**Comment by ammarahm-ed** [comment]
Fixed. Thanks everyone.
