### ISSUE TITLE
OneNote Importer

### ISSUE THREAD

**Issue by altano** [streetwriters/notesnook#454]
**Describe the bug**
I attempted to use the OneNote importer and got redirected to localhost:3000

**To Reproduce**
1. Go to https://importer.notesnook.com/
2. Click on Provider dropdown, select OneNote
3. In popop, consent to permissions request by clicking "Accept"
5. Popop navigates from consent screen to error (can't load localhost:3000)

The URL loaded looks like this:
`localhost:3000/#code=<redacted>&client_info=<redacted>&state=<redacted>&session_state=<redacted>`

**Screenshots**
Popup after accepting permissions request:
![image](https://user-images.githubusercontent.com/1009/160264727-4f26c93c-06c2-45b4-b327-4939ecac9d03.png)

**Desktop (please complete the following information):**
App: Importer v1.2.0
Browser: Firefox v98.0.2

**Comment by thecodrr** [comment]
Can you try again now?

**Comment by altano** [comment]
Looks fixed. Thanks!

**Comment by thecodrr** [comment]
Let me know how it goes. It should work much better but there might be bugs.

**Comment by altano** [comment]
I hit one so far: https://github.com/streetwriters/notesnook/issues/455
