### ISSUE TITLE
Space between heading: zoho

### ISSUE THREAD

**Issue by alihamuh** [streetwriters/notesnook#4545]
### What problem are you facing?

The spacing between the headings and the subsequent text (paragraphs). I believe reducing this spacing slightly would enhance readability.

Currently, there appears to be consistent spacing both before and after headings, which could be adjusted for improved visual flow.

### What's the solution you'd like to see in Notesnook?

---

### What alternatives have you considered?

--

**Comment by Duagolth** [comment]
Hello,

I can understand the purpose of this ticket, but the applied reduction is potentially too great.

As the screenshot shows, without double spaced lines, the text of a title can overlap the paragraph below it. Underlining when selecting a word also overlaps.

![Not_doubled_spaced](https://github.com/user-attachments/assets/6d5bce7a-ac1f-4e3d-b57c-faa6563154f6)

My phone is an OnePlus Nord CE 5G, with Notesnook 3.0.18.

Have a nice day :)
