### ISSUE TITLE
No subscription!!!

### ISSUE THREAD

**Issue by sfwnisme** [streetwriters/notesnook#4557]
I subscribed for a single month using google Play Store giftcard and the amount cutted, but I  it gives me this message on google play "open the app to confirm." I opened the app, but still no subscription activated 

![Screenshot_20240326_143158_Google Play Store.jpg](https://github.com/streetwriters/notesnook/assets/92028514/65550028-1723-4b17-a9a8-20cdf35e053b)

**Comment by thecodrr** [comment]
Hey, please reach out to us via email at support@streetwriters.co so we can help you resolve this issue.
