### ISSUE TITLE
Ability to toggle Markdown editing on mobile (suggested by 'a duck#5984')

### ISSUE THREAD

**Issue by candroid-man** [streetwriters/notesnook#456]
**Feature Request**

Grant the ability to toggle Markdown editing on mobile.

Suggested by `a duck#5984` on [Discord](https://discord.com/channels/796015620436787241/796063880677163109/956437178387431434).

**Additional Context**

I am starting to find suggestions on Discord and creating GitHub issues about them to try to keep everything in one place. This means I may or may not actually agree with the suggestion, just helping to organize all the suggestions you are getting for the app. If this is of no use to you, or you would rather me not do this, let me know.

**Comment by thecodrr** [comment]
Thank you for the help! You are awesome. 😁
