### ISSUE TITLE
2FA disable security (suggested by GC#3530)

### ISSUE THREAD

**Issue by candroid-man** [streetwriters/notesnook#457]
**Feature Request**

> Before disabling it (or managing the 2FA settings), one should have to go through it instead of just entering the password. Otherwise, somebody with access to one's account could disable 2FA without effort.

Suggested by GC#3530 on [Discord](https://discord.com/channels/796015620436787241/796063880677163109/956601164793778196).

**Personal Opinion**

I agree with it. It is just an overall security upgrade just in case something happens. As GC#3530 mentioned, Discord does this, and I think Notesnook should as well.

**Comment by thecodrr** [comment]
I agree as well. 😎

**Comment by ammarahm-ed** [comment]
2FA is enabled by default for all users and cannot be disabled anymore. Closing this.
