### ISSUE TITLE
click copy/paste does not retain formatting in desktop app

### ISSUE THREAD

**Issue by alihamuh** [streetwriters/notesnook#4578]
### What happened?

When I right click to copy and paste text from a note to another note, the formatting is not retained. 

### Steps to reproduce the problem

Copy text of a note
Paste it using right click menu
formatting is not copied.

### Version

2.6.17-c54759e76-desktop

### Platform/OS

Linux

**Comment by ammarahm-ed** [comment]
This has been fixed.
