### ISSUE TITLE
Improved Printing

### ISSUE THREAD

**Issue by candroid-man** [streetwriters/notesnook#458]
**Feature Request**

> Could the print functionality be improved? I can export my note to pdf,html,markdown ect but all those exports remove my checkmarks and turn them into bullets. Ctr+P on the web attempts to print just the view i'm looking at with all the left side navigation and ignores the bulk of the note and cuts the note off at the bottom. I love the checkmark functionality but am unable to print a note with it other than to screenshot and then print the screenshot.

Suggested by greg09#1554 on [Discord](https://discord.com/channels/796015620436787241/796063880677163109/956933558340046869).

**Personal Opinion**

I am for it. I think if Notesnook keeps up with development, you could actually create a Google Docs/Microsoft Word alternative, and this is just one step towards that. Plus, there are plenty of reasons why you would want to print a Note, and this should be available on every platform.

**Comment by thecodrr** [comment]
Note exports will get a refresh next month with much better suport for things like checklists.

**Comment by thecodrr** [comment]
This is now complete.
