### ISSUE TITLE
[OneNote Importer] Heading 1 not imported as Heading 1

### ISSUE THREAD

**Issue by altano** [streetwriters/notesnook#46]
**Describe the bug**
Heading 1 styled text is imported as normal paragraphs, but then styled to look correct, while Heading 2 elements are correctly and semantically imported as Heading 2.

**To Reproduce**
1. Have a OneNote note with a Heading 1 and a Heading 2
1. Go to [Notesnook Importer](https://importer.notesnook.com/onenote) and perform OneNote import. Download .nnbackup file.
1. Go to Notesnook desktop and click Settings -> Backup & restore -> Restore backup -> Select .nnbackup

**Expected behavior**
All headings and semantically styled elements that are supported in Markdown maintain their semantic styling

**Screenshots**
|   OneNote   |   Notesnook   |
|-------------|---------------|
| ![image](https://user-images.githubusercontent.com/1009/132161005-d9e1a742-96f8-444d-8233-af6a0638f308.png) | ![image](https://user-images.githubusercontent.com/1009/132161066-c2186290-fbb6-4fa5-8670-71a2e7249bf1.png) | 

**Desktop (please complete the following information):**
 - OS: Windows 10 20H2
 - Browser: Firefox 91.0.2 (64-bit)
 - Notesnook version 1.5.4-3939941-desktop

**Additional context**
 - Notesnook Importer Beta v1.0.24

In my opinion, this is a **medium** or **low** severity issue

**Comment by thecodrr** [comment]
Duplicate or connected to #224

**Comment by altano** [comment]
Confirmed fixed in Importer v1.2.1
