### ISSUE TITLE
Encrypt backups by default, plaintext backups should be opt-in

### ISSUE THREAD

**Issue by TheMatjaz** [streetwriters/notesnook#464]
Hi everyone. Loving the app so far! 😄 Got premium ASAP and migrated everything here. Keep up the good work! I have a simple security recommendation for your.

> TL;DR backups should always be encrypted by default. If I want them in plaintext, I should have to do disable the encryption manually on each logged instance separately (setting does not sync).

Considering that privacy is the main marketed feature of Notesnook and that E2EE is used to secure the data when transferred to the servers, it seems a bit counter-intuitive that the **local backups are unencrypted by default** and the encryption is opt-in, thus must be enabled manually. The docs [also indicate](https://docs.notesnook.com/backup-and-restore-notes-in-notesnook/#encrypted-backups) it's opt-in.

I believe it should be the other way around. It is a security risk to leave the content of our notes exposed in plaintext on the storage drives of our computer/phone, where any other application can read them easily.

On a more practical level as of now, I have to _remember_ to activate backup encryption _manually_ every time I log in into a new device and do this fast enough before the first backup happens - which is annoying. This is what I see when I logout and login into the web app or native app:

![image](https://user-images.githubusercontent.com/5064956/160904857-c5b5bd87-7f34-4770-b0aa-10e3ea370382.png)

So, I suggest the backups should be:

- **encrypted by default** when logging into the app on any platform/browser,
- decrypted backups happen _only_ when the user specifically flips the switch above to deactivate them and that _setting does not sync_. In other words, if I disable backup encryption on device A, devices B and C should _still encrypt_ them unless I manually go disabling it on B and C as well.

**Comment by thecodrr** [comment]
Done.
