### ISSUE TITLE
[OneNote Importer] Imported edit dates are not correct

### ISSUE THREAD

**Issue by altano** [streetwriters/notesnook#47]
**Describe the bug**
The default Notes view is to sort by Recent (date edited, descending). When importing notes the sort order looks totally chaotic and definitely not based on edit times. I have items I haven't touched in years at the top, whether I sort by ascending or descending.

For starters: when sorting by "Date Created", order=ascending goes from oldest to newest. When sorting by "Date Edited", order=ascending goes from newest to oldest.

For example, when sorting by "Date Edited" and order=descending, the top 3 notes in Notesnook have last edit dates (in OneNote) of:
1. 2021/05/19 
2. 2020/03/01
3. 2021/05/06

**To Reproduce**
1. Have a OneNote note with a ton of notes with very variable edit times.
1. Go to [Notesnook Importer](https://importer.notesnook.com/onenote) and perform OneNote import. Download .nnbackup file.
1. Go to Notesnook desktop and click Settings -> Backup & restore -> Restore backup -> Select .nnbackup

**Expected behavior**
1. Sorting by "Last edited" would accurately reflect the edit times from OneNote
2. The date listed below the note will be the EDIT date when sorting by edit, and CREATE date when sorting by create. Otherwise it is just confusing?

**Screenshots**
![image](https://user-images.githubusercontent.com/1009/132162136-2dcf5f72-424b-42e9-b027-744156d2d59b.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 20H2
 - Browser: Firefox 91.0.2 (64-bit)
 - Notesnook version 1.5.4-3939941-desktop

**Additional context**
 - Notesnook Importer Beta v1.0.24

In my opinion, this is a **medium** severity issue

**Comment by thecodrr** [comment]
The new importer should fix this.
