### ISSUE TITLE
Failing on npm i

### ISSUE THREAD

**Issue by aliwaqar981** [streetwriters/notesnook#4769]
### What happened?

I'm trying to run the code as suggested in the repo but failing on npm i

### Steps to reproduce the problem

Clone the repo and try npm i
Note: My node version is 18.17.1. I also have tried on node 16 and 20.

### Version

Latest

### Platform/OS

React Native (iOS/ANDROID)

### Relevant log output

```shell
ListrError: Something went wrong
    at /Users/mapmac/ReactProjects/NativeProjects/notesnook/node_modules/listr/index.js:102:18
    at async bootstrapPackages (file:///Users/mapmac/ReactProjects/NativeProjects/notesnook/scripts/bootstrap.mjs:105:3)
    at async file:///Users/mapmac/ReactProjects/NativeProjects/notesnook/scripts/bootstrap.mjs:82:3 {
  errors: [
    Error: Command failed: npm rebuild esbuild
    npm ERR! code 1
    npm ERR! path /Users/mapmac/ReactProjects/NativeProjects/notesnook/packages/core/node_modules/esbuild
    npm ERR! command failed
    npm ERR! command sh -c node install.js
    npm ERR! node:internal/errors:496
    npm ERR!     ErrorCaptureStackTrace(err);
    npm ERR!     ^
    npm ERR! 
    npm ERR! <ref *1> Error: spawnSync /Users/mapmac/ReactProjects/NativeProjects/notesnook/packages/core/node_modules/esbuild/bin/esbuild Unknown system error -88
    npm ERR!     at Object.spawnSync (node:internal/child_process:1110:20)
    npm ERR!     at spawnSync (node:child_process:871:24)
    npm ERR!     at Object.execFileSync (node:child_process:914:15)
    npm ERR!     at validateBinaryVersion (/Users/mapmac/ReactProjects/NativeProjects/notesnook/packages/core/node_modules/esbuild/install.js:99:28)
    npm ERR!     at /Users/mapmac/ReactProjects/NativeProjects/notesnook/packages/core/node_modules/esbuild/install.js:286:5 {
    npm ERR!   errno: -88,
    npm ERR!   code: 'Unknown system error -88',
    npm ERR!   syscall: 'spawnSync /Users/mapmac/ReactProjects/NativeProjects/notesnook/packages/core/node_modules/esbuild/bin/esbuild',
    npm ERR!   path: '/Users/mapmac/ReactProjects/NativeProjects/notesnook/packages/core/node_modules/esbuild/bin/esbuild',
    npm ERR!   spawnargs: [ '--version' ],
    npm ERR!   error: [Circular *1],
    npm ERR!   status: null,
    npm ERR!   signal: null,
    npm ERR!   output: null,
    npm ERR!   pid: 0,
    npm ERR!   stdout: null,
    npm ERR!   stderr: null
    npm ERR! }
    npm ERR! 
    npm ERR! Node.js v18.17.1
    
    npm ERR! A complete log of this run can be found in: /Users/mapmac/.npm/_logs/2024-04-21T15_06_15_132Z-debug-0.log
    
        at ChildProcess.exithandler (node:child_process:419:12)
        at ChildProcess.emit (node:events:514:28)
        at maybeClose (node:internal/child_process:1091:16)
        at Socket.<anonymous> (node:internal/child_process:449:11)
        at Socket.emit (node:events:514:28)
        at Pipe.<anonymous> (node:net:323:12) {
      code: 1,
      killed: false,
      signal: null,
      cmd: 'npm rebuild esbuild'
    },
    Error: Command failed: npm i --legacy-peer-deps --no-audit --no-fund --prefer-offline --progress=false --ignore-scripts
    npm ERR! code ETARGET
    npm ERR! notarget No matching version found for acorn-walk@8.3.2.
    npm ERR! notarget In most cases you or one of your dependencies are requesting
    npm ERR! notarget a package version that doesn't exist.
    
    npm ERR! A complete log of this run can be found in: /Users/mapmac/.npm/_logs/2024-04-21T15_06_15_760Z-debug-0.log
    
        at ChildProcess.exithandler (node:child_process:419:12)
        at ChildProcess.emit (node:events:514:28)
        at maybeClose (node:internal/child_process:1091:16)
        at Socket.<anonymous> (node:internal/child_process:449:11)
        at Socket.emit (node:events:514:28)
        at Pipe.<anonymous> (node:net:323:12) {
      code: 1,
      killed: false,
      signal: null,
      cmd: 'npm i --legacy-peer-deps --no-audit --no-fund --prefer-offline --progress=false --ignore-scripts'
    },
    Error: Command failed: npm rebuild esbuild ljharb-monorepo-symlink-test
    npm ERR! code 1
    npm ERR! path /Users/mapmac/ReactProjects/NativeProjects/notesnook/packages/core/node_modules/esbuild
    npm ERR! command failed
    npm ERR! command sh -c node install.js
    npm ERR! node:internal/errors:496
    npm ERR!     ErrorCaptureStackTrace(err);
    npm ERR!     ^
    npm ERR! 
    npm ERR! <ref *1> Error: spawnSync /Users/mapmac/ReactProjects/NativeProjects/notesnook/packages/core/node_modules/esbuild/bin/esbuild Unknown system error -88
    npm ERR!     at Object.spawnSync (node:internal/child_process:1110:20)
    npm ERR!     at spawnSync (node:child_process:871:24)
    npm ERR!     at Object.execFileSync (node:child_process:914:15)
    npm ERR!     at validateBinaryVersion (/Users/mapmac/ReactProjects/NativeProjects/notesnook/packages/core/node_modules/esbuild/install.js:99:28)
    npm ERR!     at /Users/mapmac/ReactProjects/NativeProjects/notesnook/packages/core/node_modules/esbuild/install.js:286:5 {
    npm ERR!   errno: -88,
    npm ERR!   code: 'Unknown system error -88',
    npm ERR!   syscall: 'spawnSync /Users/mapmac/ReactProjects/NativeProjects/notesnook/packages/core/node_modules/esbuild/bin/esbuild',
    npm ERR!   path: '/Users/mapmac/ReactProjects/NativeProjects/notesnook/packages/core/node_modules/esbuild/bin/esbuild',
    npm ERR!   spawnargs: [ '--version' ],
    npm ERR!   error: [Circular *1],
    npm ERR!   status: null,
    npm ERR!   signal: null,
    npm ERR!   output: null,
    npm ERR!   pid: 0,
    npm ERR!   stdout: null,
    npm ERR!   stderr: null
    npm ERR! }
    npm ERR! 
    npm ERR! Node.js v18.17.1
    
    npm ERR! A complete log of this run can be found in: /Users/mapmac/.npm/_logs/2024-04-21T15_06_17_330Z-debug-0.log
    
        at ChildProcess.exithandler (node:child_process:419:12)
        at ChildProcess.emit (node:events:514:28)
        at maybeClose (node:internal/child_process:1091:16)
        at ChildProcess._handle.onexit (node:internal/child_process:302:5) {
      code: 1,
      killed: false,
      signal: null,
      cmd: 'npm rebuild esbuild ljharb-monorepo-symlink-test'
    },
    Error: Command failed: npm i --legacy-peer-deps --no-audit --no-fund --prefer-offline --progress=false --ignore-scripts
    npm WARN EBADENGINE Unsupported engine {
    npm WARN EBADENGINE   package: '@standardnotes/auth@3.19.4',
    npm WARN EBADENGINE   required: { node: '>=14.0.0 <17.0.0' },
    npm WARN EBADENGINE   current: { node: 'v18.17.1', npm: '9.6.7' }
    npm WARN EBADENGINE }
    npm WARN EBADENGINE Unsupported engine {
    npm WARN EBADENGINE   package: '@standardnotes/features@1.58.0',
    npm WARN EBADENGINE   required: { node: '>=16.0.0 <17.0.0' },
    npm WARN EBADENGINE   current: { node: 'v18.17.1', npm: '9.6.7' }
    npm WARN EBADENGINE }
    npm WARN EBADENGINE Unsupported engine {
    npm WARN EBADENGINE   package: '@standardnotes/models@1.42.0',
    npm WARN EBADENGINE   required: { node: '>=16.0.0 <17.0.0' },
    npm WARN EBADENGINE   current: { node: 'v18.17.1', npm: '9.6.7' }
    npm WARN EBADENGINE }
    npm ERR! code ENOTEMPTY
    npm ERR! syscall rename
    npm ERR! path /Users/mapmac/ReactProjects/NativeProjects/notesnook/apps/web/node_modules/pdfjs-dist
    npm ERR! dest /Users/mapmac/ReactProjects/NativeProjects/notesnook/apps/web/node_modules/.pdfjs-dist-mfkWtPxJ
    npm ERR! errno -66
    npm ERR! ENOTEMPTY: directory not empty, rename '/Users/mapmac/ReactProjects/NativeProjects/notesnook/apps/web/node_modules/pdfjs-dist' -> '/Users/mapmac/ReactProjects/NativeProjects/notesnook/apps/web/node_modules/.pdfjs-dist-mfkWtPxJ'
    
    npm ERR! A complete log of this run can be found in: /Users/mapmac/.npm/_logs/2024-04-21T15_06_15_758Z-debug-0.log
    
        at ChildProcess.exithandler (node:child_process:419:12)
        at ChildProcess.emit (node:events:514:28)
        at maybeClose (node:internal/child_process:1091:16)
        at Socket.<anonymous> (node:internal/child_process:449:11)
        at Socket.emit (node:events:514:28)
        at Pipe.<anonymous> (node:net:323:12) {
      code: 190,
      killed: false,
      signal: null,
      cmd: 'npm i --legacy-peer-deps --no-audit --no-fund --prefer-offline --progress=false --ignore-scripts'
    },
    Error: Command failed: npm rebuild esbuild @swc/core monorepo-symlink-test
    npm ERR! code 1
    npm ERR! path /Users/mapmac/ReactProjects/NativeProjects/notesnook/packages/core/node_modules/esbuild
    npm ERR! command failed
    npm ERR! command sh -c node install.js
    npm ERR! node:internal/errors:496
    npm ERR!     ErrorCaptureStackTrace(err);
    npm ERR!     ^
    npm ERR! 
    npm ERR! <ref *1> Error: spawnSync /Users/mapmac/ReactProjects/NativeProjects/notesnook/packages/core/node_modules/esbuild/bin/esbuild Unknown system error -88
    npm ERR!     at Object.spawnSync (node:internal/child_process:1110:20)
    npm ERR!     at spawnSync (node:child_process:871:24)
    npm ERR!     at Object.execFileSync (node:child_process:914:15)
    npm ERR!     at validateBinaryVersion (/Users/mapmac/ReactProjects/NativeProjects/notesnook/packages/core/node_modules/esbuild/install.js:99:28)
    npm ERR!     at /Users/mapmac/ReactProjects/NativeProjects/notesnook/packages/core/node_modules/esbuild/install.js:286:5 {
    npm ERR!   errno: -88,
    npm ERR!   code: 'Unknown system error -88',
    npm ERR!   syscall: 'spawnSync /Users/mapmac/ReactProjects/NativeProjects/notesnook/packages/core/node_modules/esbuild/bin/esbuild',
    npm ERR!   path: '/Users/mapmac/ReactProjects/NativeProjects/notesnook/packages/core/node_modules/esbuild/bin/esbuild',
    npm ERR!   spawnargs: [ '--version' ],
    npm ERR!   error: [Circular *1],
    npm ERR!   status: null,
    npm ERR!   signal: null,
    npm ERR!   output: null,
    npm ERR!   pid: 0,
    npm ERR!   stdout: null,
    npm ERR!   stderr: null
    npm ERR! }
    npm ERR! 
    npm ERR! Node.js v18.17.1
    
    npm ERR! A complete log of this run can be found in: /Users/mapmac/.npm/_logs/2024-04-21T15_06_22_225Z-debug-0.log
    
        at ChildProcess.exithandler (node:child_process:419:12)
        at ChildProcess.emit (node:events:514:28)
        at maybeClose (node:internal/child_process:1091:16)
        at Socket.<anonymous> (node:internal/child_process:449:11)
        at Socket.emit (node:events:514:28)
        at Pipe.<anonymous> (node:net:323:12) {
      code: 1,
      killed: false,
      signal: null,
      cmd: 'npm rebuild esbuild @swc/core monorepo-symlink-test'
    }
  ],
  context: [Object: null prototype] {}
}

Node.js v18.17.1
npm ERR! code 1
npm ERR! path /Users/mapmac/ReactProjects/NativeProjects/notesnook
npm ERR! command failed
npm ERR! command sh -c husky install && npm run bootstrap

npm ERR! A complete log of this run can be found in: /Users/mapmac/.npm/_logs/2024-04-21T15_05_41_315Z-debug-0.log
```

**Comment by thecodrr** [comment]
You must use node 20. Then run:

```
npm run clean
npm i
```

**Comment by aliwaqar981** [comment]
I've tried on 20.12 but still some dependencies are complaining. Sharing some logs below:

`ListrError: Something went wrong
    at /Users/mapmac/ReactProjects/NativeProjects/notesnook/node_modules/listr/index.js:102:18
    at async bootstrapPackages (file:///Users/mapmac/ReactProjects/NativeProjects/notesnook/scripts/bootstrap.mjs:105:3)
    at async file:///Users/mapmac/ReactProjects/NativeProjects/notesnook/scripts/bootstrap.mjs:82:3 {
  errors: [
    Error: Command failed: npm i --legacy-peer-deps --no-audit --no-fund --prefer-offline --progress=false --ignore-scripts
    npm ERR! code ETARGET
    npm ERR! notarget No matching version found for acorn-walk@8.3.2.
    npm ERR! notarget In most cases you or one of your dependencies are requesting
    npm ERR! notarget a package version that doesn't exist.
    
    npm ERR! A complete log of this run can be found in: /Users/mapmac/.npm/_logs/2024-04-21T15_44_33_853Z-debug-0.log
    
        at genericNodeError (node:internal/errors:984:15)
        at wrappedFn (node:internal/errors:538:14)
        at ChildProcess.exithandler (node:child_process:422:12)
        at ChildProcess.emit (node:events:518:28)
        at maybeClose (node:internal/child_process:1105:16)
        at Socket.<anonymous> (node:internal/child_process:457:11)
        at Socket.emit (node:events:518:28)
        at Pipe.<anonymous> (node:net:337:12) {
      code: 1,
      killed: false,
      signal: null,
      cmd: 'npm i --legacy-peer-deps --no-audit --no-fund --prefer-offline --progress=false --ignore-scripts'
    },
    Error: Command failed: npm i --legacy-peer-deps --no-audit --no-fund --prefer-offline --progress=false --ignore-scripts
    npm WARN EBADENGINE Unsupported engine {
    npm WARN EBADENGINE   package: '@standardnotes/auth@3.19.4',
    npm WARN EBADENGINE   required: { node: '>=14.0.0 <17.0.0' },
    npm WARN EBADENGINE   current: { node: 'v20.12.2', npm: '10.5.0' }
    npm WARN EBADENGINE }
    npm WARN EBADENGINE Unsupported engine {
    npm WARN EBADENGINE   package: '@standardnotes/features@1.58.0',
    npm WARN EBADENGINE   required: { node: '>=16.0.0 <17.0.0' },
    npm WARN EBADENGINE   current: { node: 'v20.12.2', npm: '10.5.0' }
    npm WARN EBADENGINE }
    npm WARN EBADENGINE Unsupported engine {
    npm WARN EBADENGINE   package: '@standardnotes/models@1.42.0',
    npm WARN EBADENGINE   required: { node: '>=16.0.0 <17.0.0' },
    npm WARN EBADENGINE   current: { node: 'v20.12.2', npm: '10.5.0' }
    npm WARN EBADENGINE }
    npm ERR! code ETARGET
    npm ERR! notarget No matching version found for acorn-walk@8.3.0.
    npm ERR! notarget In most cases you or one of your dependencies are requesting
    npm ERR! notarget a package version that doesn't exist.
    
    npm ERR! A complete log of this run can be found in: /Users/mapmac/.npm/_logs/2024-04-21T15_44_54_770Z-debug-0.log
    
        at genericNodeError (node:internal/errors:984:15)
        at wrappedFn (node:internal/errors:538:14)
        at ChildProcess.exithandler (node:child_process:422:12)
        at ChildProcess.emit (node:events:518:28)
        at maybeClose (node:internal/child_process:1105:16)
        at ChildProcess._handle.onexit (node:internal/child_process:305:5) {
      code: 1,
      killed: false,
      signal: null,
      cmd: 'npm i --legacy-peer-deps --no-audit --no-fund --prefer-offline --progress=false --ignore-scripts'
    }
  ],
  context: [Object: null prototype] {}
}

Node.js v20.12.2
npm ERR! code 1
npm ERR! path /Users/mapmac/ReactProjects/NativeProjects/notesnook
npm ERR! command failed
npm ERR! command sh -c husky install && npm run bootstrap

npm ERR! A complete log of this run can be found in: /Users/mapmac/.npm/_logs/2024-04-21T15_44_18_454Z-debug-0.log`

**Comment by aliwaqar981** [comment]
@thecodrr any help would be appreciated, thanks

**Comment by thecodrr** [comment]
@aliwaqar981 try pulling the latest changes in the master branch and trying again.

**Comment by aliwaqar981** [comment]
@thecodrr thanks for the response. I have tried taking fresh pull but still not luck. Although this time error seems bit more explaining. Sharing logs below:

`npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@standardnotes/auth@3.19.4',
npm WARN EBADENGINE   required: { node: '>=14.0.0 <17.0.0' },
npm WARN EBADENGINE   current: { node: 'v20.12.2', npm: '10.5.0' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@standardnotes/features@1.58.0',
npm WARN EBADENGINE   required: { node: '>=16.0.0 <17.0.0' },
npm WARN EBADENGINE   current: { node: 'v20.12.2', npm: '10.5.0' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@standardnotes/models@1.42.0',
npm WARN EBADENGINE   required: { node: '>=16.0.0 <17.0.0' },
npm WARN EBADENGINE   current: { node: 'v20.12.2', npm: '10.5.0' }
npm WARN EBADENGINE }

**ERROR** Failed to apply patch for package react-native-vector-icons at path
  
    node_modules/react-native-vector-icons

  This error was caused because patch-package cannot apply the following patch file:

    patches/react-native-vector-icons+9.2.0.patch

  Try removing node_modules and trying again. If that doesn't work, maybe there was
  an accidental change made to the patch file? Try recreating it by manually
  editing the appropriate files and running:
  
    patch-package react-native-vector-icons
  
  If that doesn't work, then it's a bug in patch-package, so please submit a bug
  report. Thanks!

    https://github.com/ds300/patch-package/issues
    

---
patch-package finished with 1 error(s).
Took: 17.462s

up to date, audited 790 packages in 19s

158 packages are looking for funding
  run `npm fund` for details

5 vulnerabilities (4 moderate, 1 critical)

To address all issues, run:
  npm audit fix

Run `npm audit` for details.`

**Comment by thecodrr** [comment]
Actually, it worked. You can safely ignore that error.

**Comment by thecodrr** [comment]
You aren't using a version manager for node. Running npm as sudo is _not_ recommended. Use [volta](https://volta.sh) or something to avoid this in the future.
