### ISSUE TITLE
[OneNote Importer] Handle sub-page importing better

### ISSUE THREAD

**Issue by altano** [streetwriters/notesnook#48]
**Is your feature request related to a problem? Please describe.**
I have imported notes from OneNote. The original notes have sub-pages, which is a basic page hierarchy that lets me nest some pages below others. This hierarchy is totally lost when importing into Notesnook because (a) we don't carry over the parent/child relationship and (b) the notes are no longer sorted in the same order they were in OneNote.

**Describe the solution you'd like**
I'm not exactly sure, but I want the hierarchy to not get lost. I'm happy to tweak the notes in Notesnook once they are there, but I want the hierarchy information to be conveyed in SOME way.

Let's say you have a OneNote page titled "Parent" and a sub-page titled "Child", here are some ideas:
* Instead of creating a Notesnook note with the title of "Child" make it "Parent -> Child"
* When creating "Child" tag it with "Parent"
* Allow creating a nested topic with the same name as the parent (“Parent”) and put “Child” under that. Might mean having a “Parent” note and “Parent” topic

**Describe alternatives you've considered**
n/a

**Additional context**
|   OneNote   |   Notesnook   |
|-------------|---------------|
| ![image](https://user-images.githubusercontent.com/1009/132162591-d09942df-800b-49c8-bfde-9ff861259ef7.png) | ![image](https://user-images.githubusercontent.com/1009/132162645-973e4165-7ab1-4a6e-91d3-8988fd1b4398.png) |

**Comment by thecodrr** [comment]
The API doesn't return this information so I cannot do much.

**Comment by altano** [comment]
This looks fixed in Importer v1.2.1. thanks!
