### ISSUE TITLE
windows 10 与 android 之间无法同步

### ISSUE THREAD

**Issue by mdsqeh** [streetwriters/notesnook#4815]
### What happened?

2.6.17-ad99c87-desktop
windows 10 与 android14 之间无法同步

### Steps to reproduce the problem

windows 10 与 android14 之间无法同步

### Version

2.6.17-ad99c87-desktop，android v3.0.17

### Platform/OS

Windows, Android

**Comment by ammarahm-ed** [comment]
Kindly update to v3.
