### ISSUE TITLE
UI error on notebook deletion

### ISSUE THREAD

**Issue by ecureuill** [streetwriters/notesnook#4840]
### What happened?

After I deleted a notebook with 1 empty note, I couldn't access any other feature of Notesnook.  

![Captura de Tela 2024-04-29 às 07 23 24](https://github.com/streetwriters/notesnook/assets/993369/7acbad98-6611-4c5d-a5a2-23813e546c3d)

I tried to close the software and reopen it, but not work.
Then, from SO dock, I tried to use the options "New note", "New notebook" and "New reminder". They also didn't solve the problem. 

![Captura de tela 29 04 2024 às 07 24 37 AM](https://github.com/streetwriters/notesnook/assets/993369/fdc020e5-188e-4c30-baa7-086c11cdf37d)

After some attempt of close/reopen the software, it finally open with full interface.

### Steps to reproduce the problem

1. Create a Notebook
1. Write a note 
1. From the notebook's context menu, move it to trash 

### Version

2.6.17-ad99c87-desktop

### Platform/OS

macOS

**Comment by thecodrr** [comment]
@ecureuill please update to v3 - this should be fixed there.
