### ISSUE TITLE
3.0 web app - Stuck on database backup

### ISSUE THREAD

**Issue by shift18** [streetwriters/notesnook#4890]
### What happened?

WEB app gets stuck backing up.
After clearing browser data and loging in i get constant errors. (see below)
![Notesnook 3 0 error](https://github.com/streetwriters/notesnook/assets/37035227/85dc75ef-f5a7-4cd9-9d16-8cb696d24e5c)

### Steps to reproduce the problem

1. I'm on the webapp and i know there's an update so i refresh my browser
2. App wants to backup database but get stuck
![Notesnook 3 0](https://github.com/streetwriters/notesnook/assets/37035227/19544cf7-65df-4d48-a6ba-2f53df3b1f47)

3. I refresh the browser but it makes no difference
4. I clear browser site storage and cache
5. I can now log in.

### Version

3.0.0-583d585-web

### Platform/OS

Windows, Firefox

### Relevant log output

```shell
see above, no upload functionality here
```

**Comment by shift18** [comment]
So i just want to mention that the last updates (I'm on 3.0.5 now) haven't helped, the error still appears
I'm using the Desktop/Windows version now and it does occur hear as well, but not on android it seems.

**Comment by shift18** [comment]
This is not fixed, the constant error messages still appear in desktop and web app

**Comment by thecodrr** [comment]
@shift18 the fix hasn't been released.

**Comment by shift18** [comment]
@thecodrr
I'm on 3.0.18 now, the fix did the trick.

Applied it on three different machines running both windows and Ubuntu and the issue appears completely gone.
Good work!
