### ISSUE TITLE
Misc feedback

### ISSUE THREAD

**Issue by altano** [streetwriters/notesnook#49]
Here is some feedback I couldn't be bothered to separate out into separate issues. Feel free to break it up. Sorry :(

# Search
- [x] Note search doesn't display topic which is very relevant context:

|   OneNote   |   Notesnook   |
|-------------|---------------|
| ![image](https://user-images.githubusercontent.com/1009/132164186-6a475290-cfc3-4b96-8348-9e64b4e411d2.png) | ![image](https://user-images.githubusercontent.com/1009/132164072-b084963f-cedc-480a-8737-f2c96bc7ffee.png) | 
- [x] A note titled "2016" is nowhere near the top of the search results. Title match should be much higher in the results than content match.
- [ ] Search seems to only be "or", which is to say adding terms produces more results instead of helping me narrow things down. Making it an "or" search on all the searched tokens is fine, but MULTIPLE matches should be ranked higher.
- [ ] I can't search topics/notebook names
- [ ] When navigating to notes in the search, I'm still in the search. I can't search for a note, get to the notebook, and then see other notes in the same notebook.
- [x] I'd like a keyboard shortcut for search, e.g. make ctrl+e go to search on Windows

# Editor
- [x] Selecting text and clicking "checklist" erases text and puts a checkbox. Should turn each line into an item in the checklist instead.

# Sorting
- [x] Sort Order: should be "oldest" or "newest", not "ascending" or "descending". The latter doesn't mean anything to people not familiar with timestamps :p

**Comment by thecodrr** [comment]
> Sort Order: should be "oldest" or "newest", not "ascending" or "descending". The latter doesn't mean anything to people not familiar with timestamps :p

This is a good suggestion. However, we also have alphabetical ordering so it won't work in that case.

**Comment by thecodrr** [comment]
> I'd like a keyboard shortcut for search, e.g. make ctrl+e go to search on Windows

Ctrl + F should work everywhere.

**Comment by thecodrr** [comment]
Search is going to be overhauled soon so hang tight.

**Comment by altano** [comment]
> > I'd like a keyboard shortcut for search, e.g. make ctrl+e go to search on Windows
> 
> Ctrl + F should work everywhere.

Oh neat, thanks. Might be good to add a "Keyboard Shortcuts" section to docs (I'm not seeing one currently, apologies if it's there)

**Comment by thecodrr** [comment]
Most of these issues have been fixed. Other search related issues can be tracked here #145
