### ISSUE TITLE
version history blank screen

### ISSUE THREAD

**Issue by sharemind** [streetwriters/notesnook#490]
**Describe the bug**
if you click on a previews session of the version history in the desktop or in the web app you receive a blank screen and need to restart the app.

It works fine on android app.

**To Reproduce**
1. open a note in the desktop or in the web app 
2. edit the note
3. open version history
4. select a previews session

**Comment by thecodrr** [comment]
Fixing this ASAP.

**Comment by thecodrr** [comment]
@sharemind which version of the app are you on?

**Comment by sharemind** [comment]
Android app 1.8.7

**Comment by thecodrr** [comment]
The desktop app version i mean. Where you are having this issue.

**Comment by sharemind** [comment]
Desktop app 1.8.6

**Comment by thecodrr** [comment]
Fixed in #524
