### ISSUE TITLE
Read-only toggle on Desktop Version is not working

### ISSUE THREAD

**Issue by ecureuill** [streetwriters/notesnook#4904]
### What happened?

After update to v3, I can't disable read-only using the properties toggle. 

https://github.com/streetwriters/notesnook/assets/993369/c6568ded-d7d6-470b-8a76-c01cb088ae5f

It's possible to enable/disable readonly using the context menu option.

### Steps to reproduce the problem

1. Open a readonly note
2. Access the properties menu
3. Click on readonly toggle.
4. Nothing happens

### Version

3.0.0-94b28f8-desktop

### Platform/OS

macOS

**Comment by ammarahm-ed** [comment]
Hi, this has been fixed in the latest version.
