### ISSUE TITLE
No Settings button on Android?

### ISSUE THREAD

**Issue by muchqs** [streetwriters/notesnook#4906]
### What happened?

Manually updated to v3.0.0, can't find the Settings button on any of my Android devices. But I can see it on web browser on PC.

Then I tapped the "Tap to sync" on Android and it went into Settings menu. Please see screenshot, I tapped the red rectangle area.

Is this how it's supposed to work or a bug?

https://i.imgur.com/c4MiVI2.jpg

### Steps to reproduce the problem

please see screenshot

### Version

v3.0.0

### Platform/OS

Android

**Comment by thecodrr** [comment]
Fixed.
