### ISSUE TITLE
Pressing "Back" on Android should go back to Notes list instead of closing the app

### ISSUE THREAD

**Issue by muchqs** [streetwriters/notesnook#4907]
### What problem are you facing?

On Android phone, Notesnook v3.0.0

1. tap to open a note
2. Using the "back" gesture to go back
3. Notesnook app closes

### What's the solution you'd like to see in Notesnook?

After step 2, it should go back to the notes list, instead of closing the app.

**Comment by 4fosaefp** [comment]
Can confirm I'm experience the same issue on my Android phone.
