### ISSUE TITLE
Delay when typing text

### ISSUE THREAD

**Issue by ecureuill** [streetwriters/notesnook#4909]
### What happened?

There is a significant delay when typing text into v2 notes.
This makes it very difficult to take notes quickly and efficiently. 

https://github.com/streetwriters/notesnook/assets/993369/6916d05a-65a3-43cf-9e5f-a3f83c93dc8b

### Steps to reproduce the problem

1. Open a note created with v2
2. Type and notice the delay

### Version

3.0.0-94b28f8-desktop

### Platform/OS

macOS

**Comment by ammarahm-ed** [comment]
Hi, this has been fixed in #5724
