### ISSUE TITLE
Editor toolbar horizontal scrollbar instead of ... menu on narrow destkop windows

### ISSUE THREAD

**Issue by TheMatjaz** [streetwriters/notesnook#495]
## Describe the bug
Editor toolbar gets horizontal scrollbar when first note after startup is opened in a narrow destkop window.

## To Reproduce
1. Open the desktop app - **don't** open any note yet.
2. If the window is maximised, then "unmaximise" it, so it's floating and resizeable.
3. If not already narrow-enough, resize the window horizontally, making it narrower, until the left menu panel (_Notes_, _Notebooks_, _Favorites_, etc.) is automatically resized to just icons.
4. At this point, open any note for the first time after startup. The editor toolbar is now a single horizontally scrollable row of icons (the `...` is already expanded) instead of showing up as multiple stacked rows.

### Important note
The toolbar will stay in the same format as when it first appeared until the application is closed. It's the **first** note being opened after startup that counts.

- If the first note after startup is opened on a wide-enough window, then the toolbar renders correctly and will stay like that even when resizing the window to something smaller.
- If the first note after startup is opened on a too-narrow windows, then toolbar will have the scrollbar and will keep it even if the windows is resized to something larger.

## Expected behavior
The toolbar should appear as multi-row, just like it does when expanding the `...` menu. Horizontal scrolling is highly unpractical with the mouse.

## Screenshots
Normal behaviour, when the first note is opened on a wide window
![normal](https://user-images.githubusercontent.com/5064956/162612196-aa35049e-24bf-4625-b054-85623ea624a8.png)

Horizontal scrollbar, when the first note is opened on a narrow window.
![unexpected](https://user-images.githubusercontent.com/5064956/162612036-1fc335a1-6d7f-4c7c-a1ba-d48cba6bbfde.png)

## Desktop
 - OS: Windows 10 Pro, 21H2
 - Desktop app version: 1.8.6-20bdaa9-desktop

**Comment by TheMatjaz** [comment]
Could be added to [UI/UX Improvement Suggestions](https://github.com/streetwriters/notesnook/issues/412)

**Comment by thecodrr** [comment]
Hi, this is intended behavior and will be improved in the upcoming versions.
