### ISSUE TITLE
Unable to close note properties menu and note preview disappears

### ISSUE THREAD

**Issue by ecureuill** [streetwriters/notesnook#4952]
### What happened?

Unable to close note properties menu and note preview disappears

https://github.com/streetwriters/notesnook/assets/993369/d28a4749-1d23-4a78-969e-ff059103476d

Closing and reopening the app does not resolve the issue. 
The only way to view existing notes is to create a new note, enable focus mode, and switch to an existing note using the tabs.

### Steps to reproduce the problem

1. Open an existent note
2. Open the properties bar
3. he note properties menu cannot be closed.
4. The note preview disappears.
5. Close the app
6. Open an existent note

### Version

3.0.0-94b28f8-desktop

### Platform/OS

macOS

**Comment by ammarahm-ed** [comment]
Hi, this has been fixed in the latest version.
