### ISSUE TITLE
Table of contents feature improvements for web editor

### ISSUE THREAD

**Issue by Leviob** [streetwriters/notesnook#4977]
### What problem are you facing?

I'm so happy to have an outline / table of contents. I heavily rely on headings for hierarchy of my notes so this feature is very well appreciated. Being able to easily navigate large notes is nice. However, the implementation isn't the most useful. 

### What's the solution you'd like to see in Notesnook?

 I think these three changes would make this feature much more useful for everyone. 

- [ ] A single button below the top-right menu to expand and collapse the ToC
The ToC should be below this menu so that the menu is still accessible.

- [ ] Visibility should be statefull, so it will always be in the state last used
Because I use this feature a lot, I would prefer if the ToC was always visible. Currently I need to open it every time I start Notesnook. Then if I want to access the menu in the top right, I need to close it. 

- [ ] Increase the indentation so the hierarchy is easier to see
I think the indent should be two or three times as much.

Here's what these changes might look like:
![collapsed](https://github.com/streetwriters/notesnook/assets/59812528/1bbfb230-109b-46bd-949d-5c32eb1217d0)
![expanded](https://github.com/streetwriters/notesnook/assets/59812528/9c9d1a52-932b-4070-ab08-2922962879ff)

### Additional context

Additional interactions: Focus Mode should not hide the ToC. Disable Editor Margins should remove margins, but only up to the ToC (if it is expanded). 

- [ ] Bonus points for making the ToC width adjustable. I love how much flexibility the sidebar and notes frames have. 

The iOS ToC has appropriate indentation.

**Comment by Leviob** [comment]
As other issues have pointed out, the TOC sidebar should not overlap the text. I didn't explain that clearly here.

**Comment by CarlSinclair** [comment]
I don't particularly need a separate button for it, but I agree with your other suggestions of increasing indentation and remembering the last state of TOC (open vs closed) for each note. Adjustable width would also be nice, or at least auto-width based on the width of the headers.

**Comment by Leviob** [comment]
I think the button could live where it currently is in the menu, but it should both open and close the TOC. The TOC should not cover up the menu like it currently does.

**Comment by Leviob** [comment]
Currently, if you have many headings, you can scroll down on the ToC and cannot close the ToC until you scroll back up to the top. This issue would be fixed with the changes outlined above.
