### ISSUE TITLE
Writer mode

### ISSUE THREAD

**Issue by gr3enarr0w** [streetwriters/notesnook#4982]
### What problem are you facing?

As a user I would like the ability to put focus mode on with a simple button, this would hide the sidebars. The sidebars can be brought back by clicking the focus mode again

### What's the solution you'd like to see in Notesnook?

There should be a simple button that hides the panels and focuses strictly on writing

### What alternatives have you considered?

There are other more specific apps like ia writer

**Comment by Leviob** [comment]
This currently exists as you describe it. Click the Focus Mode button in the top right (sunglasses icon).

**Comment by ammarahm-ed** [comment]
As I understand, this is already possible.
