### ISSUE TITLE
Font is veeery small

### ISSUE THREAD

**Issue by myy12345** [streetwriters/notesnook#5]
It's not made for mobile viewing. The app font is very small.
How can you expect me to pay for something like this? I think the app has great features, but i can't use it with this small text

**Comment by thecodrr** [comment]
Hey, can you attach a screenshot and give more details on which version of the app you are using and on which device?

**Comment by myy12345** [comment]
![Screenshot_20210501-123542_Notesnook](https://user-images.githubusercontent.com/83458654/116778316-d5d1e700-aa79-11eb-9fc5-6f388a270780.jpg)

![Screenshot_20210501-123533_Notesnook](https://user-images.githubusercontent.com/83458654/116778317-d7031400-aa79-11eb-841b-98fcb537cb42.jpg)
![Screenshot_20210501-123525_Notesnook](https://user-images.githubusercontent.com/83458654/116778318-d7031400-aa79-11eb-8cd7-32032eab149b.jpg)

I'm using samsung galaxy A50
Notesnook version 1.3.73

**Comment by ammarahm-ed** [comment]
@myy12345 Hey, thanks for bringing this to our attention. I have investigated it and it appears to be correct. The next release will fix the font size on fhd devices.

**Comment by cfinnberg** [comment]
I don't know if I should create a different issue, but I have the same problem in the desktop app. I use QHD resolution (2560x1440) and font is quite small for me. Still usable, but not pleasant to use. I don't see any place in settings where I can adjust it.
System: Manjaro Linux
Version: 1.3.5

**Comment by thecodrr** [comment]
@myy12345 The font should be bigger in the new update.

@cfinnberg I can confirm this. However, you can usually scale the desktop app manually (via ctrl + scroll or ctrl + +/-). I could increase the font size slightly but it will still be pretty small for bigger displays. I'd also appreciate if you can attach a screenshot.

**Comment by cfinnberg** [comment]
@thecodrr , thanks for your answer. Unfortunately app scale is not working for me. I'm attaching an example image. As I said, it's not unusable but it's quite small. Editing area is not so bad.
![screenshot](https://user-images.githubusercontent.com/2817326/118398284-9225d280-b660-11eb-9e9c-684bf82f6b8d.png)

**Comment by thecodrr** [comment]
@cfinnberg noted. I'll add a scale slider in settings (and also look into how scaling can be enabled in the electron app).

**Comment by thecodrr** [comment]
The font size has been increased in the latest versions of both the web app and the mobile apps.
