### ISSUE TITLE
Getting a "Nothing found: " dialog box in the note view

### ISSUE THREAD

**Issue by avatar382** [streetwriters/notesnook#500]
**Describe the bug**
I'm seeing an alert notifications display in the top right of the notes window that seems out of context for the note I'm looking at.

**To Reproduce**
I'm not sure yet what preconditions are necessary for this issue to manifest, but basically:
1.) open note
2.) press return key or start typing text
3.) annoying/unnecessary alert notifications display 

**Expected behavior**
Alert notifications should only display if warranted and applicable to an action just taken

**Screenshots**
![Screenshot_2022-04-12_17-22-43](https://user-images.githubusercontent.com/130926/163070628-efb313af-be14-4ebc-8427-c7a73f98ddfa.jpg)

**Desktop (please complete the following information):**
Ubuntu Linux 21.10, 5.13.0-39-generic. XFCE window manager, Desktop app version is latest as of the submission date of this issue.

**Smartphone (please complete the following information):**
N/A

**Additional context**
Quitting and relaunching the app temporarily resolves the issue.

**Comment by thecodrr** [comment]
Looking into this. Thank you for reporting.

**Comment by abhishekarora12** [comment]
I'm getting this too

**Comment by avatar382** [comment]
Reproduced this again today, it seems to be triggered by running a search, and then clicking into one of the results and making any changes.

Thanks for looking into this!
