### ISSUE TITLE
[Spelling mistake] iOS app 1.5.4 - Pro subscription shows $49.99/month

### ISSUE THREAD

**Issue by 0oWow** [streetwriters/notesnook#51]
Minor issue with version 1.5.4 of the iOS app (iPhone 12 mini - iOS 15 beta 8).  On the settings page, in the trial notification, it says "Subscribe to Notesnook Pro ($49.99/mo)".  

It's just a typo, because clicking that link references the correct monthly amount afterward.

**Comment by thecodrr** [comment]
Oops. Thanks for reporting. Will be fixed ASAP.

**Comment by ammarahm-ed** [comment]
Fixed the issue, will ship in the next release.
