### ISSUE TITLE
Crash on dragging a link

### ISSUE THREAD

**Issue by thecodrr** [streetwriters/notesnook#5103]
Happens when I dragged a link into a NS record

Cannot+read+properties+of+null+(reading+'nodeView')
TypeError:+Cannot+read+properties+of+null+(reading+'nodeView')
++++at+mn.drop+(https://app.notesnook.com/assets/index-ad95361ef911.js:60:17426)
++++at+t.dom.addEventListener.t.input.eventHandlers.<computed>+(https://app.notesnook.com/assets/index-ad95361ef911.js:60:4736)

---
Device+information:

App+version:+3.0.0-94b28f8-desktop
OS:+OS+X+10.15.7
Browser:+Electron+29.3.1
Pro:+true

**Comment by ammarahm-ed** [comment]
Fixed.
