### ISSUE TITLE
CPU-overloading and bug with letter in Russian

### ISSUE THREAD

**Issue by vsaraikin** [streetwriters/notesnook#52]
Hello!

I've experienced two problems:
1. While using desktop CPU is constantly using because app "checking for updates". This thing does not stop and using CPU. In web there is no such problem
2. If you writing Russian letter "x", it writes instead "[" which is incorrect.

**Comment by thecodrr** [comment]
The `checking for updates` doesn't take any CPU because there is nothing happening. It can be annoying though.

> If you writing Russian letter "x", it writes instead "[" which is incorrect.

I am taking a look at this.
