### ISSUE TITLE
Search with and without accent at the same time

### ISSUE THREAD

**Issue by jrcacd** [streetwriters/notesnook#521]
This is a must, because many times we don't remember if we wrote it with or without accentuation

Ex: 
Search for 

- "jo" or "jó", ... must return results with "jõ", "jó" and "jo"
- "la", "lá", ... must return results with "lá", "la" and "lã"
- "ca", ... must return results with "ca", "cá", "ça", "cá"
- ...

**Comment by thecodrr** [comment]
This will be added as part of the new search.

**Comment by thecodrr** [comment]
Closing this in favor of #145
