### ISSUE TITLE
2FA not working properly: Zoho mail

### ISSUE THREAD

**Issue by alihamuh** [streetwriters/notesnook#5282]
### What happened?

2FA does not work.  I keep trying.  It can be entered on iPhone but cannot be submitted - can never get past entering number.  Please fix this, the whole thing is totally useless.

After sometime I got it to work somehow after about 10 tries.  It never took the 2FA code as far as I know, maybe it did, but anyway I saw a confusing screen but it asked for my password, then I was in.  It's bad when you depend on these things and suddenly they don't work.

### Steps to reproduce the problem

---

### Version

---

### Platform/OS

iOS

**Comment by ammarahm-ed** [comment]
Fixed.
