### ISSUE TITLE
Sync issues and vault issues

### ISSUE THREAD

**Issue by alihamuh** [streetwriters/notesnook#5283]
### What happened?

Previously, I could have been typing on two devices and notesnook would figure out the best way to sync. Now it will not sync at all. I get error messages. 

The problem still persists in 3.0.1. I believe the vault became very buggy. I also can't lock new notes. The syncing problem only happens in locked notes.

I cannot lock new notes and I cannot change the vault password if that gives more vault insight.
![image (2)](https://github.com/streetwriters/notesnook/assets/22678611/9da719c4-5e64-478b-8cd8-950d4dc19f41)

### Steps to reproduce the problem

--

### Version

v 3.0.1

### Platform/OS

iOS, Android, Chrome/Chromium

### Relevant log output

```shell
--
```

**Comment by thecodrr** [comment]
Fixed.
