### ISSUE TITLE
There is a problem when the notes are synchronized on different platforms.

### ISSUE THREAD

**Issue by HeroKingGo** [streetwriters/notesnook#54]
I found that some of my notes cannot be fully synchronized. They are incomplete on other platforms. Hope you guys fix it as soon as possible. Before that, I can only use other platforms to advance my work.

**Comment by thecodrr** [comment]
1. Which version and platform are you on?
2. Which is your primary platform?
3. Did you try making an edit in those incomplete notes and syncing?
4. Have you tried running the force sync from Settings?

**Comment by HeroKingGo** [comment]
# Answer:
**1.** I am using Windows(Windows 10 Pro, Version:21H1, OS build 19043.1202, Experience: Windows Feature Experience Pack 120.2212.3530.0) and Android 11(ArrowOS 11|OFFICIAL). And I am using your latest applications. 
**2.** Windows 10 & Android
**3.** No.
**4.** Yes. Of course.
*By the way, I used English and Chinese in my notes.*

**Comment by HeroKingGo** [comment]
Ops! "Before that, I can only use other platforms to advance my work." means **I am using other applications now.**

**Comment by thecodrr** [comment]
Can you try this:

1. Make a backup from your primary device (where the notes are complete) then logout.
2. Log back in and see if the notes are complete or incomplete.

**Comment by HeroKingGo** [comment]
Notes are incomplete. But I can preview my notes. However, it will not display my content when I click it. It only displays my titles.

**Comment by thecodrr** [comment]
Can you send a screenshot?

**Comment by HeroKingGo** [comment]
I had sent an email to you.

**Comment by thecodrr** [comment]
I received the email but it is encrypted with a password.

**Comment by HeroKingGo** [comment]
Password: FreeasinFreedom1

**Comment by thecodrr** [comment]
@HeroKingGo How many notes are empty?

**Comment by HeroKingGo** [comment]
About 1~5 notes. I am not sure.

**Comment by thecodrr** [comment]
@HeroKingGo Can you try force syncing again to see if all the notes sync? We deployed a couple of fixes to our sync server that should fix this issue. Not sure if the notes that are gone can be recovered though.

**Comment by thecodrr** [comment]
This should be fixed. Please reopen if the issue if the problem persists.
