### ISSUE TITLE
Single word search disabled: zoho mail

### ISSUE THREAD

**Issue by alihamuh** [streetwriters/notesnook#5426]
### What happened?

 (user is chinese)
 It is no longer possible to search all notes by a single word.

In the past, I could easily type in one word and find all related notes. After the change, the minimum search is three words. This greatly limits the number of notes I can find, and makes it much less convenient to use.

I can understand the benefits of the change, but I just want to ask if there can be a single word search, or at least a switch such as "CJK search", so that those who need it can search a little slower, but at least find the information.

### Steps to reproduce the problem

---

### Version

v3.0.01

### Platform/OS

Chrome/Chromium

### Relevant log output

```shell
---
```

**Comment by thecodrr** [comment]
Fixed.
