### ISSUE TITLE
User-provided Bucket

### ISSUE THREAD

**Issue by stevesbrain** [streetwriters/notesnook#5434]
### What problem are you facing?

When uploading images etc, due to their geographical location, upload is quite slow. Additionally, backing up of attachments isn't very well facilitated (in my opinion) - they aren't included in "note" backups, and it seems even if cached, they are re-downloaded from source in order to make a backup. This makes it a lengthy process to back up attachments separately from notes.

### What's the solution you'd like to see in Notesnook?

1. The ability for advanced users to configure their own S3-compatible bucket for storing their attachments. This would enable use cases such as behind-VPN-only buckets, or local bucket. Additionally allows those users to have a backup of their attachments in another way (i.e. they can backup the bucket themselves, and then use a decryption script if they ever need access)
2. Alternatively, I'd like to see cached attachments utilised when backing up attachments, and attachments included at least as an option in notes backup

**Comment by ammarahm-ed** [comment]
This has been fixed. We have added a cdn to improve download speeds. As far as configuring your own s3 bucket goes, that will be possible now if you self-host your own Notesnook server.

- Attachment backups have been added
- Offline mode is added to cache all attachments offline
