### ISSUE TITLE
Issues aren't automatically opened on Github when reported through app

### ISSUE THREAD

**Issue by jordanhandy** [streetwriters/notesnook#544]
**Describe the bug**
Tried to open a bug through the app, and even though it appeared to be successful, I never received a notification of the bug being opened, and it doesn't seem to be on Github

**To Reproduce**
1. Go to Settings on macOS app
2. Choose "Report an Issue"
4. Fill out issue report and submit

**Expected behavior**
- Receive confirmation email, and issue appearing under Issues in Notesnook GH Repo

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [macOS]
 - Version [1.8.8]

**Comment by ammarahm-ed** [comment]
It was a server issue. Just fixed it.
