### ISSUE TITLE
a minor bug: zoho mail

### ISSUE THREAD

**Issue by alihamuh** [streetwriters/notesnook#5453]
### What happened?

I entered a value of 1.073 on the CSOB line, which displayed correctly. After syncing, on my phone and on my computer (Windows 10), I saw the value 1.07 instead of 1.073 in the desktop version of Notesnook 3.0. I know this is a minor error that did not occur befor

### Steps to reproduce the problem

---

### Version

+3.0.1

### Platform/OS

Android

### Relevant log output

```shell
---
```

**Comment by thecodrr** [comment]
This can happen sometimes due to sync running before you are done making all the edits. There is nothing to worry about here. Just run the sync manually and it'll work (usually it automatically runs the sync again) so this should already be fixed.
