### ISSUE TITLE
keyboard covers screen on PIN page: zoho mail

### ISSUE THREAD

**Issue by alihamuh** [streetwriters/notesnook#5480]
### What happened?

In the iOS app when using a PIN to log in, I don't think there's any way to lower the keyboard once you type in your PIN, and the keyboard covers the Continue button. Is there a plan to fix this by adding a hide keyboard icon or having the Continue button shift upward so it's not blocked by the keyboard? It's not a big deal at all, just a minor inconvenience I was wondering about.

### Steps to reproduce the problem

---

### Version

+3.0.1

### Platform/OS

iOS

### Relevant log output

```shell
---
```

**Comment by ammarahm-ed** [comment]
This issue has been fixed in v3.0.12
