### ISSUE TITLE
tags not importing from evernote:zoho mail

### ISSUE THREAD

**Issue by alihamuh** [streetwriters/notesnook#5517]
### What happened?

I imported all notes (1000) from evernote to notesnook. All seemed to go successfully. I cant see any problem with attachments or notes content. But no tags. None. 

### Steps to reproduce the problem

---

### Version

--

### Platform/OS

Chrome/Chromium

**Comment by HaleTom** [comment]
Possible dupe of #5466 and #5337

**Comment by thecodrr** [comment]
Fixed.
