### ISSUE TITLE
Linux Desktop App: Synced images not showing

### ISSUE THREAD

**Issue by avatar382** [streetwriters/notesnook#554]
**Describe the bug**
Images attached to notes do not show in Linux desktop app. A placeholder appears instead.

**To Reproduce**
1. Create note with attached image
2. Close and relaunch desktop app
3. Image does not load, placeholder appears instead.

This problem does not occur with the same note in the Android and iOS versions of Notesnook..

**Expected behavior**
Images attached to a note should always appear in the note.

**Screenshots**
![Screenshot_2022-05-05_15-15-33](https://user-images.githubusercontent.com/130926/167027761-01876a21-ce55-4fed-9088-35d1f8760f27.jpg)

**Desktop (please complete the following information):**
Ubuntu Linux 21.10, 5.13.0-40-generic
App version is 1.8.8-ec26a54-desktop

**Smartphone (please complete the following information):**

**Additional context**

**Comment by thecodrr** [comment]
Hi,

There was a recent change in how and where we store attachments due to which they might not work on the desktop app just yet. I will be releasing a version that fixes this ASAP.

**Comment by thecodrr** [comment]
I can't reproduce this...
