### ISSUE TITLE
Provide a "drag option" for rearranging notebooks :)

### ISSUE THREAD

**Issue by Vonskie04** [streetwriters/notesnook#560]
I'm a fastidious guy who likes to organize things in life lol 
It would be a better feature to the app for a guy like me. 

I hope this request to be consider.

**Comment by claytondecker** [comment]
If Notebooks in the sidebar could be expanded, then drag and drop could be handy when organizing notebooks and notes.

**Comment by thecodrr** [comment]
There's currently no plan to add manual sorting for notebooks or notes.
