### ISSUE TITLE
Reminder repeat function is not working: zoho mail

### ISSUE THREAD

**Issue by alihamuh** [streetwriters/notesnook#5624]
### What happened?

Repeat function of the Reminder doesn't work anymore. I seem to not being able to set up daily or weekly reminders anymore.

### Steps to reproduce the problem

---

### Version

v3.0.04

### Platform/OS

Linux, Android, Chrome/Chromium

### Relevant log output

```shell
---
```

**Comment by thecodrr** [comment]
Fixed.
