### ISSUE TITLE
Error on lock empty note 

### ISSUE THREAD

**Issue by ecureuill** [streetwriters/notesnook#5626]
### What happened?

There is an error on attempt to add a note to vault (lock it), when the note is empty (has only the title).

https://github.com/streetwriters/notesnook/assets/993369/517e0719-b52e-4470-9626-ddb5551f38b6

### Steps to reproduce the problem

1. Create an empty note 
1. Attempt to lock it (nothing seems to happen)
1. Quit notesnook
1. Reopen notesnook
1. The note is listed locked
1. Attempt to unlock fails

### Version

3.0.4-68d57e2-desktop

### Platform/OS

macOS

**Comment by thecodrr** [comment]
Thank you for the detailed bug report. Fixing this ASAP.
