### ISSUE TITLE
Can't pin to Start on Windows 11

### ISSUE THREAD

**Issue by Melissa-Iacovidou** [streetwriters/notesnook#5627]
### What happened?

After the recent update I am not able to pin to Start on Windows 11. Even though when I right-click on the Desktop shortcut I can select 'Pin to Start', the shortcut does not appear in start. I used to have it before the update but then before or while the update was installing I did get some weird error message but I can't recall what exactly it said - the shortcut disappeared after that.

### Steps to reproduce the problem

No particular steps - the shortcut does not appear in Start after I select 'Pin to Start'.

### Version

v3.0.4-68d57e2-desktop

### Platform/OS

Windows

**Comment by ammarahm-ed** [comment]
I am unable to reproduce this on Windows 11
