### ISSUE TITLE
Can't select a pricing plan (trial started) 

### ISSUE THREAD

**Issue by gojo-limitless** [streetwriters/notesnook#5641]
Platform: Android 14 (One UI 6.1)
Notesnook version: 3.0.4

Not able to select/see a pricing plan (region:India)

Fixed tried: changing network/DNS, restarting app, nothing works. It just keeps on loading. And, when I click on the button, the values are blank for monthly/yearly, and nothing is clickable (and nothing takes me to the Play Store subscription)
![Screenshot_20240514_050934_Notesnook.jpg](https://github.com/streetwriters/notesnook/assets/14110456/fbc3c49d-4dcd-45cf-ace5-a979147ccb4d)

**Comment by ammarahm-ed** [comment]
Closed by #5657
