### ISSUE TITLE
Configure window buttons

### ISSUE THREAD

**Issue by TheIllusion24** [streetwriters/notesnook#5642]
### What problem are you facing?

Not following titlebar buttons in gnome tweaks.
[Screencast from 2024-05-14 17-06-03.webm](https://github.com/streetwriters/notesnook/assets/111121163/9687b64b-e267-4d2e-8a31-13eda7b5678b)

### What's the solution you'd like to see in Notesnook?

Follow the gnome tweaks titlebar button setting in gnome tweaks.

**Comment by thecodrr** [comment]
Those buttons are added by Notesnook (not the Desktop Environment) which is why those settings aren't having any effect. Unfortunately, Electron doesn't support this aside from replacing the custom title bar with the native one.
