### ISSUE TITLE
Editor slow/laggy when typing on desktop app (Linux/Flatpak)

### ISSUE THREAD

**Issue by ArtikusHG** [streetwriters/notesnook#5668]
### What happened?

When I try typing on the Linux desktop app in the editor in any note, there is a noticeable lag. I have tried disabling real-time sync, disabling sync altogether, and various other settings. This delay/lag does not happen in other apps. I am running the latest version from Flathub on Fedora 39, GNOME 45.

[Typing in Notesnook](https://github.com/streetwriters/notesnook/assets/24320212/30f2d514-bdce-442d-af7e-0ef2af2095ea)
[Typing in other apps](https://github.com/streetwriters/notesnook/assets/24320212/a3d0b115-99f8-486b-bffa-3ec804fb5daf)

### Steps to reproduce the problem

- Download the latest version of Notesnook from Flathub
- Try typing in the editor in a note

### Version

3.0.4-68d57e2-desktop (Flatpak)

### Platform/OS

Linux

**Comment by thecodrr** [comment]
Closed by #5724
