### ISSUE TITLE
Heic images aren't shown in Windows 10 desktop app

### ISSUE THREAD

**Issue by codetheron** [streetwriters/notesnook#5703]
### What happened?

I can't show photos from my iPhone on my Windows 10 app. Maybe .heic format is not supported by Notesnook on Windows 10? I have installed "HEIF image extension" from Windows Store btw.

### Steps to reproduce the problem

- created a note on iPhone version of Notesnook
- attached a photo from photo gallery with compression enabled
- note with above photo is being shown correctly on iPhone
- however photo from this note is not being shown in Notesnook app on my Windows 10 - it shows placeholder with small icon of broken image (like in internet browser when there is wrong path to the image)
- I can download this photo from Windows app (as heic) and it does show correctly in my IrfanView image shower

### Version

3.0.6 Windows 10 / 3.0.7 iOS

### Platform/OS

Windows

**Comment by thecodrr** [comment]
Notesnook supports whatever is supported by the Chrome browser. Chrome does not natively support HEIC images so what you are seeing is expected.

**Comment by codetheron** [comment]
Okey, let me say it in different way. I would like to see photos from my notes written on iOS device - on my Windows machine. I don't mind it those are .heic or .jpg. So maybe just covert them do .jpg while compressing.

Maybe there is something to change on my side to achieve that?

**Comment by ammarahm-ed** [comment]
Hey @codetheron the latest version of iOS app (v3.0.8) converts HEIC images to jpeg before upload now.

**Comment by codetheron** [comment]
@ammarahm-ed yes, it works :) Great :)

I have created a test note with 2 images - one compressed. one not compressed.
- compressed .jpg is shown correctly in both apps, after downloading has correct size, name and removed exif data - great
- uncompressed - is shown correctly on iOS, shown as image frame in Windows app (looks better than before - with nice image placeholder) - but can't be downloaded in Windows app from image context options ("Download attachment").

What's interesting - both of those images aren't being shown in Atachments manager - older ones are there in 'images' category.

**Comment by codetheron** [comment]
I have tested current version and it seems that everything is OK - resized / compressed pictures are nicely named and synced from iOS to desktop, Great! Thanks :)
