### ISSUE TITLE
Suggestion to swap to Tauri.

### ISSUE THREAD

**Issue by Mukul1127** [streetwriters/notesnook#572]
**Is your feature request related to a problem? Please describe.**
There is no problem

**Describe the solution you'd like**
Instead of staying with Electron, you could switch over to Tauri for much, much smaller bundles and less ram usage.
Site: [https://tauri.studio/](https://tauri.studio/)

**Describe alternatives you've considered**
Staying With Electron probably because no stable release yet, only release candidate.

**Additional context**
None

**Comment by thecodrr** [comment]
This is not a bad idea but electron has a very powerful ecosystem. Perhaps when Tauri adds Deno bindings we can consider this but for now, we are sticking with Electron.

I have tried Tauri for Notesnook and there's not a huge difference in binary size. 99.2 MB on electron vs 60+ mb on Tauri (Linux). The other big issue is the platform difference; NodeJS in Electron helps a lot with this. Tauri doesn't have anything to rival this (something like Deno would be great).

**Comment by Mukul1127** [comment]
True, to be fair Tauri is still in beta and still isn't good for production like this app because there isn't good documentaion, and no plugins. You could try Rust instead of Node.js for the platform difference, but I think that Deno is on the roadmap for Tauri.

**Comment by LeeFerreira** [comment]
Tauri v2 dropped as a stable release on 2nd October 2024 - any chance of this becoming (closer to) a reality?
