### ISSUE TITLE
Unresponsive on Android

### ISSUE THREAD

**Issue by eylenburg** [streetwriters/notesnook#5753]
### What happened?

I have noticed this for a few days now. If I open the app and want to create a new note, after writing it I can't go back to the main list. The app is unresponsive. After closing it and restarting the app, it works fine but the newly create note is not saved and needs to be written again. Then it works fine and you can go back to the main list.

Similarly, after a "cold start" of the app, I sometimes can't click on an existing note to open it. After a forced restart of the app it works then.

### Steps to reproduce the problem

Not sure how to reproduce it exactly, but the error only occurs when starting the app after it hasn't been run in a while. Then, after killing the app and opening it again, it works. 

### Version

3.0.6

### Platform/OS

Android

**Comment by ammarahm-ed** [comment]
Hi, this issue has been fixed in v3.0.8. Please update to the latest version
