### ISSUE TITLE
Outline Editor for unordered nested lists

### ISSUE THREAD

**Issue by gaganyadav80** [streetwriters/notesnook#576]
**Is your feature request related to a problem? Please describe.**
When taking study notes or some information outliner apps (like Dynalist, logseq etc) are good tools. They help organise the necessary information under each topic and nest the list for all the subtopics.

**Describe the solution you'd like**
Dynalist and Logseq provide a lot of other features for productivity. I want just the editor they provide - which includes collapsing and expanding each list item and an outline to map the nested and parent list item.  In the screenshot below `Chapter 1` is collapsed and Other items are expanded. This is a screenshot from logseq desktop application.

<img width="879" alt="Screenshot 2022-05-17 at 10 40 06" src="https://user-images.githubusercontent.com/47142137/168733761-56a14815-bf01-4bbb-9c58-ef548b2043bd.png">

**Describe alternatives you've considered**
Obsidian also has the ability to expand and collapse the unordered list items.

**Additional context**
NA.

**Comment by thecodrr** [comment]
This can be added fairly easily in the new editor. The new task list already has this actually (the collapsing part).

**Comment by thecodrr** [comment]
This has been added in the new editor. Closing this.
