### ISSUE TITLE
Cannot close note creation tab

### ISSUE THREAD

**Issue by Howarang12** [streetwriters/notesnook#5766]
### What happened?

I was trying to close a single note creation tab and it does not close when I click x. 

### Steps to reproduce the problem

1. Click create notebook when no other tabs are open
2. New tab opens
3. Click x, nothing happens

![Screenshot 2024-05-24 020133](https://github.com/streetwriters/notesnook/assets/88353050/6021b2bf-c58c-40f8-bc45-937807efdc72)

### Version

V3

### Platform/OS

Windows

**Comment by thecodrr** [comment]
This is intended.
