### ISSUE TITLE
Sync failed in web browsers

### ISSUE THREAD

**Issue by mockinbirdy** [streetwriters/notesnook#5829]
### What happened?

Hello, first off, I changed nothing in my browser or apps.

First, I see this. As you can see it claims sync is disabled but it is not.

![one1](https://github.com/streetwriters/notesnook/assets/94114278/dc9513f3-4efc-4794-8bac-a5a8f2a62f07)

Then I click on _sync_ to sync it manually but it returns this - sync failed.

![three](https://github.com/streetwriters/notesnook/assets/94114278/3fb27e08-1a8b-43ad-91be-6c395a7902e6)

### Steps to reproduce the problem

read above

### Version

latest web

### Platform/OS

Firefox

**Comment by thecodrr** [comment]
The first time you open the app, it shows the sync disabled icon. It changes when the first sync starts though. Can you send over your debug logs so I can take a look why your sync is failing?

**Comment by mockinbirdy** [comment]
It synced successfully the next day, but on the 1th of June it was broken, it refused to sync for several hours, tho I tested it over and over. If anything, the error should have been reported on your side, cause there was nothing wrong w my pc/internet. 

Have no logs; I just quit trying on that day.

**Comment by thecodrr** [comment]
The icon changes as soon as the sync runs which happens after the SSE connects. There is an issue currently in which SSE doesn't connect (fixed now but not released).
