### ISSUE TITLE
Markdown Source Editor

### ISSUE THREAD

**Issue by gaganyadav80** [streetwriters/notesnook#586]
**Is your feature request related to a problem? Please describe.**
I mostly use markdown to write my notes and the current editor is a pain to use when you want to copy/paste markdown and other editing stuff. For example) 
1. If I paste the source of a markdown file then it won't be rendered until I go to each line and then press enter. I will have to copy the generated format and then past it to be parsed in notesnook and still some items are still parsed incorrectly, such as checklists.
2. If I press enter at the start of a header 1 line then the empty line above will by default be a header 1 which then I have to go to the toolbar to change it back to paragraph. It makes it time-consuming for users like me who are used to writing notes in markdown.

**Describe the solution you'd like**
As you have said that the new TipTap editor is extensible. It would be great if you could provide an option to edit our notes in markdown source OR make the live preview editor somewhat as good as something like the Typora (best in class live markdown editor). The thing you can take from Typora is that if I am on a line which is a header 1 and then I press enter (newline) whether at the beginning or the end of the line then do not copy the text style to the new line. Reset it to default for the new line.

**Describe alternatives you've considered**
Typora, Obsidian, Joplin.

**Comment by thecodrr** [comment]
> It would be great if you could provide an option to edit our notes in markdown source

This is probably never going to be supported. Tiptap does support Markdown shortcuts which are much more reliable than the ones in TinyMCE _but_ it's still not markdown. We could add something like automatically converting markdown pasted content but that would be super flaky.

Maybe we could add a special "Paste as markdown" somewhere to enable automatic markdown conversion. Not sure about this.
