### ISSUE TITLE
replacing "\(" replace additional characters after this

### ISSUE THREAD

**Issue by krzemyczek** [streetwriters/notesnook#5928]
### What happened?

When replacing "\(" some additional text is replacing too
For example if replacing "\(" into "$$":    "\(PQS\)" --> "$$S\)"

### Steps to reproduce the problem

write somewhere "\(PQS\)"
control + 'f'
type "\("
click "toggle replace"
in "Replace" field type "$$"
stare at the result and wonder why

### Version

3.0.8-c93d82d-desktop

### Platform/OS

Linux

**Comment by krzemyczek** [comment]
someone know how to type "\" without github ignoring it?

**Comment by thecodrr** [comment]
This is no longer reproducible in v3.0.19.
