### ISSUE TITLE
Sync only works on VPN connection

### ISSUE THREAD

**Issue by m3thm4th** [streetwriters/notesnook#5930]
### What happened?

On my Android phone, when connected to my router via WiFi, sync doesn't work, neither does force sync. My router acts as a VPN server, if I connect to my router's VPN, while being connected to the same WiFi access point, thus tunneling all traffic from the router to the router itself, meaning IP address and all the rules (firewall, DNS, etc.) stay the same, sync works correctly.

This is true for any WiFi connection and any VPN server, I described the fact that this behavior is consistent even when the VPN server is the same router as the untunneled connection to emphasize the absurdity of this behavior.

### Steps to reproduce the problem

`Android -> WiFi AP -> Router -> Internet` => sync doesn't work

`Android -> WiFi AP -> Router -> Internet -> Back to the same router via VPN -> Internet again` => sync works
`        | --------------------------- VPN tunnel --------------------------- |`

### Version

3.0.9 (the latest available at the time of writing)

### Platform/OS

Android

**Comment by stevesbrain** [comment]
As in, if you connect to someone else's router and do the same VPN behaviour, it produces the same behaviour?

**Comment by stevesbrain** [comment]
Does this only happen on your Android phone? To me, it does sound more specific to your device, if it is reproducible across unrelated infrastructure.

**Comment by thecodrr** [comment]
@m3thm4th I am no networking expert so I have 0 idea what's going on here. Can you tell me what error you are getting during sync? Notesnook doesn't have any special networking infrastructure that would get in the way of accessing the Internet. It uses the exact same logic as your browser so if you can access the internet from your browser, you should be able to sync your notes from NN. What _could_ be happening is something blocking the NN app specifically.

**Comment by thecodrr** [comment]
@m3thm4th it could also be due to something in the router. I am really sorry, this looks like a device/network specific issue, and as such, I am out of ideas as to how to fix it.
