### ISSUE TITLE
Sync issue due to open tabs across devices

### ISSUE THREAD

**Issue by golden-potion** [streetwriters/notesnook#5956]
### What happened?

I reazlied that my recent sync issues was due to a given note staying open from the new tab feature. When that same note is opened and left as a tab on multiple devices, there's potential for sync issues. I think it's due to Notesnook syncing when you first open the app and the note is open, and you edit the note before Notesnook finishes syncing.

I wanted to find a way to turn off the tab feature, but there's no way to do so in the settings app. For now, I'm going to have to conciously remember that if a tab is left open on Notesnook, I shouldn't go ahead and go right to work with it, but I should close the tab and reopen it first. I also try to remember to close all open tabs when I'm finished with a session.

### Steps to reproduce the problem

Please see description

### Version

Latest across Linux, Mac, iOS

### Platform/OS

macOS, Linux, iOS

**Comment by thecodrr** [comment]
This has now been fixed in #6036
