### ISSUE TITLE
Sync not working for one note: Note appears empty or outdated in mobile app

### ISSUE THREAD

**Issue by Leviob** [streetwriters/notesnook#5957]
### What happened?

I noticed one of my notes was not up to date. The preview of the first line of text in the notebook view is updating, but the note stopped syncing. If I edit the note from my browser, the preview updates and the saved time at the top of the note updates, but the note contents do not.

I made a copy of this note and it had the same problem, which is how I created the "broken note" in the video. Similarly, adding text to this broken note from my mobile device will show up in the preview of the first line of text in the notebook view of my browser Notesnook session, but the changes will not be visible in the note.

The oldest copy of the original note in my Notesnook browser trash from May 18th has newer changes than the version visible on my iOS device. Maybe this error could have been caused by the V3 beta sync issues, but I only am noticing it now. 

I tried deleting and restoring the note, making copies, enabling and disabling sync for that note, but the note would still not update on my iOS device. Force Pull from Sync settings did not work either. 

I was able to create a new note and copy all of the contents to that note, which seems to have solved the problem for now. At least, until I discover how many other notes of mine are not syncing properly.

Other notes seem to be syncing fine, this is the first sync issue I've noticed with V3.

Video showing the empty broken note, and the preview updating when edited from browser:

https://github.com/streetwriters/notesnook/assets/59812528/9b978c19-0280-473c-bb06-9cd27ee04eb6

### Steps to reproduce the problem

 I have no idea. If I could help troubleshoot with this broken note, let me know. 

3.0.8-c93d82d-web, Firefox 127
3.0.9 iOS

### Version

3.0.9

### Platform/OS

iOS

**Comment by thecodrr** [comment]
This has now been fixed in #6036
