### ISSUE TITLE
Export Options greyed out

### ISSUE THREAD

**Issue by chikoosf** [streetwriters/notesnook#5992]
### What happened?

When I click right click > export, all the options including markdown, PDF and HTML are greyed out. I can't choose them, except the Text option. I was able to export the notes using the print option, but would be nice If we can have our export options back.

### Steps to reproduce the problem

just select a note and click export

### Version

29.3.1

### Platform/OS

Windows

**Comment by thecodrr** [comment]
They are greyed out because you aren't on a Pro subscription.
