### ISSUE TITLE
When I try to import my notes from Standard Notes the dates are messed up

### ISSUE THREAD

**Issue by ness-12** [streetwriters/notesnook#607]
Hi, 

I am trying to import my notes from Standard Notes. However, I'm getting this error:

> 1. Invalid file type: Standard Notes Backup - Wed Jun 08 2022 00_43_12 GMT+1000.zip

And the 'preview' of the notes shows a wildly inaccurate date:

> Note 318
Last modified on: 08/04/54402, 04:29

When I download the zip file and import it into Notesnook, all of my notes appear to be roughly 50,000 years in the future. wild

**Comment by ness-12** [comment]
Editing to add: the note in question was _actually_ last modified on the 7th of June at 9.48 pm...

**Comment by thecodrr** [comment]
The importer has been updated. Please try v1.3.2 at https://importer.notesnook.com/ (force reload if it still shows v1.3.1).
