### ISSUE TITLE
[Feature Request] - Add Tray Support

### ISSUE THREAD

**Issue by Jvlsc** [streetwriters/notesnook#608]
It would be nice to have tray support, so the app could be in background and easy opened/closed.

Thanks for the support.

Regards.

**Comment by aparaschiv** [comment]
Is there any chance anyone will take this into consideration?

**Comment by trymeouteh** [comment]
I would like to see this on desktop.

But I would like to see it work were when you minimised the app, the app gets minimised and when you close the app, the app gets minimised to the tray.
