### ISSUE TITLE
[Feature Request] - Add Flatpak build and release app via Flathub

### ISSUE THREAD

**Issue by Jvlsc** [streetwriters/notesnook#609]
**Is your feature request related to a problem? Please describe.**
Auto-update inside .deb or .rpm packages doesn't work due to permissions.

**Describe the solution you'd like**
I would like to have a Flatpack package available on Flathub, so every Linux distro could install/update the app easily.

**Describe alternatives you've considered**
Snap package could be an alternative, but Flatpack is better option in my opinion.

Kind regards.

**Comment by dtantono** [comment]
I seconded this. Flatpak is good for automatic update

**Comment by marco4mp** [comment]
This is the website: https://flathub.org

**Comment by developomp** [comment]
This should also solve issues where packages in different distros are maintained by different people and are behind the latest version.

**Comment by thecodrr** [comment]
It's already in progress: https://github.com/flathub/flathub/pull/3543
