### ISSUE TITLE
Session Expired bug again on Android 9

### ISSUE THREAD

**Issue by gpdevsoft** [streetwriters/notesnook#610]
**Describe the bug**
I haven't use the app for about 2 weeks and haven't even logged in through other devices, today I wanted add a note but when I opened the app it show warning "session expired" and the request to enter password appeared , unlike the reports made in December 2021 https://github.com/streetwriters/notesnook/issues/155, this problem does not seem to occur during the use of the app.

**Smartphone (please complete the following information):**
 - Device: [Samsung Galaxy]
 - OS: [Android 9]
 - Notesnook app's Version [1.8.9]

**Comment by thecodrr** [comment]
> I haven't use the app for about 2 weeks 

This is expected behavior. An access token has a limited time span during which if it isn't renewed it gets expired.

**Comment by gpdevsoft** [comment]
ok, thank you for clarification
