### ISSUE TITLE
popup 

### ISSUE THREAD

**Issue by ezekieldas** [streetwriters/notesnook#6114]
### What happened?

Whenever I paste text into the notesnook app I'm getting a popup for Notesnook Pro. 

Is this intentional? 

<img width="1355" alt="image" src="https://github.com/streetwriters/notesnook/assets/2140070/49063c50-49b9-4664-b800-7988e9fcc779">

### Steps to reproduce the problem

Paste text into the application.

### Version

Version 3.0.9 (240)

### Platform/OS

macOS

**Comment by thecodrr** [comment]
Fixed.
