### ISSUE TITLE
Can not start latest appimage (V 3.0.10)

### ISSUE THREAD

**Issue by ZigurdsG** [streetwriters/notesnook#6120]
### What happened?

Downloaded the lates appimage: https://github.com/streetwriters/notesnook/releases/download/v3.0.10/notesnook_linux_x86_64.AppImage
Tried to open as usual.

Please note! There is no such error with previous versions on Notesnook appimage:
https://github.com/streetwriters/notesnook/releases/download/v3.0.9/notesnook_linux_x86_64.AppImage
This version works as expected.

### Steps to reproduce the problem

Try to start app from console:
```
user@fatbox:~/Applications$ ./notesnook_linux_x86_64.AppImage
``` 

### Version

V 3.0.10

### Platform/OS

Linux

### Relevant log output

```shell
Squashfs image uses (null) compression, this version supports only xz, zlib.

Cannot mount AppImage, please check your FUSE setup.
You might still be able to extract the contents of this AppImage 
if you run it with the --appimage-extract option. 
See https://github.com/AppImage/AppImageKit/wiki/FUSE 
for more information
open dir error: No such file or directory
```

**Comment by thecodrr** [comment]
Fixed.
