### ISSUE TITLE
File upload failed recurring error popup 

### ISSUE THREAD

**Issue by Leviob** [streetwriters/notesnook#6125]
### What happened?

When opening the web app or iOS app, a message pops up. On iOS it says 

> File upload failed
> Please upgrade to Pro to upload attachments
> Copy Logs

On the web app this popup says "[Unknown] Please upgrade to Pro to upload attachments."
This popup goes away after a few seconds, but then comes back after a few more seconds. It has been days and it is still popping up. 

I have included the copied logs from the iOS popup. 

### Steps to reproduce the problem

I think I pasted some text and which included an image into Notesnook when this error popup first appeared. 

### Version

3.0.10-3a5b577-web

### Platform/OS

Firefox

### Relevant log output

```shell
@/private/var/containers/Bundle/Application/9F30E0DB-7519-4DB0-912A-BEDD4EFE5B95/Notesnook.app/main.jsbundle:1:3088874

generatorResume@[native code]

t@/private/var/containers/Bundle/Application/9F30E0DB-7519-4DB0-912A-BEDD4EFE5B95/Notesnook.app/main.jsbundle:40:5778108

s@/private/var/containers/Bundle/Application/9F30E0DB-7519-4DB0-912A-BEDD4EFE5B95/Notesnook.app/main.jsbundle:40:5778320

@/private/var/containers/Bundle/Application/9F30E0DB-7519-4DB0-912A-BEDD4EFE5B95/Notesnook.app/main.jsbundle:40:5491902

@/private/var/containers/Bundle/Application/9F30E0DB-7519-4DB0-912A-BEDD4EFE5B95/Notesnook.app/main.jsbundle:40:5491929

@/private/var/containers/Bundle/Application/9F30E0DB-7519-4DB0-912A-BEDD4EFE5B95/Notesnook.app/main.jsbundle:1:2363325

v@/private/var/containers/Bundle/Application/9F30E0DB-7519-4DB0-912A-BEDD4EFE5B95/Notesnook.app/main.jsbundle:1:2362074

y@/private/var/containers/Bundle/Application/9F30E0DB-7519-4DB0-912A-BEDD4EFE5B95/Notesnook.app/main.jsbundle:1:2362469

callReactNativeMicrotasks@/private/var/containers/Bundle/Application/9F30E0DB-7519-4DB0-912A-BEDD4EFE5B95/Notesnook.app/main.jsbundle:1:2364712

value@/private/var/containers/Bundle/Application/9F30E0DB-7519-4DB0-912A-BEDD4EFE5B95/Notesnook.app/main.jsbundle:1:2204813

@/private/var/containers/Bundle/Application/9F30E0DB-7519-4DB0-912A-BEDD4EFE5B95/Notesnook.app/main.jsbundle:1:2202915

value@/private/var/containers/Bundle/Application/9F30E0DB-7519-4DB0-912A-BEDD4EFE5B95/Notesnook.app/main.jsbundle:1:2204461

value@/private/var/containers/Bundle/Application/9F30E0DB-7519-4DB0-912A-BEDD4EFE5B95/Notesnook.app/main.jsbundle:1:2202873

value@[native code]

value@[native code]
```

**Comment by Leviob** [comment]
I was able to remove the popup by going to Settings > Profile > Attachments > Open Manager and manually deleting the attachments that were stuck trying to be uploaded.

**Comment by farringdon451** [comment]
Hi - #6525 was me. Thanks for the suggestion Leviob, but as far as I can see the iOS app does not have the delete attachments option? I deleted the app and reinstalled, and the problem went away ... until I manged to paste an image by mistake!

**Comment by Leviob** [comment]
3.0.18 just added the attachment manager to iOS under Account Settings! :raised_hands:

**Comment by farringdon451** [comment]
Perfect!

**Comment by ammarahm-ed** [comment]
Hi, delete the attachments in Settings -> Attachments Manager to fix the issue.
