### ISSUE TITLE
[Android] I have to open the app twice for it to show my notes

### ISSUE THREAD

**Issue by prkuctd** [streetwriters/notesnook#6189]
### What happened?

When set a biometric lock, I have to unblock the app. Then, it is loading forever. I have to kill it and launch again, unlock with biometric again. Then it works.

### Steps to reproduce the problem

Set a biometric lock
Unlock the app

### Version

latest

### Platform/OS

Android

**Comment by ammarahm-ed** [comment]
Hi, I am unable to reproduce this issue on android. Can you share more details or a screen recording of the issue.

What is your android version?
What is your phone model?

**Comment by ammarahm-ed** [comment]
Tried a fix in #6233

**Comment by prkuctd** [comment]
@ammarahm-ed It is indeed fixed, thank you so much! I wish you all the best, glad to be a pro user.
