### ISSUE TITLE
Failed to upload part at offset 0: no etag found

### ISSUE THREAD

**Issue by tharrisone** [streetwriters/notesnook#619]
### What happened?

Trying to sync my notes and they never sync. It only shows the error:
Failed to upload part at offset 0: no etag found

### Steps to reproduce the problem

I imported my notes from Joplin and got a zip file which I imported into Notesnook. 
The import went through and all my notes were there but they won't sync at all. 

I'm using Firefox 101 on Arch Linux, using the web gui. 

### Version

Online web gui

### Platform/OS

Firefox

**Comment by thecodrr** [comment]
Hey, it seems the attachments aren't uploading. Can you try a different browser? Chrome or Edge?

**Comment by tharrisone** [comment]
> Hey, it seems the attachments aren't uploading. Can you try a different browser? Chrome or Edge?

Actually I used the Linux client to import the zip and everything is sync. Thanks I'll close this issue.
