### ISSUE TITLE
Group notes by year after import is buggy

### ISSUE THREAD

**Issue by nicosomb** [streetwriters/notesnook#6191]
### What happened?

I have a `NaN` date when I import old notes (created in 2018) and when I want to group notes by year.

see #4730 

### Steps to reproduce the problem

Import old notes (with a creation date in 2018, it also occurs with a recent date in fact). 
Try to group your notes by creation year. 
You've got a `NaN` date. 

### The information about my note

<img width="385" alt="Capture d’écran 2024-07-17 à 15 07 10" src="https://github.com/user-attachments/assets/d5d1f7ea-7f8a-4b33-aba4-d58f978bb167">

### The notes, grouped by year

<img width="186" alt="Capture d’écran 2024-07-17 à 15 07 16" src="https://github.com/user-attachments/assets/9bc10b2c-a290-475c-93b2-143a56d9c779">

### Version

3.0.10-3a5b577-desktop

### Platform/OS

macOS

**Comment by DidierLmn** [comment]
I've got the same problem, but weirdly "group by week" works without problems

**Group by week**
![image](https://github.com/user-attachments/assets/488ead4d-5ae5-4243-b955-c3c7b825c3eb)

**Group by month**
![image](https://github.com/user-attachments/assets/f2e86ea1-1fb3-4e40-b479-b51855222feb)

**Group by year**
![image](https://github.com/user-attachments/assets/d902b20f-41ea-48c6-bfcc-3b8b547ddb67)

**Note Properties**
All notes have in the properties the proper created at and edited at
![image](https://github.com/user-attachments/assets/0d4a8e4c-711b-4b53-a7c6-ac7fac20611d)

**Comment by dogception** [comment]
Same exact problem after importing from Markdown with `created_at` and `updated_at` frontmatter
