### ISSUE TITLE
Option to disable new note placeholder text

### ISSUE THREAD

**Issue by TheMatjaz** [streetwriters/notesnook#620]
### What problem are you facing?

When creating a new note, some placeholder text is provided in the note body (a quote, usage hints etc.). This is:

1. Making it harder to focus on what need to be written down
2. Sometimes appears on non-empty notes and overlays with the existing text or images (related: #526)

### What's the solution you'd like to see in Notesnook?

Add an option in the Settings menu to disable the placeholder text from appearing. Many programs offer "daily tip on startup", but they can be disabled.

**Comment by thecodrr** [comment]
> Sometimes appears on non-empty notes and overlays with the existing text or images

This has been fixed in the new editor.

**Comment by candroid-man** [comment]
I will be adding this to #412

**Comment by thecodrr** [comment]
This was removed in the new editor.
