### ISSUE TITLE
Ability to created nested folders

### ISSUE THREAD

**Issue by Marin-Kitagawa** [streetwriters/notesnook#6216]
### What problem are you facing?

Now, there is only one option. Create a notebook and create notes inside it. It doesn't offer more organized workflow that comes with nested folders.

### What's the solution you'd like to see in Notesnook?

I want to have nested folders implemented in Notesnook. 

1. Nested folders for Notebooks
2. Nested folders for notes

**Comment by thecodrr** [comment]
NN already has nested notebooks.

**Comment by gilesknap** [comment]
@thecodrr I've just started using NN today and it looks to me like there is only a single level of hierarchy in nested notebooks. Root notebooks can container others but it is not at all obvious how to create notebooks inside non-root notebooks. Am I missing something?
