### ISSUE TITLE
Encrypted Attachments for Notesnook Basic is a must!

### ISSUE THREAD

**Issue by Ehab-d** [streetwriters/notesnook#6282]
### What problem are you facing?

One of the main principles of Notesnook is encryption. Everything is encrypted, no matter which plan you choose.

### What's the solution you'd like to see in Notesnook?

The Basic plan in Notesnook doesn't include encryption for attachments, which is disappointing. I hope you reconsider and make encrypted attachments available for free to Basic users.

### Additional context

Make everything encrypted in Notesnook reflect what Notesnook is built on...encryption.

**Comment by thecodrr** [comment]
There are no attachments in Notesnook Basic plan. So this doesn't make sense.
