### ISSUE TITLE
Can't escape Anchor links when adding space

### ISSUE THREAD

**Issue by jermanuts** [streetwriters/notesnook#6432]
### What happened?

After selecting text and inserting a link, I can't escape it if I won't to continue writing something on the same line.

![image](https://github.com/user-attachments/assets/37589fc6-22ab-4eaf-ac00-dbdc99d65cfb)

### Steps to reproduce the problem

insert link and try to press spacebar and continue typing

### Version

3.0.13

### Platform/OS

Windows

**Comment by thecodrr** [comment]
Fixed

**Comment by zdivelbiss** [comment]
It seems this issue has reappeared.

<img width="145" height="49" alt="Image" src="https://github.com/user-attachments/assets/e90b59c5-0c0a-4978-b196-1ecbdfdd5f0f" />

Installed from Flatpak
v3.3.8-406c637-desktop

**Comment by jermanuts** [comment]
@zdivelbiss It is half baked fix, sometimes it happens and sometimes it doesn't
