### ISSUE TITLE
Desktop: Multiple simultaneous downloads of updates by repeated clicks

### ISSUE THREAD

**Issue by paulrudy** [streetwriters/notesnook#6468]
### What happened?

Clicking "Check for Updates" while downloading update results in an additional simultaneous download of the update for each click.

### Steps to reproduce the problem

1. Click "Check for Updates" when an update is available.
2. While the app is downloading, click "Check for Updates" (or whatever is displayed—downloading progress?) again
3. See the progress indicator alternate between the % progress of two simultaneous update downloads

### Version

v3.0.13

### Platform/OS

macOS

**Comment by Adamantt777** [comment]
I have to reinstall the most recent version manually and dissable auto updates because it got in a loop saying "update ...0.16 is downloaded (needs restart)" and then when closing the app got self deleted. the error happend when its updating, leaving only empty folders.
