### ISSUE TITLE
APKs Causing Google Play Update Error

### ISSUE THREAD

**Issue by Hamster45105** [streetwriters/notesnook#6473]
### What happened?

I download the Notesnook from the GitHub releases. Despite this, Notesnook still appears in the Google Play updates section, even when it is already updated to the latest version. Clicking the update button in Google Play just gives an error saying it can't update (I suspect because of conflicting signatures?). This is annoying because Notesnook is stuck in my updates list all the time, with the message "Couldn't update". 

I have plenty of other apps that I download from alternate sources AND are available on Google Play that do not have this problem.

I know that Ente uses different app IDs for the Google Play and GitHub releases versions, maybe this could be a possible solution?

### Steps to reproduce the problem

1. Download and install the Notesnook APK
2. Go to the updates section in Google Play and try to update Notesnook when it appears
3. See the problem

### Version

v3.0.15

### Platform/OS

Android

**Comment by thecodrr** [comment]
While I agree there's no intention of "fixing" this will break a lot of users' installation especially since the GitHub apk isn't overwritten by the Google Play one.

**Comment by Hamster45105** [comment]
If there is no intention to fix this, is there any possible workaround?

**Comment by thecodrr** [comment]
There's no immediate plan to fix this. I don't think there's a workaround aside from just ignoring it.

**Comment by Hamster45105** [comment]
Ok, thanks. I'll leave this issue open in case it can be fixed in the future.
