### ISSUE TITLE
Publish FOSS version on Github.

### ISSUE THREAD

**Issue by duck09** [streetwriters/notesnook#6476]
### What problem are you facing?

FOSS version of Notesnook is only available on F-Droid and not on Github. This leaves people who would prefer  not to use F-Droid and get the APK directly from the developers through Github without a FOSS version of Notesnook.

### What's the solution you'd like to see in Notesnook?

FOSS builds of Notesnook are uploaded to Github with each release.

### What alternatives have you considered?

Using F-Droid.

**Comment by thecodrr** [comment]
This is already happening.
