### ISSUE TITLE
[Self-hosted] Add ability to back up to/from caldav/carddav/webdav servers like radicale/baikal or sabredav

### ISSUE THREAD

**Issue by applesoff** [streetwriters/notesnook#6490]
### What problem are you facing?

I want an easy storage solution for the self hosted option to back up to a server that i could hook other apps into.

### What's the solution you'd like to see in Notesnook?

 I run a radicale server that stores my contacts and calendar events. Adding notes with a fantastic front end like notesnook would be amazing for easy access to the notes

**Comment by thecodrr** [comment]
Not planned.
