### ISSUE TITLE
Winget update is at version 2.6.16

### ISSUE THREAD

**Issue by katastrophe92** [streetwriters/notesnook#6520]
### What problem are you facing?

I always choose first to use winget to install, reinstall and update my installed software.

### What's the solution you'd like to see in Notesnook?

Update to latest version on winget.

### What alternatives have you considered?

Stay version 2.6.16

### Additional context

Hello and thank you Notesnook team😘 for this amazing software. It is not a must to update the winget version but it would be great.

**Comment by thecodrr** [comment]
Feel free to open a full request at https://github.com/microsoft/winget-pkgs
