### ISSUE TITLE
Vim Keybinds, pretty please. 

### ISSUE THREAD

**Issue by Fr0g-Not-Found** [streetwriters/notesnook#6526]
### What problem are you facing?

I would be head over heals in love with this program if I could use Vim style key binds for the editor. 

### What's the solution you'd like to see in Notesnook?

Some way to enable those keybinds, along with keybind menu to view all keybinds.

### What alternatives have you considered?

once you enable 3rd party plugins, if it works similar to the way it does with obsidian.. another individual might be able to do it.. if this is somehow outside of the scope of notesnook.

**Comment by thecodrr** [comment]
I get the appeal but a rich text editor is not the intended use case for vim or vim-like bindings. It'll be very cumbersome to use (and add).

This has been requested before but it is out of scope for Notesnook.
