### ISSUE TITLE
Persistent font choice.

### ISSUE THREAD

**Issue by MsJonesy** [streetwriters/notesnook#655]
### What problem are you facing?

I could’ve sworn the issue of the font defaulting back the basic one with each return was going to be resolved.

I’d rather not have to switch fonts before I type next sentence in a list or the next paragraph. Nor, do I want to have type everything out, while looking at what I consider an ugly font, to then have to remember change everything at the end.

### What's the solution you'd like to see in Notesnook?

A permanent selection of the font within a note. Or, better yet, a permanent selection within the settings.

### What alternatives have you considered?

Letting my subscription run out and finding a different app.

**Comment by thecodrr** [comment]
This has been fixed with the new editor.
