### ISSUE TITLE
When doing a multi-word search, the app searches on titles and contents but does it separately. If part of the words is in the title, and the rest in the note contents, the record will not appear on the search results. 

### ISSUE THREAD

**Issue by jrcacd** [streetwriters/notesnook#6607]
### What problem are you facing?

When doing a multi-word search, the app searches on titles and contents but does it separately. If part of the words is in the title, and the rest in the note contents, the record will not appear on the search results. 

If we search by "abc OR xyz OR mno" then, the app will return notes with one or another word. But I need to get the notes with all words on the title OR the note contents, OR part on the title AND part on the note contents. 

### What's the solution you'd like to see in Notesnook?

.

**Comment by thecodrr** [comment]
You can do OR search for this. Example: "hello OR world".

**Comment by jrcacd** [comment]
I need to find notes with "hello" on the title AND "world" on the contents.

**Comment by thecodrr** [comment]
That would need something like `title: hello AND content: world` right?

**Comment by jrcacd** [comment]
When I reread what I wrote, I wasn't clear at all. So I revised the text.
The thing is that when searching, part of the words may be in the title and another part in the content, or not. The app should combine the content of both fields and then perform the search. So no matter where the words are, their notes will appear in the search results. And so we don't need to try different combinations of words to get to what we want to find.

**Comment by thecodrr** [comment]
Got it.

**Comment by thecodrr** [comment]
This is now working as expected in #6823:

1. If you have 3 notes with titles: "a note", "wonderful note" and "interesting note" and you search for:
   1. `note`: you'll get all 3 notes
   2. `wonderful OR note`: you'll get all 3 notes
   3. `wonderful note`: you'll just get the "wonderful note"
2. If a part of the query is in the content, you'll have to use `OR` expression. For example:
   1. If you have 2 notes like so: `{ id: 1, title: "Hello world", content: "something" }` and `{ id: 2, title: "Another note", content: "This is something content"}`. Searching for `world OR something content` would return both notes but searching just for `world` will only return `id: 1`.

The query `abc OR xyz OR mno` also works as expected as in it searches for `abc`, `xyz`, and `mno` in both title AND content separately so if `abc` is in content and `xyz` is in the title of a note, you'll get both in the final results.

I think this functions very close to how you'd expect as adding more words to the query now narrows it down. You can use double quotes to search for phrases (previously this was the default which is unexpected): `"some long phrase"` will return notes that exactly have the "some long phrase" sequence anywhere in the note (title or content).

**Comment by thecodrr** [comment]
> The app should combine the content of both fields and then perform the search.

What you suggested here is currently not possible. In the future, you'll be able to do things like:

1. Specify the exact field you want to search in (e.g. `title: abc OR content: dgf`)
2. Change the default boolean expression (e.g. default to OR instead of AND)
