### ISSUE TITLE
Unable to add lines above a table in iOS when table is on first line

### ISSUE THREAD

**Issue by Leviob** [streetwriters/notesnook#6615]
### What happened?

If the first line of a note is a table, it is impossible to add a new blank line above the table. 

In the web app, pressing the left arrow key bumped the table down and added a new line automatically. :+1: 

I would like to be able to place the cursor outside the table on the first line, and return to add a new line. Currently, it is only possible to place the cursor inside the first cell of the table. 

### Steps to reproduce the problem

Create a table on the first line of a note. Try adding text above it on iOS.

### Version

3.0.18

### Platform/OS

iOS

**Comment by ammarahm-ed** [comment]
Hi, if you double tap on the empty space in the header above editor, it should add a new line above the table.

**Comment by Leviob** [comment]
Okay, that's a helpful tip. Thank you.
