### ISSUE TITLE
Scroll not working on main window of settings in brave browser

### ISSUE THREAD

**Issue by alihamuh** [streetwriters/notesnook#6622]
### What happened?

when I am using the webapp on an desktop (Win 10 Brave Browser) I can not scroll to log out in the settings. I can not scroll in any settings. The left side (user account, customization, import &export etc.) is scrollable, the right side not.

### Steps to reproduce the problem

Use scroll in Settings on brave browser

### Version

3.0.18

### Platform/OS

Linux, Other browser

**Comment by thecodrr** [comment]
Fixed in v3.0.19. You might need to force refresh to update to the new version.
