### ISSUE TITLE
IOS share sheet not working again?

### ISSUE THREAD

**Issue by gsudre** [streetwriters/notesnook#6625]
### What happened?

I just downloaded NotesNook and the iOS share sheet doesn’t seem to work. I noticed previous bug report here, but apparently the issue had been solved and the ticket closed. However, new notes I create using the share feature in 3.0.18 are not showing up in NotesNook. Maybe the bug is back? Or
Do I need a paid subscription for that feature to work? Thanks!

### Steps to reproduce the problem

Go to any website, share, select NotesNook, then switch to web clipper, then save. 

### Version

3.0.18

### Platform/OS

iOS

**Comment by ammarahm-ed** [comment]
Hi, I just tested this on iOS 18, share sheet is working.
