### ISSUE TITLE
Automatic hyperlink creation not working on Linux Firefox web app

### ISSUE THREAD

**Issue by Leviob** [streetwriters/notesnook#6641]
### What happened?

Feature request #4454 resulted in two improvements to how hyperlinks can be created in notes. (I'm not sure what the PR number is). Links pasted into the editor automatically have the hyperlink created. If text is highlighted when a link is pasted, the text becomes a hyperlink to the copied link. This works on iOS, Android, Windows in Firefox and Chrome web apps, and on Linux in the Chrome web app. 

However, in the latest **Firefox 130.0, on Ubuntu**, this does not work at all. It behaves the same as it did before this update, where pasting a link just pastes the text and it does not turn into a hyperlink automatically. Highlighting text and pasting a link just replaces the originally highlighted text. 

I have tried launching Firefox in safe mode with all extensions disabled, disabling Firefox's enhanced tracking protection, and it still behaves as described above. 

### Steps to reproduce the problem

Paste a link into a note using the Firefox web app on Linux.
Select text and paste a link. 

### Version

3.0.18-5f0d14f-web

### Platform/OS

Linux, Firefox

**Comment by thecodrr** [comment]
Tested on Firefox 130.0.1 and it works normally.

**Comment by Leviob** [comment]
What OS did you test this on?

**Comment by Leviob** [comment]
This seems to be an issue with TipTap.
