### ISSUE TITLE
Feature Request: Trigger App Lock on Screen Lock

### ISSUE THREAD

**Issue by USCTrojan011** [streetwriters/notesnook#6646]
### What problem are you facing?

I want the app to lock only when the system locks. As long as the screen is on, the app can remain unlocked.

### What's the solution you'd like to see in Notesnook?

Implement an app lock setting that locks the app when the system screen locks.

### What alternatives have you considered?

You can set the app lock timeout, but then the app locks too soon, or can remain unlocked even after the system locks.

### Additional context

Currently, with App Lock enabled, you must unlock the app when it is launched and optionally after a specified timeout. Is it possible to trigger the app to lock when the screen locks? E.g. On desktop when the screen lock is triggered by the timeout in system system setting or when the user presses Super + L. For mobile, this would be when the screen lock timeout is reached or when the user pressed the power button. This could be in addition to or alternative to the configured app lock timeout.

**Comment by thecodrr** [comment]
You can set the App Lock Timeout to Immediately and it'll work exactly as you want. There's no way to know that the screen has locked or not.

**Comment by USCTrojan011** [comment]
For clarification, this is not the behavior when App Lock Timeout is set to Immediately. With it set to immediately, as soon as you move to another application, the app locks. This makes it very annoying to try to copy data from another app into Notesnook because every time you switch, you must re-unlock Notesnook. E.g. open Notesnook, unlock the app, switch to Google Keep and copy some data, switch back to Notesnook, now you have to re-unlock the app.

My hope was that there is some way to leave Notesnook unlocked until the screen locks. E.g. open Notesnook, unlock the app, switch to Google Keep and copy some data, switch back to Notesnook and paste, switch back to Keep and copy, switch back to Notesnook and paste, etc. Notesnook only locks again when I press Super-L (desktop) / click the power button (Android) or when the screen times out.

Regardless, thank you for considering this request.
