### ISSUE TITLE
links to external local files

### ISSUE THREAD

**Issue by Stef4678** [streetwriters/notesnook#6655]
### What problem are you facing?

I cannot drag files over Notesnook to add it as links. Also I can not create link to external local files manually.

### What's the solution you'd like to see in Notesnook?

To let us create links to local files outside of NoteNook

**Comment by thecodrr** [comment]
You can create local links using `file://` protocol. Clicking on them will open them as normal. Drag/drop support adds the file as attachment - not a link (which is rarely required since links will break when syncing to other devices).
