### ISSUE TITLE
Minimize Button is bugged. Twice available

### ISSUE THREAD

**Issue by PricacyPro0** [streetwriters/notesnook#6657]

**Comment by thecodrr** [comment]
Will be fixed in the upcoming version.

**Comment by PricacyPro0** [comment]
Hey, It doesn*t seem that it has been fixxed on Fedora Linux. 
This has been a while ago, and it never got fixxed for me. 
Low Priority, but just wanting to let you know. 
![Image](https://github.com/user-attachments/assets/79da2585-c784-4b7c-8010-710d460b3344)

I am on the latest Version. 
I checked. 

Version: 3.0.19-53a1e2c-desktop

Maybe this has something to do with the method of installation. Maybe it*s different if you use .rmp or .flatpack. 
I am not sure how i install Notesnook. But it*s one of these two methods.
