### ISSUE TITLE
Option to Purchase Lifetime Subscription. 

### ISSUE THREAD

**Issue by libbyslayer** [streetwriters/notesnook#6687]
Option to Purchase Lifetime Subscription.

<sub><a href="https://huly.app/guest/streetwriters?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzBhNzc2Y2M3ZDZhNTZhOGY5NTBiZDAiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWJkdWxsYWhhdHRhLXN0cmVldHdyaXRlci02NzA4YjYxMi0wMDA4OTgyNWM5LTRkY2EzOCJ9.PJ0uLF8HrVnr7BFIVnQkoETxfZgPVd940qQvg21yrS4">Huly&reg;: <b>NN-6553</b></a></sub>

**Comment by thecodrr** [comment]
No plans for this.
