### ISSUE TITLE
Legacy option to set Nominee and share notes

### ISSUE THREAD

**Issue by libbyslayer** [streetwriters/notesnook#6691]
### What problem are you facing?

Since many sensitive data and informations are saved in notes which may be helpful and necessary for our friends and family post our death (god forbid), option to set someone as Nominee in Legacy option and share all or some set notes.

### What's the solution you'd like to see in Notesnook?

Criterias can be Inactive account or Nominee can claim based on set rules, conditions we set. (Just like Google Inactive Manager)

### What alternatives have you considered?

*No response*

### Additional context

*No response*

<sub><a href="https://huly.app/guest/streetwriters?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzBhODM4ZGM3ZDZhNTZhOGY5NTI3YmQiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWJkdWxsYWhhdHRhLXN0cmVldHdyaXRlci02NzA4YjYxMi0wMDA4OTgyNWM5LTRkY2EzOCJ9.DSi1m1qHOzR-OYgsViIKag3JqHu1v-id1K2LwQVeETQ">Huly&reg;: <b>NN-6557</b></a></sub>

**Comment by thecodrr** [comment]
This doesn’t make sense in an E2E encrypted app since we have no control over who can access your data - only you have that control. So you can use whatever mechanisms you have available to reveal your account password in case of any unfortunate event and then that person can login to your account etc.

**Comment by libbyslayer** [comment]
1. Bitwarden implemented similar feature-

Emergency access allows users to designate and manage trusted emergency contacts, who can request access to their vault in cases of emergency.

https://bitwarden.com/help/emergency-access/

2. Ente has planned Legacy feature.


many such E2E apps are considering since this is crucial for an app.

**Comment by thecodrr** [comment]
It doesn't matter if someone implemented it or not. The whole premise of E2E is that ONLY YOU can access your data.

With that being said, you could just share your account password or store it in Bitwarden and bypass all this complexity altogether.

> many such E2E apps are considering since this is crucial for an app.

I don't think every app needs to have something like this.
