### ISSUE TITLE
"Notesnook Discord Community" takes us to Invalid Link

### ISSUE THREAD

**Issue by ifajul89** [streetwriters/notesnook#6701]
### What happened?

The bug is not in the app. But in the issues section of Github. There is a "Notesnook Discord Community" section that doesn't take us to the actual Notesnook community but to an invalid link

### Steps to reproduce the problem

Just add the actual link to discord.

### Version

0

### Platform/OS

Other browser

### Relevant log output

*No response*

<sub><a href="https://huly.app/guest/streetwriters?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzBkMGZmOWRkOThmNGIzNTk2ODdhZDAiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWJkdWxsYWhhdHRhLXN0cmVldHdyaXRlci02NzA4YjYxMi0wMDA4OTgyNWM5LTRkY2EzOCJ9.qbNhY8ANJS0L0yKZQcHbWzU1GzOlzVFhNAePSEWsMDg">Huly&reg;: <b>NN-6567</b></a></sub>

**Comment by ammarahm-ed** [comment]
Thanks for reporting. This has been fixed now.
