### ISSUE TITLE
Pressing tab when in front of a checkbox adds a tab character instead of indenting the checkbox

### ISSUE THREAD

**Issue by USCTrojan011** [streetwriters/notesnook#6710]
### What happened?

When you press TAB after creating a check-box, a tab character is inserted after the checkbox rather than indenting the checkbox:

Below, `|` represents the cursor.

If you have the following and press TAB

```
- [ ] |
```

you get:

```
- [ ]     |
```

rather than:

```
    - [ ] |
```

### Steps to reproduce the problem

1. Create a new note.
2. Click the checklist button to create a checklist.
3. Press tab.

### Version

3.0.18-5f0d14f-desktop

### Platform/OS

Linux

**Comment by thecodrr** [comment]
This is working as intended.
