### ISSUE TITLE
Not able to create Task List on Android since new update on 19.10.2024

### ISSUE THREAD

**Issue by PricacyPro0** [streetwriters/notesnook#6724]
### What happened?

Hi,
Since this release Android v3.0.19, I am not able anymore to create task lists. 
Out of 10 times trying it worked once.
I am on graphenos, and got the release directly from github via Obtanium. 
I have Pro subscribtion. 

In this screen recording I am clicking on thefirst "Task list" button several times. (it doesn*t show where I click)
But nothing happens. 
Writing something and then trying again doesn*t solve the issue. 

https://github.com/user-attachments/assets/80697578-2e52-4711-b792-7519108afccc

Sometimes  If you try to create a Task List too often, the App freezes until 20 Seconds. 
![Screenshot_20241019-170427](https://github.com/user-attachments/assets/23c1ad9c-685d-44c5-a091-66bd14ce9dd9)

Another issue I found is that in an older Note Document before the new update where I already had a Task List: when trying to create  a new bullet point by clicking on enter, it doesn*t create a new bullet point as usual, but instead jumps out of the task list. You are not able to create more then one Task in your list. This isn*t a user error. It*s a new bug. 
I tried it in different Notes Documents. I always have this issue. 

https://github.com/user-attachments/assets/fd44260d-5051-437b-96cf-a213ea9c4e24

I hope this is detailled enough. 
Next time I will activate the thing where it shows where exactly you click on your screen. 

Notesnook is getting better and better. 
Thanks for your great work. 

### Steps to reproduce the problem

Try to create Task Lists in a new note document. 

### Version

Android v3.0.19

### Platform/OS

Android

**Comment by thecodrr** [comment]
Fixed in v3.0.20.
