### ISSUE TITLE
broken interface. Duplicate minimize icon

### ISSUE THREAD

**Issue by victor-mendes25681** [streetwriters/notesnook#6727]
### What happened?

Duplicate minimize icon.  broke after an update. I use the appimage version

### Steps to reproduce the problem

![fgj](https://github.com/user-attachments/assets/e5b9551a-57ee-4bd9-98ca-84a619af9b30)

### Version

3.0.18-5f0d14f-desktop

### Platform/OS

Linux

**Comment by ammarahm-ed** [comment]
This has been fixed.
