### ISSUE TITLE
NN v3.0.18 Win11 App hangs at logo on startup

### ISSUE THREAD

**Issue by jmreidmj** [streetwriters/notesnook#6789]
### What happened?

Nextnook v3.0.18 hangs at logo screen (pulsing) when I start the app on Windows 11.
I have been migrating 28k notes from Evernote over the past week or more. Yesterday, I started seeing a message pop up every 5 seconds on the Windows app "Unknown Unexpected end of JSON input". Did not see any issues, until this morning when I rebooted and Notesnook would not open, just hangs at the logo screen.
NN v3.0.18

### Steps to reproduce the problem

Restarted NN Windows app and rebooted a couple times, still hanging at NN logo.  Have not yet tried running Notesnook Importer again. 
I have been using Notesnook Importer to migrate 28k notes from Evernote. Have successfully migrated 75% of the 28k notes from Evernote, when the Windows app started showing error message about "Unknown Unexpected end of JSON input". At this point it still seemed to be inserting new notes successfully despite the error popping up every 5 seconds.  I did grab a copy of the logs yesterday.[notesnook-logs.zip](https://github.com/user-attachments/files/17556168/notesnook-logs.zip)

### Version

v3.0.18

### Platform/OS

Windows

### Relevant log output

2024-10-28T15:25:52.641Z | INFO | [notesnook-web]: Sync status updated: synced [2643ms] 
2024-10-28T16:51:49.787Z | INFO | [notesnook-web]: Sync status updated: failed [5157146ms] 
2024-10-28T16:51:49.788Z | ERROR | [SignalR::SyncHub]: Error: Connection disconnected with error 'Error: WebSocket closed with status code: 1006 (no reason given).'.
    at Object.log (https://app.notesnook.com/assets/index-DZThMtzJ.js:405:33583)
    at o_._stopConnection (https://app.notesnook.com/assets/index-DZThMtzJ.js:170:54173)
    at features.reconnect.transport.onclose (https://app.notesnook.com/assets/index-DZThMtzJ.js:170:52149)
    at a_._close (https://app.notesnook.com/assets/index-DZThMtzJ.js:170:43772)
    at o.onclose (https://app.notesnook.com/assets/index-DZThMtzJ.js:170:42708) "{}" [5160155ms] 
2024-10-28T16:51:49.789Z | INFO | [notesnook-web]: Sync status updated: failed [2ms] 
2024-10-28T16:51:49.789Z | ERROR | Error: WebSocket closed with status code: 1006 (no reason given).
    at a_._close (https://app.notesnook.com/assets/index-DZThMtzJ.js:170:43780)
    at o.onclose (https://app.notesnook.com/assets/index-DZThMtzJ.js:170:42708) "{}" [5160156ms] 
2024-10-28T17:22:11.792Z | INFO | [notesnook-web]: Page visibility changed. Reconnecting SSE... [1822003ms] 
2024-10-28T17:22:12.110Z | INFO | [notesnook-web]: Sync status updated: syncing [318ms] 
2024-10-28T17:22:12.117Z | INFO | Auto sync requested [1822328ms] 
2024-10-28T17:22:12.128Z | INFO | Starting sync "{\"type\":\"full\",\"offlineMode\":false}" [11ms]

**Comment by jmreidmj** [comment]
Forgot to mention Notesnook Importer v2.4.0

**Comment by thecodrr** [comment]
Try logging in on the web app and see if majority of your notes are there. You might need to reset and start the import again.

The `Unknown Unexpected end of JSON input` error indicates the .zip file you got from the importer.notesnook.com contains invalid notes or its too big and it can't parse it.

**Comment by jmreidmj** [comment]
Abdullah,

The zip file being imported when the errors began is 1.67 GB.
The .enex notebook being imported has 891 notebooks and it is 500 MB. (not zipped)

When you say ... might need to reset and start again, pls give more details on reset.
My desktop client has been hung since this error happened, and I'm not clear about how best to restore the NN desktop app.

Greatly appreciate your time and feedback on this.

thanks,
Mike

**Comment by jmreidmj** [comment]
Prior to the importer error, I had successfully imported ~20k notes with ~8k remaining. I have identified the batch of EN Notebooks and narrowed it down to one large notebook that was being processed at the time of failure. I have spot-checked and it appears all the preceding notes have been imported successfully (the note counts match by notebook).

If possible, I want to avoid re-starting the import process from the beginning. I can easily restart the import at any specific notebook as I have all the enex files saved, and I know what EN notebook, where to resume .

I have been using the NN webclient since the import failure. I would like to get the desktop client back up, but I don't know what will happen with sync when desktop client is restarted. I would like to purge any imports that were in-flight on the Windows desktop app. Everything I see on NN cloud looks good to me now, and I know where to restart. But, need some guidance on how to get desktop client back in the saddle without polluting my good NN database on cloud.

The final question is what to do about the notebook that caused the import to fail. I've browsed it in EN and don't see anything. Some of those notes are 6 years old, and may have flaws the importer can't handle (there's been a lot of updates in EN over last 6 yrs). I will split the large offending notebook into smaller chunks, and hopefully identify the one or few notes that break importer and just copy them manually.

Does it matter which client used to run the import, webclient or desktop?
Thanks again.

**Comment by thecodrr** [comment]
@jmreidmj okay, that's good news then. You just need to reset the desktop app and relogin. You can do that like this:

1. Close the app
2. Delete this directory: `%APPDATA%\Notesnook` (paste it into File Explorer and it will work)
3. Restart the app and log back in

**Comment by jmreidmj** [comment]
@thecodrr,

I closed NN desktop app, deleted %AppData%/Notesnook directory, and re-started the app ... but it still hangs at logo screen (waited 15 mins, no change).
Could this issue be caused by a failed auto-update? Currentlly installed desktop is v3.0.18. I see that v3.0.19 was released about the time my import failed.
Thinking next step might be uninstall/reinstall NN desktop app. I have saved my recovery key.

**Comment by thecodrr** [comment]
Yes, a reinstall is probably needed. Not sure why its stuck though since all data has been deleted. Makes me wonder if the issue even was with the data in the first place...

In any case, try reinstalling. Your data is synced so nothing to worry about

**Comment by jmreidmj** [comment]
I finally tracked down the notes causing import issues.  Notes with a "back-link" were skipped by the importer.  Didn't see an error message.  Fortunately, only a few of these so I handled manually,

Also, had one note that was an empty webclip, created in 2022.  It was the only note in a notebook and Evernote created an .enex file, but the importer wouldn't import it.  

Whatever caused my desktop app to hang and the "end of JSON string" errors has not returned, and I've written it off to multiple colliding software updates and a power surge.

I've completed the migration of 20k+ notes from Evernote to Notesnook.  Yippee!!
Thanks for your patience and kind assistance.

**Comment by thecodrr** [comment]
@jmreidmj would love if you could upload the buggy ENEX files so I can fix the importer.

**Comment by jmreidmj** [comment]
@thecodrr

(1) Restored - Ann Coulter Here Are the Nutcases Who Believe in ‘Replacement’.enex

Attached file produced the following "empty" webclip in NN.

[image.png]

(2) Visa, Mastercard, American Express to Track Gun Purchase Info in CA.enex
I'm not able to reproduce the issue with back-links. When I rerun these thru Importer, they work fine now.
