### ISSUE TITLE
Keyboard is shown after checking off an item off checklist

### ISSUE THREAD

**Issue by candroid-man** [streetwriters/notesnook#679]
### What happened?

This only happens when you have a cursor from, for example, adding text. When you check off an item from a checklist, the keyboard will open and the app will scroll to the cursor.

### Steps to reproduce the problem

1. Create a checklist of a few items
2. Tap on any text within the note
3. Collapse the keyboard
4. Check off an item from the checklist
5. See error

### Version

v2.00

### Platform/OS

Android

**Comment by thecodrr** [comment]
Fixed. Will be there in the next version.
