### ISSUE TITLE
Titlebar buttons not displayed correctly on GNOME 47

### ISSUE THREAD

**Issue by franjsco** [streetwriters/notesnook#6816]
### What happened?

The titlebar buttons (minimize, maximize, close) are not displayed properly. 
This issue occurs in both light and dark theme modes. Despite the display issue, the buttons are functional.

Additional information:
- OS: Fedora 41
- Desktop Environment: GNOME 47

![Image](https://github.com/user-attachments/assets/838a204a-650c-4d48-a80e-cc55e3f52b4a)

### Steps to reproduce the problem

1. Open the application

### Version

3.0.19-53a1e2c-desktop

### Platform/OS

Linux

**Comment by mewithout** [comment]
![Image](https://github.com/user-attachments/assets/fcedda22-f9fe-446a-b39a-50e455782092)
I have the same problem with Fedora 41 Gnome

**Comment by franjsco** [comment]
After updating to version 3.0.22-c203b035c-desktop , it seems that the issue is no longer present. 


![Image](https://github.com/user-attachments/assets/5f7aa644-6b5b-422a-b8f1-b68974dd3f15)

**Comment by franjsco** [comment]
I close the issue as resolved.
