### ISSUE TITLE
Monograph links need to be unpublished and published again

### ISSUE THREAD

**Issue by andrejmoltok** [streetwriters/notesnook#6851]
### What happened?

I am sharing language articles with our fan gaming community andjust yesterday I noticed that the published monographs are unavailable.

After unpublishing and re-publishing them they are working, accessible again, but I don't know for how long.

Could this be due to the recen uipdate?

### Steps to reproduce the problem

I am not sure if it's reproducable.

### Version

3.0.19-22dcba840-web

### Platform/OS

Linux

### Relevant log output

```shell

```

**Comment by thecodrr** [comment]
Fixed.
