### ISSUE TITLE
A lable feature request with overall suggestion

### ISSUE THREAD

**Issue by Sinacs** [streetwriters/notesnook#6889]
### What problem are you facing?

**Notesnook currently lacks flexibility to monitor and track particular things.**

Try to imagine a case, you are now writing a science note, and you suddenly find that one paragraph of content has some logical mistakes, but if you try to correct it might cost you couple of hours, so you want to solve it later. How would you do?

**Currently, we can have 4 different methods to handle this problem:**
 
1. Create a callout block, writing down the problem, and then back to it later.
2. Create a highlight word "Logical Mistakes", and then back to it later.
3. Create a reminder and fill in a form to remind me which note and which line text that I have problem to solve.
4. Create a resident to-do list and write down the problem and details, add an internal link, and then check the list daily.

As you can see, all the above methods are not a productive way to go through the problem.

### What's the solution you'd like to see in Notesnook?

**What exactly are the needs to solve this problem?**

- A quick and easy way to create a label. (It purposes to create an exact location anchor)
- A quick and easy way to remind and navigate me to the exact location. (It is purposed to navigate user to the exact location and immediately start working on it.)
- A quick and easy way to overview all those labels. (It is purposed to monitor and track all those problems in an overview list.)
- If it can add a little description for those labels would be perfect.  (It is purposed to quickly identify the details about the problems within the overview list.)

**What solution that I prefer?**

**_Label Syntax + Label Button + Label List_**
- Add syntax like `#label name: label description#` to define label's start, name, description, and end. (Normally, it only shows label name ; Mouse hovering on the label name to show tooltip; Click to show full syntax and allow editing.)
- Add a Label button on the editor toolbar. (As an option for beginners)
- Add a Lable list option on the navigation menu, click to show all labels and description on the mid-panel.

### Additional context

**Extra Thoughts of Impacts**

Due to this feature might be related to the whole experience of using Notesnook, I would like to describe some of my thoughts for reference.

Since we have "Notebook", "Sub-notebook" for organizing notes, "Tag" seems like a duplicate exists. Logically, it can generate confusion for most of the inexperienced users. When I describe "Tag" as a "Single Layer Tag Navigation System", "Notebook" is more likely a powerful "Multi-layer Tag Navigation System". The difference between them is just single-layer and multi-layer, and "Notebook" is not handy than "Tag" when using. And that made me think about the following questions:
 
1. Why must the system combination be "notebook" + "sub-notebook" + "single layer tag"?
2. Why not use "traditional tree structure notebook" + "nested tag system"?
3. Or should they combine into one? And then redefine the new value meanings of "Tag"?
4. When Notesnook is lacking the features of "issues tracking" and "document status tracking", is it possible to be:
 
- Combine the functions of "Notebook" and "Tag" into a new "Nested Tagging-based notebook organization and navigation system?"
- Redefine the old tag feature to a new "Status Tracking" feature. (Key-value pairs that let users define custom fields to track whatever status of a note. And it should be positioned under each note's title and optionally shown on the notes overview list.)
- Add the new "Label Syntax + Label Button + Label List" that I mentioned above. Whatever you named it, Lable/Mark/Tag/Memo, just don't named it "Issues", because it should stay open for any use case.

Actually, it's just a traditional inline tag feature but having extra description for better use of issue tracking.

Overall, I think it can reduce the confusion in organizing notes and make improvement on shortcomings. It can make Notesnook more flexible for most use cases, more productive, and keep the use simple.

**Comment by thecodrr** [comment]
I like this idea but will have to think more on this. You are right that "Tags" currently aren't really useful in any meaningful way.
