### ISSUE TITLE
Notesnook typeeror: Netwrok error from zoho

### ISSUE THREAD

**Issue by alihamuh** [streetwriters/notesnook#6902]
### What happened?

I am getting this Notesnook error "Something went wrong, TypeError: network error" daily, and I'm forced to restart Notesnook after getting it, which takes a long time. 

This error mostly happens after I closed the lid of my Surface (standby), haven't opened Notesnook for some time, and then open Notesnook again...

 --- Device information: 
App version: 3.0.19-22dcba840-web
Device: Microsoft Surface Pro 8
OS: Windows 11 Home
64-bit Browser: Microsoft Edge 130.0.0.0
Pro: true![Image](https://github.com/user-attachments/assets/0d040d22-b4b4-4018-ba6f-a3024180a14d)

### Steps to reproduce the problem

--

### Version

v3.0.19

### Platform/OS

Windows

### Relevant log output

```shell
--
```

**Comment by thecodrr** [comment]
Fixed.
