### ISSUE TITLE
Cannot insert a Todo line on mobile

### ISSUE THREAD

**Issue by saccarosium** [streetwriters/notesnook#6928]
### What happened?

- **Platform**:  Android
- **Distribution**: F-Droid

When I try to insert a todo box, either with the shourtcut `- [ ]` or using the UI button, the box will not be placed.

### Steps to reproduce the problem

1. Open a note
2. Type either the shortcut or press the button

### Version

3.0.19

### Platform/OS

Android

### Relevant log output

```shell

```

**Comment by ammarahm-ed** [comment]
Hi, please update to v3.0.22. This has been fixed.
