### ISSUE TITLE
The select menu while selecting programming language is deformed

### ISSUE THREAD

**Issue by ifajul89** [streetwriters/notesnook#6932]
### What happened?

After writing the code by default, it remains in Plaintext. When I tried to open the selection box of programming languages, it showed me a kind of deformed or the names of programming languages, not having proper padding.
Issue Image: https://drive.proton.me/urls/T61AHEQ3MM#33X2ZpsbB9LC

### Steps to reproduce the problem

Just add paddings to each programming language name while selecting

### Version

3.0.20-0f84fab-desktop

### Platform/OS

macOS

### Relevant log output

```shell

```

**Comment by ammarahm-ed** [comment]
This has been fixed.
