### ISSUE TITLE
Text flashes when entering a note

### ISSUE THREAD

**Issue by candroid-man** [streetwriters/notesnook#694]
Screenshot of text:
![Screenshot_20220719-133527.png](https://user-images.githubusercontent.com/51019003/179824166-9f859982-3473-48f4-a124-f7d209f1c6a0.png)

It blinks in for less than a second and then blinks out.

**Comment by ammarahm-ed** [comment]
That's happening because it's loading the note. as soon as the note is loaded in the editor. it hides itself. Since it happens too soon, it feels like a flicker or a glitch i guess.

**Comment by candroid-man** [comment]
Could you maybe only have that show up after a certain amount of time loading the note? Like 1 second or something? It would just make it seem more polished it doesn't look great

**Comment by ammarahm-ed** [comment]
Will see what can be done about this

**Comment by ammarahm-ed** [comment]
Hi, I have made some improvements to the loading screen which would make it not feel like a glitch by showing a skeleton.
