### ISSUE TITLE
Hyperlinks redirecting to same link for all hyperlinks while in Read Only Mode

### ISSUE THREAD

**Issue by haritvsmurali** [streetwriters/notesnook#6959]
### What happened?

Multiple Different Hyperlinks updated in a single note.

Everything works perfectly when in normal edit mode.

But while accessing in Read Only Mode, all the hyperlinks in the note shows and redirects to single link which was updated initially at the top of the note.

### Steps to reproduce the problem

IN NORMAL EDIT MODE:

Hyperlink 1: mailto:abcd@gmail.com
Hyperlink 2: mailto:efgh@outlook.com
Hyperlink 3: mailto:hijk@icloud.com

All works perfectly in above mode. 

SAME NOTE WHILE IN READ ONLY MODE:

Hyperlink 1: mailto:abcd@gmail.com
Hyperlink 2: mailto:abcd@gmail.com
Hyperlink 3: mailto:abcd@gmail.com

Even though contents remains same and visible correct, redirection takes to the initial link. 

### Version

3.0.22

### Platform/OS

Android

### Relevant log output

```shell

```

**Comment by ammarahm-ed** [comment]
I am not able to reproduce this in the latest version.
