### ISSUE TITLE
I have attempted to import Evernote enex files into Notesnook, without success.

### ISSUE THREAD

**Issue by yukonquest** [streetwriters/notesnook#70]
My account in Notesnook is 'info@mjmx2'.  I exported from Evernote to enex.  When I try the import function, I do not get the "Successful Import" message.  I tried it with a single file, and with multiple files.  I let it sit overnight, still nothing.  
Please advise.

**Comment by thecodrr** [comment]
The new [Notesnook Importer](https://importer.notesnook.com/) is here which should fix this issue.
