### ISSUE TITLE
[Android] Unable to completely remove the custom proxy URL value

### ISSUE THREAD

**Issue by s0llvan** [streetwriters/notesnook#7052]
### What happened?

When the custom proxy URL is completely removed, and the app is closed and reopened, the 'h' from the beginning of the old value remains present when checking the custom proxy URL.

### Steps to reproduce the problem

1. Remove the custom proxy URL completely
2. Close the app
3. Reopen the app and check the custom proxy URL
4. The 'h' from the beginning of the old value remains present

### Version

v3.0.23

### Platform/OS

Android (15)

**Comment by s0llvan** [comment]
### Video

https://github.com/user-attachments/assets/4d436b61-2906-46fc-a6d5-792965d47584

**Comment by ammarahm-ed** [comment]
Thanks for reporting, I will fix this asap!
