### ISSUE TITLE
Better reliability when internet is going in and out

### ISSUE THREAD

**Issue by candroid-man** [streetwriters/notesnook#707]
### What problem are you facing?

I have noticed a few users including myself having issues with Notesnook when internet is questionable. Just from a brief look I found a user in the Discord complaining about it: https://discord.com/channels/796015620436787241/796063880677163109/971646447932018698. I have had some bad experiences as well, where I would get constant popups of errors and telling me I need to pick which version of a note I want for a note I just created, stuff like that.

### What's the solution you'd like to see in Notesnook?

Obviously improving it would be good, but as a different option, maybe adding a toggle to go completely offline would be beneficial. It would also be good for people who don't want sync and just want to use it locally with absolutely no internet connection from the app. I am not sure how possible this is, but it would be a great addition

### Additional context

Mainly adding this so you can add it to the reliability to-do list project thing

**Comment by thecodrr** [comment]
Sync controls are coming in the next version.
