### ISSUE TITLE
Show encryption keys within the properties menu of each note

### ISSUE THREAD

**Issue by candroid-man** [streetwriters/notesnook#709]
### What problem are you facing?

As a part of the freedom of software movement, people expect to have full access to all information about everything that is theirs. As this is a privacy first application, it is vital to make sure that the user can do whatever they want with their notes.

### What's the solution you'd like to see in Notesnook?

Within the properties menu, you should allow the user to view the encryption key for each note. It would be a good idea to hide the key and have the user enter their password or use biometrics in order to gain access.

**Comment by thecodrr** [comment]
Currently notes do not have their own encryption key so this is a no-op.
