### ISSUE TITLE
Is this app Code Signed?

### ISSUE THREAD

**Issue by dtantono** [streetwriters/notesnook#726]
### What happened?

When I installed a Windows client, the Windows Smart Screen popup appears. Is the Windows client code signed?

### Steps to reproduce the problem

1. Double click the app
2. Windows Smart Screen popup appears

### Version

2.1.2

### Platform/OS

Windows

**Comment by thecodrr** [comment]
At this point, we cannot afford a code signing certificate ($400/yr - $600/yr). Perhaps another option is delivering the app via Microsoft Store.

**Comment by cnoize35** [comment]
Just so you know. That's almost a reason for me not to install the app. Especially in an enterprise environment. 
I specifically came here to see why the code isn't signed. Now i might reconsider installing it and getting a pro subscription to help you out with your certificate. ;)

**Comment by thecodrr** [comment]
@cnoize35 if it is preventing you to install the app, you can just use the web app for the time being.

**Comment by protocolist** [comment]
EV code signing cert isn't strictly necessary for suppression of SmartScreen prompts. When using an OV cert, Microsoft will eventually suppress the prompt based on reputation heuristics. This could reduce cost to somewhere in the realm of 120 USD/yr. 

Getting any signing, even with an OV certificate, would help increase assurance that the binary hasn't been modified after you build it. I'd love to see this happen. It's my one complaint with the product.
