### ISSUE TITLE
Android or iOS app update to recent version reverted some notes, deleted others from main account (desktop, web app)

### ISSUE THREAD

**Issue by avatar382** [streetwriters/notesnook#734]
### What happened?

I'm using Notesnook on my Linux computer, iPad, and Android phone.

I upgraded Notesnook on my Linux desktop to the latest version, which includes the updates and server migrations. 

After I upgraded my desktop, Notesnook on my Android phone was unusable because the latest client available to it (or me) was out of date.

This morning I was able to upgrade Notesnook on Android to a version that could access the migrated database. That upgrade seemed to go smoothly.

I haven't used Notesnook on my iPad in a while. I ran the app and it started the migration, but the app froze and as unresponsive for several minutes. I killed the app, and when I re-ran it, I saw hundreds of note conflicts appear. I deleted the app off my iPad and reinstalled it.

When I reinstalled the iOS app, it seemed to sync fine.

After updating Notesnook on both of my mobile devices, I immediately noticed that several notes (my most often used and most important ones) were either gone, or reverted to a state that was several weeks old!

Using the backups on my android device, I was able to restore my most important notes, but I almost had a heart attack when I saw the mess created by the failed sync process.

I'm not sure if it was the Android or iOS update process that caused the problem.

### Steps to reproduce the problem

This was a complex chain of events and I don't know if I can reproduce it. It seems like there is a problem in the upgrade, sync, or database migration process.

Honestly, it's hard to even describe. Let me know if you have any follow up questions to try to narrow down the cause. 

Let me know if certain log files from my devices would be helpful.

### Version

Latest on desktop, android, iOS

### Platform/OS

Linux, iOS, Android

**Comment by thecodrr** [comment]
> I haven't used Notesnook on my iPad in a while.

This is the culprit. Since your notes on your iPad were very old, once they migrated & synced they caused a conflict...

> and when I re-ran it, I saw hundreds of note conflicts appear.

However...

> I deleted the app off my iPad and reinstalled it.

Doing the above should have prevented the damage you mention as...

> I immediately noticed that several notes (my most often used and most important ones) were either gone, or reverted to a state that was several weeks old!

Unless your iPad pushed its versions of notes before it errored out. That isn't possible though. Migration happens in steps:

1. Open app
2. Database is migrated if required
3. Sync runs - data is fetched
5. Conflicts appear
6. Conflict are resolved
7. Sync runs again - data is fetched, merged & pushed

> I'm not sure if it was the Android or iOS update process that caused the problem.

Definitely the iPad.
