### ISSUE TITLE
notes migrated from previous version have newlines replaced by the string "[[%NN_NEWLINE_IN_PRE%]]" everywhere

### ISSUE THREAD

**Issue by avatar382** [streetwriters/notesnook#735]
### What happened?

After updating to the latest version of Notesnook, with the updated code block editor, I'm seeing many notes with newlines replaced with the string "[[%NN_NEWLINE_IN_PRE%]]" all over the place.

Here's an example:
![Screenshot_2022-07-25_09-33-34](https://user-images.githubusercontent.com/130926/180817547-7efb94c7-0905-4dbf-966b-62c532b03348.jpg)

### Steps to reproduce the problem

The step taken was simply upgrading Notesnook to the most recent version.

### Version

v2.1.2-fede059-desktop

### Platform/OS

Linux

**Comment by thecodrr** [comment]
This is a critical bug in the migration system (which was fixed but an edge case slipped through). I have redone the logic around codeblock migration which should fix this.

However, your notes will need to be remigrated once v2.1.3 (on web/desktop) is out. This can be done by restoring a recent backup.

If that is not possible, I can reset your account to the state it was before the migration to the new version.

**Comment by avatar382** [comment]
Ok, sounds good. 

Once 2.1.3 comes out, can I simply install that version and have the notes I haven't cleaned up yet be automatically fixed?

I've fixed quite a few notes already and would rather not revert back now that this work has been done.

**Comment by thecodrr** [comment]
> Once 2.1.3 comes out, can I simply install that version and have the notes I haven't cleaned up yet be automatically fixed?

Unfortunately no. The fastest way is to import a recent backup which will fix all the notes. The second fastest way is to import the backup in a temporary account and copy paste the affected notes from that account to your own one by one.

**Comment by thecodrr** [comment]
If this is resolved for you @avatar382 we can close it.
