### ISSUE TITLE
Tag and location of note can sometimes stick to the next note you make

### ISSUE THREAD

**Issue by candroid-man** [streetwriters/notesnook#756]
### What happened?

When creating one note with a specific Tag and location, the next note you make can sometimes carry over that information regardless of where in the app you create a note.

### Steps to reproduce the problem

1. Create a new note in a specific location other than Notes, and add a Tag to said note
2. Create another note from the Notes menu 
3. Notice that the Tag and location you added to the last note is also on the new note

### Version

2.1.4

### Platform/OS

Android

**Comment by ammarahm-ed** [comment]
This has been fixed. Will ship in next release
