### ISSUE TITLE
Cannot make new line after attaching image

### ISSUE THREAD

**Issue by candroid-man** [streetwriters/notesnook#760]
### What happened?

I discovered that if you try to create a new line after an image, instead of creating the new line, the image deletes because it is still selected.

### Steps to reproduce the problem

1. Create new note
2. Attach an image
3. Attempt to create new line below image

### Version

2.1.4

### Platform/OS

Android

**Comment by ammarahm-ed** [comment]
Have you tried double tapping on the blank area at the end of a note? It should create a new line.

**Comment by candroid-man** [comment]
I just tried it and that did not work. The reason it doesn't work is because the blank area currently does not register as a text box since the new editor was released. I made an issue about this #712 and is currently pending release if I see that correctly, so perhaps that will fix the issue

**Comment by thecodrr** [comment]
> The reason it doesn't work is because the blank area currently does not register as a text box

That issue was specific to the desktop browsers. Scroll to the end of the note & double tap just above the toolbar: it'll add a new paragraph.

**Comment by thecodrr** [comment]
> instead of creating the new line, the image deletes because it is still selected.

We can handle this by creating a new line if image is selected & the user presses Enter. (It'll get deleted if some other key is pressed though).

**Comment by candroid-man** [comment]
Double tapping above the editor bar creates a new line above the image, and once again it is impossible to remove said line because the cursor is not able to get behind the image, or after to create another line after the image

**Comment by thecodrr** [comment]
This has been fixed.
