### ISSUE TITLE
Text not scrolling properly while writing titles

### ISSUE THREAD

**Issue by candroid-man** [streetwriters/notesnook#761]
### What happened?

When creating titles for things on mobile, such as note titles and task list titles, the text doesn't follow the cursor very well. In other words, while you are typing it is hard to see if you are typing things correctly.

### Steps to reproduce the problem

1. Create new note
2. Make a long title that forces the text to scroll to the right
3. See error, it is very choppy and has a hard time following you as you type

### Version

2.1.4

### Platform/OS

Android

**Comment by ammarahm-ed** [comment]
Hi, I tried typing in the title bar of a note. It seems to work normally. The cursor stays at the end of the title bar as you type on-wards which seems to be normal behavior.

**Comment by candroid-man** [comment]
I figured out what specifically is the problem. Use spaces while typing, and make sure the title is long enough to where the text has to scroll, and you will see it

**Comment by ammarahm-ed** [comment]
@candroid-man you meant that the space goes behind the padding on pressing space? But as you type in a word it becomes visible.. i will test more.

**Comment by candroid-man** [comment]
Yes, sorry for the terrible explanation

**Comment by thecodrr** [comment]
This has been fixed.
