### ISSUE TITLE
Desktop: Extra text formatting toolbar is partially covered when paragraph formatting buttons overflow to new line

### ISSUE THREAD

**Issue by rufusgerm** [streetwriters/notesnook#772]
### What happened?

The extended/extra text formatting bar becomes obscured (or mostly) when the window size is adjusted such that the paragraph adjustment buttons (alignment, paragraph direction) overflow to a new line. Here are two example images:
One line:
![overflow-before](https://user-images.githubusercontent.com/35353724/182921754-17771754-6119-431c-956f-d411e5ff0554.png)

Two lines:
![overflow-after](https://user-images.githubusercontent.com/35353724/182922275-76aaeb61-f9a9-459e-9efe-d9fcc7ae542f.png)

**Mac OS:** Monterey
**Notesnook:** v2.1.3-2b62c70-desktop

### Steps to reproduce the problem

1. Have the desktop window width sized such that all of the text formatting options in the menu bar take up one line.
2. Activate the extended/extra text formatting button (three dots to the right of the **Underline** button
3. Narrow the desktop window width until the text formatting options in the menu bar overflow to a second line

### Version

v2.1.3-2b62c70-desktop

### Platform/OS

macOS

**Comment by thecodrr** [comment]
Confirmed. Fix on the way.
