### ISSUE TITLE
Note could not be published: s is null

### ISSUE THREAD

**Issue by gammexane** [streetwriters/notesnook#777]
### What happened?

When I try to publish a note in the web client I get the error:
`Note could not be published: s is null`
When I try doing the same in the Android app:
`Could not publish note
Cannot read property: "InsertMedia" of null.`

### Steps to reproduce the problem

-Open Notesnook
-Open any note
-Press publish button. (It doesn't matter if I choose password or self destruct, the problem is the same)

### Version

2.1.3-2b62c70b-web

### Platform/OS

Android, Firefox

**Comment by thecodrr** [comment]
This has already been fixed in #751 & will be released in the next version.
