### ISSUE TITLE
Last word missing while pasting copied content 

### ISSUE THREAD

**Issue by rahulTPatil** [streetwriters/notesnook#782]
Issue found: v 2.1.5 
Platform: Android
Scenario: Copy some text and paste below, but the last word doesn't get pasted inside the app. It does get resolved when I switch to a different app and paste again inside the app.

Ex: This is a statement

Result after pasting: This is a statemen

**Comment by thecodrr** [comment]
I cannot reproduce this. Make sure you are copying the whole sentence.

**Comment by thecodrr** [comment]
Hi, I was able to later reproduce this on the web/desktop client. This will be fixed in the next release.
