### ISSUE TITLE
Collapsing List Doesn't Expand

### ISSUE THREAD

**Issue by bgrubs** [streetwriters/notesnook#801]
### What happened?

I collapsed a list and tried to expand it, but the button doesn't function. The list doesn't open.

### Steps to reproduce the problem

1. Create a collapsible list/outline.
2. Make some nested points.
3. Collapse the list.
4. Try to expand the list.

### Version

2.1.4

### Platform/OS

Chrome/Chromium

**Comment by thecodrr** [comment]
Fixed. Will be in the next version.
