### ISSUE TITLE
Outline List does not expand/collapse in the same note (Linux and Android)

### ISSUE THREAD

**Issue by rahulTPatil** [streetwriters/notesnook#814]
### What happened?

Outline List once expanded, does not collapse when clicking on the arrow button if being in same note. Vice-versa when the list is collapsed. Once I switch to other note and come back to the first note, then it does let expand/collapse once.

### Steps to reproduce the problem

1. Click on the **+** icon in the toolbar
2. Select **Outline List**
3. Provide data for header and sub-list
4. Click on the down arrow mark for closing the list (which is not working if in the same note)
5. Go to any other notes and come back to the main one, try clicking arrow mark for closing the list. (Which should work). Then try expanding the list (This doesn't work)

### Version

v2.1.4-889a8d9-desktop (Linux); v2.1.5 (Android)

### Platform/OS

Linux, Android

**Comment by ammarahm-ed** [comment]
This has been already reported and fixed. A new version will be out soon. today or tomorrow.
