### ISSUE TITLE
Bug #714 - But when you export the notes

### ISSUE THREAD

**Issue by gammexane** [streetwriters/notesnook#817]
### What happened?

When you export to PDF, Markdown or HTML you get an extra line between lines . 
When you export to TXT you get a single line with all the text.

Original note: 
![image](https://user-images.githubusercontent.com/509348/184683073-b7b78f9c-be6d-4c08-8d4c-7297f3f6e64e.png)

Export to PDF (BTW, the additional text pointed by the red arrows should be removed, or at least have an option to remove it):
![image](https://user-images.githubusercontent.com/509348/184683118-429ab26a-a98b-44f9-9d32-eba129edba59.png)

Export to TXT:
![image](https://user-images.githubusercontent.com/509348/184683322-ab6bf811-1406-48ab-b516-71f33a2ebe6d.png)

Export to Markdown:
![image](https://user-images.githubusercontent.com/509348/184683505-dd12c634-5e1b-44e3-97e8-76787ef45429.png)

The double spaced option added to fix the bug #714 is off, I turned it on just to test, but I got the same result:
![image](https://user-images.githubusercontent.com/509348/184683744-3653a466-4957-4875-9121-b4a4ec0bb898.png)

Thank you!

### Steps to reproduce the problem

1) Export any note, 
2) Select the formats I mentioned.

### Version

2.1.4-889a8d98-web

### Platform/OS

Firefox

**Comment by davidag** [comment]
I think this basically renders exports useless if you're not a paying user. You can still extract the html from a backup file [like this](https://gist.github.com/davidag/2b3e43946bb1f138d5e322189b6d024c).

**Comment by thecodrr** [comment]
> Export to TXT

This has been fixed.

**Comment by thecodrr** [comment]
Will fix the other exports ASAP.

**Comment by thecodrr** [comment]
> Export to PDF 

This has also been fixed. Only markdown export is still broken for single-spaced paragraphs.

**Comment by alihamuh** [comment]
in ...notesnook/packages/core/node_modules/@streetwriters/showdown/dist/showdown.js

`  var parent = node.parentNode;
  var children = parent.querySelectorAll("p")

  if(children[0]===node) return txt;
  if(node.getAttribute("data-spacing")==="double")
  return "\n\n"+txt;
  else return "\n"+txt; `
  
  and 
  
  `showdown.subParser('makeMarkdown.node', function (node, options, globals, spansOnly) {
  'use strict';
 .....
....
....
    case 'p':
      if (!spansOnly) { txt = showdown.subParser('makeMarkdown.paragraph')(node, options, globals); }
      break;
      ...
....
....
}`
