### ISSUE TITLE
[Andriod] can't perform unencrypted/encrypted backups app version 2.1.7

### ISSUE THREAD

**Issue by gpdevsoft** [streetwriters/notesnook#825]
### What happened?

on Samsung Galaxy Android 9 after upgrade to 2.1.7 version when i press on backup button in settings menu nothing happens as if the function was disabled, I tried to enable encrypted backups but the problem isn't solved

### Steps to reproduce the problem

1) open the app and press on "Settings" button

2) go to backup function and press "Backup now"

3) nothing happens

### Version

2.1.7

### Platform/OS

Android

**Comment by ammarahm-ed** [comment]
Fixed. I will make a release asap
