### ISSUE TITLE
Paragraph Spacing, Line Spacing Issues with single spacing set

### ISSUE THREAD

**Issue by grs09** [streetwriters/notesnook#828]
### What happened?

I looked through the top issues posted and don't see this on the radar. I have the single spacing option set on both my android and windows computer. After a paragraph is written, hitting enter puts a single space, then enter again reverts to double spacing paragraphs. So enter, enter goes back to double spacing mode... This happens on both android and windows. Just updated both to the newest versions this morning and its still an issue. 

Google dosc, MS Onenote are both platforms I used in the past. They are both single spacing everywhere. There's no possibility to go to double spacing unless chaining options somewhere. So hitting enter multiple times always stays in single spacing and its what i'm hoping for with Notesnook. 

### Steps to reproduce the problem

Hit enter in your notes, then enter again. 

### Version

2.1.5-c431a5e-desktop

### Platform/OS

Windows, Android

### Relevant log output

```shell
No log to output for this
```

**Comment by thecodrr** [comment]
Hi, this is intentionally done. 2 enters create a double spaced paragraph which allows for really good formatting during copy-paste. It also acts as a shortcut when you do need double spaced paragraphs.

**Comment by grs09** [comment]
Dang that is unfortunate, was really hoping the new line spacing upgrade was going to mimic gdocs/onenote. Both of which I'm coming from but don't want to be tied to big tech going forward so I'm wanting to land with Notesnook long term. I guess I'll work with it the way it works for now.

**Comment by ammarahm-ed** [comment]
@grs09 hitting enter twice creates a paragraph with some top margin. However if you press enter again it is back to single line spacing again so it doesn't switch modes but only uses double spacing for that specific line only.
