### ISSUE TITLE
Sync Conflict Date Format

### ISSUE THREAD

**Issue by sharemind** [streetwriters/notesnook#843]
### What problem are you facing?

The date format that is shown under the title's note when there is a sync conflict is the American format MM/DD/YYYY. 

### What's the solution you'd like to see in Notesnook?

It will be nice to be able to change it in the European format DD/MM/YYYY

**Comment by thecodrr** [comment]
Hi, I'll see if we can use the current device locale for all dates.

**Comment by thecodrr** [comment]
Tracking in #959
