### ISSUE TITLE
Properties menu does not pop-out on notes

### ISSUE THREAD

**Issue by thackmaster** [streetwriters/notesnook#845]
### What problem are you facing?

I know that we are able to right-click in the desktop application to bring up export options, the ability to move notebooks, etc. However, when you're in a web browser, it doesn't bring up that menu when right-clicking.

### What's the solution you'd like to see in Notesnook?

I'd like to see that menu in the "Properties" pop-out. It would also help first-time users in finding these options.

**Comment by thecodrr** [comment]
Hi, which version of the app are you on? This looks like a bug (not a feature request). I cannot reproduce it though.

**Comment by thackmaster** [comment]
App version: 2.1.6-deb04d68-web
OS: Windows 10 64-bit
Browser: Chrome 104.0.5112.101
Pro: true
