### ISSUE TITLE
Spellcheck not working on Mac

### ISSUE THREAD

**Issue by thackmaster** [streetwriters/notesnook#853]
### What happened?

Spellcheck doesn't seem to be working on Mac installations.

### Steps to reproduce the problem

1. Install Notesnook desktop app on a Mac device
2. Purposefully type something misspelled
3. Observe that it will not be highlighted

### Version

v2.1.6

### Platform/OS

macOS

**Comment by thecodrr** [comment]
Hi, thanks for creating this issue. This is already being tracked here: #404
