### ISSUE TITLE
ERR_NAME_NOT_RESOLVED in Google Chrome

### ISSUE THREAD

**Issue by fadil5890** [streetwriters/notesnook#855]
### What happened?

I created a new account in Windows app and when i want to confirm verification of my email, I click the link in my email and sends me to this error. I tried what Chrome suggest (other websites works fine, changing google-cloudflare DNS, disable-enable network prediction in Chrome settings, disable-enable firewall, proxy server) but nothing works. I look at the link and at the end of it says "type=CONFRIM_EMAIL" and wondering is that a typo or is it like that. I tried to change to CONFIRM but no luck.

### Steps to reproduce the problem

1. Click "Confirm your email to sync your notes."
2. Click "Resend"
3. Go to your E-mail and click the verification link

### Version

version 2.1.6-deb04d6-desktop

### Platform/OS

Windows

**Comment by thecodrr** [comment]
This has been fixed. Please try again.
