### ISSUE TITLE
Android 13 breaks the gesture bar on Pixel 6 Pro

### ISSUE THREAD

**Issue by candroid-man** [streetwriters/notesnook#856]
![Screenshot_20220825-093817.png](https://user-images.githubusercontent.com/51019003/186695010-d2e53085-1499-449f-b962-802044e4d380.png)

Android 13 broke a lot of things, but since Notesnook is web based everything else seems to work so far

**Comment by ammarahm-ed** [comment]
What's the gesture bar? Can you explain a bit. I am confused 🤔

**Comment by candroid-man** [comment]
As shown in the image, the gesture bar allows you to go to the home screen, switch apps, etc. It is basically the same thing as iPhone. But in Android 12 the background of the gesture bar has the correct color behind it while in Android 13 this seems to not be the case and is just black. Hope that clears that up

**Comment by candroid-man** [comment]
Looking again, the screenshot doesn't show all of it for some reason, but even more of the bottom of my screen is black than usual, but a lot of apps are having this issue including GitHub as I am typing this

**Comment by ammarahm-ed** [comment]
Hmmm 🤔 maybe there would be a way to manually set the color. I know it was possible in android 12 so it should be in 13 too.

**Comment by candroid-man** [comment]
Probably, but what I find weird is that the screen cuts off at the very bottom in many apps. That screenshot, imagine there being half an inch more black space underneath it that can't even be shown with a screenshot. I don't know if this is something you will have to fix yourself, or if this is a weird bug with Android 13 that will be fixed in the future

**Comment by ammarahm-ed** [comment]
I think it's a bug probably 🤔

**Comment by candroid-man** [comment]
I just edited my previous comment, it is not nearly half an inch haha, in total there is about 1 cm of black space on the bottom of my screen in many applications including GitHub

**Comment by thecodrr** [comment]
@candroid-man are you still having this issue?

**Comment by candroid-man** [comment]
Yes
