### ISSUE TITLE
Issue with Notesnook website redirection

### ISSUE THREAD

**Issue by alanjacobmathew** [streetwriters/notesnook#858]
When accessing the 'ctrl' and 'enter' to complete url, the website goes to **www.notesnook.com** (Connection timed out) and not to https://notesnook.com.

While manually entering notesnook.com it works fine.
 
So please automatically redirect [https://www.notesnook.com](https://www.notesnook.com)  to [https://notesnook.com](https://notesnook.com)

**Comment by thecodrr** [comment]
Fixed.
