### ISSUE TITLE
the appimage file doesn't work

### ISSUE THREAD

**Issue by stem69** [streetwriters/notesnook#862]
### What happened?

Downloaded the notesnook appimage on my Linux Mint OS and when I tried to open it nothing happened. When I click on the file it says unknown file type. I run other appimage files like Audacity and they work. I think appimage is a poor way to run software as it doesn't actually install to the system so no menu links or updates, etc. Why not install as a .deb file?

### Steps to reproduce the problem

Download appimage on Linux Mint 20.3 kernel 5.4.0-125-generic
click on downloaded file

### Version

unknown

### Platform/OS

Linux

### Relevant log output

```shell
no log output available
```

**Comment by thecodrr** [comment]
Hey, we also provide deb. https://notesnook.com/downloads

**Comment by Opfour** [comment]
Run the following commands to start the image.
```
chmod +x notesnook_x86_64.AppImag
./notesnook_x86_64.AppImag
```
This worked for me.
