### ISSUE TITLE
Couldn't report an issue from app.notesnook.com

### ISSUE THREAD

**Issue by stem69** [streetwriters/notesnook#863]
### What happened?

Unable to open appimage, so went online to report issue and received the error: failed to fetch.

### Steps to reproduce the problem

go to https://app.notesnook.com/
login
click on report an issue
fill out title and description
click on submit
![Screenshot from 2022-09-03 08-46-53](https://user-images.githubusercontent.com/6112148/188261546-030fbb29-4da9-4ec0-80e9-4f1b5d2e0a40.png)

### Version

2.1.6-deb04d68-web

### Platform/OS

Linux

### Relevant log output

```shell
N/A
```

**Comment by thecodrr** [comment]
It should be working again.
