### ISSUE TITLE
Math Block Dead End

### ISSUE THREAD

**Issue by d-kanti** [streetwriters/notesnook#880]
### What happened?

* In the mobile app
* adding a math Block at the end of the note 
* pretty much makes nothing else addable.

I got stuck trying to add a text below math Block and wad not able to do that. Because there is no way to get below ob the math Block. (In mobile app)
In the web version, ctrl+enter takes the cursor below the block.

### Steps to reproduce the problem

I think automatically adding one or two blank lines below the math Block, at the time of creating a math equation, should work fine... As we can tap there to go there.

### Version

V2.1.8

### Platform/OS

Android

**Comment by ammarahm-ed** [comment]
@d-kanti Will fix this in next release. I think this problem exists with other nodes too. Especially on mobile. Adding an extra line below might help.

**Comment by thecodrr** [comment]
Fixed in v2.2
