### ISSUE TITLE
OneNote import: JS error during import: `TypeError: m.parentNotebook is null`

### ISSUE THREAD

**Issue by altano** [streetwriters/notesnook#9]
> Uncaught (in promise) TypeError: m.parentNotebook is null

![image](https://user-images.githubusercontent.com/1009/119628152-b05aa380-bdc1-11eb-98d6-59d009680ef9.png)

I grabbed the `m` object to aid in debugging, but I redacted the GUIDs in case they expose my personal data:

```json
{
	"id": "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
	"self": "https://graph.microsoft.com/v1.0/users/BBBBBBBBBBBBBBBBBBBBB/onenote/sectionGroups/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
	"createdDateTime": "2017-01-04T20:34:09Z",
	"displayName": "Attachments",
	"lastModifiedDateTime": "2017-01-04T20:34:09Z",
	"sectionsUrl": "https://graph.microsoft.com/v1.0/users/BBBBBBBBBBBBBBBBBBBBB/onenote/sectionGroups/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/sections",
	"sectionGroupsUrl": "https://graph.microsoft.com/v1.0/users/BBBBBBBBBBBBBBBBBBBBB/onenote/sectionGroups/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/sectionGroups",
	"createdBy": {
		"user": {
			"id": "BBBBBBBBBBBBBBBBBBBBB",
			"displayName": "alan"
		}
	},
	"lastModifiedBy": {
		"user": {
			"id": "BBBBBBBBBBBBBBBBBBBBB",
			"displayName": "alan"
		}
	},
	"parentNotebook@odata.context": "https://graph.microsoft.com/v1.0/$metadata#users('BBBBBBBBBBBBBBBBBBBBB')/onenote/sectionGroups('AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA')/parentNotebook/$entity",
	"parentNotebook": null,
	"parentSectionGroup@odata.context": "https://graph.microsoft.com/v1.0/$metadata#users('BBBBBBBBBBBBBBBBBBBBB')/onenote/sectionGroups('AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA')/parentSectionGroup/$entity",
	"parentSectionGroup": null
}
```

**Comment by thecodrr** [comment]
@altano this is certainly an issue. However, I personally don't have a Windows PC (I use Linux) where I could test importing sectionGroups. To fix this, I'd need to know the following:

1. Can a Section Group exist outside a OneNote Notebook?

**Comment by altano** [comment]
It might be possible. You can export a section (not a section group as far as I can tell) as a flat ".one" file. That flat file can be opened in OneNote so it might be possible to sync that back up to OneDrive or SharePoint. And if you can export a section surely there's some way to export a section group?

The section, when opened in OneNote, just looks like this in the Notebook pane:
![image](https://user-images.githubusercontent.com/1009/119633137-485a8c00-bdc6-11eb-9c6d-65e7edda6a22.png)

**Comment by thecodrr** [comment]
From the `m` data you attached, it seems `Attachments` sectionGroup has no parent notebook. Can you verify this?

**Comment by altano** [comment]
> 
> 
> From the `m` data you attached, it seems `Attachments` sectionGroup has no parent notebook. Can you verify this?

I went to my Microsoft 365's OneDrive. It doesn't look like the normal OneDrive... I think it is a SharePoint file library. Inside that library the very first thing is a folder called "Attachments" that has some files in it. Neither the folder nor its contents are OneNote related.

The only OneNote thing I have in this SharePoint library is a single OneNote notebook.

**Comment by altano** [comment]
And that OneNote notebook is empty: it has a "Quick Notes" section and an "Untitled Page" with no contents. That's it

**Comment by thecodrr** [comment]
@altano Can you try importing now in the new version `1.0.21`? You'll have to refresh the Importer page.

**Comment by altano** [comment]
Blows up on undefined `content`:
![image](https://user-images.githubusercontent.com/1009/119636407-74c3d780-bdc9-11eb-9f49-ddfdd2cf1b2e.png)

This is from the wrong account (my SharePoint library) for sure and the Notebooks _are_ empty:
![image](https://user-images.githubusercontent.com/1009/119636260-51009180-bdc9-11eb-9738-eaf2e76a5c80.png)

I don't personally need you to fix this since I'm not hitting this issue with my real notebook (I don't have any blank pages) but you might want to fix this for others? *shrug*

**Comment by thecodrr** [comment]
Both the issues are now handled properly in `v1.2.22`.
