### ISSUE TITLE
Unable to click out of tables in a note 

### ISSUE THREAD

**Issue by Beebeeoii** [streetwriters/notesnook#947]
### What happened?

When I have a table, I am having troubles to 'click out' of it to insert new blocks/text underneath/above the table. On the web version (via firefox), trying to click below the table will automatically put the cursor at the bottom right cell of the table. This is still acceptable as I can use the `↓` arrow key to exit out of the table to type/insert more stuff below the table.

However, on mobile (via android), there does not seem to be a way at all for me to exit out of the table. Attempts of clicking below the table does not have any response, hence the only thing I can do is to click on the table. However, after clicking into the table, I cant find a way for the cursor to exit out of the table. I have tried the `Enter` key at the bottom right cell but that just creates a new line in the bottom right cell of the table and not exit out of the table (which makes sense).

Am I missing something? Is there a more intuitive way for users to input more stuff under/above tables by simply clicking on those regions?

### On the web version:
1) Create a new note with a table (number of cells shouldn't matter)
2) Try clicking below the table (the cursor would automatically be placed in the bottom right cell of the table)
3) To exit the table, one has to click the `↓` arrow key and 'Enter'.

### On the Android app:
1) Same as web
2) Same as web
3) There seems to be no way to exit the table to insert more text/blocks below it.

### Version

v2.1.8 (Android), v2.1.6-deb04d68-web (Web)

### Platform/OS

Android, Firefox

**Comment by ammarahm-ed** [comment]
Hi, on android, you can close the keyboard and then double tap on the bottom area near the toolbar to create a new line under the table. Let me know if that works for you.

**Comment by Beebeeoii** [comment]
hi, thanks ! it works. any idea if it is also possible to create a new line above the table? and also is it worth it for us to consider making it more intuitive for users? i tried double tapping below the table, but it wasn't near the bottom area and hence did not create a new line.

thanks in advance !

**Comment by thecodrr** [comment]
Fixed in #1185
