### ISSUE TITLE
Splash screen for Dark Mode

### ISSUE THREAD

**Issue by McBaumwolle** [streetwriters/notesnook#955]
### What problem are you facing?

When the phone (and app) is set to dark mode, the splash screen of the app (when opening it) is white. 

### What's the solution you'd like to see in Notesnook?

A black (or dark) splash screen when dark mode is toggled. 

### What alternatives have you considered?

I think there is an integrated splash screen tool in the Android SDK, but I am not quite sure about that. 

### Additional context

Here is a screenshot of the opening sequence of Notesnook in dark mode (don't mind the cut-off, it's just the screenshot).

![image](https://user-images.githubusercontent.com/67203883/189499667-56797230-b248-471a-bc56-b3b694a45b36.png)

Android 13, Pixel 5, T1B1.220819.006

**Comment by ammarahm-ed** [comment]
We are using android's own splashscreen api however i will have to see if it's possible to change the background color in day/night mode.

**Comment by ammarahm-ed** [comment]
Hey, this has been added. Will ship in next release.

**Comment by McBaumwolle** [comment]
Thank you so much!
