### ISSUE TITLE
Any plan for on-premise deployment?

### ISSUE THREAD

**Issue by ybzhaoplus** [streetwriters/notesnook#966]
### What problem are you facing?

notesnook is a very great note tool. It is really nice that it supports open source. So far, I did not see on-premise deployment.
This will be good for internal use and limited connetion to the notesnook server. 

### What's the solution you'd like to see in Notesnook?

Is there any plan for on-premise deployment? A good case is GitLab, which supports both on-premise deployment and cloud, community and enterpise version.

**Comment by vysecurity** [comment]
Or use iCloud. The current model is a bit broke and doesn’t match the point of the app.

**Comment by ammarahm-ed** [comment]
Sync server will be open sourced in the upcoming months water which you will be able to self host Notesnook. No iCloud option will be available.

**Comment by ybzhaoplus** [comment]
It is good to know that. It's super cool!

**Comment by dameng324** [comment]
> Sync server will be open sourced in the upcoming months water which you will be able to self host Notesnook. No iCloud option will be available.

any progress on this?

**Comment by ammarahm-ed** [comment]
> > Sync server will be open sourced in the upcoming months water which you will be able to self host Notesnook. No iCloud option will be available.
> 
> any progress on this?

Sync server has been open sourced. Self hosting is WIP.

**Comment by thecodrr** [comment]
Closing as duplicate. Track progress here: https://github.com/streetwriters/notesnook-sync-server/issues/1
