### ISSUE TITLE
Move toolbar location

### ISSUE THREAD

**Issue by Donkey-Doug** [streetwriters/notesnook#976]
### What problem are you facing?

Whenever I am trying to scroll accross the toolbar on notesnook on android, my gestures trigger and I am not able to interact with the toolbar.

### What's the solution you'd like to see in Notesnook?

Optionally move the toolbar to the top.

### What alternatives have you considered?

-

### Additional context

Android 12

**Comment by ammarahm-ed** [comment]
Can you share a screenshot? also does it happen both with keyboard opened and closed or only when keyboard is closed?

**Comment by Donkey-Doug** [comment]
Should have been more clear. This only happens when keyboard is not opened. However, why show a toolbar I cannot interact with? Maybe only show it when the keyboard is showing as well.


![Screenshot_20220914-112939_Notesnook](https://user-images.githubusercontent.com/50382414/190117401-ea5ac10c-f801-4d07-92b9-b4491a94b412.png)
![Screenshot_20220914-112943_Notesnook](https://user-images.githubusercontent.com/50382414/190117406-c6566d37-51ca-4b3d-8a0e-de54ef0ffa55.png)

**Comment by ammarahm-ed** [comment]
I will add some padding on bottom, it's probably too close to the bottom and interferes with gestures.

**Comment by thecodrr** [comment]
This issue has been fixed.
