### ISSUE TITLE
Add possibility to see email events and create tasks for them

### ISSUE THREAD

**Issue by SamuelPinho** [streetwriters/notesnook#985]
### What problem are you facing?

I'm trying to find a place where I can hold all my notes and also create new ones for meetings that I have or will have in the future.

### What's the solution you'd like to see in Notesnook?

A place that I can connect my Calendar (Gmail, Outlook...) and see my upcoming events. When I click on one of those events, one new note will be created and that note will be attached to that calendar event.

### What alternatives have you considered?

[Mem.ai](https://mem.ai/) - they're already do it
[Fellow](https://fellow.app/)

### Additional context

Since this is an open source and I'm familiar with React and Typescript, I was considering doing this feature and creating a PR

**Comment by thecodrr** [comment]
> A place that I can connect my Calendar (Gmail, Outlook...) and see my upcoming events. When I click on one of those events, one new note will be created and that note will be attached to that calendar event.

Hey, can you explain this a bit more? I am not sure I understand fully.

**Comment by SamuelPinho** [comment]
> Hey, can you explain this a bit more? I am not sure I understand fully.

Like this functionality that Mem.ai has
![f4318249-1a49-40fe-a83e-ff1d80b1506d](https://user-images.githubusercontent.com/20033265/190677518-5818b305-8354-47c3-8ff9-f2038125a348.gif)

There's a list of upcoming events. When you hover over it, there's this button that when clicked, will create a note that's attached to that Event.

I was not thinking of replicating that `hover` feature, instead, I would just make that each item on the event list, is a button that when pressed: 
 1. If there's no previous note attached to the event, create a new note attached to it.
 2. If there's already a note attached to it, open it instead of creating a new one.

**Comment by thecodrr** [comment]
Closing as out of scope.
