### ISSUE TITLE
Can't see Notesnook Importer options

### ISSUE THREAD

**Issue by jdonlan17** [streetwriters/notesnook#991]
I'm trying to create an import file but when I go to https://importer.notesnook.com/ the area giving me the source options is blank. I've tried with Chrome and Firefox with same results. Thanks, John Donlan jdonlan@vivaldi.net
![NotesNookImporter](https://user-images.githubusercontent.com/68293156/190616590-5431576e-712a-4225-ab27-99c9873611dc.png)

**Comment by thecodrr** [comment]
It's blank because you have to click on it and select the notes app from the list yourself.

**Comment by jdonlan17** [comment]
AH, my old eyes missed the drop-down arrow!! Thanks!
